### ISSUE TITLE
Messy Settings

### ISSUE THREAD

**Issue by BaraoVlask** [laravel-idea/plugin#1]
After install the plugin for the trial i notice the many settings have bem broke, such as multiple cursors creation que estavam desabilitadas, fixed line spaces, content selection.

**Comment by adelf** [comment]
Hi, @BaraoVlask . PhpStorm doesn't allow plugins to override settings. So, installing Laravel Idea shouldn't break your settings. However, there is one key combination, which will come with plugin: Ctrl-Shift-Comma. It can override the same combinations from other plugins.
You can setup them in File > Settings > Keymap.
