### ISSUE TITLE
Add input field for command signature and description

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#10]
It would be cool to be able to enter a command signature and description in the creation window.

Also, I think it’s useful to uncheck the command registration box, since in new versions of the framework teams are registered automatically. And now you have to manually turn it off.

![2020-01-29_09-39-12](https://user-images.githubusercontent.com/10347617/73333580-4092e200-427b-11ea-9102-c359c755a083.png)

**Comment by adelf** [comment]
Will this be enough to close this issue? :)

https://twitter.com/laravel_idea/status/1532311870069215233

**Comment by andrey-helldar** [comment]
Wizard!
