### ISSUE TITLE
[Enhancement] Auto-complete the $loop variable in blade templates

### ISSUE THREAD

**Issue by squatto** [laravel-idea/plugin#100]
When looping in blade templates the `$loop` variable is available and has a number of useful properties ([docs link](https://laravel.com/docs/7.x/blade#the-loop-variable)). It would be great to have auto-completion of the properties.

The `$loop` properties are defined in the `ManagesLoops` trait at [laravel/framework/src/Illuminate/View/Concerns/ManagesLoops.php](https://github.com/laravel/framework/blob/7.x/src/Illuminate/View/Concerns/ManagesLoops.php)

Thanks!

**Comment by adelf** [comment]
Good idea. Thanks!

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/90593794-80a6bb80-e1f1-11ea-9a93-ebfb59bc6fc4.png)

:)

**Comment by squatto** [comment]
@adelf 🙌🏻 🙌🏻 🙌🏻 You're amazing, thank you! I'm looking forward to the next release!

**Comment by adelf** [comment]
3.2 version already available.

**Comment by squatto** [comment]
Just checked the changelog and it's a great release, to boot. Nice work! 👍🏻
