### ISSUE TITLE
[Bug]: Not parsing PHP File Header 

### ISSUE THREAD

**Issue by fastsol** [laravel-idea/plugin#1000]
### Bug description

When creating file the #parse(PHP File Header.php) is being included but not parsed, so it generates the file with ${PRODUCT_NAME} instead of replacing the variable with the correct text.  I am using PhpStorm version 2024.1.2 and plugin version 8.1.4.241 .  Please advise.
![phpstorm1](https://github.com/laravel-idea/plugin/assets/30446819/2ddeea41-ff20-4cec-9b8e-6d6355949dbe)

### Plugin version

8.1.4.241

### Operating system

Windows

**Comment by adelf** [comment]
Yes. Right now, Laravel Idea doesn't put some parameters in the templates. And the ${PRODUCT_NAME} is one of them. We will try to fix.

**Comment by adelf** [comment]
Fixed in 8.2 version.
