### ISSUE TITLE
[Bug]: getGlobalSearchEloquentQuery protected instead public

### ISSUE THREAD

**Issue by abkrim** [laravel-idea/plugin#1002]
### Bug description

Create a model with relation with model user with wrong method `protected static function getGlobalSearchEloquentQuery()`

Must be public.

### Plugin version

8.1.4.241

### Operating system

MacOS

### Steps to reproduce

Create a Post Model with relation constrained with User

### Relevant log output

PHP Fatal error:  Access level to App\Filament\Resources\PostResource::getGlobalSearchEloquentQuery() must be public (as in class Filament\Resources\Resource) in /Users/abkrim/Sites/aicha/app/Filament/Resources/PostResource.php on line 104

   Symfony\Component\ErrorHandler\Error\FatalError 

  Access level to App\Filament\Resources\PostResource::getGlobalSearchEloquentQuery() must be public (as in class Filament\Resources\Resource)

  at app/Filament/Resources/PostResource.php:104
    100▕                 SoftDeletingScope::class,
    101▕             ]);
    102▕     }
    103▕ 
  ➜ 104▕     protected static function getGlobalSearchEloquentQuery(): Builder
    105▕     {
    106▕         return parent::getGlobalSearchEloquentQuery()->with(['user']);
    107▕     }

**Comment by dcaswel** [comment]
@adelf I see that you tagged this as implemented and waiting for the next release a month ago. I just downloaded an update that obviously didn't include this. I have been running into this error A LOT and it would be really nice if it could actually be included in the next release. Thanks!

**Comment by adelf** [comment]
@dcaswel it's fixed for the new resource creation in the Laravel Idea 8.2 now it analyzes the base `getGlobalSearchEloquentQuery` and uses the same modifier.

Could you show in which cases it works incorrect?
