### ISSUE TITLE
[Feature Request]: Add postfixes for dd and dump

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#1003]
### Feature Description

I realized that I always end up adding my own postfixes for dd and dump, would be cool if this was native to the plugin. 

Essentially allowing us to do `$somecoolCode.dd<tab>` and it becomes `dd($somecoolCode);`. 

Here is an example of a postfix I created for pest.
https://github.com/JetBrains/pest-intellij/blob/master/src/main/kotlin/com/pestphp/pest/templates/PestItPostfixTemplate.kt

**Comment by adelf** [comment]
https://x.com/laravel_idea/status/1800839414157038072 ;-)

**Comment by olivernybroe** [comment]
Awesome, fast as always! 🎉 It's good to be back in Laravel world again ❤️
