### ISSUE TITLE
[Bug]: Vendor User class breaks helper code generation

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#1004]
### Bug description

Something was odd with my `User` Model completions, and I discovered that the helper-code generation must have been confused about a different User model found in the vendor folder.
[This vendor package](https://github.com/abbasudo/pulse-users) includes a User model in a namespace called `Workbench\App\Models`, which is autoload-dev only.

The result is that vendor/_laravel_idea contains two versions of all the _IH_User classes (also _QB and _C), one in`LaravelIdea\Helper\App\Models` and the other in `LaravelIdea\Helper\Workbench\App`.
And my other models that have a relation to User, include references to the wrong User model:
```
* @ownLinks created_by_user_id,\Workbench\App\Models\User,id
```

### Plugin version

8.1.4.241

### Operating system

MacOS

### Steps to reproduce

1. Create a fresh Laravel project.
2. Add some model with a BelongsTo relationship to User
3. Install `abbasudo/pulse-users` with composer.
4. Generate helper code

**Comment by adelf** [comment]
I fixed this yesterday)
