### ISSUE TITLE
[Request] Add code completion/clicktrough for barryvdh/laravel-dompdf

### ISSUE THREAD

**Issue by spaantje** [laravel-idea/plugin#101]
When you use the following code: 

```php
PDF::loadView('path.to.view', ['data' => 'data'])->save('pdflocation.pdf');
```

It would be nice if we could click trough to the view. (and vice-versa)

Package: https://github.com/barryvdh/laravel-dompdf

**Comment by adelf** [comment]
Hi, Sonny. I'll add this completion or just allow to configure view completions in the plugin settings. Thanks!

**Comment by olivernybroe** [comment]
What if this could be read from docblocks so package creators can add a docblock tag in to add autocompletion support for views?

**Comment by adelf** [comment]
I'm still thinking about how to implement it. During performance reasons, I have to know the exact method name. So, maybe some configuration file... like laravel-idea.json and there can be a lot of such configurations. But my plugin still not a standard for Laravel community, so I'm not sure )
What do you think about special configuration files for packages? For views, view namespaces, blade/livewire components paths,  etc.

**Comment by olivernybroe** [comment]
@adelf Normally when I create packages I would not add stuff in specifically for one plugin tbh. 

I think some packages would add it in, but some would not, as it adds more maintenance work. 

A solution could be to create a repository where we can submit json files for packages, this way that repository will be responsible for updating the configs. Then rely on users to submit to this repository. 

However I think you would get more luck with it, if it is not tied to your plugin, so not naming it `laravel-idea`and so on. As that would mean others could use it to make a plugin for vscode and that would make package creators more interested in adding support.

**Comment by adelf** [comment]
Makes sense. Something like `ide.json` file with common rules about everything: paths, method parameters, etc. Thanks.

Anyway, I just added support for PDF::loadView method for now.

**Comment by adelf** [comment]
Added to 3.3 version.
