### ISSUE TITLE
[Feature Request]: Add suppression for "Member has protected visibility but can be accessed via '__call' magic method"

### ISSUE THREAD

**Issue by pindab0ter** [laravel-idea/plugin#1020]
### Feature Description

When using `$model->increment('column_name')` I get the following warning:

> Member has protected visibility but can be accessed via '__call' magic method

It seems that this would benefit from having a suppression option just like "Non-static method should not be called statically" and "Undefined field/method" are suppressed.

**Comment by adelf** [comment]
Fixed in 8.2.
