### ISSUE TITLE
[Bug]: Click through of components does not work when using Livewire v2 class namespace in Livewire v3

### ISSUE THREAD

**Issue by adampatterson** [laravel-idea/plugin#1021]
### Bug description

I have a Laravel app that was updated from Laravel 10 + Livewire 2 to Laravel 11 + Livewire 3

After the update component click through stopped wroing.

### Plugin version

8.1.4.241

### Operating system

MacOS

### Steps to reproduce

My Livewire config was left as `'class_namespace' => 'App\\Http\\Livewire',` which allowed everything to work but my Idea click through stopped working.

I updated my class name space to 'App\\Livewire'` to match the v3 conventions and that fixed my click through issues.

```
@livewire('portal.payment.payment-form',  ['invoice'=> $invoice])
<livewire:portal.payment.payment-form :invoice="$invoice"/>
```

Both inclusion types had the same problem and both work correctly after the change.

Not mentioned, but my completions were also not working and are also fixed.

I'd like Idea to look for the `class_namespace` path in `config/livewire.php` otherwise it's probably safe to assume the default based on the installed version.

**Comment by ThiVer99** [comment]
I also have the same problem i suspect components tag namespace is not working as intended

<img width="457" alt="Screenshot 2024-07-11 at 10 54 07" src="https://github.com/laravel-idea/plugin/assets/113504312/c8892da8-53c1-4c9c-8a5b-ae8c83a0c897">

have you found a solution?

**Comment by adelf** [comment]
@ThiVer99 please revert this value back to "livewire".

Right now this value is used to determine Livewire classes namespace:

<img width="632" alt="image" src="https://github.com/user-attachments/assets/9728196c-9536-4b1b-9dc8-ab82b7f0f057">

I'll try to look to the config file.

**Comment by adampatterson** [comment]
@adelf  I did see this but because it said create, I thought it was only for the component creation config. 

Good to know, but maybe not obvious to find.
