### ISSUE TITLE
[Feature Request]: Auto-completion on Heroicons within Filament methods

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#1025]
### Feature Description

It would be great to have auto-completion on heroicon names within common Filament methods. For example, `->icon()` methods on pretty much every Filament component, `->onIcon()`/`->offIcon()` on Toggle, `->prefixIcon()`/`->suffixIcon()`/`->hintIcon()` on fields.

Or simply implemented it on all matching `->*icon()` methods on Filament objects.

Would be super useful, since often I do remember which icon I want, but it still happens more often than you would expect that you still don't get the name entirely right.

Thanks!

**Comment by adelf** [comment]
Hi, Ralph.

You can add `ide.json` file with this content to the project/package
```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "bladeIcon",
            "condition": [
                {
                    "methodNames": ["icon", "offIcon", "prefixIcon"],
                    "parameters": [1]
                }
            ]
        }
    ]
}

```

Result:

<img width="645" alt="image" src="https://github.com/user-attachments/assets/01a98b2a-7ed0-42b9-aebc-b3141f67eb03">

**Comment by adelf** [comment]
It's possible to complete even here.

```php
IconColumn::make('is_featured')
    ->options([
        'heroicon-o-x-circle',
        'heroicon-o-pencil' => 'draft',
        'heroicon-o-clock' => 'reviewing',
        'heroicon-o-check-circle' => 'published',
    ])
```

If you will decide to add an 'ide.json' file to the package, I'll help you with it.

**Comment by jackwh** [comment]
@adelf Thanks for sharing, really helpful to have this! I extended your example with the remaining method names I could find in Filament, there might be some more I couldn't find, but hopefully this is helpful for others.

```json
{
    "$schema":     "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete":  "bladeIcon",
            "condition": [
                {
                    "methodNames": [
                        "icon",
                        "trueIcon",
                        "falseIcon",
                        "offIcon",
                        "onIcon",
                        "prefixIcon",
                        "suffixIcon",
                        "activeIcon",
                        "completedIcon",
                        "badgeIcon",
                        "hintIcon",
                        "modalIcon",
                        "descriptionIcon",
                        "groupedIcon",
                        "emptyStateIcon"
                    ],
                    "parameters":  [
                        1
                    ]
                }
            ]
        }
    ]
}
```

**Comment by adelf** [comment]
This file could be added somethere in Filament package and these completions will be available for everyone ;-)

**Comment by ralphjsmit** [comment]
Thank you @adelf, that's really great to hear! Been a bit busy this week with preps before my vacations but your example is very helpful. I will close this issue then since Jack's already provided a Filament PR (thanks :) ) 👌
