### ISSUE TITLE
[Bug]: laravel 11 new structure, middleware not autocompleted 

### ISSUE THREAD

**Issue by Abdelraman** [laravel-idea/plugin#1028]
### Bug description

using middleware inside controller like the image below
![image](https://github.com/user-attachments/assets/6548d668-8f5b-4067-b37d-92aca1a8705c)

![image](https://github.com/user-attachments/assets/602dbd7e-b5ff-41e8-b418-1b0bc985f0cd)

autocomplete is not working, middleware is not clickable when writing middlewares inside controller 

### Plugin version

8.2.1.241

### Operating system

Windows

### Steps to reproduce

create a new middleware
add alias for this middleware
use this middleware inside a controller

**Comment by Abdelraman** [comment]
the same for only and except, autocomplete is not working

**Comment by Abdelraman** [comment]
thanks @adelf it is now working after upgrading to 8.2.2.241 but the only and except parameters still not auto completing 
![image](https://github.com/user-attachments/assets/8fd0b6d1-d0bc-4995-9bac-6f3a985d49ff)

**Comment by Abdelraman** [comment]
Hello @adelf any updates for this

**Comment by adelf** [comment]
@Abdelraman could you check Laravel Idea 8.2.3?

**Comment by Abdelraman** [comment]
![image](https://github.com/user-attachments/assets/9dddfd21-da68-47ea-b9ca-e25d064db7c1)
![image](https://github.com/user-attachments/assets/3ff1b126-b40f-4458-b698-88472b8e2779)

when calling only parameter, it autocompletes the middlewares not the controller functions

**Comment by Abdelraman** [comment]
@adelf shall I open a new issue for that ?

**Comment by adelf** [comment]
No. I've fixed it. But I can't estimate the release date.

**Comment by adelf** [comment]
Please check the latest update.
