### ISSUE TITLE
[Bug]: wire:key 'statement expected' bug

### ISSUE THREAD

**Issue by DanielSpravtsev** [laravel-idea/plugin#1029]
### Bug description

The plugin started to erroneously emphasize the contents of {{ $some_var }} inside wire:key. If you disable the plugin, the errors disappear.

![telegram-cloud-photo-size-2-5249330852356282853-y](https://github.com/user-attachments/assets/a20beb26-2417-43b7-81d9-0ca92caf2149)

### Plugin version

8.2.1.242

### Operating system

MacOS

**Comment by xswebfr** [comment]
It looks like the issue is not limited to wire:key : 
![issue](https://github.com/user-attachments/assets/78b46047-e24e-4f3a-bf9b-e62712dfa7e8)

**Comment by adelf** [comment]
Could you check the 8.2.2 version? I've made some fixes.

**Comment by xswebfr** [comment]
Just upgraded to 8.2.2 and it works perfectly for me, thanks !

**Comment by DanielSpravtsev** [comment]
> Could you check the 8.2.2 version? I've made some fixes.

Works as expected, thanks!
