### ISSUE TITLE
[Enhancement] Changelog

### ISSUE THREAD

**Issue by fieu** [laravel-idea/plugin#103]
Can we have a public changelog?

**Comment by adelf** [comment]
Good idea! I'll add it to this repository soon.

**Comment by adelf** [comment]
https://github.com/laravel-idea/plugin/blob/master/changelog.md

There are 3.3 version changes also. It hasn't approved by JetBrains yet.

**Comment by adelf** [comment]
There is also a roadmap in the readme :)
