### ISSUE TITLE
[Bug]: PhpStorm doesn't show Undefined property inspection

### ISSUE THREAD

**Issue by iwex** [laravel-idea/plugin#1044]
### Bug description

![KPmY26XG](https://github.com/user-attachments/assets/2baf6daa-4016-4527-9d6c-0116e0963f01)
As you can see - property `x` is not highlighted.

### Plugin version

8.2.2.241

### Operating system

None

**Comment by iwex** [comment]
@adelf hello! could you please check?

**Comment by adelf** [comment]
Fixed. Sorry. The update will be released this week.

**Comment by iwex** [comment]
@adelf thank you 🙏

**Comment by adelf** [comment]
Fixed in the 8.2.3 version. Thank you.
