### ISSUE TITLE
[Bug]: `env() function is used outside of config files...` inspection ignores `Config directory` setting.

### ISSUE THREAD

**Issue by NickSdot** [laravel-idea/plugin#1045]
### Bug description

Under `Settings | Languages & Frameworks | Laravel Idea | General | Config directory` we can set a custom config path. If I recall correctly this allowed to get rid of this inspection message:

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/139374f6-106c-4088-8592-4a974ca1b293">

It seems one of the latest updates did break this feature.

### Plugin version

8.2.2.241

### Operating system

MacOS

### Steps to reproduce

1) Set a custom config path in `Config directory` under `Settings | Languages & Frameworks | Laravel Idea | General`.
2) Move a config file there
```php
return [
    'debug' => (bool) env('APP_DEBUG', false),
];
```
3) Inspection warns about usage outside of config files.

**Comment by adelf** [comment]
Yes. There were some places with hard-coded "config" string. Sorry. Fixed. The update will be released this week.

**Comment by NickSdot** [comment]
Thanks Adelf, I will report back after the release. 🤝

**Comment by NickSdot** [comment]
Fixed in the latest release. Thank you, Adelf! <3
