### ISSUE TITLE
[Bug]: Missing "Package development" module system

### ISSUE THREAD

**Issue by Jacobtims** [laravel-idea/plugin#1049]
### Bug description

I suddenly started noticing that my PHPStorm IDEA was no longer creating some files (using the Laravel IDEA plugin) properly when I was developing a package. It now appears that it is no longer possible to select "Package development" under the "Module System" settings, while this was previously possible.

![image](https://github.com/user-attachments/assets/27b22d83-b315-4ccc-baa8-68f6fbec7560)

### Plugin version

8.2.3.241

### Operating system

MacOS

### Steps to reproduce

1. Install PHPStorm IDEA
2. Install Laravel Idea plugin
3. Open settings
4. Go to the `Languages & Frameworks -> Laravel Idea -> Module System` settings
5. Try to select "Package development" in the Module system dropdown

**Comment by adelf** [comment]
Hello.

There is no Package development module anymore. The only change that should be made is the application directory value("src")

<img width="636" alt="image" src="https://github.com/user-attachments/assets/10c6b412-8826-481f-b35d-83b9959e2c02">

**Comment by Jacobtims** [comment]
Ok, I think that did the trick.
The only thing that's still not working is the translation functionality. It should add the package's prefix to the translations. 
Is there any way to fix that?

**Comment by adelf** [comment]
<img width="622" alt="image" src="https://github.com/user-attachments/assets/728ae3d8-62e2-4498-ba09-fee67b462352">

**Comment by Jacobtims** [comment]
Thx for your quick help!
