### ISSUE TITLE
[Bug]: Cannot activate perpetual fallback license

### ISSUE THREAD

**Issue by sudoist** [laravel-idea/plugin#1051]
### Bug description

How to activate the perpetual fallback license?

I've subscribed and started using PhpStorm again but cannot activate my license.

![Screenshot from 2024-08-09 23-49-41](https://github.com/user-attachments/assets/79878c20-d7f7-493c-a620-04d8db9f9a42)

I tried downloading the activation code but it doesn't work.

For reference:

Here is the version I had before.

![Screenshot from 2024-08-11 11-23-23](https://github.com/user-attachments/assets/c8fe764a-f5c2-44b6-9d6e-7d2d91abf989)

### Operating system

Linux

**Comment by adelf** [comment]
You can try by Jetbrains account. If it doesn't work, please write to sales@jetbrains.com. They manage all licenses.

**Comment by adelf** [comment]
BTW, 0.4 versions don't support the new PhpStorm.

**Comment by sudoist** [comment]
Oh got it
Could be because of unsupported for new PhpStorm.

I've sent an email to sales@jetbrains.com.
Will just wait for their reply.

Thanks!
