### ISSUE TITLE
Route class is not recognized in routes/web.php

### ISSUE THREAD

**Issue by emilas44** [laravel-idea/plugin#106]
I had installed barryvdh/laravel-ide-helper and routes were all recognized.
I removed barryvdh/laravel-ide-helper, installed this package through PHPStorm, invalidated cache and restarted PHPStorm,
but the 'Route' class is not recognized.

![image](https://user-images.githubusercontent.com/15637006/91322848-7e7bc880-e7c0-11ea-8319-2f4f644ffc43.png)

Under settings for  Laravel Idea Current state is: Enabled. Framework: laravel. Version: 6.0

what else can I check to make it work???

OS: Ubuntu 18.04
PHPStorm version 2020.02
----------------------------------------------------------
update:
Actually all the facades like:
```
DB
Str
Arr
Route
```
are not  recognized... maybe I need to do some extra steps?

**Comment by adelf** [comment]
I haven't fully replaced ide-helper yet. Facades are the missing thing. I'll fix this for standard Laravel facades in the next version, but it won't work for custom ones.

**Comment by adelf** [comment]
Should work with 3.3 version.
