### ISSUE TITLE
[Bug]: The plugin doesn't suggest ->where() method

### ISSUE THREAD

**Issue by rstarinsky** [laravel-idea/plugin#1062]
### Bug description

Hello dear developer of this nice plugin! 💯 

I use the plugin Laravel Idea
And it doesn't suggest ->where() method.
If I use User::where() - no result
If I use User::query()->where() - it works

But lang suggestion is works well
__('products.catalog_name') - suggest me an autocomplete.

Attaches:
1th screen is from video about the plugin
<img width="543" alt="Screenshot 2024-09-10 at 15 17 00" src="https://github.com/user-attachments/assets/61a8d95b-555c-4d09-8a5b-dfcb21ab9544">

2th screen is from my PhpStorm
<img width="368" alt="Screenshot 2024-09-10 at 15 18 01" src="https://github.com/user-attachments/assets/5559b38e-73e1-4183-ab1a-82863533d946">

I use the last version of plugin.

### Plugin version

6.2.2.213

### Operating system

MacOS

### Steps to reproduce

Just write a basic code 
$user = User::where(); // no suggestions
$user = User::query()->where(); // suggested well

But the plugin works for lang structure
__('products.catalog_name'); // suggest me an autocomplete well
<img width="354" alt="Screenshot 2024-09-11 at 19 26 37" src="https://github.com/user-attachments/assets/01c938e7-7afc-4192-881a-967d157b348b">

**Comment by adelf** [comment]
Hello, Roman.

You should generate a helper code to get these completions. You can do it in the main menu - Laravel - Generate Helper Code. Or by Cmd-Shift-period(.)

BTW, Laravel Idea 6.2.2 version is released almost 2 years ago... and a bit outdated. It doesn't support latest Laravel versions.

**Comment by rstarinsky** [comment]
Thanks you for helping! I generate helper code and it works!
Please help me to know, where the generated helper code stores? In the code of my project (which directory) or in PhpStorm application files?

I use old PhpStorm version 2021.3.3 and seems the plugin downloads the old version too.

**Comment by adelf** [comment]
It's in vendor/_laravel_idea by default.
