### ISSUE TITLE
[Bug]: Custom Generations's parameters are empty after restarting the IDE

### ISSUE THREAD

**Issue by kurokeita** [laravel-idea/plugin#1064]
### Bug description
The Custom Generations's parameters are always cleared after restarting the IDE. There are no error log.

### PHPStorm version
2024.2.1 242.21829.154

### Plugin version

8.2.5.242

### Operating system

Windows

### Steps to reproduce

1. Create a Custom Generation with parameters. For example:

![image](https://github.com/user-attachments/assets/a80741f1-0614-4706-a8e5-0be27092e0c8)

2. Restart the IDE.
3. After the IDE is restarted, go to the `Custom Generations` setting, edit the previously created item, it is now filled with empty parameter entries like this:

![image](https://github.com/user-attachments/assets/89cd891b-2e69-4292-aba1-834ad54d4732)

### Relevant log output

```shell
There are no log output for this.
```

**Comment by adelf** [comment]
Fixed in 8.3. Thank you and sorry.
