### ISSUE TITLE
[Bug]: Extract view refactor broken after update 

### ISSUE THREAD

**Issue by emmadesilva** [laravel-idea/plugin#1066]
### Bug description

After using the extract view refactor in the new update, this is what is inserted

```php
@include('ViewFile(name=foo-bar, namespace=)')
``` 

### Plugin version

8.2.5.242

### Operating system

MacOS

### Steps to reproduce

Use extract view refactor

I also just update to PhpStorm 2024.2

**Comment by adelf** [comment]
Ooops. Thank you for reporting. Will be fixed ASAP.

**Comment by adelf** [comment]
Fixed in 8.3.1. Thank you.
