### ISSUE TITLE
[Bug]: Long translation strings in auto-suggest not working

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#1068]
### Bug description

Auto-completing a translation, it is not entirely visible:

<img width="887" alt="Scherm­afbeelding 2024-09-14 om 21 15 10" src="https://github.com/user-attachments/assets/7b2de22c-0210-428f-bfb8-97ed61680715">

Thanks!

### Plugin version

8.2.4.242

### Operating system

MacOS

**Comment by adelf** [comment]
Hello, Ralph. I can't do anything with it; however, you can resize the completion popup! Just use the mouse.

**Comment by ralphjsmit** [comment]
Aha, amazing, thank you! It will even keep the completion popup size for subsequent completions 👌
