### ISSUE TITLE
[Feature Request]: Add ability to define custom methods as alias for Laravel internal functions

### ISSUE THREAD

**Issue by smares** [laravel-idea/plugin#1069]
### Feature Description

I love how Laravel Idea offers auto-complete for things like `config(...)` or `Config::get(...)`. Is it possible to define custom aliases for such functions? In our codebase we have some helpers like `ConfigHelper::getStringOrFail(...)` which is a wrapper for `Config::get(...)` with added checks if the config is a string. We have more of those for other data types. Since we're using those helpers most of the time, we miss out on a cool feature.

It would be nice to define that `ConfigHelper::getStringOrFail` should be treated as config accessor, `ViewHelper::fooBar` should be treated as view accessor, `RouteHelper::fooBar` should be treated as route accessor, etc.

**Comment by adelf** [comment]
Hello. It can be solved by adding ide.json file to the project. With "configKey" completion.

https://laravel-idea.com/docs/ide_json/completion
