### ISSUE TITLE
[Bug]: Completion/navigation for `loadViewsFrom()` with multi path does not work

### ISSUE THREAD

**Issue by NickSdot** [laravel-idea/plugin#1071]
### Bug description

Hi Adelf! 👋

Laravel allows an array to be passed to the view loader:

```php
$this->loadViewsFrom(['path1', ''path1''], 'admin');
```

This allows to have multiple paths under one namespace. 
In our case is a kinda fallback-mechanism / override under the same namespace.

It seems Laravel Idea cannot handle this. 
Completion and navigation do not / no longer (?) work. 

Would be awesome if you could have a look. 
Cheers & thanks in advance1 

### Plugin version

8.2.5.242

### Operating system

MacOS

### Steps to reproduce

```php
final class ProvidesViews extends ServiceProvider
{
    /**
     * @var list<string>
     */
    protected array $viewPaths = [
        __DIR__ . '/views/',
        __DIR__ . '/Feature/views',
       // ...
    ];

    public function boot(): void
    {
        $this->loadViewsFrom($this->viewPaths, 'admin');
    }
}
```

<img width="462" alt="image" src="https://github.com/user-attachments/assets/0cc1cb55-4ea5-41cb-a85f-8b1904d69d29">

**Comment by adelf** [comment]
Hello.

I can make this work:

```php
$this->loadViewsFrom([
        __DIR__ . '/views/',
        __DIR__ . '/Feature/views',
       // ...
    ], 'admin');
```

Or you can add an `ide.json` file to your project with:
```json
{
  "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
  "view": {
    "paths": [
      {
        "path": "custom/views",
        "namespace": "admin"
      },
      {
        "path": "/resources/modules/foo",
        "namespace": "admin"
      }
    ]
  }
}
```

**Comment by NickSdot** [comment]
> I can make this work:

You mean on your end it works in the current version; or that you could make it happen?

If the latter, I'd prefer and appreciate it. Always better to not maintain things in two places. 😃🙏


**Edit:**
The Json approach works. It made me think if the following works, too.  And it does. 
Even thouh I'd prefer to keep the array; this's good enough for the time being. 
So, no rush with making the arrray approach work.

```php
$this->loadViewsFrom(__DIR__ . '/views', 'admin');
$this->loadViewsFrom(__DIR__ . '/Feature/views', 'admin');
```

**Comment by adelf** [comment]
I've implemented it. It will work in the next version. Thank you.

**Comment by NickSdot** [comment]
Hey Adelf! 👋 

I just got my hands on the update, and would like to report back. 
8.3.1.242 works as you described above. Thank you! 

---

For others, the array must be passed in directly. Passing variables does not work.

```php
// ✅
$this->loadViewsFrom([
    __DIR__ . '/views/',
    __DIR__ . '/Feature/views',
]; 'admin');

// ❌
$viewPaths = [
    __DIR__ . '/views/',
    __DIR__ . '/Feature/views',
];

$this->loadViewsFrom($viewPaths; 'admin');
```
