### ISSUE TITLE
[Bug]: License activated, but plugin sees it as expired

### ISSUE THREAD

**Issue by fono-byborg** [laravel-idea/plugin#1081]
### Bug description

I have the plugin installed in PhpStorm and activated by `Help / Register... / Laravel Idea` via a license server. It correctly says _"Licensed to: ..."_
However, the plugin isn't activated. The "Laravel" menu is displayed upon startup for a fraction of second and then it disappears. In `Settings / Language & Frameworks / Laravel Idea / General` I have "Fetch Laravel automatically" checked, and below that it says: "Current state: Disabled (License expired)". But my license is not expired, it has been renewed in August for another year.

Tried:
* restart
* remove license and activate again
* `Files / Repair IDE`
* deleting caches
* disable/enable plugin
* reinstall plugin

PhpStorm version: 2024.2.3 (#PS-242.23339.16)
Laravel version: 10.48.22

<img width="804" alt="licenses" src="https://github.com/user-attachments/assets/77afdfe2-81eb-4264-a045-c88aa4967a92">
<img width="904" alt="settings" src="https://github.com/user-attachments/assets/8dfe977f-e4de-49a8-a06f-9084f0ea5f94">

### Plugin version

8.3.3.242

### Operating system

MacOS

**Comment by adelf** [comment]
Hello. Seems it's a bug. Sorry. It will be fixed soon.

**Comment by adelf** [comment]
Could you share your email or company information? Email: support@laravel-idea.com

**Comment by adelf** [comment]
Please update to 8.4. It should be fixed there.
