### ISSUE TITLE
[Bug]: LiveWire support is missing

### ISSUE THREAD

**Issue by Siebov** [laravel-idea/plugin#1082]
### Bug description

ivewire syntax highlight is missing((

![image](https://github.com/user-attachments/assets/f8b0514a-e8d2-4fe2-9471-ecc6ec13d278)

```
PhpStorm 2024.2.3
Build #PS-242.23339.16, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-45-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 24
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.intellij.ml.llm (242.23339.40)
  ru.adelf.idea.dotenv (2024.2.1)
  com.laravel_idea.plugin (8.3.3.242)
  org.sonarlint.idea (10.11.1.79663)
Current Desktop: ubuntu:GNOME

```

Livewire directives not recognized:

![image](https://github.com/user-attachments/assets/09aba983-f06d-441d-857b-525e64df3691)

![image](https://github.com/user-attachments/assets/ee8ef020-82d5-4fed-b381-d765f614971c)

### Plugin version

8.3.3.242

### Operating system

Linux

**Comment by adelf** [comment]
Do you have livewire/livewire package installed in this project?

**Comment by Siebov** [comment]
> Do you have livewire/livewire package installed in this project?

@adelf yes sir. I have it in my composer file and it's all works fine, bit no sythax highlights.

**Comment by adelf** [comment]
That's weird.

Could you check this option?

<img width="897" alt="image" src="https://github.com/user-attachments/assets/28bc10a7-66ab-4272-a552-caf3488be313">

**Comment by Siebov** [comment]
I created this issue 2 weeks ago. Since then I've reinstalled my Linux, created new fresh project and now it started working. Sorry for disturbing you, now it's works. 
Last time I checked it wasn't and livewire\livewire package was greyed-out in this menu (but livewire worked for me). Now it's active too.

**Comment by adelf** [comment]
You probably uninstalled the Blade plugin. It works only with it.

**Comment by earmsby** [comment]
Hello, I'm having the same issue. I checked the screen shot you posted above and LiveWire is enable with all the same things checked off. LiveWire components and blade function fine in the browser but the IDE flags livewire directives as not allowed. I have other projects in PHPStorm where the livewire syntax is recognized just fine. Not sure what the difference is. Tried restarting PHPStorm just to see if it was a temporary glitch but that had no effect. Anything else I should look into?

**Comment by adelf** [comment]
@earmsby, that's weird. This is the condition for supporting `<livewire:` tags.

```kotlin
    override fun isAvailable(file: PsiFile): Boolean {
        return LivewireSettings.getInstance(file.project)?.enabled() == true && file.name.endsWith(".blade.php")
    }
```

So, if Laravel Idea is enabled(this screen) and the Livewire package is enabled(previous screen), it definitely should work.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/bf082437-d6df-4e97-9ad3-b24f1cad3127">

**Comment by earmsby** [comment]
Thanks for your reply. I couldn't figure it out, but several days later when I reopened PHP storm, I could see that Laravel Idea plug-in was NOT enabled and I found where to enable it. After that, everything was working as expected.
