### ISSUE TITLE
[Bug]: Doesn't work when Model is named "_Class"

### ISSUE THREAD

**Issue by robertmylne** [laravel-idea/plugin#1088]
### Bug description

We have a model named "_Class". However, it doesn't seem to parse it and essentially that model is just ignored. Running "generate helper code" ignores it essentially.

### Plugin version

8.4.0.241

### Operating system

Windows

### Steps to reproduce

Create a model named "_Class" then try and generate helper code. It works for all other models.

```
class _Class extends Model
{
    protected $table = 'classes';
}
```

![image](https://github.com/user-attachments/assets/5589a384-9e85-4723-860d-222737de5dd6)

**Comment by adelf** [comment]
Yes, Laravel Idea considers all files with the "_" prefix as internal or helper classes. Maybe better "ClassModel"?

**Comment by adelf** [comment]
I'm sorry, but I won't be able to support files with "_." It's important for performance and to avoid including test stubs in the helper code, and your case is super rare.
