### ISSUE TITLE
Support for projects with multiple content roots

### ISSUE THREAD

**Issue by joshuadwire** [laravel-idea/plugin#109]
I have a PHPStorm project with multiple content root directories. My Laravel code is a subdirectory of one of those content roots. No matter what I do, the Laravel Idea plugin config says "Current state: Disabled (composer.json not found)"

I've tried several different values for the Laravel directory setting as well as leaving it blank, and nothing makes the plugin detect Laravel. Enabling it manually also doesn't help, as none of the Ctrl+B navigation works.

Is there a way to use the plugin in a project with multiple content roots? If so, what value should go in the Laravel directory setting?

**Comment by adelf** [comment]
Hi, Joshua. 
I made some tests. Seems it works when the project with Laravel is the first one. In other cases, PhpStorm works a bit strange: doesn't see vendor classes...  I'll try to make some research and maybe add support for this kind of project.

**Comment by olivernybroe** [comment]
@joshuadwire This is usually where IntelliJ Idea Ultimate shines as it uses modules. 

So with Ultimate you would mark your subdiretory as a module and that should make the php plugin able to find the composer file. 

When it can find the composer file, this plugin should then work as far as I know :)

**Comment by joshuadwire** [comment]
@adelf My project seems to be displaying the folders in alphabetical order with no way to rearrange them. Did you find a specific way to mark a folder as the "first" one, or did it just happen that way? One other note is that my Laravel project isn't directly in the root of the folder. I tried to set the directory in the laravel-idea plugin settings, but given the multi-root project, I couldn't figure out what to enter as the path.

@olivernybroe As far as I can tell, Modules are an IntelliJ-only feature and aren't available in PHPStorm?

**Comment by adelf** [comment]
Maybe I misunderstood you... if you have laravel project in "foo/bar/" folder inside the project, so "foo/bar/composer.json" file contains the laravel/framework dependency in its `require` section, then you can try to set "foo/bar" value to the **Laravel directory** option and press Apply button. Laravel Idea will find the needed composer.json file and should start to work.

**Comment by olivernybroe** [comment]
@joshuadwire Yes. Its an IntelliJ Idea feature not phpstorm feature. However you can just install the php plugin which is what phpstorm uses.

A easy phpstorm solution could also be to just create a new project with the Laravel project as root. So you have to go to that project to touch your Laravel project

**Comment by joshuadwire** [comment]
@adelf If I only had a single content root, I'd think that would work, but in addition to having the laravel project inside "foo/bar", I also have multiple content roots added under PHPStorm's directories section. Here's what my Directories section looks like under PHPStorm settings:
![image](https://user-images.githubusercontent.com/3169995/92530744-f3a4c000-f1fa-11ea-930b-665f8ec78e35.png)

The root of my Laravel project is in C:\Users\jdwire\Sites\wilds\olr\app, which is a subfolder of the C:\Users\jdwire\Sites\wilds\olr\, so composer.json is at C:\Users\jdwire\Sites\wilds\olr\app\composer.json

I've tried leaving the "Laravel directory" setting under PHP->Laravel Idea blank, and I've also tried "olr\app", "app", and many other things, but I'm not sure what I'd be expected to put in that box, since it's not clear what that box is relative to in a multi-root project. Ideally, it would provide some sort of directory picker that would let me just select which of my project folders is the Laravel root?

@olivernybroe True, I could use IntelliJ, but I'm only paying for PHPStorm, not the full suite, so I think I'd lose some functionality by downgrading to the community IntelliJ edition. Switching to have a single root is also a possibilty, but I do find the multi-root functionality pretty valuable, and for now, I'm getting reasonable functionality with the free Laravel plugin that does work with multi-root projects, that I don't really want to switch to a paid plugin if it's going to break my other workflows.

**Comment by adelf** [comment]
@joshuadwire got it now. Thanks! Yes, currently it uses the first content root it met. I'll try to make it configurable... or find another solution.

**Comment by joshuadwire** [comment]
@adelf Thanks. I did just try editing the .iml file to put the content entry containing my Laravel project, and that didn't seem to help, so maybe PHPStorm is rearranging which one is returned first internally.

**Comment by adelf** [comment]
Sorry, it took a lot of time, but I've implemented it :)

**Comment by adelf** [comment]
4.0 version is available.

**Comment by joshuadwire** [comment]
@adelf I've been using it for a while, and it's working great. Thanks for your work on this!
