### ISSUE TITLE
[Feature Request]: Support new `CollectedBy` attribute

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#1091]
### Feature Description

They recently added new way to define custom collections. 

Thanks in advance if you decide to support it 👍 

https://laravel.com/docs/11.x/eloquent-collections#custom-collections

```php
<?php
 
namespace App\Models;
 
use App\Support\UserCollection;
use Illuminate\Database\Eloquent\Attributes\CollectedBy;
use Illuminate\Database\Eloquent\Model;
 
#[CollectedBy(UserCollection::class)]
class User extends Model
{
    // ...
}
```

**Comment by adelf** [comment]
Supported in 9.0. Thanks!
