### ISSUE TITLE
When creating a model, automatically create a migration

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#11]
Often, creating a model means that you need to create a migration to it. Now this requires a separate action.
It would be cool to have a checkmark “create migration” in the model creation window.

**Comment by finchy70** [comment]
`php artisan make:model Post -mc`
Makes model, migration, and controller.

**Comment by adelf** [comment]
@finchy70, true.
Laravel 7 will contain stub files, which makes this artisan command more convenient.

I'm still thinking about this issue... I'm going to implement a big "Create model" form. With convenient fields and relations creator, with migration, controller, model, policy and other files generation. This might be useful for some applications.

**Comment by K2ouMais** [comment]
This is a good idea for completely new projects. From my part where I work with already made Databases I dont need migrations. Should only be optional...

**Comment by anburocky3** [comment]
@adelf  Laravel 8+ released. Do we have this functionality now? Any update on this?

**Comment by adelf** [comment]
Ok :)

**Comment by anburocky3** [comment]
Is there any ETA for this feature?

**Comment by adelf** [comment]
I'll try to release v3.6.1 in December.

**Comment by andrey-helldar** [comment]
> `php artisan make:model Post -mc`
> Makes model, migration, and controller.

`php artisan make:model Post -a`
// Generate a migration, seeder, factory, and resource controller for the model

![image](https://user-images.githubusercontent.com/10347617/102055624-32e73c00-3dfc-11eb-93bc-626983d4244c.png)

**Comment by anburocky3** [comment]
Thanks for your suggestion @andrey-helldar I have read the Laravel documentation and I'm aware of these flags.

Since, We are using the Laravel Idea plugin, which is a GUI friendly one for speeding up the development time. Shouldn't be implemented there? 

That's my question and that's why I have commented on this issue. :) Hope you understand. :)

**Comment by andrey-helldar** [comment]
@anburocky3, as you can see in the quote, I posted [@finchy70](https://github.com/laravel-idea/plugin/issues/11#issuecomment-591611206)'s post.

The message of my post was that the CLI allows one command to create all the necessary classes for working with the model. And if this is implemented in Laravel Idea, it will be just gorgeous.

**Comment by anburocky3** [comment]
CLI is super cool for intermediate or pro users. But also beginner-friendly like GUI which will have several checkboxes, depending upon that, it should create the required files. It would be cool. Also, artisan commands should also be useful!

**Comment by andrey-helldar** [comment]
The use of the CLI does not determine the professionalism of the developer.
It is much easier and faster to tick the box than to enter the command into the console every time.

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/102758947-83bedd80-4384-11eb-84ea-7828af98996d.png)
Creating a Factory is useless before describing fields and relations, so without it.

**Comment by adelf** [comment]
Added in 3.6.1 version.
