### ISSUE TITLE
[Request] Mark Command classes as used

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#110]
In Laravel when creating a new command, it is shown as if the class is not used anywhere.

This makes the introspection for finding all unused classes more useless. It could be nice if this plugin would mark commands which are used as in use. 

Even cooler if it could find the line where the command is included.

Incuding commands in Laravel can be done in multiple ways
https://laravel.com/docs/7.x/artisan#registering-commands

**Comment by adelf** [comment]
It's not easy... but maybe I could make something... with find usages

**Comment by olivernybroe** [comment]
Yeah, realised myself how big a task this was when I found out that it wasn't as simple as just everything in the Commands folder.

**Comment by adelf** [comment]
O couldn't reproduce the warning in 2021.1. Seems, they removed these inspections for classes and public methods...

**Comment by olivernybroe** [comment]
@adelf yeah just looked myself, I also wasn't able to find them. 

I think you are right that they have been removed 👍
