### ISSUE TITLE
[Bug]: Nested routes pointing to incorrect controller and missing gutter icons

### ISSUE THREAD

**Issue by walterdis** [laravel-idea/plugin#1101]
### Bug description

Hello.

I'm experiencing two related issues with Laravel Idea:

1. In my routes file, I have nested controllers. When I try to click on an action, it directs me to the parent controller instead of the correct controller.

2. The gutter icons that should point to the corresponding route are not appearing next to the method in any of my project's controllers.

## Example

```php
Route::controller(UserController::class)
      ->name('users.')
      ->group(function () {
          Route::controller(UserProfileController::class)
              ->name('user-profiles.')
              ->group(function () {
                  Route::get('users/{user}/profiles', 'index')->name('index');
                  Route::post('users/{user}/profiles', 'store')->name('store');
              });
  
          Route::get('users', 'index')->name('index');
          Route::post('users', 'store')->name('store');
          Route::get('users/{id}', 'show')->name('show');
      });
```

Thank you ;)

### Plugin version

8.4.0.242

### Operating system

MacOS

**Comment by adelf** [comment]
Fixed. Thanks.
