### ISSUE TITLE
[Bug]: Laravel menu appears then disappears

### ISSUE THREAD

**Issue by earmsby** [laravel-idea/plugin#1102]
### Bug description

When I open a new Laravel project, for a moment, as the project is opening, I am able to see "Laravel" in the main menu but as the project completes opening, that menu item disappears. I can't find any way to bring it back. I have checked in the PHPStorm settings and see that the menu is set up under Appearance & Behavior > Menus & Toolbars > Main Menu. 

If I'm reading the docs correctly, I should be also able to bring up code generation with the keyboard shortcut Ctrl-Shft-, however that also does not work.

I'm not sure if this is an issue with PHPStorm itself or the plug-in. Perhaps there is a setting I've missed somewhere that is preventing this menu from showing correctly. Thanks for anything you can point me to find the problem.

### Plugin version

9.0.0.243

### Operating system

Windows

### Steps to reproduce

open project -> menu displays very briefly then disappears

**Comment by adelf** [comment]
Could you check Settings > Languages and Frameworks > Laravel Idea > General?

**Comment by earmsby** [comment]
I figured out the problem. I had to change the settings since the laravel app was not in the root directory of the project. After changing that and directing it to the sub-directory and also turning off fetch automatically, the menu item appeared (although only after moving it in the menu settings, hitting apply, then moving it back where I wanted it.)

**Comment by earmsby** [comment]
resolved.
