### ISSUE TITLE
[Request] Disable indexing for storage folder 

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#111]
It could be pretty awesome if this project marked the storage folder by default as excluded.

It would save a lot of time on indexing for users and there is not reason for it to be indexed.

**Comment by adelf** [comment]
3.3 version already under JetBrains check :) there are some index improvements... but I can add this exclusion also. Thanks!

**Comment by olivernybroe** [comment]
For me it's mainly because when finding references it can be found it compiled blade files. 

So marking it excluded fixes this

**Comment by adelf** [comment]
What index do you mean? I already removed `storage` folder from view files references...

**Comment by olivernybroe** [comment]
When using find usages on a method, php is able to find usages in blade files without your plug-in. However they also find them in compiled blade files.

To fix this, I simply mark the Storage directory as excluded. 

My idea here was that instead of having to mark the storage directory excluded in all Laravel projects, your plug-in did it for us.

**Comment by adelf** [comment]
Got it 👍 
I can try to suggest this exclusion on project startup.

**Comment by adelf** [comment]
I added silent exclusion of this folder in the Laravel project opening. With configuration option to don't do that :)
Another record? The longest ticket implementation? :)

**Comment by olivernybroe** [comment]
@adelf Haha amazing! 😄 

Trying to clean up in the older requests?

**Comment by adelf** [comment]
Yep :)

**Comment by adelf** [comment]
4.3.2 version is available.
