### ISSUE TITLE
[Bug]: \Illuminate\Database\Eloquent\Collection class not found. Please run 'composer install'

### ISSUE THREAD

**Issue by almesery** [laravel-idea/plugin#1111]
### Bug description

When open new or old laravel project and wait for phpstrom to complete indexing and trying to make Code Generation 

this error appear "\Illuminate\Database\Eloquent\Collection class not found. Please run 'composer install'" 

the vendor folder is already exits and the project is already running fine 

### Plugin version

9.0.0.243

### Operating system

Windows

**Comment by adelf** [comment]
Could you try the main menu > File > Invalidate Caches? It seems PhpStorm doesn't see the Collection class...

**Comment by almesery** [comment]
thanks 👌
