### ISSUE TITLE
[Bug]: Generating from Database table, enum, string needs to be array.

### ISSUE THREAD

**Issue by alturic** [laravel-idea/plugin#1113]
### Bug description

When generating a model from a database table that has an enum column, the plugin generates `$table->enum('country', 'US', 'Canada');` when it should be `$table->enum('country', ['US', 'Canada']);`

### Plugin version

9.0.0.243

### Operating system

Windows

### Steps to reproduce

Generate model from database table with an enum column.

**Comment by adelf** [comment]
Fixed. Thanks!
