### ISSUE TITLE
Can not get Laravel idea to work/show up. 

### ISSUE THREAD

**Issue by Kevin9019** [laravel-idea/plugin#1114]
Hi everyone, 

I have phpstorm on my windows 11 machine. I recently installed laravel idea and activated the license. In my settings i can see laravel idea installed under the languages tab. However, thats the only place where i am able to see it. I do not have the plugin in the tob navigation bar, Ctrl+shift+, does not show op a shortcut helper or anything. I just cant seem to get it to work. 

Does anyone have any idea what i am doing wrong or where its having issues? 

I have a laravel project opened, so it is not the fact im not working in laravel. I can do php artisan commands and the whole bunch. Just when i would like to work with laravel idea i have no clue on how to implement it. 

Looking forward to your response, 

Kind regards, 

Kevin

**Comment by adelf** [comment]
Hello. Please check this in the Settings. It should be "Current state: Enabled". If not, your Laravel installation is not in the root folder, so you can set it there.

![image](https://github.com/user-attachments/assets/e54171c3-82dc-4d4c-8ccd-bff2fe95d6fb)

**Comment by Kevin9019** [comment]
Thank you so much!!
