### ISSUE TITLE
[Request] Add code completion to test `seed()` method

### ISSUE THREAD

**Issue by gtjamesa** [laravel-idea/plugin#112]
Please can you add code completion to the [`InteractsWithDatabase::seed()`](https://github.com/laravel/framework/blob/af8ac1b102648a6e4adb581a2d15286c565747cd/src/Illuminate/Foundation/Testing/Concerns/InteractsWithDatabase.php#L142) method.

![](https://i.imgur.com/gOaWWRU.png)

I would expect to see a list of filenames (minus the file extension) inside the `./database/seeds/` directory. For example, if we have a file at `./database/seeds/RoleSeeder.php`, it will autofill with `RoleSeeder`.

```php
$this->seed('RoleSeeder');
```

**Comment by adelf** [comment]
This is the same:
```
$this->seed(RoleSeeder::class);
```
and PhpStorm completes `RoleSeeder` and `::class` values.

However, it's possible. I'll think about it. Thanks!

**Comment by adelf** [comment]
In the last Laravel versions seeders have a namespace, so, using ::class is more preferable. So, I don’t think it should be implemented. Closing this.
