### ISSUE TITLE
[Help]: Code completion for Inertia

### ISSUE THREAD

**Issue by shafik993** [laravel-idea/plugin#1120]
I'm using [inertia-laravel](https://github.com/inertiajs/inertia-laravel) package to render vue pages, the autocompletion for pages located in /resources/js/Pages works with no problems.
I created another folder for additional vue pages outside the resources filder i.e /clients/xyz/resources/js/Pages . How can I get autocompletion to work for these vue pages when I start typing Inertia::render('pageName')?

Additionally, can I get autocompletion to work if I prefix the pages Inertia::render('xyz::pageName')?

**Comment by adelf** [comment]
Hello.

Please check this setting.

<img width="968" alt="image" src="https://github.com/user-attachments/assets/af6f9690-90d3-40c9-9a74-38a586be38d5" />

**Comment by shafik993** [comment]
Thank you!
