### ISSUE TITLE
[Bug]: generates User model helper from `performance_schema.users` instead of the app schema

### ISSUE THREAD

**Issue by alexkart** [laravel-idea/plugin#1122]
### Bug description

When using **Fetch data from: Connection** with MySQL data source, the plugin fetches system tables and mistakenly uses the `performance_schema.users` table to generate helper code for the `User` model.
It happens if the app db is alphabetically ordered after `performance_schema`, causing the plugin to find and use the `performance_schema.users` table first.
It fetches system tables even when they are not explicitly loaded in the PhpStorm data source. PhpStorm prefetches these system schemas by default, so you need to disable this feature to prevent the plugin from using those tables.
![image](https://github.com/user-attachments/assets/7f640eb7-ca0b-4947-be32-4709fac0e461)
To disable this behavior, navigate to the Data Source properties, then go to **Options** and uncheck **Use pre-introspected objects for system catalogs that are not introspected**.
I believe this behavior should be fixed within the plugin itself. At the very least, a clear note should be added near the **Fetch data from: Connection** setting to inform users about this behavior.

### Plugin version

9.0.0.243

### Operating system

Windows

**Comment by adelf** [comment]
Hello. I tried to fix that, so all these system schemas are in the secondary tables set. So they will be used only if the table wasn't found in the primary set.
I understand that it is better to ask the user not only about connection but also about databases inside... Maybe we will implement it in the future. Thank you for posting this.
