### ISSUE TITLE
[Request] Add inspection for finding unused blade files

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#113]
Could be awesome if I could run an inspection to find all unused blade files 👍

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1404779327556882438

**Comment by olivernybroe** [comment]
@adelf Thanks! Is it made as a inspection or is it an action

**Comment by adelf** [comment]
It will be an action in Code generations. Inspections analyze a file, but here I should analyze a whole project.

**Comment by olivernybroe** [comment]
Alright, awesome 👍

**Comment by adelf** [comment]
4.3.2 version is available.
