### ISSUE TITLE
[Request] Add completion for arguments and options in Artisan commands

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#116]
It would be awesome if you could add argument/option completion in these three scenarios:

1. In the Command class itself, e.g. when typing `$this->argument("` or `$this->option("`.

2. Globally when calling an Artisan command using the Facade, e.g. `Artisan::call("some:command", ["`

3. In `App\Console\Kernel` when adding a command to the schedule, e.g. `$schedule->command("some:command", [")`.

Calling `getDefinition()` on a Command object will return an instance of `Symfony\Component\Console\Input\InputDefinition` which describes all the available arguments and options.

**Comment by adelf** [comment]
Hi, Morten. Good proposition. Thanks.

> Calling getDefinition() on a Command object will return an instance of Symfony\Component\Console\Input\InputDefinition which describes all the available arguments and options.

I can't call any PHP code, so I have to fetch information about parameters by analyzing the command code... Will try to do that.

**Comment by adelf** [comment]
It's implemented in the 4.4.4 version.
