### ISSUE TITLE
[Request] Route parameter auto-completion in route helper method.

### ISSUE THREAD

**Issue by CodeLover254** [laravel-idea/plugin#117]
Are you guys working on a feature to have route parameter completions on controllers? By this I mean, if you have a route defined as Route::get('user/{**id**},'Controller@method)->name('user.grab');  then in a controller when you call return redirect()->route('user.grab',['**id**'=>$the_id]). Autocompletion of the **id** key in the array is what am looking forward to. I have been trying out your plugin and it is so amazing. I saw one of the features listed as route parameter completions but I am confused as to what it exactly means.

**Comment by adelf** [comment]
We will try to implement it in one of the next versions. Thanks.

**Comment by adelf** [comment]
Implemented in 9.1. Sorry it took too long.

**Comment by CodeLover254** [comment]
At least the feature is finally here
