### ISSUE TITLE
env parameter suggestion

### ISSUE THREAD

**Issue by ibrahimabdo** [laravel-idea/plugin#118]
Hello,

Another suggestion that would be cool to have would be for `env(<param>)` function, that should suggest variables defined in `.env` file.

Thank you!

**Comment by adelf** [comment]
Hi, Ibrahim.
I wrote a special plugin for it - .env files support https://plugins.jetbrains.com/plugin/9525--env-files-support

**Comment by ibrahimabdo** [comment]
Ah, I see. I will give it a try.

Thank you!
