### ISSUE TITLE
[Request] Create listener from event listener button

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#119]
As we now have this awesome even listener button on an event, it would be really nice, if we could have a button at the end of the list for creating a new event listener for this specific event.

**Comment by olivernybroe** [comment]
So basically open the create event listener window but prefill with data

**Comment by adelf** [comment]
I can do it the same way as for Eloquent models. With Generate command (Alt-Insert or Command(Ctrl)-N): 
![](https://laravel-idea.com/img/docs/eloquent/factory_generation.gif)

P.S. Seems you have a lot of events and listeners in your project )

**Comment by olivernybroe** [comment]
@adelf We use them extensively 😉 

That would also be really awesome and be good enough for me 👍 

The reason for adding it to the btn is also because that is something you see in a lot of phpstorms own features. For example the run test btn
![image](https://user-images.githubusercontent.com/5870441/93475056-76630480-f8f8-11ea-9365-7be25447289e.png)

**Comment by olivernybroe** [comment]
Just wanted to say that I recently googled this one again as I wanted to do this today 👍 

Used the generator hotkey class instead which is awesome
![image](https://user-images.githubusercontent.com/5870441/117121514-fa3d0480-ad94-11eb-85dc-2d71165e61a3.png)

**Comment by adelf** [comment]
<img width="361" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/efdedd2e-3986-4a9b-8b17-5dbf0cf3f644">

Implemented some versions ago)
