### ISSUE TITLE
Laravel migrations increments() default behavior changed since 5.8

### ISSUE THREAD

**Issue by gorbunov** [laravel-idea/plugin#12]
Laravel migrations use ->bigIncrements('id') since 5.8, doesnt' match with code generated by plugin. This leads to problems with foreign_keys are unable to be created, if referenced field doesnt match int type exactly.

**Comment by adelf** [comment]
I just released 2.1... :) Will be in the next update. Thanks.

**Comment by adelf** [comment]
BTW, you can change it here - File | Settings | Editor | File and Code Templates | Code | Laravel Ideal Database Migration

**Comment by adelf** [comment]
Changed in 2.2 version
