### ISSUE TITLE
Blade-ui-kit components does not have completion

### ISSUE THREAD

**Issue by bastien-phi** [laravel-idea/plugin#121]
component names and properties are not resolved for https://github.com/blade-ui-kit/blade-ui-kit components.

I'm using laravel idea 3.3.0.202

**Comment by adelf** [comment]
Hi. Yes, blade-ui-kit has dynamic components configuration. I'll try to add package support. Also, there is an idea to add a feature to configure each package's components, views, routes, etc.

**Comment by adelf** [comment]
Implemented a long time ago )
