### ISSUE TITLE
Missing route name completion for routes defined with Route::view

### ISSUE THREAD

**Issue by bastien-phi** [laravel-idea/plugin#122]
I have these routes in my `web.php` file

![image](https://user-images.githubusercontent.com/10199039/93901194-8dd62f00-fcf6-11ea-99ab-95bbf61b4978.png)

but completion shows me this 

![image](https://user-images.githubusercontent.com/10199039/93901476-d68de800-fcf6-11ea-85ac-27530b8e09c7.png)

It looks like defining the route with `Route::view` does not work

**Comment by adelf** [comment]
You're right! Thanks! :) I'll fix it soon.

**Comment by adelf** [comment]
Fixed in 3.4 version.
