### ISSUE TITLE
[bug] Read properties are included in autocompletion on create

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#123]
In our application we have some model attributes which are read-only, meaning they only have an attribute getter, no setter.

We mark them in phpdoc by using
```
@property-read bool a_read_only_property
````

However these fields are suggested in the autocompletion on factory create on that model
![image](https://user-images.githubusercontent.com/5870441/93996475-98460680-fd92-11ea-867f-c32f62a80b69.png)

phpstorm is able to handle that these properties are read only 
![image](https://user-images.githubusercontent.com/5870441/93996535-ad229a00-fd92-11ea-9304-3804d66785ae.png)

**Comment by adelf** [comment]
Hi. Yes. In some cases, it's hard to understand whether read properties allowed there. 
`User::all()->where('')` - here they are ok. `User::where('')` - here they aren't.
However, for `create` and some other methods I can try to hide them. Thanks!

**Comment by olivernybroe** [comment]
@adelf Awesome :)

Yeah I get that, for me I think the most important places would be
- `Model#create`
- `Model#update`
- `factory#create`

but it is tough, because as you say, you can use them in Collection methods but not in query builder methods

**Comment by adelf** [comment]
I removed them from some methods, like `create`, `update`, etc. Also implemented special "virtual properties only" completion for some methods. I'm sure there are still some wrong completions, but they will be fixed time by time.

**Comment by olivernybroe** [comment]
Will report specific usecases when I find any!
