### ISSUE TITLE
[Request] Add inspection about env function usage outside config

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#124]
In Laravel you cannot cache your config file if you call `env` function from outside the config files.

Or rather you can, but the env method will always return null of your config files are cached.

My proposal is adding a simple inspection for warning the user about this.
https://laravel.com/docs/8.x/deployment#optimizing-configuration-loading

My current solution is just doing this in phpcs by disallowing env function.

**Comment by adelf** [comment]
I have this task in my internal tracker more than 6 months )) but thanks
for creating it here!

**Comment by adelf** [comment]
Added in 3.5.
