### ISSUE TITLE
[Request] Add autocompletion for optional

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#125]
It would be nice to have autocompletion for `optional` method in Laravel.

Think I had this at a point, just can't remember if it was this package which did it our something I had in `.phpstorm.meta.php`

**Comment by adelf** [comment]
I think it's the same as `tap()`. Added it to Laravel Idea's internal `.phpstorm.meta.php`

**Comment by adelf** [comment]
BTW, thank you for your [requests] :)

**Comment by olivernybroe** [comment]
@adelf Haha no problem, It looks like it is catching on in this repo 👍 

I mainly do it because it makes it easier for myself to look through notifications.

**Comment by adelf** [comment]
I mean, thank you for sharing all your requests about the plugin. They help a lot.

**Comment by olivernybroe** [comment]
@adelf Ah, no problem 👍 

Basically I just open an issue each time I stumble upon something I am trying to solve, which the IDE could help me do better.

Love this plugin and the speed of which you get new features out is soo nice. Not something I would expect even for a paid product ❤️ 
Will keep opening issues when I stumble upon something that could be better

**Comment by adelf** [comment]
Added to 3.4 version.
