### ISSUE TITLE
[bug] Localization key generation not working with .blade files outside resources path

### ISSUE THREAD

**Issue by mvalim** [laravel-idea/plugin#127]
If I use the shortcut Alt+Insert on a .blade file that is stored in the [main]/resources/, or any plain PHP file, the shortcut works perfectly, but in one of our applications we have the following structure [main]/app/Domain/Website/Resources/views, and if I try to use the shortcut when editing .blade files that are stored in any of the Domain/XXX folders it does not show the option to generate the key, shouldn't the shortcut work in every blade file, regardless of where it is saved?

PhpStorm 2020.2.2
Build #PS-202.7319.77, built on September 23, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

**Comment by adelf** [comment]
I'll take a look. Thanks for reporting!

**Comment by adelf** [comment]
Fixed in 3.4 version.
