### ISSUE TITLE
Seeder in wrong directory

### ISSUE THREAD

**Issue by DylanDec** [laravel-idea/plugin#128]
If I create a seeder, it doesn't make a seeder in the right directory (where the DatabaseSeeder is located).

![image](https://user-images.githubusercontent.com/14364739/94609606-525fd580-029f-11eb-96b4-486ebe05db5b.png)

Latest version of laravel & laravel idea

**Comment by adelf** [comment]
Hi. It is fixed in the next version, which will be released soon. For the current one you can configure the path here - https://laravel-idea.com/docs/generation#configuration

**Comment by adelf** [comment]
Fixed in 3.4 version.
