### ISSUE TITLE
Adding multiple and/or sub-directories to blade-x settings

### ISSUE THREAD

**Issue by cbaconnier** [laravel-idea/plugin#13]
Hi, first of all thank you very much for your work! I was not expecting a blade-x support and it blew my mind!

However, I'm decoupling my components in sub-directories and it's kinda frustrating to not be able to use it on all the components.

```
/components
    - /form
    - /icons
    - /buttons
    - /...
    - aTopLevelComponent.blade.php
```

In my case I only need sub-directories, but I'm guessing that in the near future, someone will asks for different directories.  Maybe, we could add the folders separated by a comma?

**Comment by adelf** [comment]
Hi, Clement.
I'm glad you liked it. Yesterday I heard that this syntax will be in the Laravel 7 core also :)

I'm not familiar with blade-x so much. How do you register these folders? 

```
BladeX::component('components.*');
BladeX::component('components.forms.*');
```

Like that? So, each folder components are used without any prefixes? components/forms/myButton.blade.php -> <my-button> ?

**Comment by cbaconnier** [comment]
I can't wait to use Laravel 7 :)
Hopefully the migration from blade-x to laravel 7 will be easy.

I'm registering them like that
```php 
$bladeX = $this->app->get(BladeX::class);
$bladeX->components([
    'components.*',
    'components.form.*',
    'components.icons.*',
    ]);
```

I organizing the files like that
```
components/form/textField.blade.php
components/form/dateTimeField.blade.php
components/icons/commentIcon.blade.php
components/icons/sortFieldIcon.blade.php
```

Then I use them without prefix.

```html
<text-field name="email" :value="$user->email" label="E-mail"/>
<comment-icon :count="$task->comments_count">
```

**Comment by adelf** [comment]
Thanks. I can this to the next 2.2 version.

**Comment by adelf** [comment]
I added recursive scanning and comma separated components path. Please check 2.2 version

**Comment by cbaconnier** [comment]
I tested with the recursive scanning and it's working great! Thank you very much!

*Note; It was initially not working because I had added the tags to "custom tags" in PHPStorm.
To remove them I had to go in **Settings** -> **Editor** -> **Inspection** -> **Html** -> **Unknown HTML tag attribute**.*
