### ISSUE TITLE
[Request] Improve completion support when using the Shallow Nesting

### ISSUE THREAD

**Issue by hagishi** [laravel-idea/plugin#131]
```
Route::resource('photos.comments', CommentController::class)->shallow();
```

Now, The following route name suggestions appear.

<table>
  <thead>
  <tr>
  <th>Route Name</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td>photos.comments.index</td>
  </tr>
  <tr>
  <td>photos.comments.create</td>
  </tr>
  <tr>
  <td>photos.comments.store</td>
  </tr>
  <tr>
  <td>photos.comments.show</td>
  </tr>
  <tr>
  <td>photos.comments.edit</td>
  </tr>
  <tr>
  <td>photos.comments.update</td>
  </tr>
  <tr>
  <td>photos.comments.destroy</td>
  </tr>
  </tbody>
  </table>

---

The correct route name is below.

<table>
  <thead>
  <tr>
  <th>Route Name</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td>photos.comments.index</td>
  </tr>
  <tr>
  <td>photos.comments.create</td>
  </tr>
  <tr>
  <td>photos.comments.store</td>
  </tr>
  <tr>
  <td>comments.show</td>
  </tr>
  <tr>
  <td>comments.edit</td>
  </tr>
  <tr>
  <td>comments.update</td>
  </tr>
  <tr>
  <td>comments.destroy</td>
  </tr>
  </tbody>
  </table>

**Comment by adelf** [comment]
Thanks for reporting. I’ll try to fix.

**Comment by adelf** [comment]
3.4.2 version is available. It should fix this.
