### ISSUE TITLE
All routes are prefixed with cashier

### ISSUE THREAD

**Issue by goddas** [laravel-idea/plugin#132]
I have this bug after updating to the latest version. All the routing functionality of the plugin is not working, assuming because everything got prefixed with "cashier". 
So when typing  `{{ route(' ` all the suggestions are prefixed with "cashier". Any ideas on how to fix it? The routes themselves are working fine, it's just the plugin thinking everything is prefixed with "cashier" for some reason.

I'm on Laravel 8 (upgraded from 7), plugin version 3.4.1.202

**Comment by adelf** [comment]
Thank you. Will try to fix it soon.

**Comment by adelf** [comment]
3.4.2 version is available. It should fix this.
