### ISSUE TITLE
[Request] Add support for custom view autocomplete parameters

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#134]
v0.6.5 of larastan was just released adding support for a new doctype called `view-string`.

This is to indicate that the string should be a valid view file.

It would be awesome if this plugin also supported that, so all package maintainers can just add that doctype and then autocompletion works.

https://github.com/nunomaduro/larastan/releases/tag/v0.6.5

**Comment by adelf** [comment]
I decided to don't do it due to performance reasons. However, view completion can be added by the new `ide.json` files feature: https://laravel-idea.com/docs/ide_json

**Comment by olivernybroe** [comment]
Makes sense, I was hoping performance wouldn't be an issue when using things like their new `PhpCustomDocTagTypeProvider`.
