### ISSUE TITLE
[Improvement] Go-to blade file should remove newlines

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#135]
When viewing the go-to action on blade files and the usage has new lines, it looks a bit weird.

I think it would make sense to trim away newlines from it, maybe replace them with spaces would be even better?

![image](https://user-images.githubusercontent.com/5870441/96551860-3dc99880-12b3-11eb-90a5-626098cce128.png)

**Comment by adelf** [comment]
Fixed in 3.5
