### ISSUE TITLE
[Request] Find actions using search modal

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#137]
Right now we have a lot of handy shortcuts, for example we can find all usages of a blade files, event listeners and so on.

However all of these uses a modal which shows a list, but does not support the build-in search mode in phpstorm.

For example when I use find all class usages in phpstorm, I have to option to show it in the find window instead.
![image](https://user-images.githubusercontent.com/5870441/96711952-a477b080-139e-11eb-8146-f3c74479578f.png)
By doing that I can easily go through all of my results one-by-one and change something. 

However when using laravel idea actions, it does not have this option. 
I stumbled upon this today, because I had to add a new parameter to all the usages of a specific blade file. So instead I had to open them all up at once or go back to the blade file and see all usage and select the next one in the dropdown.

Hope changing this is not a big task 👍

**Comment by adelf** [comment]
You can try to make Find usages in the view file:
![image](https://user-images.githubusercontent.com/2818394/96713036-acd4e900-13a8-11eb-9d56-5723af48d577.png)

**Comment by olivernybroe** [comment]
@adelf Awesome, that works for blade files. 

However it doesn't work for events 😄

**Comment by adelf** [comment]
For events, you can use the default Find Usages. So, let me close this.
