### ISSUE TITLE
Add autocompletion for livewire testing 

### ISSUE THREAD

**Issue by Insolita** [laravel-idea/plugin#139]
https://laravel-livewire.com/docs/2.x/testing

Template name for method assertSeeLivewire()

Component data for Livewire::test()->... call/set/emit/assertSet/assertEmit

**Comment by adelf** [comment]
Completion for set() and call() method parameters will also be good, I suppose)

**Comment by adelf** [comment]
What can I complete for `emit/assertEmit`?

**Comment by Insolita** [comment]
Oh... seems it is impossible, events haven't static declarations, it called like `$this->emit('eventName', [...$params]);`

**Comment by adelf** [comment]
True ) BTW, completions for `set`, `call` and `test` is almost ready. Just making the last tests. So, it will be included in the next release.

**Comment by adelf** [comment]
Added in 3.5
