### ISSUE TITLE
no reply from 	licenses@laravel-idea.com

### ISSUE THREAD

**Issue by Nothing-Works** [laravel-idea/plugin#14]
Hi I emailed this address `licenses@laravel-idea.com` and asking about a student license I provided my username and email address registered with Jetbrains. But have not got any reply, is it still available for student license?

**Comment by adelf** [comment]
Hi, Andy.

I've sent all requests, including yours, to JetBrains, but seems this employee doesn't work today. Is it urgent for you?

**Comment by Nothing-Works** [comment]
@adelf  no, it's not urgent at all, just wondering what's happening. Thank you very much.
