### ISSUE TITLE
Jump to policy doesn't work when using auto-discovery

### ISSUE THREAD

**Issue by MatanYadaev** [laravel-idea/plugin#140]
Jump to policy doesn't work when using the [auto-discovery](https://laravel.com/docs/8.x/authorization#policy-auto-discovery) feature.

When explicitly defining policies in the `$policies` array variable, the jump to policy works great. The issue is only with the auto-discovery.

**Comment by adelf** [comment]
I think I can try to add it. Thanks!

**Comment by MatanYadaev** [comment]
@adelf Great! Thanks.
I've started using Laravel Idea today, it works amazing. Great job. 🙏

**Comment by adelf** [comment]
It will be added in the next version but for now, it will work only if the second parameter with known type is provided.

**Comment by adelf** [comment]
Added in 3.5
