### ISSUE TITLE
[Request] add "Go To declaration" ability for URL Facade

### ISSUE THREAD

**Issue by anhofmann** [laravel-idea/plugin#142]
When I'm in a blade template, I can press `ctrl+b` on a `route()` name to get to the route implementation. It would be great if this would also work on the URL Facade like `URL::signedRoute('my.route.name')`

**Comment by anhofmann** [comment]
Another thing: my workflow here is that I want to go to the controller method that implements the route. So I have to press `ctrl+b` to get to the route definition and there press `ctrl+b` again on the controller method. It would be really great if I could press `ctrl+alt+b` (To trigger the "Go To Implementations" action) on the `route()` name and get directly to the controller method that implements the route.

**Comment by adelf** [comment]
I added "signedRoute" and "temporarySignedRoute" method parameters completions. Going to release a new version this week. Not sure about the next one. Maybe sometime in the future. And better to create a new issue for it ) This one will be closed after releasing the next version.

**Comment by adelf** [comment]
Should work in the 3.5 version.
