### ISSUE TITLE
Add support for detecting Laravel Zero

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#145]
Right now it seems like the plugin does not have support for Laravel Zero 👍 

It would be cool if it could auto enable itself if Laravel Zero also 😄

**Comment by adelf** [comment]
Done :)

**Comment by olivernybroe** [comment]
That's a new record, 11 minutes 🥇

**Comment by adelf** [comment]
11 minutes to add one line of code... yes. it's a record )

**Comment by adelf** [comment]
Added in 3.5
