### ISSUE TITLE
Incorrect namespace when creating tests in modules

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#146]
![image](https://user-images.githubusercontent.com/10347617/99395739-e9d1c400-28f1-11eb-9d4f-9070b0396d76.png)

![image](https://user-images.githubusercontent.com/10347617/99395769-f35b2c00-28f1-11eb-9803-e88f0fd243cd.png)

If you use the `art module:make-test BarTest V3` command to generate, you get the correct path:

![image](https://user-images.githubusercontent.com/10347617/99395848-0ff76400-28f2-11eb-9b10-bc82e6d05531.png)

Module package is `nwidart/laravel-modules`.

**Comment by adelf** [comment]
Thanks.

**Comment by adelf** [comment]
Fixed in 3.5

**Comment by andrey-helldar** [comment]
Thanks
