### ISSUE TITLE
Blade component views directory

### ISSUE THREAD

**Issue by RJFares** [laravel-idea/plugin#148]
I have a private library, based as a subdirectory, such as [root]/packages/[company_name]/[the_private_library].
The library is added into composer.json as a local file, so symlinked by composer automatically into the vendor folder.

The only blade components that are loading are the ones found in [root]/resources/views/components (as set in the plugin settings) and the x-jet-___ .
How can I configure, or is it possible, to get the components inside that library to get discovered and appear in auto-complete?
I tried adding that folder into the plugin settings and it worked, but there doesn't seem a way to add more than one folder (the [root]/resources/views/components AND [root]/packages/[company_name]/[the_private_library]).

**Comment by adelf** [comment]
Hi. I'm going to implement support for special files, like `ide.json` where package writers and plugin users can configure everything: blade components, views, route files paths, etc. But it will be in the next major version. 
For now... plugin analyzes all ServiceProvider classes and tries to find component paths there. How do you register components in your service provider?

**Comment by RJFares** [comment]
That's good to know.
I'm mimicking the jetstream way, but instead of registering each file one by one as they did, I'm iterating over all blade files by code and adding them into an array, cleaning the name and then something like:

```
$this->loadViewComponentsAs('mc', $componentViews);
$this->loadViewsFrom(__DIR__.'/../resources/views', 'mc');
//and finally alias them
[...]
Blade::component("mc::$dirName.$filename", "$dirName.$filename");
```

**Comment by adelf** [comment]
Yes. I had to write special support for JetStream. There is no way to configure your package yet. But soon it should be possible by custom configuration files, like `ide.json`.

**Comment by iksaku** [comment]
Question about this...
It means that I could include a `ide.json` file in my own packages and Laravel Idea will automatically pick it up from vendor as well? Or will only apply for _project root_?

**Comment by adelf** [comment]
@iksaku these files are basically for packages. But, of course, they can be used in the project also.  And yes, the main idea is to create some kind of standard for libraries to create these files to help IDE's(not only me) to complete everything. Routes, blade views, blade components, livewire components, etc. And everything with correct namespaces.

**Comment by RJFares** [comment]
@adelf I saw v4 resolved the issue! What's missing is only identifying the alias.
Currently it's identifying <x-my::text/>
I have an alias which removes the need for "my" inside my package service provider, so that in my projects I'm using <x-text/>.
Is it on the roadmap to identify the custom alias of packages?

**Comment by adelf** [comment]
Could you show how you register your components?

**Comment by RJFares** [comment]
Here goes:

for each layout in the package, I'm following the "jet" way, so
`Blade::component("mc::layouts.$filename", "$filename-layout")
`which would render `<x-guest-layout> [...] </x-guest-layout>` for file (base_path/package_name/[etc...]/views/layouts/guest.blade.php)

for each component in components dir, ie  (base_path/package_name/[etc...]/views/components/text.blade.php), I'm using
`Blade::component("mc::components.$name", $name)
` so that I can call `<x-text>A text</x-text>`


I'm following the same pattern for any other component I have, by calling Blade::component on each of them to alias them properly.

**Comment by adelf** [comment]
Ok. Thanks. The main issue is that I can't run PHP code in the plugin. Well, I can but don't want to :)
So, I can't understand all these magic component creations. However, I'm preparing some `ide.json` files support. In the next or one of the next version, you will have the ability to write something:

```
{
  "blade": {
    "components": [
     {
       "view_path": "base_path/package_name/[etc...]/views/components",
       "namespace: ""
     }
    ]
  }
}
```

And everything will work. I hope it will be the next version which is going to be released next week.

**Comment by RJFares** [comment]
I wanted to mention that if the PHP code is an issue, you may be able to create a box inside the plugin settings where the user can make those customizations manually if automatic plugin detection of the Blade::component is too much work.
I'll be waiting for the ide.json to see how it works so that the above would not be necessary.

**Comment by adelf** [comment]
https://laravel-idea.com/docs/ide_json

This file should help:
```
{
"$schema": "http://laravel-ide.com/schema/laravel-ide-v1.json",
"blade": {
        "components": {
            "viewPaths": [
                {
                    "path": "directory/with/blade/component/views",
                    "namespace": "namespace"
                }         
            ]
        }
    }
}
```

**Comment by RJFares** [comment]
I just tried with the ide.json.
Although there is autocomplete, but on clicking the component, it does not go to it if that component reference was from ide.json, nor does it autofill the props.
Also, in your opinion, would it be a good idea to replace the duplicate components?
ie, when I added the folder path to the custom components, I'm getting for each component 2 entries: 
<x-text> let's say and <x-PREFIX-text>

**Comment by RJFares** [comment]
I just tried with the ide.json.
Although there is autocomplete, but on clicking the component, it does not go to it if that component reference was from ide.json, nor does it autofill the props.
Also, in your opinion, would it be a good idea to replace the duplicate components?
ie, when I added the folder path to the custom components, I'm getting for each component 2 entries: 
`<x-text> let's say and <x-PREFIX-text>`

It might be a problem with my understanding of the json markup maybe, or the fact that it's available in a next release?
Here's my config:
`{
"$schema": "http://laravel-ide.com/schema/laravel-ide-v1.json",
"blade": {
        "components": {
            "viewPaths": [
                {
                    "path": "packages/[...]/ANAME/resources/views/components",
                    "namespace": "",
                    "prefix": "",
                    "viewNamespace": "ANAME"
                }
            ]
        }
    }
}
`
The end result is to get <x-txt> from a blade file called txt inside the above path

**Comment by adelf** [comment]
I tried to repeat your case.
Usual Laravel app:
```
$this->loadViewsFrom(__DIR__.'/../../resources/anotherViews', 'mc');
```
and `text.blade.php` in the `/resources/anotherViews/components` directory. Laravel Idea completes `<x-mc::text>`.
I add ide.json:
```
{
    "$schema": "http://laravel-ide.com/schema/laravel-ide-v1.json",
    "blade": {
        "components": {
            "viewPaths": [
                {
                    "path": "resources/anotherViews/components",
                    "namespace": ""
                }
            ]
        }
    }
}
```

And Laravel Idea completes only `<x-text>` and GoTo to the correct view file... Are we missing anything? I didn't add a `$this->loadViewComponentsAs('mc', $componentViews);` call since there is a variable, so Laravel Idea also should ignore it.

**Comment by RJFares** [comment]
Resolved.
I removed "viewNamespace" and everything worked.
Awesome!

**Comment by adelf** [comment]
Yes. Sorry, I forgot to say that viewNamespace should be "mc" in your case I suppose... it's added to support the cases when a user copies the package views to the `resources/views/vendor/mc/components` folder and wants to change them. For this case viewNamespace: "mc" can help to GoTo to these files instead of the package folder.

**Comment by isaackearl** [comment]
Any update on this?  
It's a very important feature for me and I can't figure out how to configure the ide.json file.

I am using wireUI blade/livewire components, and I would really like the code completion.
