### ISSUE TITLE
Change language in language files

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#149]
# Problem
So in our project we have multiple languages, we use the json files for storing all of the strings in the different languages.

However opening one of these files up are really annoying when dealing with non-english languages, as it marks half of the words as a spelling error.
![image](https://user-images.githubusercontent.com/5870441/99539485-970a1200-29ae-11eb-80a2-2727b48bc863.png)

# Solution 
I suggest a new feature which automatically changes the language of all the values in the key/value array to the language of the file. If PhpStorm does not support this language, then just ignore spelling errors.

# Current solution
Right now it can be solved by adding multiple languages to the proofreading
![image](https://user-images.githubusercontent.com/5870441/99539768-f10ad780-29ae-11eb-8e99-57c136e02002.png)
However this applies it to all files, which means I have now allowed danish words in all files, but I only want to allow them in `da.json`.

# Alternative current solution
It can also be solved by not adding the proofreading scope, but just ignoring the highlighting on a scope which selects the language files.

**Comment by andrey-helldar** [comment]
PhpStorm automatically detects the language of the text. This does not apply to the plugin.
You can manually change the rules of conduct in other languages:

![image](https://user-images.githubusercontent.com/10347617/101485453-3d24b880-396c-11eb-8e87-07b8d3c04fdb.png)

**Comment by adelf** [comment]
There are no extension points for that.
