### ISSUE TITLE
With dot notation autocompletion when relationship in trait

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#15]
Hi thanks for this amazing plugin,

So I wanted to use the autocompletion for with statements, on the following code
```
Hire::with([
            'company.primaryProfile',
        ])
```

However it is not able to find the relationship `primaryProfile`. It is able to find other relationships in Company model, so it's not because it doesn't find the model. However the relationship `primaryProfile` is defined in a trait used by the model and it looks like it doesn't look for relationships in traits.

**Comment by adelf** [comment]
Hi, Oliver.
Laravel Idea currently uses fields and relations from phpDocs generated by laravel-ide-helper. Is `primaryProfile` relation there? 
```
$company = new Company();
$company->
```
Does PhpStorm autocompletes `primaryProfile` here?

**Comment by olivernybroe** [comment]
@adelf Yes, PhpStorm can autocomplete it. It might be because there is phpdocs for it, but the docs are on the trait itself like so
```php
/**
 * @property Profile primaryProfile
 */
trait HasProfiles {
    /**
     * Get the users primary profile.
     *
     * @return BelongsTo
     */
    public function primaryProfile(): BelongsTo
    {
        return $this->belongsTo(Profile::class);
    }
}
```

**Comment by adelf** [comment]
Got it. Thank you. I'll try to fix.

**Comment by adelf** [comment]
Should work in the 2.2 version

**Comment by olivernybroe** [comment]
Amazing! It works perfectly 👍
