### ISSUE TITLE
[Request] - Support for Laravel actions (laravelactions.com)

### ISSUE THREAD

**Issue by anyb1s** [laravel-idea/plugin#150]
I am not sure how many people use this package; it is very useful to isolate logic into classes and have everything in one place. 
Would you consider adding support for it; like you have for laravel modules?
Features could include generating action classes, autocomplete on validation/authorization.

**Comment by adelf** [comment]
It's pretty easy... what do you mean by "autocomplete on authorization"?

Complete `$this->can()` first parameter?

**Comment by anyb1s** [comment]
Sorry for the vague explanation, did not expect much attention to it.

Yes, exactly what you posted, to autocomplete the gates as we have it auth()->user()->can(...), @can(...)
Autocompleting attributes (similar workflow as the form request objects, I know they are completely different in terms of logic)
Validation rules autocompletion would be an awesome feature.
Maybe action class generation as it has artisan command for creating classes.

These are all just ideas, seeing more & more people starting to use the package and they would benefit from such a feature.
Thank you for the amazing work you do with this plugin!

**Comment by adelf** [comment]
3.6 version is available. I think most completions should work. Please, report here or in the new issue if something doesn't.

**Comment by anyb1s** [comment]
Holly Molly, you are amazing!
It works perfectly! Thank you so much for insanely quick response on this!
That's why this plugin is the best!

**Comment by adelf** [comment]
Thank you :)
