### ISSUE TITLE
Phpstorm hints wront Model::paginate() return 

### ISSUE THREAD

**Issue by nicolasbinet** [laravel-idea/plugin#153]
Hi,
When using ::paginate on an Eloquent model and returning that query, Phpstorm suggests the return type to be
"\LaravelIdea\Helper\App\Models\_JournalQueryBuilder". instead of LengthAwarePaginator

Here is the basic code we're using.

```
/**
 * Archive list
 *
 * @return LengthAwarePaginator
 */
public function archive(): LengthAwarePaginator
{
    return Journal::orderBy('created_time', 'desc')
                ->paginate(30);
}

```

Can the _ide_helper_models include paginate as well as other Eloquent methods ?

Thanks for your help.

Nicolas

**Comment by adelf** [comment]
I think there should be `_JournalCollection|LengthAwarePaginator`. Thank you. Will be fixed.

**Comment by nicolasbinet** [comment]
@adelf Thanks for your answer.
Still trying the plugin but loves it !

**Comment by adelf** [comment]
3.6 version with fix is available.
