### ISSUE TITLE
Blade @yield directive with default value is interpreted as a whole section name

### ISSUE THREAD

**Issue by MaksTech** [laravel-idea/plugin#154]
Basically, if parent layout has something like:
```
@yield('test-section', 'default-value')
```
Then, in a child component that extends the parent, when writing the section directive, `test-section, default-value` is interpreted as a name for that section, instead of just `test-section`:  

![image](https://user-images.githubusercontent.com/25028046/99826471-16d7de00-2b61-11eb-8906-1b480b335ad7.png)

**Comment by adelf** [comment]
This completion is from the old Laravel plugin. However, I don't know why I don't complete here. Let me check.

**Comment by adelf** [comment]
Clear test without old Laravel plugin:

![image](https://user-images.githubusercontent.com/2818394/121937667-9aeaf080-cd53-11eb-8122-02dd0c7d639e.png)

Better to delete it...
