### ISSUE TITLE
No namespace specified for Database Class Factory creation

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#156]
Plugin version: 3.5.0.202

![image](https://user-images.githubusercontent.com/10347617/99948003-d3ac8380-2d89-11eb-97da-45a17969711b.png)

![image](https://user-images.githubusercontent.com/10347617/99948056-e4f59000-2d89-11eb-80f9-db36fa3a8a04.png)

![image](https://user-images.githubusercontent.com/10347617/99948134-02c2f500-2d8a-11eb-9f6e-b81e89f3f38f.png)

![image](https://user-images.githubusercontent.com/10347617/99947925-baa3d280-2d89-11eb-9523-ea655eeb2f64.png)

**Comment by andrey-helldar** [comment]
Step 2: change namespace

![image](https://user-images.githubusercontent.com/10347617/99948533-ab715480-2d8a-11eb-9d5a-438c410f571a.png)

![image](https://user-images.githubusercontent.com/10347617/99948568-b4fabc80-2d8a-11eb-94a4-856834927076.png)

![image](https://user-images.githubusercontent.com/10347617/99948590-ba580700-2d8a-11eb-8a8a-ed2320c56209.png)

![image](https://user-images.githubusercontent.com/10347617/99948606-c0e67e80-2d8a-11eb-9763-b2924fb70ee1.png)

![image](https://user-images.githubusercontent.com/10347617/99948634-c80d8c80-2d8a-11eb-9caf-204b2f35b939.png)

**Comment by adelf** [comment]
Migrations are not in the `app` folder, so you should choose "In directory" here. It's the default value.

![image](https://user-images.githubusercontent.com/2818394/99950854-428bdb80-2d8e-11eb-8d35-e9b0dc7edc45.png)


BTW, what is wrong with your User class name? :)

**Comment by andrey-helldar** [comment]
> BTW, what is wrong with your User class name? :)

https://github.com/laravel-idea/plugin/issues/40

**Comment by adelf** [comment]
So, `Authenticatable` there for some kind of universal policies?

**Comment by andrey-helldar** [comment]
Right.

I have three different models for implementing user authentication. Don't ask why - that's how it should be.

There are places where authentication should only be for `User`, there is only for `Employer` and there is only for `Workplace`. In addition, there are places where any of them must be authorized, in this case the definition of the `Authenticatable` contract is used.

**Comment by adelf** [comment]
Maybe I should automatically add `Authenticatable` as the option for policy creation if there is more than 1 "user" class?

**Comment by andrey-helldar** [comment]
> Migrations are not in the `app` folder, so you should choose "In directory" here. It's the default value.

It's works! Thanks!

![image](https://user-images.githubusercontent.com/10347617/99957028-15442b00-2d98-11eb-90ee-e6cf3012134f.png)

![image](https://user-images.githubusercontent.com/10347617/99957049-1f662980-2d98-11eb-82f4-acf943f3e227.png)

![image](https://user-images.githubusercontent.com/10347617/99957066-242add80-2d98-11eb-8f99-f97e76f2fd92.png)

**Comment by andrey-helldar** [comment]
> Maybe I should automatically add `Authenticatable` as the option for policy creation if there is more than 1 "user" class?

A good idea)
