### ISSUE TITLE
Add go to method in routes folder

### ISSUE THREAD

**Issue by bubaluza** [laravel-idea/plugin#159]
The functionality "go to method from a router function" works on default routes files (e.g. api.php, web.php, etc) but does not work in a included file  from the defaults routes files.

for example: I have my api routes in api.php inside routes folder. If I include a new route file inside api.php then the new file will not work "go to in method".

-routes folder
---api.php
---new folder
------new route file included

**Comment by adelf** [comment]
This is still not supported. There is a workaround by creating a special phpDocs in the route file: https://laravel-idea.com/docs/routing#route-files-recognition

**Comment by bubaluza** [comment]
@adelf thanks for sharing the workaround

> This is still not supported. There is a workaround by creating a special phpDocs in the route file: https://laravel-idea.com/docs/routing#route-files-recognition
