### ISSUE TITLE
Question: different class directory

### ISSUE THREAD

**Issue by Algeneralo** [laravel-idea/plugin#160]
Is it possible to create jobs, controllers, etc.... outside the default App directory?
Like change it from App directory to Domain directory or so on?

**Comment by adelf** [comment]
Sure. Please check https://laravel-idea.com/docs/modules

**Comment by Algeneralo** [comment]
Great!
Thanks for your quick help

**Comment by Algeneralo** [comment]
@adelf 
I tried to change it to second option "Simple directory modules", and then restart PHPStorm, but it still putting all things inside default directory.
Is there anything else that I should do?

**Comment by adelf** [comment]
Yes. Sorry. I'll try to make this more convenient in the future. You can set up what should be created in the modules, or in the main app folder here:
![image](https://user-images.githubusercontent.com/2818394/100602210-a7a67a80-3314-11eb-9ed4-3d612d469d62.png)

**Comment by Algeneralo** [comment]
it's fine, I guess this option is good, you only need to document it so no one get confused when using it.

**Comment by Algeneralo** [comment]
@adelf 
still faceing same issue 
![image](https://user-images.githubusercontent.com/32073999/100602953-97db6600-3315-11eb-8fa8-a13bb4d1e3a1.png)

**Comment by adelf** [comment]
You didn't create any module in your Modules directory

**Comment by Algeneralo** [comment]
@adelf 
Ok got it,works now 
thanks for helping
