### ISSUE TITLE
Autocompletion not working 

### ISSUE THREAD

**Issue by alisanie** [laravel-idea/plugin#161]
OS: Mac OS 11.0.1
PhpStrom : 20.2.4
Larvel Idea: 3.5.0.22
Type of Project : Laravel 8.15.0

Invalid Catch reset :Done ✅
Reinstall Plugin : Done ✅
Generate Eloquent Helper : Done ✅

Hi
First of all thanks for this wonderful plugin.I have two machine with same problem.After using "Generate Helper" every thing is detected by plugin but auto completion not working at all.

Also when I'm generate factory the definition function is empty.

I hope you can solve my problem 

![Screen Shot 2020-12-01 at 4 36 03 PM](https://user-images.githubusercontent.com/1991361/100744964-d5aebc00-33f3-11eb-8701-ec9ebf100bca.png)

![Screen Shot 2020-12-01 at 4 43 15 PM](https://user-images.githubusercontent.com/1991361/100745308-55d52180-33f4-11eb-92c9-503ebe0c4337.png)

**Comment by alisanie** [comment]
After using `php artisan ide-helper:models` problem solved.

**Comment by adelf** [comment]
Hi, Ali.
Do you have your vendor folder marked as Excluded? If so, PhpStorm don't
see the helper file, because it's default location is
vendor/_ide_helper_models.php

**Comment by adelf** [comment]
For some reason, my answer sent by email arrived only now...

**Comment by alisanie** [comment]
No its not! But for your information when I use ` php artisan ide-helper:models` every thing seems to be working but again when I use plugin helper generator the completion stop working .

**Comment by adelf** [comment]
The reason might be the `vendor` directory marked as Excluded. 

https://twitter.com/laravel_idea/status/1334539817263247363

**Comment by alisanie** [comment]
Excluding vendor is not good idea and I never do that. Even in New Project I should always run `php artisan ide-helper:models`!

**BTW I always check your twitter** 😀

**Comment by adelf** [comment]
Sorry, I don't know the reason :) I hope this will be changed when in the 4.0 version a new Eloquent helper code generator will be implemented. For now, you can continue to use `ide-helper:models`

**Comment by alisanie** [comment]
🙏

**Comment by adelf** [comment]
I've made a lot of improvements in the Eloquent helper code generation... so I hope it's fixed now?

**Comment by AstroBoy269** [comment]
The DB column autocompletion isn't working for me, although I'm not 100% if I'm having the same issue or a slightly different one.

OS: Mac OS 11.4 (20F71)
PhpStrom : 2021.1.3
Larvel Idea: 4.3.2.211
Type of Project : Laravel 8.48.2

I have invalidated the caches, reinstalled Laravel Idea, and generated the Eloquent Helper. I'm not getting the DB column completion but oddly I'm getting a warning that Customer::where isn't defined in the model.

![Screen Shot 2021-06-27 at 11 32 54 AM](https://user-images.githubusercontent.com/10376292/123550447-77ed1300-d73b-11eb-9f9e-5ca09d9c1cf9.png)

So I'm not sure if this is an autocomplete issue or an issue where my Model isn't recognized as an Eloquent Model?  Any troubleshooting advice would be greatly appreciated.

Thanks

**Comment by adelf** [comment]
> my Model isn't recognized as an Eloquent Model?

Looks like that... Do you have just `class Customer extends Model` and Model class here is the Eloquent base model class or something different?

**Comment by AstroBoy269** [comment]
We always extend Model and include the `use Illuminate\Database\Eloquent\Model;`.  One thing that might be important is that this project moved the models into a `/database/Models` directory.  Would that cause this issue?

**Comment by AstroBoy269** [comment]
Is there any feedback about autocompletion not working if the project's Models have been moved into a different directory?

**Comment by adelf** [comment]
@AstroBoy269 could you share where are your model files and composer.json psr-4 section?

**Comment by AstroBoy269** [comment]
> @AstroBoy269 could you share where are your model files and composer.json psr-4 section?

Our models are in ./database/Models.  Here's the section from the composer.json 
```
 "autoload": {
        "classmap": [
            "database/migrations"
        ],
        "files": [
            "app/Helpers/GlobalHelpers.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "Baum\\": "vendor/baum/baum/src/Baum",
            "Database\\": "database/",
            "Http\\": "http/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "database/factories"
        ],
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
```

**Comment by adelf** [comment]
I'll check this case. Thank you

**Comment by adelf** [comment]
It might be a problem with excluded `vendor` folder. The new 4.3.4 version fixes it automatically. Please, check.

**Comment by AstroBoy269** [comment]
@adelf updated Laravel Idea this morning and am on version 4.3.4.211.  Then I regenerated the Idea 'Helper Code' and the Idea 'Eloquent Helper Code' which seemed to work just fine.  Unfortunately, PHPStorm isn't recognizing Eloquent helpers like `where` nor is it suggesting column names.  At this point I'm considering _flushing_ PHPStorm and starting from a clean slate to get this feature working unless you have any other ideas.  I appreciate your help with this and know troubleshooting things like this can be very difficult.

**Comment by adelf** [comment]
It should work without "flushing"... 
Does the "Eloquent Helper Code" generation warn about anything? Like "Couldn't find table for some models"?
Do you have files in the `vendor/_laravel_idea` folder? 
is there any folder `vendor` or `vendor/_laravel_idea` with red mark? Like in this tweet? https://twitter.com/laravel_idea/status/1334539817263247363

**Comment by AstroBoy269** [comment]
The `vendor` directory and none of the subdirectories, especially not `_laravel_idea` have been excluded, so no read marks.  The `_laravel_idea` directory does contain files 
```
-rw-r--r--   1 lcr  staff   198707 Jul 21 08:09 _ide_helper_facades.php
-rw-r--r--   1 lcr  staff     2755 Jul 21 08:09 _ide_helper_macro.php
-rw-r--r--   1 lcr  staff     2937 Jul 21 08:09 _ide_helper_macro_static.php
-rw-r--r--   1 lcr  staff  1217335 Jul 21 08:51 _ide_helper_model_builders.php
-rw-r--r--   1 lcr  staff  1020145 Jul 21 08:51 _ide_helper_model_collection_proxies.php
-rw-r--r--   1 lcr  staff  3046262 Jul 21 08:51 _ide_helper_models.php
```

The "Eloquent Helper Code" generation does flag some some missing tables: 
```
8:49 AM	Warnings
					Table not found for \Database\Models\AuditableTypeActivityMappingExact
					Table not found for \Database\Models\AuditableTypeActivityMappingWildCard
					Table not found for \App\Support\DataObjects\CommandTotalsObject
					Table not found for \App\Support\DataObjects\UserEngagementObject
					Table not found for \App\Support\DataObjects\IndividualPerformanceRecipientObject
					Table not found for \Database\Models\TeamCompetition
					Factory class not found for \Database\Models\Aggregates\EventsByUnitGroupUserMonthly
					Factory class not found for \Database\Models\Aggregates\EventsByUnitGroupMonthly
					Factory class not found for \Database\Models\Aggregates\EventsByFacilityMonthly
					Factory class not found for \Database\Models\Aggregates\EventsByUnitMonthly
					Table not found for \Database\Models\TeamMember
					Table not found for \Database\Models\IsolationCodeRoomConfig
					Table not found for \Database\Models\QuietPeriod
					Table not found for \Database\Models\SystemPermission

8:51 AM	Eloquent Helper Code generated successfully
				Eloquent models found: 216
				Show 14 warnings.
				Don't show this again
```

I'll investigate those errors.

**Comment by adelf** [comment]
Have you checked `SomeModelWithoutTableNotFoundError::where()` call?
If you open the `vendor/_laravel_idea/_ide_helper_models.php` file in PhpStorm - does it warn about "File is too big"?

**Comment by AstroBoy269** [comment]
I'm sorry but I'm not sure what you mean about `SomeModelWithoutTableNotFounbError::where()` but if you're suggesting that I try any of the 'not found' tables to see if PhpStorm recognizes the Eloquent function where, I did try that and unfortunately that didn't work and also says `method not found`.

PhpStorm doesn't give me a warning when opening the `_ids_helper_models.php`, although it is a big file for sure.  Although the file does seem to have some kind of errors that PhpStorm is warning about.
![Screen Shot 2021-07-21 at 9 33 31 AM](https://user-images.githubusercontent.com/10376292/126497390-d4a32fbe-07d0-4950-b440-e51971ab419c.png)

**Comment by adelf** [comment]
These errors are interesting, but they can't be the reason for completion issues. 
If it's not under NDA, I can check `_ide_helper_models.php` and all other files in the `vendor/`_laravel_idea` folder. Or we can make a screen-sharing meeting and make it work...

**Comment by AstroBoy269** [comment]
My CTO is a little uncomfortable sharing the data from those files.  However, I'm happy to do a screen-sharing meeting if you like.  I could share a Zoom link if you like.  Let me know what you're comfortable with.

**Comment by adelf** [comment]
@AstroBoy269 ok. Please write adel@laravel-idea.com
