### ISSUE TITLE
Detect custom blade directives

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-idea/plugin#162]
Hey,

first of all thanks for the great plugin!

Is it possible to detect custom blade directives? 

Something like this:
```php
Blade::directive('money', fn ($expression) => "<?php echo number_format((float)($expression), 2, ',', '.') .' '. \"&euro;\"?>");
```

A nice bonus would be to click on the @money and phpstorm goes to the declaration.

**Comment by adelf** [comment]
Is it important to have PHP language injection for these directive parameters?

**Comment by SudoGetBeer** [comment]
I would say yes. Since you can write php in there (usually ?? Or optional()).

**Comment by SudoGetBeer** [comment]
@adelf Thanks!

**Comment by adelf** [comment]
It hasn’t released yet)

**Comment by SudoGetBeer** [comment]
But you implemented it so fast. 

Now I'm waiting patiently

**Comment by adelf** [comment]
3.6 version is available. Blade custom directives should be registered after each project opening. Also new "Register Blade Custom directives" code generation does the same.

**Comment by SudoGetBeer** [comment]
@adelf Working great! Thanks a lot.
