### ISSUE TITLE
Generate Eloquent Helper Code from Database?

### ISSUE THREAD

**Issue by plweil** [laravel-idea/plugin#163]
The docs indicate that there is an option to choose between migrations and the database to generate the Eloquent Helper code. But I don't see this option in Generate Eloquent Helper Code. It would be great to have this, since we are not using migrations in all of our projects. I'm using v3.5.0.202.

![image](https://user-images.githubusercontent.com/1033771/100819857-a22f5a00-3412-11eb-9214-804469942487.png)
-------------------------
(Edit)
When I run the generator, I do get a new` _ide_helper.php` file, but I also get this response:

    1:43 PM	Eloquent Helper Code generated successfully
				Eloquent models found: 34
				Tables not found for 33 models. Show.
				Don't show this again

All of these models have tables. I'm not sure whether I'm getting a complete `_ide_helper.php` file or a half-baked one. Can you please clarify what is going on here?

**Comment by adelf** [comment]
This option is available if the Database plugin is installed. https://plugins.jetbrains.com/plugin/10925-database-tools-and-sql

**Comment by plweil** [comment]
Great! Sorry if I missed that ...

**Comment by adelf** [comment]
No problem. I'll add this to the documentation. Thank you.
