### ISSUE TITLE
Factory class types not working

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#168]
In issue #105, there should have been added support for factory classes, however it seems like this is not working for me at least.
![image](https://user-images.githubusercontent.com/5870441/101457234-8ad1fe80-3935-11eb-9921-64dd01d19b7b.png)
User is not part of it's types.

The same is true for the other syntax.
![image](https://user-images.githubusercontent.com/5870441/101457303-9fae9200-3935-11eb-9634-f6230e98147a.png)

Laravel idea: 3.5.0.203

**Comment by olivernybroe** [comment]
Alright, after regenerating helper files, the first scenario works, however it seems like there is a small issue in the generation.
![image](https://user-images.githubusercontent.com/5870441/101457714-2499ab80-3936-11eb-99d4-d93e1d477961.png)
This field should be optional 👍

**Comment by adelf** [comment]
There were some issues with variadic parameters. Fixed. Thanks. 3.6 version is available.

**Comment by olivernybroe** [comment]
This seems like it is still an issue when using the following syntax
`$offer = OfferFactory::new()->create();`
