### ISSUE TITLE
Table name field is not populated when selecting migration change

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#169]
When we select the "create" item, there are no problems:

![image](https://user-images.githubusercontent.com/10347617/101484950-7d376b80-396b-11eb-9e62-e2106a672afc.png)

But when we choose "change", then:

![image](https://user-images.githubusercontent.com/10347617/101485172-d3a4aa00-396b-11eb-96f1-a7f3c4cdce75.png)

**Comment by adelf** [comment]
Do you have many migrations with "change_some_table" name? What about migration names uniqueness?

**Comment by andrey-helldar** [comment]
В названии файла я пишу что происходит внутри.

For example:

![image](https://user-images.githubusercontent.com/10347617/101501749-2ccb0880-3981-11eb-8b98-31a75ea386f0.png)

**Comment by andrey-helldar** [comment]
Version `4.3.2.211` - some problem.

![image](https://user-images.githubusercontent.com/10347617/122587102-1c999180-d066-11eb-8411-484bd8409336.png)
![image](https://user-images.githubusercontent.com/10347617/122587109-1f948200-d066-11eb-82e4-77adf3f200fc.png)
![image](https://user-images.githubusercontent.com/10347617/122587113-215e4580-d066-11eb-8ec6-2de2b5055b14.png)

**Comment by adelf** [comment]
The template is this:
make_something_to_employers[_table]
make_something_at_employers[_table]
make_something_from_employers[_table]

**Comment by andrey-helldar** [comment]
Hm...

**Comment by adelf** [comment]
BTW, I like `vaccinated_at` field)) make it not null)

**Comment by andrey-helldar** [comment]
If not null, then:
![image](https://user-images.githubusercontent.com/10347617/122589525-080ac880-d069-11eb-9d4f-251036de9a54.png)

If is null, then:

![image](https://user-images.githubusercontent.com/10347617/122589623-2b357800-d069-11eb-83a9-06ec24c5bc7c.png)

**Comment by adelf** [comment]
Just kidding)
