### ISSUE TITLE
Command signature auto complete in app/Console/Kernel.php

### ISSUE THREAD

**Issue by sautchenkov** [laravel-idea/plugin#17]
Hi! 
```
 $schedule->command('command:signature_wont_auto_comlete')
            ->monthlyOn(1, '02:00')
```

Is it possible to add command signature auto-complete in app/Console/Kernel.php

Thanks!

**Comment by adelf** [comment]
Hi.
Latest Laravel versions auto discovers console commands. So, better to find all inheritors of console command class and complete their signatures... Thanks. Will try to add it to the nearest release.

**Comment by adelf** [comment]
added in 2.3 version. please check and comment if there are some issues.
