### ISSUE TITLE
Values declared in @props within blade components raise "Undefined variable" inspection problem

### ISSUE THREAD

**Issue by orchidcode** [laravel-idea/plugin#170]
Screens from default Laravel 8 installation.

![Zrzut ekranu 2020-12-9 o 19 53 27](https://user-images.githubusercontent.com/23462863/101674007-38d5c980-3a58-11eb-9cd4-7b5ff672111e.png)

![Zrzut ekranu 2020-12-9 o 19 54 16](https://user-images.githubusercontent.com/23462863/101674092-573bc500-3a58-11eb-80df-ef7e69eccdf4.png)

**Comment by adelf** [comment]
I added a type resolving for variables declared in @props. It should help.

**Comment by adelf** [comment]
3.6 version is available.
