### ISSUE TITLE
Auto-complete rules from Form Request with methods

### ISSUE THREAD

**Issue by MatanYadaev** [laravel-idea/plugin#173]
Sometimes we split Form Request rules' to a few methods, it can be decided by a variety of reasons (conditions, too long methods, batch rules...).
Laravel Idea doesn't auto-complete rules that arrive from methods. It would be very nice if this feature could be implemented.

Examples:

Laravel Idea auto-completes this code:
```php
class UpdateUserRequest extends FormRequest
{
    public function rules(): array
    {
        if ($this->user()->role === 'admin') {
            return [
                'full_name' => ['required', 'string'],
                'role' => ['string'],
            ];
        }

        return [
            'full_name' => ['required', 'string'],
        ];
    }
}
```

But not this code:
```php
class UpdateUserRequest extends FormRequest
{
    public function rules(): array
    {
        if ($this->user()->role === 'admin') {
            return $this->adminRules();
        }

        return $this->userRules();
    }

    public function adminRules(): array
    {
        return [
            'full_name' => ['required', 'string'],
            'role' => ['string'],
        ];
    }

    public function userRules(): array
    {
        return [
            'full_name' => ['required', 'string'],
        ];
    }
}
```

It could be even nicer if it will be smart enough to recognize `array_merge` and manipulations on the `$rules` variable:
```php
class UpdateUserRequest extends FormRequest
{
    public function rules(): array
    {
        $rules = $this->userRules();

        if ($this->user()->role === 'admin') {
            $rules = array_merge($rules, $this->adminRules());
        }

        return $rules;
    }

    public function adminRules(): array
    {
        return [
            'role' => ['string'],
        ];
    }

    public function userRules(): array
    {
        return [
            'full_name' => ['required', 'string'],
        ];
    }
}
```

**Comment by adelf** [comment]
Hi. Please, check File | Settings | Languages & Frameworks | Laravel Idea | Other Settings
and add your methods there :)

**Comment by MatanYadaev** [comment]
@adelf Thanks for the quick reply.

I didn't notice this setting, it's probably a solution, but not an ideal one.
I have dynamic method names in my app, we have 50+ requests, I think it won't be easy to map all of them, and it will get out-of-date quickly.

Isn't it will be more logical to make it smart and dynamic by design? Is that a complexity issue?

**Comment by adelf** [comment]
It might take a lot of resources. Each string in your code will be checked that way. I can add all "*Rules" methods to the set...

**Comment by MatanYadaev** [comment]
@adelf Sounds great!

**Comment by adelf** [comment]
4.0 version is available.
