### ISSUE TITLE
Auto-complete `$request->validated()` array schema

### ISSUE THREAD

**Issue by MatanYadaev** [laravel-idea/plugin#174]
Laravel Idea auto-complete properties using the `$request->get()` method, but it doesn't auto-complete properties within the `$request->validated()` array.
`$request()->validated()` is safer to use, I would really appreciate implementing this feature.

Example:

Request:
```php
class UpdateUserRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'full_name' => ['required', 'string'],
        ];
    }
}
```

Laravel Idea will auto-complete `full_name` property here:
```php
class UserController extends Controller
{
    public function updated(UpdateUserRequest $request)
    {
        $request->get('full_name'); // `full_name` gets auto-completed
    }
}
```

But not this:
```php
class UserController extends Controller
{
    public function updated(UpdateUserRequest $request)
    {
        $validatedPayload = $request->validated();
        $validatedPayload['full_name']; // `full_name` doesn't get auto-completed
    }
}
```

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
