### ISSUE TITLE
Getting configuration keys when using constants

### ISSUE THREAD

**Issue by kennyhorna** [laravel-idea/plugin#175]
Hey folks! Again, amazing work.

I noticed this today: When using a constant as a configuration key, it doesn't load the depper elements

Example.

```php
# config/integrations.php

use App\Models\Merchant;

return [

    Merchant::ADIDAS => [  // <------
        'api' => [
            'baseUri' => env('XXX'),
            'username' => env('XXX),
            'password' => env('XXX'),
        ],
        // ...
    ];
```

The elements are not listed in the autocompletition
![image](https://user-images.githubusercontent.com/16125117/103234344-74540d00-490d-11eb-98b5-ac0287e11487.png)

But, if I write the key directly:

```php
# config/integrations.php

return [

    'adidas' => [  // <------
        'api' => [
            'baseUri' => env('XXX'),
            'username' => env('XXX),
            'password' => env('XXX'),
        ],
        // ...
    ];
```

Then they are loaded:
![image](https://user-images.githubusercontent.com/16125117/103234434-acf3e680-490d-11eb-97b5-e72285cc3182.png)

**Comment by adelf** [comment]
Hi. I'll try to solve this.

**Comment by adelf** [comment]
4.0 version is available.
