### ISSUE TITLE
Allow separate "sources path" in/outside of modules

### ISSUE THREAD

**Issue by inxilpro** [laravel-idea/plugin#176]
Right now the "Directory modules as composer.json packages" option let's you choose the name of your "sources path" but this overrides the root module as well. The default setup for [InterNACHI/modular](https://github.com/InterNACHI/modular) puts your module source files in `src/` while keeping your app's source files in `app/`.

For example:

- `App\Http\HomeController` is in `[root]/app/Http/`
- `Modules\Demo\Http\DemoModuleController` is in `[root]/app-modules/demo/src/Http/`

We're currently using `src` as "Sources path" and `app-modules` as "Root directory path" which works for all our modules, but it means that when we create a file in the "root module" it's created in `[root]/src/...` rather than `[root]/app/...`

I think the fix would just to add a "Module sources path" and a "Application sources path" or similar. An even more flexible option would be to read the `autoload.psr-4` configuration inside each module's composer.json file, but this would come with the added complexity of handling additional PSR-4 mappings (i.e. Tests).

Thank you again for all your hard work on this!

**Comment by adelf** [comment]
> it means that when we create a file in the "root module" it's created in [root]/src/... rather than [root]/app/...

That is strange. Currently, the `app` folder is hard-coded as the main folder for all root module code files. I just checked the 3.6.1 version, and it creates everything correctly: `app` folder for the Root module and `src` folders for modules.

**Comment by adelf** [comment]
My module settings for InterNACHI/modular project:

![image](https://user-images.githubusercontent.com/2818394/103700547-af150f80-4fb5-11eb-8a4f-38526bc048ba.png)

**Comment by inxilpro** [comment]
Hm. This is what happens for me with plugin version 3.6.1.203 on PhpStorm 2020.3:

https://user-images.githubusercontent.com/21592/103708514-b0771580-4f7e-11eb-9f19-ffb411686911.mp4

**Comment by adelf** [comment]
Found the reason. Thank you. Will be fixed.

**Comment by inxilpro** [comment]
I think it's because I overrode the code generation settings before the module option existed! I'm going to try to revert those back and see if that fixes it.

**Comment by inxilpro** [comment]
No… that didn't fix it.

**Comment by inxilpro** [comment]
Oh, I take that back. It won't revert back. Clicking "Apply" does nothing, and if I hit "OK" and return to the plugin settings, the settings revert:

https://user-images.githubusercontent.com/21592/103711388-53329280-4f85-11eb-815f-fd93d104d04a.mp4

**Comment by adelf** [comment]
It was implemented in one of the previous versions. I hope we can close this now.

<img width="701" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/8c473e2f-55e0-49f4-abe5-1f9d86a7c058">
