### ISSUE TITLE
Support for Livewire Inline Scripts JS in blade files

### ISSUE THREAD

**Issue by ralphschindler** [laravel-idea/plugin#177]
Currently, the livewire JS blade syntax causes JS errors to be emitted in the ide. Syntax such as `@this.get()` or `@this.set()`, specifically the `@` part causes syntax errors.

See: https://laravel-livewire.com/docs/2.x/inline-scripts

![Screen Shot 2021-01-08 at 10 27 42 AM](https://user-images.githubusercontent.com/76674/104040142-e98cd100-519c-11eb-995b-91e249a70263.png)

**Comment by adelf** [comment]
Hi, Ralph. I've done some research. Javascript plugin ECMAScript6 and some other dialects use `@` symbol to support TypeScript Class Decorators: https://www.typescriptlang.org/docs/handbook/decorators.html#class-decorators

The only way is to create a special Javascript dialect for Livewire, based on ECMAScript6 or something else... It's not trivial. I'll try to ask the PhpStorm/WebStorm team for advice.

**Comment by ralphschindler** [comment]
Thats fair, I'll keep an eye on this issue. If you file a YouTrack issue please put that here too. Thanks!

**Comment by fabio-ivona** [comment]
Here's my YouTrack entry about this issue

https://youtrack.jetbrains.com/issue/WI-60091
