### ISSUE TITLE
Eloquent helper file is broken if the method definition is too long

### ISSUE THREAD

**Issue by ozanhazer** [laravel-idea/plugin#178]
I generated the eloquent helper code and everything looked normal except the paginate method:
  
![image](https://user-images.githubusercontent.com/1287658/104095364-6ad08a80-52a7-11eb-93b6-fca1d45b5643.png)

So I checked the generated `vendor/_ide_helper_models.php` file and I noticed that long lines were wrapped so phpstorm is unable to resolve the method:

![image](https://user-images.githubusercontent.com/1287658/104095323-45dc1780-52a7-11eb-8800-3cc60b39c925.png)

Other examples:

![image](https://user-images.githubusercontent.com/1287658/104095523-52ad3b00-52a8-11eb-8a84-8e8e67582aeb.png)

![image](https://user-images.githubusercontent.com/1287658/104095545-74a6bd80-52a8-11eb-935a-0de82570bd22.png)

**Comment by adelf** [comment]
Thank you. Will be fixed.

**Comment by SlyDave** [comment]
This also breaks using the file as a stubFile in PHPStan/LaraStan (https://github.com/nunomaduro/larastan/issues/760#issuecomment-760896034)

**Comment by adelf** [comment]
I removed code formatting in the 4.0 version.
