### ISSUE TITLE
Tables aren't being found for models

### ISSUE THREAD

**Issue by dejagersh** [laravel-idea/plugin#179]
Hello!

I am trying to generate a IDE helper file using the "Generate Eloquent Models Helper Code" feature, but I'm getting the following error:

`Tables not found for 8 models`.

Any idea how I should debug this? I tried both options "From migrations" and "From connection".

**Comment by adelf** [comment]
It might be some models from packages. There is a link “Show models”. It should help.

**Comment by thejager** [comment]
Hi @adelf thanks for your swift reply!

It's not just the package models, it's all the models (except 1 for some reason):

![image](https://user-images.githubusercontent.com/9981548/104108073-0111aa00-52c2-11eb-98a0-296a62fbf03b.png)

**Comment by adelf** [comment]
That’s strange. Do you have any non-standard rules for table naming? Like, non-plural...

**Comment by adelf** [comment]
Or table name prefix?

**Comment by thejager** [comment]
I don't think so!

![Uploading image.png…]()

**Comment by thejager** [comment]
It's a rather standard Jetstream setup, I didn't customise anything.

**Comment by thejager** [comment]
Couple of things I tried to fix it:

- Explicitly set the table in the model: `protected $table = 'users';` 
- I removed my `laravel-ide-helper` helper files, I thought they might have been interferring
- Restart phpstorm 😅

**Comment by thejager** [comment]
Hm, on a fresh Jetstream setup, it does seem to recognise the `User` model and also models that I create afterwards

**Comment by thejager** [comment]
Could it be because I squashed my migrations?

![image](https://user-images.githubusercontent.com/9981548/104108297-b2650f80-52c3-11eb-838b-23c2deb6b6c9.png)

That would be weird, because even if I have use the Connection open, it still doesn't work 🤔

**Comment by adelf** [comment]
Yes. I thought dump files should have at least sql extension... I’ll analyze this and check. Thank you.
About Connection option: do you have one database in your connection?

**Comment by thejager** [comment]
> Yes. I thought dump files should have at least sql extension... I’ll analyze this and check. Thank you.
Hm, I think that file was given to me when I ran the squash command, I doubt I changed it myself to `.dump`

> About Connection option: do you have one database in your connection?

**Comment by thejager** [comment]
Ok so I just noticed there's a small difference between the result of "Connection" and "Migrations". When I use migrations it finds 1 table: `meal_plans`. When I look at my migrations:

![image](https://user-images.githubusercontent.com/9981548/104108415-cbba8b80-52c4-11eb-97cb-bdb81d6c07ad.png)

The rest of my tables are created in the dump file created by squash. Alright, I guess it makes sense that "Migration" option does not work.

Still weird that Connection doesn't work though 🤔

**Comment by thejager** [comment]
The configuration I tried to use for the "Connection" setup:
![image](https://user-images.githubusercontent.com/9981548/104108478-2f44b900-52c5-11eb-877f-9a76a69b8f31.png)

**Comment by adelf** [comment]
If you expand it - is there all these tables? In other word - is this connection active?

**Comment by thejager** [comment]
https://user-images.githubusercontent.com/9981548/104108575-29030c80-52c6-11eb-89a2-595ff1aa5ccf.mov

Nothing shows when I expand when I expand it. Let me see! I never use this feature of phpstorm 😅

**Comment by thejager** [comment]
I pressed the refresh button, got this:

![image](https://user-images.githubusercontent.com/9981548/104108602-623b7c80-52c6-11eb-9ded-8a8c004bff4f.png)

Now I retried and it finds all, except some vendor models that I don't use anyways.

Thank you!

**Comment by adelf** [comment]
I’ll try to Refresh it automatically in the next versions. Thank you.

**Comment by michabbb** [comment]
i am not sure if i am facing the same problem here:

![image](https://github.com/laravel-idea/plugin/assets/3524595/f4d4a240-84d9-4a77-bbe5-2598cc20e3c6)

i do see the helper code and its properties, but still, the IDE gives the warning and none of the properties are being recognized.

the database connection exists, the tables are there, the helper code is there with properties.... very strange.
i did a refresh, deleted all helper files, restarted phpstorm with deleting its cache, nothing helped 😕 

I would be happy if someone could help me here to debug this.

**Comment by adelf** [comment]
@michabbb could you share the table names for these models?

**Comment by michabbb** [comment]
@adelf sure, table names are different than file names

| filename | table name |
|--------|--------|
| ItemOffer.php | item_offers |
| ItemsDiscounts.php | items_discount | 

both models use `protected    $table      = '........';`

**Comment by michabbb** [comment]
just for testing, i renamed the filename, class-name and $table all the same... i still get the same warning 😕

**Comment by michabbb** [comment]
i also tried this in a different project, same warning. has there recently been an update that might cause this ??? 🤔

**Comment by adelf** [comment]
Do you have other Eloquent models in the project? I see there are 5 models, but which of them are in the project and which are in the vendor folder? If yes, please share model class names and tables.

**Comment by michabbb** [comment]
![image](https://github.com/laravel-idea/plugin/assets/3524595/73dad7c6-a90e-4df2-8ed1-daada55c7b96)
these are in my project. the rest is something that was found under "vendor". the generated helper code shows something like:

```php
class DatabaseNotification extends Model {}
class PersonalAccessToken extends Model {}
```

so 3 models inside project and the other two are somewhere under vendor.
but again, the helper code is generated for the 2 models where I get the warning. but phpstorm does not recognize these.

**Comment by michabbb** [comment]
from other issues here i found out that there are some options when it comes to generating helper code in the settings of the plugin. i already tried some stuff there, but still, the properties of the models are unknown.

**Comment by adelf** [comment]
Why are your models located in not PSR filenames? ItemOffer in the item_offers.php files...

**Comment by michabbb** [comment]
since when is that an issue ? ;)

**Comment by adelf** [comment]
I'm trying to find the reason... maybe something strange in the model files?

**Comment by michabbb** [comment]
here´s an example of "item_offers.php" - if something is strange, please let me know ;)

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class item_offers extends Model
{
    public $table = 'item_offers';
    protected $primaryKey = 'ito_id';
    public $timestamps = false;

    protected $connection = 'mysql';

    protected $fillable = [
        'ito_itd_id',
        'ito_creation_date',
        'ito_modified_date',
        'ito_offer_id',
        'ito_offer_status',
        'ito_offer_revision',
    ];

    protected array $dates = [
        'ito_creation_date',
        'ito_modified_date',
    ];
}
```

**Comment by adelf** [comment]
Thank you. I'll check this tomorrow.

**Comment by michabbb** [comment]
@adelf may i ask if you have found anything ? is there anything I can do ? I can also offer you a screen share to debug this. (as a paying customer it´s my interest to solve that mystery)  😏

**Comment by adelf** [comment]
I'm curios why it shows Table not found for App\Models\ItemOffer. But your class name is item_offers.

**Comment by michabbb** [comment]
No, don't be confused. As said earlier, I changed everything, so that

- class name 
- filename
- $table

Is all the same.
Some of my screenshots were old.

I also did:

- checked tables are there in the mysql explorer (schema and tables)
- cleared the phpstorm cache
- deleted the helper files
- checked other projects

So at the end, there are always tables "not found" and I have no clue. Doesn't matter if it's a laravel 8 or 10 project.

So please let me know what you need to help you.

Thanks

**Comment by michabbb** [comment]
maybe you can let me know: which circumstances must be given that a table get´s "found". i guess it makes more sense to check this the other way around. maybe you can let me know which requirements must be set and I can check them one by one. thanks.

**Comment by michabbb** [comment]
@adelf i created a complete fresh new laravel project, duplicated the model "Model/User.php" (and removed some stuff):

https://github.com/michabbb/testing-idea/blob/master/app/Models/Test.php

I generated the helper code:

https://github.com/michabbb/testing-idea/blob/master/_laravel_idea.7z

but got the warning again:

![image](https://github.com/laravel-idea/plugin/assets/3524595/215d014b-6538-4968-bb96-834611d79944)

so with my demo repo, maybe you can test yourself, let me know if I am doing something wrong or whatever.

i am working under Linux with:

```
plugin version: 7.1.4.231
PhpStorm 2023.1.3
Build #PS-231.9161.47, built on June 22, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-75-generic
Current Desktop: KDE
```

thanks !! 🙏

**Comment by adelf** [comment]
This message is correct. This project doesn't contain a migration for the "tests" table.

**Comment by michabbb** [comment]
finally we are getting to the point: so.......... to make this all work we "always" need a migration file ??
is there any alternative to that, let´s say creating the "@property" in the doc blocks of the model file ?

**Comment by adelf** [comment]
> to make this all work we "always" need a migration file ??

No. If you use the database connection for Helper code.

**Comment by michabbb** [comment]
> No. If you use the database connection for Helper code.

in that case, I am there, where it all started. in all my projects I have that connection.
okay, so I will use my test-project here and will create a database, will setup a connection
and then, I shouldn´t see that warning and idea should be able to fetch all columns. 

i am pretty sure that won´t work, because it doesn´t in my other projects, but anyway... i will test.....

**Comment by michabbb** [comment]
@adelf okay, please let me know, what am i doing wrong 😢 

![image](https://github.com/laravel-idea/plugin/assets/3524595/58008830-ac99-4d4e-a37d-0070ea218820)

![image](https://github.com/laravel-idea/plugin/assets/3524595/6ccb1a0b-a831-4fb1-abb7-73f7e25ff07b)

I also added `protected $table = 'test';` but still: "not found".

am I missing something ? 🤔 

is there somewhere a "flag" in the settings I need to check to let plugin know, that it should use the database connection for the helper code ???

**Comment by adelf** [comment]
It asks in the first helper code generation. But you can also use main menu > Laravel > Helper Code Parameters...

**Comment by michabbb** [comment]
@adelf i am very sorry if i am blind... i don´t know what you referring to, please be more specific if there is any option I have to "switch on".... 

![image](https://github.com/laravel-idea/plugin/assets/3524595/687b6362-3c90-4bfc-85df-c57c96c42609)

**Comment by adelf** [comment]
<img width="516" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/af725758-04d1-47e7-9253-b98578acc5c2">

**Comment by michabbb** [comment]
![image](https://github.com/laravel-idea/plugin/assets/3524595/25bd0be8-24f9-452b-8867-0401f5ddcca4)

holy guacamole, that was a long journey.  🙈 finally.... finally I do understand how this work.... 🤦 

and yes, the code now generates the columns.

sorry for taking me so long and thanks a lot for your patience !!!

i am sorry, I didn´t see that info in the docs: https://laravel-idea.com/docs/eloquent

maybe it´s an idea to create a FAQ that covers such issues.
something like:

Q: Why do I don´t see any auto-completing for my Models?
 - do you use migrations ?
   ----> check this
 - if not, use database
    -----> in that case, do this

Q: Why do I don´t see any auto-completing for Facdes of vendor packages?
  - do they use doc blocks a la "@method....."  ? (something I also had to face)

just an idea.

**Comment by adelf** [comment]
Yes. We are already working on documentation updates. I just merged an Eloquent section update. https://laravel-idea.com/docs/eloquent

<img width="700" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/d6c4cf87-6a59-4038-bb1a-03a17df462d8">
