### ISSUE TITLE
Route name auto-completion for Laravel Dusk methods

### ISSUE THREAD

**Issue by SjorsO** [laravel-idea/plugin#180]
When writing Dusk tests, methods like `waitForRoute` do not auto-complete route names. Any chance this could be added?

**Comment by adelf** [comment]
Easy ) Any other methods maybe?

**Comment by SjorsO** [comment]
On `Laravel\Dusk\Browser`
- `waitForRoute`
- `assertRouteIs`
- `visitRoute`

I think those 3 are it

**Comment by adelf** [comment]
Done. Thank you.

**Comment by SjorsO** [comment]
Does the label "wait next release" mean the next major version? I'm using version 3.6.1.203, which released somewhere last week, and this feature doesn't seem to included yet. Just checking to make sure nothing has gone wrong

**Comment by adelf** [comment]
No. It was a release for the new PhpStorm EAP. 2021.1
I'm going to release a new major version this week.

**Comment by adelf** [comment]
BTW, it seems I should start to make an update each week for example... It's sad that you should wait for this so long, especially when it was done about a month ago. Sorry.

**Comment by adelf** [comment]
4.0 version is available.
