### ISSUE TITLE
_ide_helper_models.php redudencies

### ISSUE THREAD

**Issue by SlyDave** [laravel-idea/plugin#182]
When generating the _ide_helper_models.php file, Laravel Idea is creating a bunch of redundancies by using both the long and short form of various types

Duplicate type 'integer'
`     * @property int|integer $user_id`

The recommendation from various standards (in particular PSR-12) is to use short form type keywords.

Oddly I found examples where it does short form and long form within the same class definition. I can't explain this.

This is the SubscriptionItem from Laravel Cashier:
```php
    /**
     * @property int $id
     * @property int $subscription_id
     * @property string $stripe_id
     * @property string $stripe_plan
     * @property int|integer $quantity
     * @property Carbon|null $created_at
     * @property Carbon|null $updated_at
     * @property Subscription $subscription
     * 
```
Note that `$quantity` has produced `int|integer` but `$id` and `$subscription_id` are `int`

**Comment by adelf** [comment]
Fixed in 4.0 version.
