### ISSUE TITLE
Feature request: Call migration property or migration directly like php variables.

### ISSUE THREAD

**Issue by anburocky3** [laravel-idea/plugin#183]
When I call the PHP variable with its name, it will be prefixed by the `$` symbol. Likewise, if I call any method inside the controller(`myMethod`) it will be prefixed by `$this->myMethod`. 

So likewise, what suppose I enter any migration type inside the migration table. 

For example,  string that should insert (`$table->string()`) It would be good to have it?

Here is my reference image:

![image](https://user-images.githubusercontent.com/15264938/104807615-365c5180-5806-11eb-9a07-3550bf135425.png)

Please revert if you can't understand what I'm saying. Thanks.

**Comment by adelf** [comment]
Good idea. I’ll try to implement. Thank you.

**Comment by adelf** [comment]
4.0 version is available.
