### ISSUE TITLE
Feature request: Showing error while using 404 laravel components.

### ISSUE THREAD

**Issue by anburocky3** [laravel-idea/plugin#184]
As you can see, if I have a Laravel anons component, I can reference it like below.

![image](https://user-images.githubusercontent.com/15264938/104809280-2e0a1380-5812-11eb-93d4-4c75917979ee.png)

But what suppose I don't have any component like `input > textarea.blade.php`? Wouldn't be good if we show any ide error while accessing the component?

**Comment by adelf** [comment]
Currently I can’t recognize some components from 3rd party packages for example. I have plans to make it possible soon, but now it will generate too many false positives.

**Comment by anburocky3** [comment]
How about adding support only for the inbuilt components for now? Later based on the suggestion can think for the support for 3rd party packages.

Also, do you run any beta plugins to test before release?

**Comment by adelf** [comment]
If some component didn’t found, it can be in some package. I can’t understand the source of component by its tag.

Not yet, but I’m going to start EAP program soon.

**Comment by anburocky3** [comment]
(Y) Good to know. But what I'm trying to suggest is, if we can find the components that the user has created internally, it would be great for now. 

I can understand the complexity behind this. Just suggesting anyway. Thanks for the wonderful product. Have tweeted you Kindly check.

**Comment by adelf** [comment]
Yes, but we are trying to implement the case when we don’t find the component ) in that case nobody can understand what component user means - own or from package.

**Comment by adelf** [comment]
Implemented in one of the previous versions...
