### ISSUE TITLE
Feature Request : Add a button to navigate to the view

### ISSUE THREAD

**Issue by rohithmeethal** [laravel-idea/plugin#185]
Hi,  I would like to jump to Laravel view from controller action/Livewire class, and back to controller action/livewire class from view in a quick way. 
I have seen some plugins adding a button on the left of line numbers to navigate to related files, I would like to request something similar to be added to the Laravel Idea plugin.
eg : 
![Screenshot from 2021-01-16 16-34-01](https://user-images.githubusercontent.com/12010328/104810211-39ad0880-5819-11eb-8e3e-7d216b310138.png)

Why this can be helpful: finding render function in a Livewire class that has so many other functions is difficult, multi clicks is needed, same goes for a Laravel controller action which has more lines.

Thanks

**Comment by adelf** [comment]
Good idea. It already should work for views(marker in the left in the first line of blade view). I can try to add it for component classes.

**Comment by rohithmeethal** [comment]
Thank you, you are right it is possible to navigate to controller action from a laravel view, could you please add a button for going to view from the action. I use ctrl+b or ctrl+click on view('filename'), but when the controller actions are longer this is bit tedious.

**Comment by adelf** [comment]
We added this button for Livewire components since they can have implicit view calls. We won't add this for controllers. Cmd(Ctrl)-B or click in view name should be enough.
