### ISSUE TITLE
Feature request: Laravel Components (@props) identify inside that view

### ISSUE THREAD

**Issue by anburocky3** [laravel-idea/plugin#186]
I have declared a few props as you can see in the image. So it will be better if the ide autosuggest these inside that view file.

![image](https://user-images.githubusercontent.com/15264938/104812219-cca06f80-5826-11eb-835d-56ba247c4d02.png)

**Comment by anburocky3** [comment]
Since we are passing `trailingAddOnLeft` prop on the top. It would be great, if we can access/call it inside the view.

**Comment by adelf** [comment]
4.0 version is available.
