### ISSUE TITLE
Feature request: Make blade components behave like default html

### ISSUE THREAD

**Issue by BertvanHoekelen** [laravel-idea/plugin#187]
When I try to add a class attribute to blade components like `<x-logo />` it always typehints `@endcomponentClass`. It would be great to have default html attributes suggested (next to the props ofcourse).

<img width="547" alt="Screenshot 2021-01-18 at 11 03 58" src="https://user-images.githubusercontent.com/7521173/104901229-6417d680-597d-11eb-9313-f4d8c03299d2.png">

I really love the blade component integration :) But I always end up removing the `@endComponentClass`, something with muscle memory I think 😂

**Comment by anburocky3** [comment]
Yea using the default html attributes would be helpful in most cases in think @adelf

**Comment by adelf** [comment]
Hi. Yes, thank you for the suggestion. Do we need all HTML attributes here, or only some of them(like `class`) will be enough?

**Comment by anburocky3** [comment]
If we can find the input element inside the component, then we should input related attributes, or it's best to have all I think so. 

Based on the usage, we can decide later.

**Comment by BertvanHoekelen** [comment]
I think treating them as HTML elements would be nice.Some examples of where more attributes can be handy. But I have no idea if anybody else is doing the same as I do.

```php

// input-component.blade.php
<input class="some-tailwind-classes" {{ $attributes }} />

// usage.blade.php
<x-input-component type="text" value="foobar" />



// table-cell.blade.php
<td {{ $attributes->merge(['class' => 'px-2 py-2.5 whitespace-nowrap text-sm text-gray-600']) }}>
    {{ $slot }}
</td>

// Usage
<tr>
  <x-table-cell colspan="12">
    Description
  </x-table-cell>
</ tr>

**Comment by adelf** [comment]
Thank you, guys. I'll try.

**Comment by adelf** [comment]
4.0 version is available.
