### ISSUE TITLE
Problem in calling/detecting the grabbed components from the vendor package

### ISSUE THREAD

**Issue by anburocky3** [laravel-idea/plugin#189]
These are the default generated ones while installing laravel with jetstream. 

**Problem:**
Jetstream has these components(nav-link) in their vendor directory. Laravel Idea is smart enough to read it from there. Which is great. But what suppose, if we want that to be customizable, we published the jetstream views and now it make an offline copy in our project view directory(`resources/views/vendor/jetstream/components/nav-link.blade.php`) but while clicking the `<x-jet-nav-link>` component tag, it goes to the package components not grabbed user components..

```blade.php
<div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')" >
        {{ __('Dashboard') }}
    </x-jet-nav-link>
</div>
```

I hope you get my point. Thanks.

**Comment by adelf** [comment]
Yes. I added this to my internal tracker 2 days ago :) but it's good that you created it here.

**Comment by anburocky3** [comment]
Great! Waiting for the release. Thanks.

**Comment by adelf** [comment]
4.0 version is available.
