### ISSUE TITLE
Mark routes as deprecated

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#19]
If the method is marked as deprecated, I propose to display it crossed out in routes.

If the class is marked as deprecated, I suggest not only the class, but also its methods, to be crossed out in routes.

> Translated:
> Если метод помечен как устаревший, предлагаю в роутах отображать его зачеркнутым.
> 
> Если класс помечен как устаревший, предлагаю в роутах отображать зачеркнутым не только класс, но и его методы.

![2020-02-29_17-22-22](https://user-images.githubusercontent.com/10347617/75609259-17829d00-5b18-11ea-809a-d2dab193d9d9.jpg)
![2020-02-29_17-22-04](https://user-images.githubusercontent.com/10347617/75609262-18b3ca00-5b18-11ea-99cb-1473e44833c4.jpg)

**Comment by xVismutx** [comment]
+

**Comment by adelf** [comment]
I'll take a look :)

**Comment by andrey-helldar** [comment]
I just noticed that the deprecated method is tagged in the service, not in the controller.
I’ll check the controller soon.

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/78736395-b1c6d380-7955-11ea-9041-af6ed19872ec.png)

 :)

**Comment by andrey-helldar** [comment]
Dankeschön 😊

**Comment by adelf** [comment]
implemented in 2.4 version. please check and comment if there are some issues.

**Comment by andrey-helldar** [comment]
I'll wait until the update appears on 2020.1.1 Preview, and I can check. Thanks!

![2020-04-22_19-51-41](https://user-images.githubusercontent.com/10347617/80010207-c0bf9100-84d2-11ea-8ddf-6c2f246064f6.jpg)
![2020-04-22_19-51-30](https://user-images.githubusercontent.com/10347617/80010210-c1582780-84d2-11ea-9314-436e28281e75.jpg)

**Comment by andrey-helldar** [comment]
@adelf, If you mark the method obsolete, then there are no problems. But if you mark the entire class obsolete, then the methods appear active even though the class appears crossed out.

![2020-04-27_21-07-31](https://user-images.githubusercontent.com/10347617/80405407-3eb4db00-88cb-11ea-87a6-a13d045b93a7.jpg)
![2020-04-27_21-06-58](https://user-images.githubusercontent.com/10347617/80405412-3fe60800-88cb-11ea-88f0-959f3f28a762.jpg)

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/80408557-04017180-88d0-11ea-82b7-81682de82e00.png)

)

**Comment by andrey-helldar** [comment]
Hmm ... Strange behavior, but okay)
