### ISSUE TITLE
Improvement: Show error when not using root element in livewire component.

### ISSUE THREAD

**Issue by anburocky3** [laravel-idea/plugin#190]
I was creating a livewire component and was having multiple divs and the livewire was not working as expected, I almost forgot that livewire expects only a single root element. but IDE shows no errors or warning..

It will be good if we have any visual indication.

**Comment by DanielSpravtsev** [comment]
> "IDE shows no errors or warning.."

I think it is not an IDE or Laravel Idea story 
It's just a livewire specification that you need to keep in your mind.
Therefore when you creating livewire component using make:livewire, it is already have single root div.

**Comment by BVFI** [comment]
I would like to reopen this, it's easy for new people to miss this and there is ABSOLUTELY NO INDICATORS that would point the user in the right direction. Everything is just broken and doesn't work, but there's no errors, nothing. This is also thrown when the root div is wrapped with Blade's ```@if()``` and similar, not just when having more than 1 root element
