### ISSUE TITLE
Add the ability to create scopes

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#192]
![image](https://user-images.githubusercontent.com/10347617/105580273-7c805a80-5d9c-11eb-8672-e2e71d92c469.png)

![image](https://user-images.githubusercontent.com/10347617/105580284-873aef80-5d9c-11eb-866d-2e47fc74d894.png)

**BUT** the file can be created manually.

It is convenient because the specified scope does not need to be written inside the model - it is general.

![image](https://user-images.githubusercontent.com/10347617/105580296-9621a200-5d9c-11eb-80fd-d2015092ebeb.png)

It would be great to be able to create a scoped file via Laravel Idea ☺

**Comment by adelf** [comment]
Template for them? only apply method? or?

**Comment by andrey-helldar** [comment]
There's a simple, interface implementation:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Scope.php

```php

namespace App\Scopes;

use Illuminate\Database\Eloquent\Scope;

class MyScope implements Scope
{
    ///
}
```

**Comment by adelf** [comment]
Forgot to close)
