### ISSUE TITLE
Incorrect app/config hint suggestions 

### ISSUE THREAD

**Issue by DanielSpravtsev** [laravel-idea/plugin#195]
I created new multidimensional config file for my Laravel app file with following (incorrect) syntax
```
    'admin.name' => env('ADMIN_NAME', 'LikeCat Admin'),
    'admin.email' => env('ADMIN_EMAIL', 'admin@example.com'),
    'admin.password' => 'asdsaDLI!H@R*OASud',
```
Laravel Idea started to suggest me it, but it's incorrect syntax and when using config('admin.name') it will be NULL

Correct syntax:
```
    'admin' => [
        'name' => env('ADMIN_NAME', 'LikeCat Admin'),
        'email' => env('ADMIN_EMAIL', 'admin@example.com'),
        'password' => env('ADMIN_PASSWORD', '123456789'),
    ]
```

It was my mistake as I assumed the syntax was correct, but the plugin hint misled me even further.
It's not a critical, but it has taken a lot of time to figure out who is lying to me 😆

**Comment by adelf** [comment]
Didn't know about it. Thanks :) I'll try to add also an inspection about it.

**Comment by adelf** [comment]
4.0 version is available.
