### ISSUE TITLE
Plugin doesn't seem to work.

### ISSUE THREAD

**Issue by ChrisBrenton** [laravel-idea/plugin#197]
I have recently purchase a 1 year license of this project, and thought I'd try it out on a new dummy project. I created a new Laravel project, installed Homestead, `vagrant up`, installed Breeze and such. The project shows the default Laravel page in my browser as expected.

I have generated the helper files using the Ctrl+Shift+, shortcut.

I am not getting any autocomplete options whatsoever on models, in blade template files for blade compenents, or anything else really.

I also seem to be missing a section in the plugin settings menu. At a bit of a loss for what to do.

Laravel: 8.24.0
PHPStorm: 2020.3.2
OS: Ubuntu 20.04
PHP: 8.0.1

![image](https://user-images.githubusercontent.com/3601346/106341078-e6649c80-6293-11eb-86a6-ac32c97d7e45.png)
![image](https://user-images.githubusercontent.com/3601346/106341142-1f9d0c80-6294-11eb-8f08-4304857f22ef.png)

**Comment by adelf** [comment]
Hello, Chris.
It’s weird. Code generation works, so plugin is turned on. Do you have Laravel installation in the root of the project, not inside some folder?
You can try also click File > Invalidate caches & Restart in the main menu.

> I also seem to be missing a section in the plugin settings menu.
If “Blade” section is missing you don’t have Blade plugin installed. Do you?

**Comment by ChrisBrenton** [comment]
Hello @adelf 

Sorry for the delay. 

Laravel is indeed stored in the root of the project. I have tried invalidating caches and restarting, but to no avail.

If by Blade plugin, you mean the Jetbrains one, then this is indeed installed.

**Comment by adelf** [comment]
Very strange. Do you at least have completion for `config()` values? What is in the `vendor/_ide_helper_models.php` file?

**Comment by ChrisBrenton** [comment]
Unfortunately not.

vendor/_ide_helper_models.php: https://gist.github.com/ChrisBrenton/40c889f0ea09b089269291f3dc724407

**Comment by ChrisBrenton** [comment]
Out of curiousity, I tried to install it from disk instead of through the plugins section, and it made no difference either.

**Comment by adelf** [comment]
Helper file looks good. Is Laravel Idea turned on now? Settings > Languages and frameworks > Laravel Idea?
Maybe vendor folder is marked as excluded? https://mobile.twitter.com/laravel_idea/status/1334539817263247363

**Comment by ChrisBrenton** [comment]
Laravel Idea is turned on, and both ways I tried installing the plugin the IDE confirmed it is installed. My vendor folder is not marked as excluded, but the vendor/composer directory is.

**Comment by adelf** [comment]
The last guess: do you have multiple content roots? https://www.jetbrains.com/help/phpstorm/configuring-content-roots.html
 If not I’m ready to help you by any screen sharing app.

**Comment by ChrisBrenton** [comment]
Single content root.

I am up for that - do you have a preference?

**Comment by adelf** [comment]
The only preference - not today. I’m going to sleep) Tomorrow or Monday - as you wish.

**Comment by ChrisBrenton** [comment]
Sound reasonable!

I am on UK time, and will be around tomorrow.

**Comment by ChrisBrenton** [comment]
Good afternoon, @adelf 

Shall we organise a time?

**Comment by adelf** [comment]
Yes. Please write adel@laravel-idea.com
