### ISSUE TITLE
Detecting Laravel installation by analyzing composer.lock instead of composer.json

### ISSUE THREAD

**Issue by zlodes** [laravel-idea/plugin#198]
Hi!

I should enable the plugin manually when the Laravel is not a direct dependency and it's required by another package from current package requirements.

And I suggest to use current behavior as fallback, when composer.lock is not found.

**Comment by adelf** [comment]
Will it be enough if I will check `vendor/laravel/framework` and other folders?

**Comment by zlodes** [comment]
Yeap. I think it's a good way. 

And the plugin has a "version" option and it will be cool to set it automatically too. 

Laravel has the version constant here:

https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Application.php

**Comment by adelf** [comment]
Implemented by analyzing `composer.lock`. Thanks :)

**Comment by adelf** [comment]
4.0 version is available.

**Comment by zlodes** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/1114387/107695777-1a8f8280-6cc2-11eb-9501-faac7e9877dc.png)

**Comment by adelf** [comment]
it was your idea, so thank you )
