### ISSUE TITLE
Command + Shift + , shortcut doens work

### ISSUE THREAD

**Issue by RomkaLTU** [laravel-idea/plugin#199]
**Command + Shift + , shortcut doens work**

PhpStorm 2020.3.1
Build #PS-203.6682.180, built on December 30, 2020
Runtime version: 11.0.9.1+11-b1145.63 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.draculatheme.idea, com.mallowigi, com.github.inxilpro.intellijalpine, com.laravel_idea.tailwind, de.espend.idea.php.annotation, ru.adelf.idea.dotenv, com.laravel_idea.plugin

**Comment by RomkaLTU** [comment]
Actually by pressing Command + Shift + , simbol < being registered instead of "," so I made custom shortcut Command + Shift + <

**Comment by adelf** [comment]
Yes. This is broken after some macOS update. I'll add Command + Shift + < as a secondary keymap.

**Comment by gorbunov** [comment]
FYI, shortcuts with Shift+ combinations are already fixed in last stable release of phpStorm.
