### ISSUE TITLE
Free licenses for students

### ISSUE THREAD

**Issue by TartanLeGrand** [laravel-idea/plugin#2]
Hello,

I am a student and we were using Laravel in class and your plugin is very interesting. Unfortunately it is not free....

We are on in sandwich course, so several of us could offer it to our future companies.

Are you thinking of making a student offer?

**Comment by adelf** [comment]
Hi, @TartanLeGrand . Plugin is free for students and open source, like PhpStorm. You can use trial for now, I’ll ask Jetbrains stuff and write here how to get your free licenses.

**Comment by adelf** [comment]
Current temporarily solution:

1. Apply to Jetbrains student program here - https://www.jetbrains.com/student/ - and get your free student license(if you don't have it yet)
2. Write email with name and email you used to get license for IDE here - licenses@laravel-idea.com
3. Wait a bit and plugin license will appear in your Jetbrains account. (Email with license infomation should notify you about it)

**Comment by TartanLeGrand** [comment]
Perfect, I just sent you an email.

**Comment by adelf** [comment]
I'll reopen it for other students.

**Comment by TartanLeGrand** [comment]
Why not put the information in the readme or a wiki?

**Comment by adelf** [comment]
I definitely will, but it takes some time. I'll create a website at laravel-idea.com and put all information there. But currently plugin only have **Issues** url to this page :)

**Comment by iaroel** [comment]
Hi, @adelf I've also sent an email for student license a couple of days ago but haven't received the license yet.

**Comment by adelf** [comment]
Hi, @iaroel 
I've sent all requests, including yours, to JetBrains, but seems this employee doesn't work today. Is it urgent for you?

**Comment by iaroel** [comment]
Thanks @adelf 
Not really, I still have over 20 days until the end of the trial period. 
As of now, I haven't heard from JB, but I'll let you know once I have.

**Comment by iaroel** [comment]
Thanks @adelf 
I've received the license.

**Comment by w99910** [comment]
Hello ... I'm a student and I sent email for free license.I wanna know if I can get free license for laravel-idea addon and how long I should wait for reply .I've been using PhpStorm with my free student license.Thanks You in advance.

**Comment by adelf** [comment]
@w99910 usually 1-2 business days.

**Comment by juniorkibirige** [comment]
I've sent an email from jlkibirige@cis.mak.ac.ug for plugin activation

**Comment by juniorkibirige** [comment]
Not sure why, but I've not received a student license, but i sent in a request, Please help me out. Thanks

**Comment by adelf** [comment]
@juniorkibirige, please write licenses@laravel-idea.com

**Comment by juniorkibirige** [comment]
> @juniorkibirige, please write [licenses@laravel-idea.com](mailto:licenses@laravel-idea.com)

Very much appreciated received my license

**Comment by ShekhSaifuddin007** [comment]
@adelf yeh I got my free license thank you..

**Comment by dounasth** [comment]
Hello, I have an education license from my university but the plugin is not getting activated.
I cannot find the option for education although logged in with my account
Can you help me on how to do it?

![εικόνα](https://user-images.githubusercontent.com/3296263/146927058-fb9fe94e-ef27-4501-a57f-0c3da82863a9.png)

**Comment by adelf** [comment]
Please use this - https://plugins.jetbrains.com/docs/marketplace/community-programs.html
If you have any issues - ask sales@jetbrains.com

**Comment by dounasth** [comment]
i saw the previous post but dont see the option for discounts for students and teachers
so it is a jetbrains issue right? thanx!

**Comment by bishwajitcadhikary** [comment]
I have an education license from my university but the Laravel Idea plugin is not getting activated.

**Comment by Ojsholly** [comment]
You have to get a special license for the plugin. It's at the point of
payment for the licence that your educational license comes into play and
you get the license for free.

**Comment by aozen** [comment]
I can't see the `Discounts available` menu. I have student license but cannot use `laravel-idea`. Any help? Thanks.
![image](https://user-images.githubusercontent.com/16261617/219054186-0b3866f9-cf62-469d-8aa0-5b6e9e465e11.png)

**Comment by adelf** [comment]
Please use this - https://plugins.jetbrains.com/docs/marketplace/community-programs.html
If you have any issues - ask [sales@jetbrains.com](mailto:sales@jetbrains.com)

**Comment by arisawali2014** [comment]
is this still available? for educational?

**Comment by Ojsholly** [comment]
Yeah, it is. Just ensure to add your student email address to your
JetBrains account.

**Comment by jrmessias** [comment]
Hi,
I have the student e-mail on my JetBrains account but the plugin don't recognize.
Someone know what i need to do?
Thanks.

**Comment by jersoncarin** [comment]
is this still available? i cant find the discount menu

![image](https://github.com/user-attachments/assets/144de31d-e238-4cd9-827e-d478e4c5858e)

**Comment by leo60228** [comment]
It seems like the plugin page doesn't properly display the discount in some cases. However, if you try to purchase a yearly subscription, the price will be listed as $0.00 (and it won't ask for payment information).

**Comment by 00bx** [comment]
updated solution: select the last option (PHPStorm and Laravel Idea) together. The payment will treat Laravel Idea as free (0.00) if you already own PHPStorm. Simply remove the IDE from the invoice, place the order, and you’ll receive a free Laravel Idea license. Then, return to PHPStorm and activate it using the account you used to purchase the license.

**Comment by rootfebri** [comment]
> updated solution: select the last option (PHPStorm and Laravel Idea) together. The payment will treat Laravel Idea as free (0.00) if you already own PHPStorm. Simply remove the IDE from the invoice, place the order, and you’ll receive a free Laravel Idea license. Then, return to PHPStorm and activate it using the account you used to purchase the license.

Thank you, you save the precious time

**Comment by demiurw** [comment]
> updated solution: select the last option (PHPStorm and Laravel Idea) together. The payment will treat Laravel Idea as free (0.00) if you already own PHPStorm. Simply remove the IDE from the invoice, place the order, and you’ll receive a free Laravel Idea license. Then, return to PHPStorm and activate it using the account you used to purchase the license.

Hey I'm having the same issue but I see none of these things you are referring to. how do i find them

**Comment by Kamrul-Haque** [comment]
Does this still work?

![Image](https://github.com/user-attachments/assets/f124936f-4717-4c58-806e-ec29d70d84ed)

**Comment by adelf** [comment]
Yes. You've probably used another JetBrains account.

**Comment by youssef-ahmed-cs** [comment]
Dear Laravel Idea Team,

I hope this message finds you well.

My name is Youssef, and I am a university student currently studying at the Faculty of Computers and Artificial Intelligence, Benha University.

I have an active GitHub Student Developer Pack linked to my university email: youssef419386@fci.bu.edu.eg. I would like to request a free educational license for Laravel Idea as part of my development tools.

Laravel is a core part of my academic and personal projects, and I believe Laravel Idea would significantly improve my productivity and learning experience.

Please let me know if you need any further verification or documentation.

Thank you for providing such an amazing tool for the Laravel community!

Best regards,  
Youssef Ahmed
youssef419386@fci.bu.edu.eg

**Comment by SamarArfa** [comment]
I am a Master's student at the Islamic University of Gaza. I previously held a valid educational license using my university email: sarfa1998@students.iugaza.edu.ps. However, when I tried to renew my license recently, the system rejected my email address stating it is blocked or not accepted. I am currently enrolled and can provide official documents to verify my student status. Could you please assist me in reactivating my educational license or guide me on how to proceed with manual verification
@adelf

**Comment by adelf** [comment]
@SamarArfa The Laravel Idea plugin is free now. If you have issues with the PhpStorm license, please write to JetBrains.
