### ISSUE TITLE
Does not "Code generation" when laravel install is within a directory inside root

### ISSUE THREAD

**Issue by trevorllarson** [laravel-idea/plugin#20]
We have a folder structure that follows

project-name/
    src/
        laravel install here
    ...

And I load my project at that higher level, with laravel one folder deep. Code generation does not show, and potentially nothing at all works? I'm not seeing suggestions or anything either.

Is there a way to mark a single directory deep as the laravel install?

**Comment by adelf** [comment]
Hi, Trevor.
What do you mean? You just have Laravel installation not in the root of the PhpStorm project? If so, you can setup folder with Laravel here: Main menu > Settings(or Preferences) > Languages and Frameworks > PHP > Laravel Idea. Just set Laravel directory there and click Apply.
If you have non-standard Laravel project structure, it may be not so easy. Please describe this structure then.

**Comment by trevorllarson** [comment]
Wow I feel silly! That was exactly it! I didn't drill as far down in the settings as I had needed. Thanks for the very quick response!!
