### ISSUE TITLE
[Feature Request]: Auto complete disks names

### ISSUE THREAD

**Issue by filhocodes** [laravel-idea/plugin#200]
Here are some example of methods that accept disk names:

* I would bet that the most commonly used is `Illuminate\Support\Facades\Storage::disk()`
* Another one should be the options parameter in `Illuminate\Http\UploadedFile::store()` and his variations (like `storeAs()` and `storePublicly()`)
* The main service, `Illuminate\Filesystem\FilesystemManager`, has methods that accept disk names, like `drive()` and `disk()`

It would be nice if at least in the first two entries, the plugin suggested the disks names configured in `config/filesystems.php` to be autocompleted into the parameters.

**Comment by adelf** [comment]
It’s already done. I hope to release it next week. However, seems I forgot about UploadedFile. Thanks.

**Comment by adelf** [comment]
4.0 version is available.
