### ISSUE TITLE
[Feature Request] Relationship method builder

### ISSUE THREAD

**Issue by squatto** [laravel-idea/plugin#201]
As we all know, trying to remember (or even figure out!) the relationship methods and arguments is always a huge pain. Since your plugin already knows everything about models/tables/etc. it is in the perfect position to help build relationship methods. What I envision is a modal with the first option being the relationship type ("Has One", "Has Many", "Belongs To", etc.) Once a relationship type is selected, the applicable inputs would be shown.

For example, the "Has One" relation would show inputs for:
1. Base model (the one that the relationship method will be added to)
2. Related model
3. Relationship name (auto-populated with the correct name based on the model selected in input 2)
4. Foreign key (auto-populated with fields from the model selected in input 2)
5. Local key (auto-populated with fields from the model selected in input 1)

The key fields would be optional, just like in the `hasOne()` method signature. Or you could pre-fill the "correct" keys by using the same logic that Laravel uses to determine the keys when they aren't provided.

A great example of what I'm thinking of is a tool that a good friend of mine built: https://laravelhasmanythrough.com/ - it makes it **very** easy to generate a `HasManyThrough` relationship method, which is always one of the most difficult ones to remember/figure out. Make sure to click "Edit Details" under each option to see how you can customize the keys and the name of the relationship. For those that don't want to click through and try it out, here's a complete example of what it does:

![image](https://user-images.githubusercontent.com/748444/106942986-1079ec80-66e2-11eb-9639-dc603f825a69.png)

**Comment by adelf** [comment]
I like the idea. Thank you. I'm not sure when but I'll try to implement it.

**Comment by squatto** [comment]
Excellent! I had thought about trying my hand at creating a PhpStorm plugin, but then I quickly realized that I would have to figure out how to determine the models, tables, fields, etc. and decided that you are far more capable of doing this than I am 😂

**Comment by adelf** [comment]
Laravel Idea solved it by IDE way - completing possible relation methods with their bodies. Other model classes and columns are also completed.
