### ISSUE TITLE
[Feature Request] Better translation generation handling

### ISSUE THREAD

**Issue by EtoileFilante** [laravel-idea/plugin#204]
Hi there,

Currently when you generate a translation by right clicking on a text and clicking on generate, it always creates changes in the english translation file. It would be better if we could configure which language we want it created to, and if possible on multiple languages at the same time.

**Comment by adelf** [comment]
Sure :) Please check the "Default language" setting in the plugin settings: https://laravel-idea.com/img/docs/install/settings.png
