### ISSUE TITLE
PhpStorm Eloquent Helper Code "Property accessed via magic method"

### ISSUE THREAD

**Issue by pxlrbt** [laravel-idea/plugin#205]
When generating the Eloquent Helper Code via Laravel Idea I always get warnings inside a model referencing the same models properties.

![image](https://user-images.githubusercontent.com/22632550/107372142-63d6ab00-6ae5-11eb-8bb6-58bca5d2487e.png)

E.g.

The following code will highlight `$this->name` as "Property accessed via magic method"
```php
class User {
    public function getName()
    {
        return $this->name;
    }
}
```

When accessing a property from outside the models scope it works fine. E.g. accessing `->name` on role inside the User model is fine.
```php
class User {
    public function getRoleName()
    {
        return Role::first()->name;
    }
}
```

Using `laravel-ide-helper` with `php artisan ide-helper:models -M` which generates a `@mixin` DocBlock also works.
```php
/**
 * @mixin IdeHelperApplicant
 */
class User
```

Adding the DocBlock directly to the model also works, but is messing up the models code:
```php
/**
 * @property string $name
 */
class User 
```

Maybe this in an issue with PhpStorm but it would be great to have a workaround (e.g. via the `--write-mixin` option)

**Comment by adelf** [comment]
Yes. It's a PhpStorm issue. I created a bug in their YouTrack - https://youtrack.jetbrains.com/issue/WI-54460

I didn't want to add any helper code to the models, but yes... adding a @mixin is probably the only good solution here.

**Comment by pxlrbt** [comment]
> I didn't want to add any helper code to the models, but yes... adding a @mixin is probably the only good solution here.
Sure. Ideally PhpStorm team will have a look at this. I just commented their issue to bump it.

Otherwise it would be great if you could add a note about the known issue to the documentation. I thought I misconfigured PhpStorm or Laravel Idea and was searching for the issue for hours.

**Comment by adelf** [comment]
Sorry for that.

**Comment by pxlrbt** [comment]
No need to be sorry. It's not your fault. But maybe we can help others to save some time.

**Comment by adelf** [comment]
Yes. Please don't close. I'll try to add a mixin

**Comment by adelf** [comment]
The new Eloquent Helper Code Generator from 4.1.1 version released today contains an option about generating needed mixins. Thank you for reporting this! :)

**Comment by pxlrbt** [comment]
Thank you.

**Comment by agnius-vasiliauskas-di** [comment]
> Using `laravel-ide-helper` with `php artisan ide-helper:models -M` which generates a `@mixin` DocBlock also works.

Thanks a lot, `laravel-ide-helper` is really a life-saver for Laravel developers.
