### ISSUE TITLE
Detect custom blade if statements

### ISSUE THREAD

**Issue by Vmadmax** [laravel-idea/plugin#206]
Hi,
it would be nice, if this plugin can also detect custom Blade::if statement and not only custom Blade::directive.

See Laravel documentation for custom blade if statements: https://laravel.com/docs/8.x/blade#custom-if-statements

Best Regards

**Comment by adelf** [comment]
I added it to my internal tracker yesterday :) thank you, anyway!

**Comment by adelf** [comment]
4.0 version is available.
