### ISSUE TITLE
[Feature Request] Route names completion in JavaScript

### ISSUE THREAD

**Issue by Daanra** [laravel-idea/plugin#207]
The [route names completion functionality](https://laravel-idea.com/docs/routing#route-names-completion) is awesome!

I think it would be even better if it could be extended to JavaScript / Vue files. I personally use [Ziggy](https://github.com/tighten/ziggy) to get a JavaScript `route` function that behaves very similar to Laravel's `route` function. 

I also inject this as a global function in my Vue instance such that I can use it like so:
```vue
<a :href="$route('users.index')">Click me</a>
```
I think adding the option to have route names completion for JavaScript functions would be a great addition :smile:

**Comment by adelf** [comment]
> I think adding the option to have route names completion for JavaScript functions would be a great addition

Agree )

**Comment by hailwood** [comment]
When implementing this, an option to say what method name should be considered a route method would be great.

That would deal with something like `import laravelRoute from 'my-route-package';`

**Comment by adelf** [comment]
It should work in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release

Please write here if something isn't working.
