### ISSUE TITLE
Idea: Refactor to blade component

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-idea/plugin#211]
Hey there,

I don't know if this is possible but it would be great to have a "refactor to blade components" in blade files.
Almost the same as if I would extract to method in a class file i.e. 
Is this possible?
Would be great to cleanup some of the bigger blade files who grew over time.

And thanks for the great plugin!

**Comment by adelf** [comment]
I already have this in my roadmap: https://laravel-idea.com/docs/overview#roadmap 
Currently, I'm working on the "Macro helper code generator" and improving the Eloquent helper code. After this, I'll try to implement these extractions.

**Comment by SudoGetBeer** [comment]
Ah nice!

Thanks a lot.

**Comment by adelf** [comment]
Implemented some time ago)
