### ISSUE TITLE
Autocompletion for css class does not work with "@layer components {}". (app.css)

### ISSUE THREAD

**Issue by camya** [laravel-idea/plugin#214]
I'm using Laravel Idea, so this could be an "Larvel Idea / Tailwind CSS Smart Completions" plugin problem.

I added two custom classes via @apply (.link-1, .link-2). One of them (.link-2) uses the "@layer components {}" feature of TailwindCSS.

Autocompletion for link-1 in the blade template just works fine.

**The "link-2" is not found** by the autocompletion.

Here is my app.css.

```
@tailwind base;
@tailwind components;
@tailwind utilities;

.link-1 {
        @apply text-blue-500;
}

@layer components {

    .link-2 {
        @apply text-blue-600;
    }

}
```

**Comment by adelf** [comment]
Hi. Yes, there is a bug. But it's in the HTML part of IDE. 
I complete all these classes as you see here:

![image](https://user-images.githubusercontent.com/2818394/108199022-78dabc00-712d-11eb-8d7f-d84ee648cd42.png)

But only `link-1` is completed in the blade or HTML files... Could you please report it here: https://youtrack.jetbrains.com/

**Comment by camya** [comment]
Thank you for your fast answer. I reported the bug to JetBrains. https://youtrack.jetbrains.com/issue/WI-58701
