### ISSUE TITLE
Autocompletion broken when smart keys insert pair quote feature enabled

### ISSUE THREAD

**Issue by karlmiles** [laravel-idea/plugin#215]
Hi, I'm currently trying to get the plugin working as expected and have been battling with autocompletion not working for me - I do have the Blade plugin enabled, the ide-helper composer package installed, vendor is not excluded either.

After much trial and error over a couple of evenings, disabling various other plugins, tinkering with options, etc., I've discovered that enabling the "Insert pair quote" options in Settings | Editor | General | Smart Keys, prevents the autocompletion working - an option I always have turned on.

For some things, I might get _some_ completion working by typing the first letter, hitting [ctrl]-[space], getting a list of options that don't include what I'm expecting (e.g. "operator:", and "value:" and then hit the left arrow, it then works.  Not always though - form requests there's no suggestions at all.

From watching the demo video, it looks like it should work perfectly fine, and I have noticed that it works okay briefly whilst re-indexing (thought not immediately from clearing the cache and restarting).  I'm wondering if I've just got lucky with finding a way to make it work, or there's something else I can try so that I can continue using the "insert pair quote" option, and get full use of the plugin?

**Comment by adelf** [comment]
Hi, Karl. Very strange... I also have this option turned on, and there are no problems.
Does the old "Laravel" plugin work correctly for you?

**Comment by karlmiles** [comment]
No, though the behaviour is different, I see "boolean:", "column:", "operator:" and "value:" as options with [ctrl]-[space].

Very odd.  I spoke to another dev earlier who's using the plugin and he's not had any of these issues; he just needed to enable the Blade plugin and clear his cache I think.

I'm thinking, I've probably got some other plugin interfering maybe?

**Comment by adelf** [comment]
Another plugin shouldn't be a reason.

> I see "boolean:", "column:", "operator:" and "value:"

Where? I don't remember these completions. Could you check the settings. Is the plugin turned on? Settings | Languages and frameworks | Laravel Idea

**Comment by karlmiles** [comment]
That's with the other Laravel plugin.  Just twigged, they're the parameter names for the `where` method.

![image](https://user-images.githubusercontent.com/2984054/108418638-6fcf1500-7229-11eb-821b-9651a6485374.png)

**Comment by karlmiles** [comment]
Your plugin gives me better results, though I still see those other entries that the Laravel plugin gave:

![image](https://user-images.githubusercontent.com/2984054/108419296-3ea31480-722a-11eb-93bb-3fa333720df7.png)

**Comment by adelf** [comment]
Interesting... what plugin gives these "email" and other fields completions? I give the same but icon repeats Laravel icon(red cubes). Anyway, if you won't manage to get it working I can try to help tomorrow via some screen sharing soft if you want to.

**Comment by karlmiles** [comment]
That, I'm unsure, I thought it was yours but, now you mention the red icons... and I do see those in other places, like autocompletion for `config()`.  Oh... and it's fine with the auto-inserted closing quote and bracket in that case too.

I'm going to go back through all my plugins again and try to track it down.  If I do find a conflict or, at least, the plugin responsible for those screenshots, I'll let you know.

Thanks for the support, appreciated.

**Comment by karlmiles** [comment]
I didn't manage to find the cause of my problems but, I've just install IDEA Ultimate, added the PHP, Blade & Laravel Idea plugins, generated the helper code, and opened up the project (having removed the .idea directory "just in case"), and it seems to be okay.  I don't see the Laravel logos alongside the Eloquent model fields, and I still see the "operator:", "column:", and "value:" entries but, I can live with that.

The reason for trying it with IDEA instead, was that it would be a completely clean install with nothing sync'd from my account so, I should be pretty much stock.  The issue with the smart keys feature impacting autocompletion seems to have gone away too.

Still strange I don't have the exact same experience as you with the Eloquent fields but, as long as I'm not actually missing any feature/functionality, that's fine.

**Comment by adelf** [comment]
It may be just a little bug with icons...

**Comment by adelf** [comment]
> I see "boolean:", "column:", "operator:" and "value:"

They are definitely not from Laravel Idea.
