### ISSUE TITLE
"Disabled (composer.json not found)" when "Laravel directory" filled

### ISSUE THREAD

**Issue by Mapteg34** [laravel-idea/plugin#216]
Hello.

# Steps to reproduce:
1. Open project with laravel installed in subfolder (for example laravel)
2. Check that you really have ./laravel/composer.json
2. Open File | Settings | Languages & Frameworks | Laravel Idea
3. Fill "Laravel directory" field with "laravel"
4. Select "Automatic" in "Plugin enabled" field.

# Expectation
All ok, plugin work correctrly.

# Now:
I see "current state: Disabled (composer.json not found)"

Please fix it.

# Versions:
Laravel Idea 4.0.0.202, purchased, license is active until Jan 04, 2022
PhpPhpStorm 2020.2.4 Build #PS-202.8194.11, built on November 25, 2020
laravel/framework 6.0.4

**Comment by adelf** [comment]
Hi. Did you try:

6. Click "Apply" button?

**Comment by Mapteg34** [comment]
> Hi. Did you try:
> 
>     1. Click "Apply" button?

of course yes

**Comment by Mapteg34** [comment]
```
$ ls -la laravel/composer.json 
-rw-rw-r-- 1 mapt mapt 2,3K 2021-02-18 21:14 laravel/composer.json
```

![Screenshot_2021-02-19_18-25-38](https://user-images.githubusercontent.com/26138251/108524378-04944a00-72e0-11eb-82e3-c883e6fd90f9.png)

**Comment by adelf** [comment]
Sorry. I couldn't reproduce this. Could you show the project structure?

**Comment by Mapteg34** [comment]
Problem solved. It was: invalid project path in my project. Problem not in plugin.
