### ISSUE TITLE
[Feature Request] Livewire rendering hint suggestions

### ISSUE THREAD

**Issue by DanielSpravtsev** [laravel-idea/plugin#217]
Since Laravel 8 you may to define extends | layouts | section | slot at component render function if you using whole component for route 
It's will be great to see suggestions for it 😃 
[Docs](https://laravel-livewire.com/docs/2.x/rendering-components#custom-layout)

Component example:
```php
class Settings extends Component
{
    public function render()
    {
        return view('livewire.admin.settings')->extends('layouts.app')->section('content');
    }
}
```

**Comment by adelf** [comment]
My new Macro helper generator already creates a helper code to complete these `extends` and `section` methods(will in the next version). Parameters completion is also possible...
