### ISSUE TITLE
[Feature Request] Auto-complete on validator helper

### ISSUE THREAD

**Issue by PanjiNamjaElf** [laravel-idea/plugin#219]
Laravel has helper to create new validation instance using [helper](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/helpers.php#L872)

Can you make this plugin support auto-complete rules for this helper ?

**Comment by adelf** [comment]
Sure. Thanks!

**Comment by adelf** [comment]
This is fixed in the 4.1.1 version released today.

**Comment by BassemN** [comment]
Hello @adelf 

I'm using the latest plugin version 8.0.4.233.

Auto-complete is no longer working with the [`validator()` helper function](https://github.com/laravel/framework/blob/v10.43.0/src/Illuminate/Foundation/helpers.php#L991) with rules, please check the following example:
```
        \validator()->make(
            $data,
            [
                'name' => ['required', 'max:191'],
                'email' => ['required', 'email', 'max:191'],
            ]
        );
```

Please advise

**Comment by adelf** [comment]
It never worked in this case. It only works here:
```php
\validator([], [
                'name' => ['required', 'max:191'],
                'email' => ['required', 'email', 'max:191'],
            ]
        );
```

I'll try to support your case also.

**Comment by BassemN** [comment]
> It never worked in this case. It only works here:
> 
> ```
> \validator([], [
>                 'name' => ['required', 'max:191'],
>                 'email' => ['required', 'email', 'max:191'],
>             ]
>         );
> ```
> 
> I'll try to support your case also.

Many thanks, hope to see this soon
