### ISSUE TITLE
Unknown `$faker->phone` key in the factories

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#22]
![2020-03-12_17-51-59](https://user-images.githubusercontent.com/10347617/76534212-3ffc8680-648a-11ea-95d7-295a5e1a7b6f.png)

See https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php#L37-L38

**Comment by adelf** [comment]
Yesterday I changed it to `phoneNumber`. Thanks :) Will be in the v2.3
