### ISSUE TITLE
[Feature request] Event listeners autocomplete and clickability for subscribers

### ISSUE THREAD

**Issue by zlodes** [laravel-idea/plugin#221]
Hi!

It is about Laravel event Subscribers: https://laravel.com/docs/8.x/events#writing-event-subscribers

There are two parts of the feature request.

1. At first it will be cool to have listeners methods autocomplete (second array item of second argument):
```php
public function subscribe(Dispatcher $events): void
{
    $events->listen(
        UserRegistered::class,
        [self::class, 'afterRegistrationSendNotification']
    );
}
```

2. And it should be clickable (like a "go to declaration")

P.S.: It seems like as array-style of `callable` and it's behaviour.

P.P.S: And now the listener method is marked as unused:
![image](https://user-images.githubusercontent.com/1114387/109297930-dcf33380-7843-11eb-9fa6-adc614094912.png)

**Comment by trin4ik** [comment]
Yes, and it will be cool, if subscriber" be in code-generation. like "Listener"
all needs -- radio button in listener form, which one, listener or subscriber

**Comment by adelf** [comment]
It's completed by PhpStorm now.
