### ISSUE TITLE
Get from Model::factory() method to the real factory

### ISSUE THREAD

**Issue by Gummibeer** [laravel-idea/plugin#222]
Right now the eloquent IDE code generation solves the return type problem of the `Model::factory()` method but there's no way to get from `User::factory()` method call to the `UserFactory` class.
It would be nice if there would be a context action or special click to get from the `factory()` method call to the corresponding factory class.

https://twitter.com/devgummibeer/status/1365651175534714883

**Comment by adelf** [comment]
It was a great idea and simple to implement. Thanks, man :)
https://twitter.com/laravel_idea/status/1366334880712437760
