### ISSUE TITLE
Get from Model::$casts default string cast to cast implementation

### ISSUE THREAD

**Issue by Gummibeer** [laravel-idea/plugin#223]
The `Model::$casts` array values are already autocompleted. But PHPStorm makes them clickable if a global function with same name exists (`date` cast for example).
**Side note:** it could be the PHPStorm [Php Inspections](https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) plugin doing this.

It would be nice if these strings would redirect to the cast implementation - for example `\Illuminate\Database\Eloquent\Concerns\HasAttributes::castAttribute()`. Or the more granular methods like `\Illuminate\Database\Eloquent\Concerns\HasAttributes::fromFloat()`.

Similar to what's already done in FormRequests with the rules.

https://twitter.com/devgummibeer/status/1365651594809925637

**Comment by adelf** [comment]
Fixed in 8.0.2. Thank you.
