### ISSUE TITLE
Link from model to observer and vice versa

### ISSUE THREAD

**Issue by Gummibeer** [laravel-idea/plugin#225]
The model already has a little Laravel logo on class definition line which links to the policy. It would be great if this could get a dropdown and links to policy and/or observer.

Same for the observer which should link to the attached model - this isn't that important as most observer definitions will be `saving(User $user)` so there's a fast way to get from observer to model.

It would also be great if a custom query builder would be added to the dropdown in the model class and the custom query builder will link to the model(s) using it.

I'm not sure if global scopes are possible but if so they would be also great.

https://twitter.com/devgummibeer/status/1365652452226269186

**Comment by Gummibeer** [comment]
Would also be great if the used factory class could be added to the dropdown.

https://twitter.com/schmidfelix13/status/1366444306299572235

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1369955304688001025 :) 
I added the task about global scopes to my internal tracker. So, closing this.
