### ISSUE TITLE
Automatically inject php or Vue attribute depending on component tag

### ISSUE THREAD

**Issue by aguingand** [laravel-idea/plugin#227]
Hello,

I use both Vue and laravel 7+ components in my views and I was wondering if it would be possible to automatically detect what to inject depending on component tag:
- starting `<x-` = inject php
- else = inject Vue

Currently we can chose between Blade and Vue (in :attributes owner). 

![image](https://user-images.githubusercontent.com/17453506/109665940-fe6b5c80-7b6e-11eb-8123-aac943691c1c.png)

Side note: I noticed all Vue attributes (`v-if` ...) are disabled when "Blade" is selected

**Comment by adelf** [comment]
@aguingand sadly, but Vue plugin allows to only ignore the whole files, not some tags. That's why you need to choose who is the owner. You can ask to change it in the JetBrains tracker: https://youtrack.jetbrains.com/
