### ISSUE TITLE
Does the Laravel Idea replace the "old" Laravel plugin entirely?

### ISSUE THREAD

**Issue by dmitry-ivanov** [laravel-idea/plugin#228]
Hello,

Could you please advise, are there any reasons to use both plugins, or the Laravel Idea fully replaces (and expands) the functionality of [the "old" one by Daniel Espendiller](https://plugins.jetbrains.com/plugin/7532-laravel)?

I've noticed some weird issues today when I had both plugins enabled: `@livewire` Blade directives weren't highlighted. I've disabled the "old" plugin, restarted PHPStorm, and it helped. After that, it works fine even with the old plugin enabled.

So I was curious, is it better to remove the old plugin when using the Laravel Idea to prevent possible conflicts between them? Are there any pitfalls related to that?

Thank you!

**Comment by adelf** [comment]
Laravel Idea fully covers old Laravel plugin features, except one I added to there myself)) "Extract partial blade view". But I'll add it to Laravel Idea soon.

`@livewire` was registered automatically after the restart by Laravel Idea. I'll try to make this registration right after adding livewire to your project...

**Comment by dmitry-ivanov** [comment]
Got it, thank you! 👍
