### ISSUE TITLE
[Request] Ability to use custom translation key's template

### ISSUE THREAD

**Issue by KAZAHTIP2007** [laravel-idea/plugin#229]
Hi! Request a ability for customize translation key's template.

E.g.: I'm use a custom ``Translator`` class, where instead ``Hello, :name!`` used a ``Hello, {name}!``

**Comment by adelf** [comment]
Hi. You mean during the "Generate Laravel Translation"?

**Comment by KAZAHTIP2007** [comment]
Yes.

**Comment by adelf** [comment]
Please check File | Settings | Languages & Frameworks | Laravel Idea | Other Settings. Prefix and suffix should be there.
