### ISSUE TITLE
Do not display abstract controllers in route hints

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#23]
I have an abstract controller connecting to several others. It contains logic common to various entities with the replacement of only one variable.
When adding a route, the plugin suggested its methods.

![2020-03-13_13-07-13](https://user-images.githubusercontent.com/10347617/76611588-d2a13200-652b-11ea-89e0-e0c46e08d91a.png)
![2020-03-13_13-07-31](https://user-images.githubusercontent.com/10347617/76611590-d3d25f00-652b-11ea-9b5e-87c336fda432.png)

**Comment by adelf** [comment]
added in 2.3 version. please check and comment if there are some issues.

**Comment by andrey-helldar** [comment]
![2020-03-25_02-09-53](https://user-images.githubusercontent.com/10347617/77485302-db540b00-6e3d-11ea-8358-7330490993b3.jpg)

Nice! Thanks!
