### ISSUE TITLE
[Request] Auto-complete column name on default models

### ISSUE THREAD

**Issue by PanjiNamjaElf** [laravel-idea/plugin#230]
Hello...
Laravel can make default model value on relationship => https://laravel.com/docs/8.x/eloquent-relationships#default-models
Can you make this plugin support for auto-complete the available column name based on generated [ide-helper](https://github.com/barryvdh/laravel-ide-helper) files like on factory attribute. Thanks before 😊

**Comment by adelf** [comment]
It should work in the 4.2 version released a few minutes ago. Thank you.
