### ISSUE TITLE
[Suggestion] Autocomplete/suggest timezones

### ISSUE THREAD

**Issue by squatto** [laravel-idea/plugin#231]
It would be super useful to have timezones autocomplete/suggest in Carbon/DateTime/related methods. It would be super extra useful if the suggestion popup showed the offset of each timezone as well, but maybe I'm just being greedy ;)

Thanks!

**Comment by adelf** [comment]
The main problem with offset is its floating nature) it is different for different dates... I can calculate them for today for example... and show warning about it somewhere...

**Comment by squatto** [comment]
That makes sense. It's definitely variable enough to maybe just not worry about the offset. What do you think of just autocompleting/suggesting the timezones themselves?

I doubt you'd need to autocomplete _all_ of them, or maybe so if it's easy enough. [Here's a complete list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

Thanks!

**Comment by adelf** [comment]
I’ve found a better source: https://www.php.net/manual/en/function.timezone-identifiers-list.php :)

**Comment by squatto** [comment]
haha alright alright, go the easy route ;) I honestly had no idea it was built in!

**Comment by adelf** [comment]
I only found a DateTimezone/CarbonTimeZone class constructor parameter and `Carbon::createFromFormat`. Do you know other places to complete?

**Comment by squatto** [comment]
@adelf Thanks for implementing this! There are three others that I'm aware of:

- Carbon instances have a `timezone()` method that's used to change the timezone
- Laravel's task scheduler class `\Illuminate\Console\Scheduling\Schedule` has three:
  1. The constructor accepts a timezone string (I don't think this is commonly used though since you typically inject the class dependency)
  2. Instances have a `timezone()` method to set the timezone of the scheduled task (the method comes from `\Illuminate\Console\Scheduling\ManagesFrequencies`)
  3. You can define a `scheduleTimezone()` method in `\App\Console\Kernel` that returns a timezone string if you want all of your tasks to run in the same timezone (instead of calling the `timezone()` method on each one)

The [Task Scheduling docs](https://laravel.com/docs/8.x/scheduling#timezones) talk about using timezones.

**Comment by adelf** [comment]
Thanks. I'll try to add them. Anyway, a timezone completion will be available in the `ide.json`: https://laravel-idea.com/docs/ide_json

**Comment by adelf** [comment]
4.2 is out.

**Comment by squatto** [comment]
Thank you so much! I seriously can't imagine my day without your plugin 🙏🏻
