### ISSUE TITLE
The function return type is not correctly recognized（函数返回类型不能被正确识别）

### ISSUE THREAD

**Issue by ZHOUXING1997** [laravel-idea/plugin#232]
I'm happy to use it, but the return type of the '- > get()' method can't be correctly identified, and the identified content is '\App\Models\BaseModel[]|VehicleExtModel[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\LaravelIdea\Helper\App\Models_IH_BaseModel_C|\LaravelIdea\Helper\App\Models\Vehicle_IH_VehicleExtModel_C'

This was not a problem in previous releases, about 3 releases ago

我使用的很愉快，但是 '->get()' 方法的返回类型不能被正确的识别，识别出来的内容 '\App\Models\BaseModel[]|VehicleExtModel[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\LaravelIdea\Helper\App\Models_IH_BaseModel_C|\LaravelIdea\Helper\App\Models\Vehicle_IH_VehicleExtModel_C'

这在之前的版本是没有问题的，大约在3个版本之前

**Comment by adelf** [comment]
Hi; Thank you. Can you share the `vendor/_laravel_idea/_ide_helper_models.php` file and the `get()` call where you get this exception?

**Comment by ZHOUXING1997** [comment]
Yes,How can I give it to you

**Comment by adelf** [comment]
You can send it to support@laravel-idea.com

**Comment by ZHOUXING1997** [comment]
Hi, I've sent it. I'm looking forward to your feedback


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laravel-idea/plugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 下午4:15
收件人:&nbsp;"laravel-idea/plugin"<plugin@noreply.github.com&gt;;
抄送:&nbsp;"周星"<zhou991869558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [laravel-idea/plugin] The function return type is not correctly recognized（函数返回类型不能被正确识别） (#232)





 
You can send it to support@laravel-idea.com
