### ISSUE TITLE
Autocomplete fields when creating models through factories

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#237]
Hi, so we create factories in the following way
```
$user = UserFactory::new()->create([
            'name' => 'new name',
        ]);
```

However the autocompletion for the fields on the user is not working.

The reason we do it this way instead of `User::factory()`, is because we do not want to include traits specific for testing in production code.

**Comment by adelf** [comment]
It should work in 4.2. Thanks!

**Comment by olivernybroe** [comment]
Awesome! Tested it out and it works 👍
