### ISSUE TITLE
Question: Still use barryvdh/laravel-ide-helper and can I generate the helper files outside of vendor folder?

### ISSUE THREAD

**Issue by gradedcatfood** [laravel-idea/plugin#238]
Hello,

Love this plugin and a happy customer.

Just 2 quick questions:

1) I have always used [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper). Should I removed those docblocks on my models, .phpstorm.meta file, and the ide_helper file?

When I use the Laravel Idea Code Eloquent/Code Helper files it seems to do all the same thing but I just wanted to verify that I can completely replace barryvdh/laravel-ide-helper package all together with Laravel Idea's generated helper files.

2) I think I used to be able to generate these helper files to a location other then the "/vendor" folder. I believe there is a screenshot of what it used to like like here: https://laravel-idea.com/docs/eloquent

When I go to generate the helper file, I no longer see a file path option to generate these files. It would be nice to have this option so I could commit the files to my repo. Was this option removed?

Thanks!

**Comment by adelf** [comment]
Hi, Michael.

1. if you don’t make aliases and then call it like `app(‘your-alias’)` you don’t need ide-helper anymore. The only command I still didn’t cover is “ide-helper” meta, but Laravel Idea already contains .phpstorm.meta file for all framework aliases, like app(‘config’).
2. I’ll make it configurable, but why you want to push it to git? I don’t recommend it. Git merge conflicts... and every new version of plugin can change this helper code...

**Comment by gradedcatfood** [comment]
1) Thank you, that makes sense!

2) It's def not a big deal if this is not configurable but yeah, I see your point. Maybe it's best no to commit these files

Thank you for answering my questions :)
