### ISSUE TITLE
Trouble with multiple view directories

### ISSUE THREAD

**Issue by smares** [laravel-idea/plugin#239]
Hi, I have a Laravel project which displays news articles for different target audiences. For each target audience, there is a different portal. They all share the same code basis and are switched via an environment variable.

The views are stored in `resources/views/default`, but portals can override those views by having Blade files in `resources/views/portal-xyz`. In `config/view.php` I tell Laravel to look for views in the portal specific folder first, and then in the default one:

```
    'paths' => [
        resource_path(sprintf('views/%s', env('PORTAL_NAME'))),
        resource_path('views/default'),
    ],
```

I tried configuring this via an `ide.json` file that contains the following block:

```
  "view": {
    "paths": [
      {
        "path": "resources/views/default"
      },
      {
        "path": "resources/views/portal-abc"
      },
      {
        "path": "resources/views/portal-xyz"
      }
    ]
  },
```

Now let's say I have `resources/views/default/pages/home.blade.php` and in my `HomeController` I do `return view('pages.home')`, the plugin does not find the view. If I do `return view('default.pages.home')` it does, but this breaks my concept.

Is this something you can add support for?

**Comment by adelf** [comment]
Hi, Sebastian. Will it be ok for you if there will be all `pages.home` view files when you click GoTo view?

**Comment by smares** [comment]
You mean a list to choose the file from in case there is `resources/views/default/pages/home.blade.php` and `resources/views/portal-abc/pages/home.blade.php` for example?

**Comment by adelf** [comment]
Yes.

**Comment by smares** [comment]
That would be perfect!

**Comment by smares** [comment]
Ah, one more thing: When using the code generator to create a view, would the plugin automatically place it in the first directory defined, or would it prompt in which directory to create it?

**Comment by adelf** [comment]
It uses settings value:
![image](https://user-images.githubusercontent.com/2818394/110484282-9206d500-80fb-11eb-8c88-8a3cc8685c78.png)

**Comment by adelf** [comment]
Please, try 4.2 version. And close this issue if everything is ok.

**Comment by smares** [comment]
Hmm, I can't see any change in the behavior unfortunately. Maybe I am doing something wrong.

![image](https://user-images.githubusercontent.com/818380/110774692-62241280-825e-11eb-8bf0-b9a36c5a8205.png)

So I have `return view('pages.home');` in my controller. The view is placed inside `resources/views/default/pages/home.blade.php`. `ide.json` looks like this:

```
{
  "$schema": "http://laravel-ide.com/schema/laravel-ide-v1.json",
  "view": {
    "paths": [
      {
        "path": "resources/views/default"
      },
      {
        "path": "resources/views/portal-abc"
      },
      {
        "path": "resources/views/portal-xyz"
      }
    ]
  },
  "blade": {
    "components": {
      "viewPaths": [
        {
          "path": "resources/views/default/components"
        },
        {
          "path": "resources/views/portal-abc/components"
        },
        {
          "path": "resources/views/portal-xyz/components"
        }
      ]
    }
  }
}
```

When inside the controller, I cannot click on the `pages.home`. It only works if I change the line to `return view('default.pages.home');` but then I am hard-coding that Laravel should use the default view and cannot use a portal-specific view in `resources/views/portal-abc/pages/home.blade.php`.

**Comment by adelf** [comment]
Seems, I missed that your view directories are inside the main `resources/views` folder. I’ll reproduce your issue exactly and will find a solution. Sorry.

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/111443821-cf321f00-871a-11eb-9ab1-fff7d3ab5010.png)

It works now. But there still a lot of useless completions from the base `resources/views` folder:

![image](https://user-images.githubusercontent.com/2818394/111443936-eec94780-871a-11eb-800b-a3b2e12d680f.png)

I suggest a new option in the settings, like "Disable main resources/views" folder from completion.

**Comment by adelf** [comment]
4.2.1 is released today. You can turn off the default resources/view folder here:

![image](https://user-images.githubusercontent.com/2818394/111652501-29fd7080-8818-11eb-9fde-ea6e2a1fb242.png)

**Comment by smares** [comment]
I just updated and it works! Thanks a lot! :)

**Comment by smares** [comment]
The stopped working with the latest update that came out today. 😢

**Comment by adelf** [comment]
Thank you, Sebastian. For information that might be useful for others :)

**Comment by smares** [comment]
Actually, it was not re-indexing that fixed the problem, but me opening the settings navigating through the Laravel Idea options. Even if I don't change anything, the problem gets fixed just by browsing through those settings.

I just had this issue again after the latest update to 4.3.4.211 and also after installing and configuring PHP_CodeSniffer, Mess Detector and PHP CS Fixer in PhpStorm.

Any idea what causes this problem?

**Comment by adelf** [comment]
This information might be handy. Thanks.
