### ISSUE TITLE
Add functionality to create custom castes

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#24]
https://laravel.com/docs/7.x/eloquent-mutators#custom-casts 😊

**Comment by adelf** [comment]
How often you create a custom cast class? :)

**Comment by andrey-helldar** [comment]
Created a couple of times. But to be able to do this through the plugin is priceless :)

**Comment by andrey-helldar** [comment]
There is just a need to create a custom cast. BUT in the form in which work with it is now implemented, it is impossible to use it.

**Comment by adelf** [comment]
added in 2.3 version. please check and comment if there are some issues.
