### ISSUE TITLE
Model navigation to nova resource

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#240]
Could be cool to add a link to Nova resources also 👍 
![image](https://user-images.githubusercontent.com/5870441/110778705-fdb78200-8262-11eb-8d8e-edb1a754ddad.png)
![image](https://user-images.githubusercontent.com/5870441/110778756-0d36cb00-8263-11eb-8c2c-c1966ca55097.png)

**Comment by adelf** [comment]
Added it to my internal tracker yesterday)) but it’s nice to have it here.

**Comment by adelf** [comment]
4.2.1 is released today )
