### ISSUE TITLE
Autocomplete for model attributes does not work

### ISSUE THREAD

**Issue by mathiasgrimm** [laravel-idea/plugin#241]
I have ide-helper enabled models and the models have the doc blocks but it won't autocomplete it, even inside its own class.

class lives in `namespace App\Models;` and extends a model that extends the eloquent model

**Comment by mathiasgrimm** [comment]
<img width="1261" alt="Screen Shot 2021-03-11 at 15 07 35" src="https://user-images.githubusercontent.com/450069/110833728-85a98600-827b-11eb-87f4-048e98dcefd9.png">

**Comment by mathiasgrimm** [comment]
it doesn't show the created_at for ex

**Comment by mathiasgrimm** [comment]
<img width="717" alt="Screen Shot 2021-03-11 at 15 08 56" src="https://user-images.githubusercontent.com/450069/110833920-b689bb00-827b-11eb-9190-3591a6322271.png">
if I remove the `with` it works

**Comment by adelf** [comment]
Helper code generated by `ide-helper:models` doesn’t support this. But you can try to generate Eloquent helper code by Laravel Idea: these completions will be supported.
Main menu - Code - Laravel Idea Code Generation- Eloquent helper code generation.
If you want to have completions inside the model classes you should choose “with mixin” option.

**Comment by mathiasgrimm** [comment]
works
