### ISSUE TITLE
Custom completions and *Twig* component namespaces via ide-twig.json ?

### ISSUE THREAD

**Issue by huna02** [laravel-idea/plugin#242]
the 'idea-php-laravel-plugin' laravel/idea plugin provides Blade namespace support in PhpStorm

	https://github.com/Haehnchen/idea-php-laravel-plugin#user-content-blade-template-namespace

enabling autocompletion via config in "ide-blade.json"

for those that use Twig in Laravel, enabled via

	https://github.com/rcrowe/TwigBridge

that plugin does NOT provide Twig namespace support.  the author does provide it in their Symfony/Idea plugin,

	The feature with the ide-twig.json file was added in the Symfony Plugin in version 0.11.110 years ago
	https://naxoc.net/2018/10/17/phpstorm-twig-namespaces/

@adelf I see in your latest laravel-idea/plugin ChangeLog,

	Version 4.1 (2021-02-25)
	Custom completions and Blade component namespaces via ide.json files check documentation

Can laravel-idea/plugin be extended to provide similar namespace support for Twig templates in Laravel?

**Comment by adelf** [comment]
Hi.
Could you share the case which should be supported? Like which directories, which namespaces? Laravel Idea supports twig views... but I can check your exact case.

or you haven’t installed Laravel Idea yet? There is a 30 day free trial.

**Comment by huna02** [comment]
Hi,



> or you haven’t installed Laravel Idea yet? There is a 30 day free trial.

I just realized/installed the trial a few minutes ago / thanks!

> Could you share the case which should be supported? Like which directories, which namespaces? Laravel Idea supports twig views... but I can check your exact case.

I'm probably not familiar enough to answer you correctly yet.

Generally, it should work with the Twig environment provided by

	https://github.com/rcrowe/TwigBridge

So in my current test case, e.g.,

for Twig templates in
```
cd <project root>
tree -d myresources/views/
	myresources/views/
	└── templates
		├── base.twig
		└── front
			└── front.twig
```

without laravel-idea, I've assigned a loader path & namespace
```
AppServiceProvider.php

<?php

	...
	public function boot() {

		$loader = new \Twig\Loader\FilesystemLoader();
		$loader->addPath(
			base_path() . '/myresources/views/templates',
			'templates',
		);
		\Twig::getLoader()->addLoader($loader);

	}
}
```


That allows me to use in project Twig templates, e.g.
```
{% extends 'templates.base' %}
```

or
```
{{ include('templates.front.front') }}
```

IIUC in laravel-idea, as a first step, that loader stanza from AppServiceProvider.php, would move to `ide.json`

But the specific goal is for PhpStorm to see/recognize that

```
'templates.base'
'templates.front.front'
```

and/or autocomplete
```
{{ include('...') }}
```

when creating new references.

Also, if in PhpStorm project window, you refactor/rename a file -- e.g., 
```
-	front/front.twig
+	frontB/front2.twig
```

you'd want the exec of "Do Refactor" to find/change those namespaced refences automatically. e.g.,
```
-	'templates.front.front'
+	'templates.frontB.front2'
```

at the moment, they're ignored/unchanged

**Comment by adelf** [comment]
4.2.1 version should cover almost all these needs.
You can try to configure the path here: 

![image](https://user-images.githubusercontent.com/2818394/111661505-20780680-8820-11eb-83a2-06725b5e1d14.png)

Or with ide.json. "*.twig* files are supported. Completion will be supported for all PHP calls, like `view('')`. Renaming also renames all these calls, but only file renaming. File movements to another folder... a bit more complicated. Twig plugin provides completions for a lot of cases:

{% include 'front/front.twig' %} - every word here will be completed. And renaming also should work.

**Comment by huna02** [comment]
> 4.2.1 version should cover almost all these needs.

good to hear.

but, with 4.2.1 installed, i'm getting no recognition/reaction with any namespaced .twig components

so no autocomplete, refactoring, etc of anything of the form 'templates.front' or 'templates.front.front'

atm, i have

```
cd <project root>

tree resources*/views
	myresources/views/
	└── templates
		├── base.twig
		└── front
			└── front.twig

	resources/views
	├── api
	│   ├── api-token-manager.blade.php
	│   └── index.blade.php
	├── auth
	│   ├── confirm-password.blade.php
	│   ├── forgot-password.blade.php
	...
	└── welcome.blade.php
```

and
```
cat config/view.php
	<?php

	return [

		'paths' => [
			base_path('myresources/views'),
			resource_path('views'),
		],

		'compiled' => env(
			'VIEW_COMPILED_PATH',
			realpath(storage_path('framework/views'))
		),

	];
```

since there's no mention of twig that I can see at https://laravel-idea.com/docs/ide_json,
I've just randomly tried adding this

```
cat ide.json
	{
		"$schema": "https://laravel-ide.com/schema/laravel-ide-v1.json",

		"view": {
			"paths": [
				{
					"path": "myresources/views/templates",
					"namespace": "templates"
				}
			]
		},

		"blade": {
			"components": {
				"viewPaths": [
					{
						"path": "resources/views/components",
						"namespace": "",
						"prefix": "jet-",
						"viewNamespace": "jetstream"
					}
				]
			}
		},
	}

	"twig": {
		"components": {
			"viewPaths": [
				{
					"path": "myresources/views/components",
					"namespace": "templates",
					"viewNamespace": "templates"
				}
			]
		}
	},
```

but, in in a `file.twig` template, if I start typing
```
{{ include('templ
```

there's no autocompletion, context/dropdown ... or any reaction on hover or type, at all.

what specific changes need to be made to that^ config to get twig autocompletion working?

**Comment by adelf** [comment]
twig files not under my control... seems I should implement something for twig... 
I can only complete PHP calls: like 
```php
<?php
view('complete here');
```

**Comment by huna02** [comment]
Yep, the 'view' completions seem to work; not the in-twig-template expansions, though.

Blade is, of course, 'official' for Laravel.

But there's lots of good reasons that devs choose to use Twig.  Not the least of which is cross-project compatibility/use, and the Symfony compat/support.

Hnce, TwigBridge exists.

Twig as a 1st class template env (as Blade) in Laravel-Idea would be (1) very useful, and (2) unique.  Great options for a paid product. Particularly since the 'competiton' has relegated Twig support to the Symfony-only plugin.

One question to ask is -- how reliable is TwigBridge project, and whether it makes sense to 'depend' on it, or fork it into Laravel-idea.

**Comment by huna02** [comment]
Just checking in.  Is Twig support something that you're interested in / planning to implement?

Either way, ok, of course.  Just helpful to know whether to stick around, or move on.

**Comment by adelf** [comment]
It's in the plans. However, I don't have any experience with Twig. Could you write here some examples where exactly you want to have completions? `{{ include('<template names here>' }}`. Any other places?

**Comment by huna02** [comment]
> It's in the plans.

+1

> However, I don't have any experience with Twig.

And my challenge is lack of experience with Laravel :-/

I'm, 'coming from' Twig+Symfony via PHPStorm SymfonyPlugin.

So I'll need to better understand what it is you're specifially looking for too.

> Could you write here some examples where exactly you want to have completions? {{ include('<template names here>' }}. Any other places?

Probably the best _first_ answer I can provide is

(1) Like Blade support, but for Twig (yes, I understand that's not terribly helpful)

&

(2) these:

https://www.jetbrains.com/help/phpstorm/symfony-twig.html
https://blog.jetbrains.com/phpstorm/2013/06/twig-support-in-phpstorm/

If I can get to understand more of what you're looking for, I can try to provide some specific examples.

Would be useful to get some input from @barryvdh or @rcrowe (of TwigBrdige work), if they'd be interested/available

**Comment by adelf** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/2818394/218090608-ed708054-2876-4307-932c-5e2bf924687f.png">
