### ISSUE TITLE
autocomplete *in* '.env' fails; autocomplete _of_ referenced env vars works OK

### ISSUE THREAD

**Issue by huna02** [laravel-idea/plugin#244]
I'm using
```
PhpStorm 2021.1 Beta
Build #PS-211.6305.24, built on March 5, 2021
PhpStorm EAP User
Expiration date: April 4, 2021
Runtime version: 11.0.10+9-b1341.18 amd64
```

My Laravel8 project includes
```
laravel/framework   v8.32.1
.env files support  2021.1
Laravel Idea        4.2.0.211
```

With that setup, env var completion in PHP files works as expected, as shown at

https://plugins.jetbrains.com/plugin/9525--env-files-support.

-- selections are available in dropdown context menu.

but completion of items in .env itself, as shown at

https://laravel-idea.com/docs/other#.env

do nothing.  on typing (e.g., BROADCAST_DRIVER=, as in the example), there's no automatic dropdown or autocompetion at all.

no error, just no autocomplete.

**Comment by adelf** [comment]
Thanks.

**Comment by adelf** [comment]
It should be fixed in the 4.2.1 version released today. Please check.

**Comment by huna02** [comment]
upgraded to v4.2.1.211

restarted PhpStorm

opened .env

still NO context dropdowns or autocompletion.

**Comment by huna02** [comment]
typing "." after the "=" does drop a menu down, from which you can select.  byt the selected value is *appended* after the ".", so you have to manually delete the "."

**Comment by adelf** [comment]
You're right. It doesn't work in PhpStorm 2021.1 right after installation. I tried the main menu: File > Invalidate Caches + Restart. Helped. EAP versions contain such little bugs...

**Comment by huna02** [comment]
@adelf 

invalidated all caches
restarted
allowed a complete reindexing
tried again ...

same behavior:

(1) no dropdown at "=".  have to type a letter that's IN one of the options
(2) space/tab do NOT cause a dropdown
(3) "." does cause the dropdown, but remains after selection, requiring a manual delete

**Comment by adelf** [comment]
Do you mean fully automatic completion at the end of "="? No, it doesn't work like that. It works only after Ctrl-Space or after the first letters typed...

**Comment by huna02** [comment]
Ah.

I completely missed Ctrl-Space !  (Is it _in _ the docs?) But, that works.  

I'm used to autocomplete completing as you type -- e.g. even 'in' "BROAD..."
But this is good enough. Thx for the fix!
