### ISSUE TITLE
Missing field name hint in `isDirty`,`isClean` and `wasChanged` models methods

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#25]
![2020-03-13_15-53-58](https://user-images.githubusercontent.com/10347617/76622605-e1471380-6542-11ea-895c-e3d5537cf1f9.png)
![2020-03-13_15-53-38](https://user-images.githubusercontent.com/10347617/76622607-e1dfaa00-6542-11ea-9d20-d414ff34f8b3.png)
![2020-03-13_15-53-16](https://user-images.githubusercontent.com/10347617/76622608-e2784080-6542-11ea-9847-03735d52f255.png)

**Comment by adelf** [comment]
added in 2.3 version. please check and comment if there are some issues.

**Comment by andrey-helldar** [comment]
Thanks!
