### ISSUE TITLE
Auto complete on translation replace attribute

### ISSUE THREAD

**Issue by PanjiNamjaElf** [laravel-idea/plugin#250]
I have translation like this

```
'tag_format_invalid' => 'The tag `:tag` format is invalid.'
```

When call the `trans` helper it can display auto-complete for translation key `validation.tag_format_invalid`.
Can u also make it to auto-complete on replace placeholder for the `:tag` an another placeholder if exist on that translation on helper second parameter ? Thank you before 😄

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/helpers.php#L798
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/helpers.php#L824

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
