### ISSUE TITLE
In projects with more than one IDEA module, the plugin doesn't find composer.json

### ISSUE THREAD

**Issue by ProudOne** [laravel-idea/plugin#251]
I have a project in IDEA that contains two modules. Not Laravel modules, but IDEA modules:
![image](https://user-images.githubusercontent.com/4275294/111553159-2acfcd00-875a-11eb-8999-e9b12ad10ba5.png)

The `api` module contains a Laravel project while the `api-library` module does not. Unfortunately, LaravelIDEA seems to only pick up on the `api-library` module and can't find the composer.json in the project.

![image](https://user-images.githubusercontent.com/4275294/111553289-6e2a3b80-875a-11eb-942c-89d0518a9ff8.png)

That means that even if I manually turn on the plugin, all the paths and generated file locations are wrong since they reference the `api-library` module. Manually setting the path also doesn't seem to do anything.

Am I missing a configuration option or is this an oversight?

**Comment by adelf** [comment]
Please try 4.2.1 released today. It should be fixed there.

**Comment by ProudOne** [comment]
That fixed it, thank you!
