### ISSUE TITLE
Generate Eloquent Helper doesn't want to work on project with 80+ models

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#252]
Using latest 4.2 version of Laravel Idea plugin, PHP 7.4, latest PHPStorm. 

![image](https://user-images.githubusercontent.com/20278756/111780801-cc1c6780-88af-11eb-9049-51b0f1a334b0.png)

On a smaller project I have got this helper working first time without any issues. 

My vendor folder is not excluded. 

In this particular project when running the generator it says it finds 88 tables, here are the settings used:

![image](https://user-images.githubusercontent.com/20278756/111779514-24eb0080-88ae-11eb-8c2f-aa025d5792aa.png)

The helper file it generates in `vendor/_laravel_idea/_ide_helper_models.php` is over **40,000** lines long and I wonder if phpstorm can't cope with processing such a large file. 

Every time I go to the file it seems to take a long time to analyze and seems to keep re-analyzing it:

![image](https://user-images.githubusercontent.com/20278756/111779860-8c08b500-88ae-11eb-93f2-70dfb3ab52a2.png)

Perhaps an option is needed to generate separate helper files for each table?

**Comment by adelf** [comment]
You're right. I'll try to implement different files, but not sure when.
For now, you can try to don't generate Collection proxy helper classes. They are heavy.

**Comment by dmason30** [comment]
@adelf I removed the collection proxy setting option as and the file it generated is around 32000 lines long. This seems to have made the mixins resolve correctly. I would love to have the proxy stuff but can live without for now.

One weird thing is this time round it said it found 145 models second time round the 88 was accurate. 

Thanks for the great plugin!

**Comment by adelf** [comment]
4.2.1 version contains some fixes. They might help)

**Comment by dmason30** [comment]
@adelf It appears I am already on 4.2.1 

![image](https://user-images.githubusercontent.com/20278756/111785807-f886b280-88b4-11eb-8c7b-113e496f971c.png)

**Comment by dmason30** [comment]
@adelf Possibly related to this but I am not getting any completion on `Model::factory()` without the collection proxies or count options generated. 

If I `Command + Click` the factory method it takes me to the factory class correctly. 

But when typing out `Model::factory()->...` I do not get any code completion on the custom methods that are defined in that models factory. 

In the `ide_helper_models.php` I can see on the mixin that the method return definition has been added:

```php
/*
 * ...
 * @method static _IH_IntercomFactory_ factory(...$parameters)
 */
class IdeHelperIntercom extends Model {}
```

And the generated factory code is correct

```php
/**
 * @method Intercom makeOne(array|callable $attributes = [])
 * @method _IH_Intercom_C|Intercom[]|Intercom create(array $attributes = [], Model|null $parent = null)
 * @method Intercom createOne(array $attributes = [])
 * @method _IH_Intercom_C|Intercom[]|Intercom make(array $attributes = [], Model|null $parent = null)
 * @method _IH_Intercom_C|Intercom[] createMany(iterable $records)
 * @method $this accessToken(string $accessToken = null)
 * @method $this client()
 * @method $this appId(string $appId = null)
 */
class _IH_IntercomFactory_ extends IntercomFactory {}
```

If I stick the factory phpdoc directly on my model then completion works as expected. 

```php
/**
 * @mixin IdeHelperIntercom
 * @method static \LaravelIdea\Helper\Database\Factories\_IH_IntercomFactory_ factory(...$parameters)
 */
 class Intercom extends Model
 ```

![Screenshot 2021-03-22 at 15 14 25](https://user-images.githubusercontent.com/20278756/112012822-68997080-8b21-11eb-96e6-8116917fd3eb.png)

**Comment by adelf** [comment]
Yes. If the `_ide_helper_models.php` file is big PhpStorm might ignore it. At least partially. I'll try to fix this by separating helper files somehow...

**Comment by dmason30** [comment]
@adelf Understood, in the mean time I planned to manually add the factory doc to all my models but this seems to prevent the generator from generating the factories 😢 . I guess I can go without factory completion for now too. 

```php
/**
 * @mixin IdeHelperIntercom
 * @method static \LaravelIdea\Helper\Database\Factories\_IH_IntercomFactory_ factory(...$parameters)
 */
 class Intercom extends Model
```

**Comment by adelf** [comment]
I've changed the helper code generation in the Laravel Idea 4.2.2. Now it separates helper code into 3 files and it should fix this issue.

**Comment by dmason30** [comment]
@adelf initial run looks great thanks! even running nicely with the collection proxies 😱
