### ISSUE TITLE
Remove phpdocs from models warnings appears behind generator settings window

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#253]
Plugin: 4.2

Sorry got another one, see below video when you select the option the box appears and then quickly hides itself behind the setting window.

https://user-images.githubusercontent.com/20278756/111783347-0a1a8b00-88b2-11eb-834d-b0bbaa03e3bd.mp4

**Comment by adelf** [comment]
Seems, its an issue with 2 modal windows in Mac. Thanks for reporting this. And no need to sorry)

**Comment by adelf** [comment]
I just moved it to the own action. So, it's fixed) 8.0.2 released today. Thank you.
