### ISSUE TITLE
Factory method with constant as argument default error leads to phpdoc error in Eloquent Helper File

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#254]
Plugin: 4.2.1

![image](https://user-images.githubusercontent.com/20278756/111793552-4b646800-88bd-11eb-91b5-5d78efd8d74e.png)

In our factory we have this helpful state method:

```php
class MemberInvoiceFactory extends Factory
{
    //...

    public function payable(string $type = MemberPaymentSource::PAYMENT_SOURCE_TYPE_CARD): self
    {
        return $this->state([
            'payable_type' => 'member_payment_sources',
        ]);
    }
}
```

It appears to have issue with constants as default arg values or maybe it a truncation issue?

**Comment by adelf** [comment]
Thank you.

**Comment by adelf** [comment]
Laravel Idea 4.2.2 is out.
