### ISSUE TITLE
Idea: refactor validation rules from string to array

### ISSUE THREAD

**Issue by stidges** [laravel-idea/plugin#256]
When working on a project I found a lot of string validation rules that I would like to change into an array. It would be awesome if there was a quick refactor for this:

```php
// before
return [
    'email' => 'required|string|email',
];

// after
return [
    'email' => ['required', 'string', 'email'],
];
```

**Comment by adelf** [comment]
Implemented some time ago. Option(Alt)-Enter on validation rules.
