### ISSUE TITLE
Laravel-idea.com seems to be down

### ISSUE THREAD

**Issue by flammehawk** [laravel-idea/plugin#257]
Greetings, 

after thinking about trying this plugin I wanted to check out the documentation for it. 
But it seems like the site for it is not reachable. 

Any place where I could Look for the documentation?

**Comment by adelf** [comment]
Hi. Correct url is https://laravel-idea.com/

**Comment by flammehawk** [comment]
Sorry, typo in the tittle. 

After Clicking on your link I get the following page: 
![image](https://user-images.githubusercontent.com/57394581/112155786-ef178600-8be5-11eb-84ee-35e560efd098.png)

**Comment by s1rc** [comment]
I've been having the same issue for a while now.

**Comment by adelf** [comment]
I was checking https://laravel-idea.com/ by self and by uptime monitors - everything is ok all this time. Maybe issues somewhere between you and laravel-idea.com... 
Is it still unavailable? Could you make `traceroute laravel-idea.com`(linux/mac) or `tracert laravel-idea.com`(windows) in your command line?

**Comment by s1rc** [comment]
Turns out it was geo restriction from my ISP.

**Comment by adelf** [comment]
Any idea why? Maybe I should move it somewhere else...

**Comment by s1rc** [comment]
I have no idea why, seems a little odd to me. I can access the website fine with VPN.
