### ISSUE TITLE
I renew my license but I cannot reactive it

### ISSUE THREAD

**Issue by LTroya** [laravel-idea/plugin#259]
I renew my license (After a few months be expired) and I don't see where I can reactivate it

![image](https://user-images.githubusercontent.com/6491259/112789153-0e694580-9022-11eb-9e36-d1e0b865135e.png)

![image](https://user-images.githubusercontent.com/6491259/112789165-13c69000-9022-11eb-98fd-f697f2b2abf9.png)

I have an activate license on jetbrains 

![image](https://user-images.githubusercontent.com/6491259/112789184-2345d900-9022-11eb-802e-7474b37b1a9c.png)

How can I reactivate it again?

**Comment by LTroya** [comment]
I have disabled -> enable and uninstall -> install again. Nothing works

**Comment by webtamizhan** [comment]
Same problem to me, I have another PHPStorm License, so i purchased Laravel Idea again, Shows me License expired for the new PHPStorm License.

Is there anything i missed it out?

**Comment by webtamizhan** [comment]
I solved it by Help -> Register.
There you will have a plugin option to reactivate license. This is happened to me because of i switched phpstorm license to new account and also Laravel Idea license expired yesterday. Now its working good.

**Comment by adelf** [comment]
@LTroya it should be done in the main menu: Help > Register... window.

**Comment by LTroya** [comment]
Oh thanks! That solved my problem!
