### ISSUE TITLE
Variable substitution ${DATE} ${TIME} does not work when creating a file 

### ISSUE THREAD

**Issue by lessons-web** [laravel-idea/plugin#26]
![Аннотация 2020-03-16 155003_LI](https://user-images.githubusercontent.com/60647114/76739558-f0c29880-679e-11ea-931e-cb2b114156af.jpg)

**Comment by adelf** [comment]
Thank you. I thought PhpStorm will add it automatically :) Will be fixed.

**Comment by adelf** [comment]
added in 2.3 version. please check and comment if there are some issues.
