### ISSUE TITLE
Module composer.json file not found

### ISSUE THREAD

**Issue by terry-lonesski** [laravel-idea/plugin#261]
When I tried to create model using laravel-idea a got an error.

**Create model failed**
Module composer.json file not found

why is it necessary to create composer.json file for each module if I don't need them?

I decided to disable composer.json file for every module by my ownm using nWidart package

**Comment by adelf** [comment]
Seems, you've chosen a Module system which requires `composer.json` files. I need them to understand the namespace for created classes. What kind of structure your application has?

**Comment by adelf** [comment]
nWidart with disabled composer.json files? mmm... Let me check.

**Comment by adelf** [comment]
I'll try to fix this in the next version. It will use an "upper" composer.json file to find a namespace.

**Comment by adelf** [comment]
Laravel Idea 4.2.2 with the fix is out.
