### ISSUE TITLE
PhpDocMissingReturnTagInspection deprecated

### ISSUE THREAD

**Issue by slapoguzov** [laravel-idea/plugin#263]
The plugin uses `PhpDocSignatureIsNotCompleteInspection` that has been disabled and removed since 2021.1 RC. The functionality of this inspection was implemented in a new inspection `PhpDocSignatureIsNotCompleteInspection`. It would be nice if this usage is removed\replaced.

**Comment by adelf** [comment]
Hi, Alexander. Thank you. As I see it's still just deprecated... When the RC will be released?

**Comment by adelf** [comment]
Laravel Idea 4.2.2 is out.
