### ISSUE TITLE
[Feature request] Context action to create missing blade files

### ISSUE THREAD

**Issue by SjorsO** [laravel-idea/plugin#266]
It would be nice if the plugin had a "Create blade file" context action. 

For example, in a new controller, with a blade file that doesn't exist yet:
![image](https://user-images.githubusercontent.com/7202674/113737578-72fd6200-96fe-11eb-959d-47895dd79b23.png)

It would be great if there was a context action for creating this missing blade file. The context action could create and open the blade file with one click.

**Comment by adelf** [comment]
Done in the 4.3.1
