### ISSUE TITLE
lumen $this->validate popup code completion not work

### ISSUE THREAD

**Issue by frank-kios** [laravel-idea/plugin#267]
lumen $this->validate popup code completion not work

$request->validate work fine. but lumen does not have this
![Screenshot 2021-04-09 003419](https://user-images.githubusercontent.com/529505/114071487-5febbd00-98cb-11eb-94cc-cb382525b93d.png)

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1384134170817925131 )

**Comment by adelf** [comment]
Laravel Idea 4.2.2 is out.
