### ISSUE TITLE
Auto completion / type hints for L7 blade-x tags

### ISSUE THREAD

**Issue by joveice** [laravel-idea/plugin#27]
Would be awesome if it could display auto completion and type hints for the L7 blade-x tags [https://laravel.com/docs/7.x/blade#displaying-components](https://laravel.com/docs/7.x/blade#displaying-components). I see it supports spatie/laravel-blade-x which is dropped since it got integrated with Laravel.

**Comment by adelf** [comment]
Working on it right now :)

**Comment by joveice** [comment]
@adelf Then count me in as a paying subscriber after the trial!

**Comment by adelf** [comment]
added in 2.3 version. please check and comment if there are some issues.
