### ISSUE TITLE
Query Builder pluck() method should return Collection, not the Query Builder

### ISSUE THREAD

**Issue by Kovah** [laravel-idea/plugin#270]
I noticed this issue while checking an application with Enlightn. After generating the Eloquent helper code, my IDE complains about the following piece of code:

```php
SomeModel::where('db-field', $vvar)->pluck('name')->join(', ');
```

The IDE tells me that `join()` is missing a second parameter. The issue is the generated helper code for pluck. Currently, it returns `$this`, which is the query builder, but it should return a Collection.

```php
@method $this pluck(string $column, null|string $key = null)
```
must be changed to
```php
@method Collection pluck(string $column, null|string $key = null)
```

**Comment by adelf** [comment]
That was a very deep bug. Thank you for posting. Fixed.

**Comment by Kovah** [comment]
Awesome. Thanks!
