### ISSUE TITLE
Eloquent::query() makes the result not being marked as the specified model, but as a generic model

### ISSUE THREAD

**Issue by lsalazarm99** [laravel-idea/plugin#271]
The following snippets return the same thing:
```php
Model::query()
    ->with('anoterModel')
    ->where('id', '=', 1)
    ->get()
;
```

```php
Model::with('anotherModel')
    ->where('id', '=', 1)
    ->get()
;
```

I use `query()` because it makes all the other functions (`with`, `where`, `whereHas`, etc) at the same indent level. But when I use it, the result's type is marked as `Illuminate\Database\Eloquent\Builder[] | Illuminate\Database\Eloquent\Collection`. Without it, the result is  `App\Models\Model | Illuminate\Database\Eloquent\Builder[] | Illuminate\Database\Eloquent\Collection | Illuminate\Database\Query\Builder[] | Illuminate\Support\Collection`, the correct one.

Just in case, the autocompletion inside the query builder (for example, the `where` function) works perfectly fine. The issue is only in the result.

**Comment by adelf** [comment]
Do you use our Eloquent Helper generator (https://laravel-idea.com/docs/eloquent#helper-code-generation)?  Or from Barry's package?

My helper code is smart enough for this:

![image](https://user-images.githubusercontent.com/2818394/115461691-61ee3e00-a232-11eb-9323-b9e2b56cf8f3.png)

**Comment by lsalazarm99** [comment]
I use the one from Barry because it allows me to have those autocompletion docs in a separate file. Do you think it's an issue from there so I should post it there?

**Comment by adelf** [comment]
Laravel Idea also generates everything in the separate file.
