### ISSUE TITLE
[Feature Request] Migrations as anonymous classes

### ISSUE THREAD

**Issue by zlodes** [laravel-idea/plugin#272]
Hi!

There is new feature in Laravel 8. 
Now we can create migration within anonymous class object instead of just class.
It will solve the issue with duplicated class names of migrations. 

For more information about this feature: https://github.com/laravel/framework/pull/36906

I think it could be implemented as checkbox in the migration creation window.

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1384484240168034306 )
Thanks)

**Comment by adelf** [comment]
Laravel Idea 4.2.2 is out.
