### ISSUE TITLE
[Feature Request] Go to other translation definitions

### ISSUE THREAD

**Issue by Daanra** [laravel-idea/plugin#273]
I often find myself having to edit a single translation in multiple languages.

This process can be quite tedious if you have *a lot* of translations. 

To speed up this process, I think it would be nice to have a feature that allows us to quickly navigate between the translation files in different languages when we press on some quick action next to the translation key. If you click on the action it would show a dropdown that allows you to navigate to the translation files that define the same key in a different language.

This would work similarly to the quick action next to a model class that allows you to navigate to its corresponding migration and factory class.

**Comment by adelf** [comment]
Yes. I know that feeling. I've worked on 45 lang project) One of the features which should help is a Translation manager. It will be a tool window with some features like - find all missing translations, edit one key translations (this one should help you), and some others. What do you think?

About your suggestions... I can't imagine a really convenient implementation for now... moving between 20+ languages will be not very productive... but I'll try to make something. Thank you.

**Comment by adelf** [comment]
I think this will be covered by the Translations Editor feature: https://twitter.com/laravel_idea/status/1425438027174850561
Closing this.

**Comment by RoodFruit** [comment]
@adelf Any update on the Translations Editor?

**Comment by adelf** [comment]
There are some issues with it, so it was postponed. But I hope to release it in March.

**Comment by vjanssens** [comment]
@adelf is this or the translations editor still on the roadmap? If the translations editor is too much work, it would already be of great help to implement what was suggested by OP.
