### ISSUE TITLE
Eloquent autocompletion not working

### ISSUE THREAD

**Issue by jamesRUS52** [laravel-idea/plugin#274]
After update on php storm 2021 and last laravel idea
Eloquent model autocompletion not working while _ide_helper_models.php in vendor/_laravel_idea

if copy file to root folder of project, it work well again as expected

**Comment by adelf** [comment]
Just checked in the last PhpStorm 2021.1 - works ok. 
Have you excluded `vendor` folder manually? Maybe File > Invalidate Caches & Restart and generate Eloquent helper again?

**Comment by jamesRUS52** [comment]
you are right
vendor was manual excluded
thank you
