### ISSUE TITLE
add auto-completion for accessors

### ISSUE THREAD

**Issue by michabbb** [laravel-idea/plugin#275]
if a model has functions like:

```php
public function getSomethingAttribute()
```

i would be happy to see auto-completion for `$model->Something`
and when following "Something", i should get redirected to "getSomethingAttribute()" at the referencing model.

thanks!

**Comment by adelf** [comment]
If you use Eloquent Helper Code generation: https://laravel-idea.com/docs/eloquent#helper-code-generation it should already complete `something` if the model has `getSomethingAttribute()` method.
But thank you for the redirect suggestion. Will try to implement it.

**Comment by michabbb** [comment]
I'm using the helper, but don't see that suggestion, sorry, that's why I made this issue 😏

**Comment by adelf** [comment]
That's strange. If a model class has the `getSomethingAttribute()` method, `something` field should be in its helper code(not `Something`). If not, could you please send your models code?

**Comment by michabbb** [comment]
![image](https://user-images.githubusercontent.com/3524595/115468362-47689480-a233-11eb-99a4-3a62f4e71bd2.png)

i am using tabnine, that´s why i see it.....
but i thought, laravel-idea should show me this, too 😏 

in my productvariant model, i have these functions:

```php
public function getBestandAttribute(): float
public function getBestandVerfuegbarAmAttribute(): Carbon
```

and to avoid confusion: "Bestand" and "BestandVerfuegbarAm" are *NOT* columns of my model.
they are independent "accessors".

**Comment by adelf** [comment]
Could you try to generate without mixins? It seems there some issues with new PhpStorm and mixins...

![image](https://user-images.githubusercontent.com/2818394/115474189-961f2a00-a245-11eb-8e20-9b671e6762dd.png)

**Comment by michabbb** [comment]
![image](https://user-images.githubusercontent.com/3524595/115474862-b0093e80-a23e-11eb-96f3-36d17a5fd613.png)

that´s wired... i also did not use mixins, i also didn´t select "Create Collection proxy helper classes", i will check again, to see if it has anything to do with that....

**Comment by michabbb** [comment]
no... you´re right. as soon as i don´t use "mixins", the auto-completion is working. what exactly does "with mixins" do?

**Comment by adelf** [comment]
After generation without mixins:

User.php: `class User extends Model`
_ide_helper_models: `/*tons of phpDocs*/ class User extends Models`

with mixins:

User.php: `/* @mixin IdeHelperUser */ class User extends Model`
_ide_helper_models: `/*tons of phpDocs*/ class IdeHelperUser extends Models`

PhpStorm has some issues when I use the first method. I thought I can solve them with mixins. But in the new versions, it just doesn't work. Thank you.

**Comment by michabbb** [comment]
thank **YOU** 👍 ❤️
