### ISSUE TITLE
How do I switch from my personal license to one provided by my employer?

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#276]
I've managed to convince my employer to buy subscriptions for the whole team.
Currently I have a personal license, and I'd like to cancel that subscription and switch to the one my employer pays for.
How do I do that?

**Comment by adelf** [comment]
Hi, Morten. The sales and licenses are fully on the JetBrains side. So, please write to sales@jetbrains.com. They will definitely help.

Thanks for choosing Laravel Idea and influence the team, BTW :)
