### ISSUE TITLE
firstWhere incorrect property type

### ISSUE THREAD

**Issue by leecolarelli** [laravel-idea/plugin#277]
Using the latest phpstorm and latest Laravel Idea, the firstWhere method is incorrectly detected as a hasMany property type, where it should be an object.

E.g. `$model->firstWhere('attribute', $attribute)` is detected as a hasMany where as `$model->where('attribute', $attribute)->first()` is correctly detected.

Is this something that Laravel Idea would look to take care of? I assume so but didn't want to upset anyone.

**Comment by adelf** [comment]
Have you generated an Eloquent Helper Code by Laravel Idea?
https://laravel-idea.com/docs/eloquent#helper-code-generation

**Comment by leecolarelli** [comment]
Yes that fixed it thank you!

**Comment by adelf** [comment]
Great 👍
