### ISSUE TITLE
Can't generate Eloquent helper code for many databases

### ISSUE THREAD

**Issue by lsalazarm99** [laravel-idea/plugin#279]
My project connects to 4 different databases. When I generate the code for one of them (using the "connection" method), it erases the previously generated code and writes a new file for the found models. It makes it impossible to have all the models with their generated code.

Is there any way to solve this?

**Comment by adelf** [comment]
> Is there any way to solve this?

Not for the current version, but I'll fix this. Thank you.

**Comment by lsalazarm99** [comment]
In #252 you said you could solve that issue by separating the generated file. Maybe you can separate it by model? So it would just erase the files of the models that were found in the database in order to rewrite them and leave the ones that were not found.

It's just an idea. In any case, many thanks for the "will be fixed"! 😄

**Comment by lsalazarm99** [comment]
Meanwhile, I was able to solve this by renaming the generated files for each connection.

![image](https://user-images.githubusercontent.com/42286051/115747885-47fc4a80-a35b-11eb-91e0-96e2a6a81fcc.png)

**Comment by adelf** [comment]
Awesome :) Everything works and completion is ok?

**Comment by lsalazarm99** [comment]
I've been working for a few hours with this and everything seems fine. Code completion for properties, relationships, and strings works great. "Collection proxies" and "builders" works too. I didn't have any issues.

As you might know, the code generator generates code for all the models, included the ones that didn't found in the database. I didn't delete them. The IDE doesn't complain about it, so, great 😄.

**Comment by lsalazarm99** [comment]
Update: Inside the model, the IDE complains about the "Property accessed via magic method" thing, but the code completion works.

![image](https://user-images.githubusercontent.com/42286051/115780956-6a07c400-a37f-11eb-9461-cfa952142ae2.png)

Also, if you use a scope method of a model inside an anonymous function, the code completion doesn't work. If you type it anyway, it shows a warning.

![image](https://user-images.githubusercontent.com/42286051/115781244-bbb04e80-a37f-11eb-9650-26d00f684e3c.png)

The latter works well if used like this.

![image](https://user-images.githubusercontent.com/42286051/115781523-1f3a7c00-a380-11eb-9267-02b53d0030b8.png)

It's nothing annoying in my opinion.

**Comment by adelf** [comment]
Yes, it's a known problem about not completing inside a class - https://youtrack.jetbrains.com/issue/WI-54460

And Builder class also doesn't have the `active()` method :) But I'll try to fix it by providing the correct type for `$query` variables.

**Comment by adelf** [comment]
Laravel Idea 5.0 is out. It can use more than 1 database for helper code.
