### ISSUE TITLE
Support for blade icons

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-idea/plugin#281]
Hello,

is it possible to add support for these?
https://github.com/blade-ui-kit/blade-icons

They (the different icon packages) get registered like that:
https://github.com/blade-ui-kit/blade-heroicons/blob/main/src/BladeHeroiconsServiceProvider.php 

Great plugin!

Best regards

**Comment by adelf** [comment]
Hi, Lars. Yes, I know about Blade UI and icons. They have a bit complicated components registration, but I think I could support them.

**Comment by AndreSchwarzer** [comment]
This would be awesome to have

**Comment by adelf** [comment]
The 4.3 version with blade-icons support is released
