### ISSUE TITLE
Incorrect Gate argument types in generated helper code

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#283]
Plugin: 4.2.2

The generated phpdoc for `Gate::denies` and others is incorrect as the `$arguments` argument can be either an `array` or a `string`:

```php
     * @see \Illuminate\Contracts\Auth\Access\Gate::raw
     * @method static mixed raw(string $ability, array $arguments = [])
     * @see \Illuminate\Contracts\Auth\Access\Gate::check
     * @method static bool check(iterable|string $abilities, array $arguments = [])
     * @see \Illuminate\Contracts\Auth\Access\Gate::denies
     * @method static bool denies(string $ability, array $arguments = [])
     * @see \Illuminate\Contracts\Auth\Access\Gate::any
     * @method static bool any(iterable|string $abilities, array $arguments = [])
```

The below is valid code but is warning me that it should be an array:

![image](https://user-images.githubusercontent.com/20278756/115869035-37b89e00-a435-11eb-9984-25b74ac4ab49.png)

**Comment by adelf** [comment]
Somehow I forgot about this issue. Sorry. I've fixed it. I hope to release a new version with it next week. Or maybe a bit later.

**Comment by adelf** [comment]
4.3.2 version is available.
