### ISSUE TITLE
Factory completion not working with large number of models

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#284]
Plugin: 4.2.2

After updating most of the issues in #252  were resolved except for factory completion. Not sure if this is still related to having a lot of models or not.

I am using mixins as shown below and I have tried invalidating caches.

I am not getting any completion on `Model::factory()` with or without the collection proxies or count options generated. 

If I `Command + Click` the factory method it takes me to the factory class correctly. 

But when typing out `Model::factory()->...` I do not get any code completion on the custom methods that are defined in that models factory. It only does completion for the base factory class.

In the `ide_helper_models.php` I can see on the mixin that the method return definition has been added:

```php
/*
 * ...
 * @method static _IH_IntercomFactory_ factory(...$parameters)
 */
class IdeHelperIntercom extends Model {}
```

And the generated factory code is correct in `ide_helper_model_factories.php`

```php
/**
 * @method Intercom makeOne(array|callable $attributes = [])
 * @method _IH_Intercom_C|Intercom[]|Intercom create(array $attributes = [], Model|null $parent = null)
 * @method Intercom createOne(array $attributes = [])
 * @method _IH_Intercom_C|Intercom[]|Intercom make(array $attributes = [], Model|null $parent = null)
 * @method _IH_Intercom_C|Intercom[] createMany(iterable $records)
 * @method $this accessToken(string $accessToken = null)
 * @method $this client()
 * @method $this appId(string $appId = null)
 */
class _IH_IntercomFactory_ extends IntercomFactory {}
```

If I stick the factory phpdoc directly on my model then completion works as expected. 

```php
/**
 * @mixin IdeHelperIntercom
 * @method static \LaravelIdea\Helper\Database\Factories\_IH_IntercomFactory_ factory(...$parameters)
 */
 class Intercom extends Model
 ```

![Screenshot 2021-03-22 at 15 14 25](https://user-images.githubusercontent.com/20278756/112012822-68997080-8b21-11eb-96e6-8116917fd3eb.png)

**Comment by mortenscheel** [comment]
I'm on plugin version 4.3.2.211.
One of my projects has a 5 MB `_ide_helper_models.php` file, and the only way I could get completion to work was with this workaround.

Help menu > Edit Custom Properties
Add `idea.max.intellisense.filesize=10000`
Restart PhpStorm.

**Comment by dmason30** [comment]
@adelf Is there scope for the plugin to chunk the factories by X per file to mitigate this and possibly could work for the other files like models etc? Rather than having to change this setting?

**Comment by adelf** [comment]
@dmason30 I'll try to implement this chunking... in the next version. 

@mortenscheel how many models do you have in the project?

**Comment by dmason30** [comment]
The generator says 147 for me but a lot of those are from vendor total models in my code is 89.

**Comment by mortenscheel** [comment]
@adelf 440 models in total. 390 in the App namespace

**Comment by dmason30** [comment]
@adelf @mortenscheel My files aren't more than 5mb so changing that setting didn't do anything for me. Is there anything IDE setting wise that might prevent this from working? I get completion for literally everything else except factories using mixins.

**Comment by adelf** [comment]
@dmason30, could you tell again why you are using the "with mixin" option?

**Comment by dmason30** [comment]
@adelf I think originally there was an issue on phpstorm which meant I needed mixins to get any completions at all.

I just removed all mixins and invalidated caches and I seem to be getting completions for everything still including factories 🎉.

I would have thought mixins help completions not break it, could that be some other phpstorm bug?

**Comment by adelf** [comment]
"With mixins" option is a try to fix one PhpStorm problem: https://youtrack.jetbrains.com/issue/WI-54460
PhpStorm doesn't see my helper code when a user types anything inside this class. But it doesn't work also... So, I think I'll remove this option and will ask the PhpStorm team to do something with this bug.

**Comment by dmason30** [comment]
Understood, I can live without that completion until they decide to fix it, however, I use factories so much and was tired of `@var`-ing to hint the models 😃  Thanks for your help!

**Comment by adelf** [comment]
I managed to reduce the amount of Eloquent helper code dramatically in the 4.4.2 update. So, I think I can close the issue.
