### ISSUE TITLE
[Feature Request] Support Completion and Navigation for Mail::send array

### ISSUE THREAD

**Issue by dan-iway** [laravel-idea/plugin#286]
The plugin already supports completion and navigation to views in 
```php
Mail::send('<tab>');
```

It would be great if support could be extended to also work when providing the view as array with the keys 'text', 'raw' and 'html'

```php
Mail::send(['text' => '<tab>']);
Mail::send(['html' => '<tab>']);
Mail::send(['raw' => '<tab>']);
```

**Comment by adelf** [comment]
Added. Thanks.

**Comment by adelf** [comment]
4.3 is released
