### ISSUE TITLE
[Feature request] ability to create missing blade view

### ISSUE THREAD

**Issue by dsazup** [laravel-idea/plugin#287]
Hey! Apologies if this was already requested -  I couldn't find it 🤔  Would it be possible to check if the blade view exists and add an option to create it in this context menu? 

![Screenshot 2021-04-27 at 15 33 03](https://user-images.githubusercontent.com/8631224/116241695-db73b800-a76d-11eb-8ad0-afe9d4f3186c.png)

**Comment by adelf** [comment]
Thanks for posting) it will be implemented soon.

**Comment by madman-81** [comment]
Do you have something similar planned for missing language strings? Or should I create a separate issue for that?

**Comment by adelf** [comment]
@madman-81 please create a separate issue. I'll try to implement it in one of the next versions.
BTW, https://laravel-idea.com/docs/localization#key-generation - you can create keys that way for now.

**Comment by adelf** [comment]
Implemented in the 4.3.1 version.
