### ISSUE TITLE
[Feature Request] Form Request Rules in Traits

### ISSUE THREAD

**Issue by bogdankharchenko** [laravel-idea/plugin#288]
I want to be able to have autocomplete support for FormRequest rules which are shared via trait

It seems like I can autocomplete `additionalRules(): array` given this method is inside the FormRequest class, but as soon as I move to it to a trait I lose autocomplete.

We would much appreciate it

**Comment by zlodes** [comment]
I think it's a bad idea to share rules between several `FormRequests` via trait. 

As a solution you may try add `@mixin FormRequest` into your trait's phpdoc.

**Comment by adelf** [comment]
Hi, Bogdan. So, basically, you want to complete `additionalRules()` method for **any** class?

**Comment by bogdankharchenko** [comment]
@adelf so right now, if you have a method ending in "rules" in a form request, it will automatically complete the rules -- so we've been trying to separate some common rules by calling them "paymentMethodRules" for example -- which works great given that these rules exist in the same class as FormRequest you are working with -- but when you move these methods into a trait the auto complete stops working.

We would like to be able to put a method in a trait called `anyNameWeWishRules()` and have it autocomplete as part of the rule set...


Example
```php
<?php

trait AdditionalRuleTrait {
   public function anyNameWeWishRules()
   {
       return ['phone'=>'required'];
   }
}

class ProcessPaymentRequest extends FormRequest
{
        use AdditionalRuleTrait;

	public function authorize()
	{
		return $this->user()->can('update', $this->route('user'));
	}
	
	public function rules()
        {
             return array_merge(['name'=>'required'], $this->anyNameWeWishRules());
        }
}


$request->input('name'); // Autocompletes just fine
$request->input('phone'); // currently it does not autocomplete unless the trait is inlined inside the class

```

**Comment by adelf** [comment]
Do you have only one trait with additional rules in the project?

**Comment by bogdankharchenko** [comment]
Yeah for now we only have one trait which does this functionality, shared with two form requests, in our case just validating credit card information.

**Comment by adelf** [comment]
For now, you can just add this class here:

![image](https://user-images.githubusercontent.com/2818394/116781326-d8890800-aa8a-11eb-90bd-4cad1d591fa4.png)

And have at least the rules completion:

![image](https://user-images.githubusercontent.com/2818394/116781344-e5a5f700-aa8a-11eb-811b-d876f9619ce4.png)

**Comment by bogdankharchenko** [comment]
@adelf that's perfect 

thank you
