### ISSUE TITLE
Wont work with layouts?

### ISSUE THREAD

**Issue by nezaboravi** [laravel-idea/plugin#290]
Hi, awesome, i am testing it and will purchase it if happy. Today is a first day, seems it works so far.
However one thing bugs me.
```
  return view('livewire.landing')
            ->layout('layouts.base');
```
            
```view('livewire.landing')```  is clickable, while ```layout('layouts.base');``` is not.

This is noticed by other members of laravel livewire community as well. Is it possible to get that work?

**Comment by adelf** [comment]
I'll try to add this to the next version. Thanks!

**Comment by adelf** [comment]
4.3 is released

**Comment by ph7jack** [comment]
@adelf Is it working? For me, I cant get references to `layout` or any other `view macro`.

**Comment by adelf** [comment]
@PH7-Jack have you generated a helper code? main menu - Laravel - Generate Helper Code?

**Comment by ph7jack** [comment]
@adelf Thanks, I don't. Now it's working.
