### ISSUE TITLE
[Feature Request] Automatically replace spaces with underscores in migration names

### ISSUE THREAD

**Issue by squatto** [laravel-idea/plugin#293]
Spaces are allowed when typing in the name of the migration class/file name but they cause an error when you press "OK". It would be great to have them automatically replaced with underscores to avoid having to type underscores manually between words. As I type that out I realize how lazy it makes me sound 😂 

Here's a visual:

![migration name with spaces](https://user-images.githubusercontent.com/748444/116621214-1279d300-a900-11eb-8de1-d882c7347ae5.gif)

Thanks!!

**Comment by adelf** [comment]
> As I type that out I realize how lazy it makes me sound

True)) But I'll try to implement this)

**Comment by adelf** [comment]
It should work in the 4.3 version.
