### ISSUE TITLE
Can't create anonymous migration if the class already exists

### ISSUE THREAD

**Issue by squatto** [laravel-idea/plugin#295]
When creating an anonymous migration, it will fail if you enter the name of an existing migration class. This should be allowed since it isn't actually going to create a named class.

Here's an example. I tried to create a migration using the same name as a migration from a package.

![Screen Shot 2021-05-05 at 1 20 42 PM](https://user-images.githubusercontent.com/748444/117197310-e6999a00-ada4-11eb-962f-5c65bda80a7d.png)

![Screen Shot 2021-05-05 at 1 20 47 PM](https://user-images.githubusercontent.com/748444/117197346-f1542f00-ada4-11eb-9397-d67e043fc0a2.png)

Thanks!

**Comment by adelf** [comment]
Fixed, thanks!

**Comment by adelf** [comment]
4.3 is released
