### ISSUE TITLE
Plugin causes weird issue with function references

### ISSUE THREAD

**Issue by canvural** [laravel-idea/plugin#298]
**Plugin version:** 4.2.2.211

Hello,

First I thought it was PHPStorm issue. [Asked](https://twitter.com/can__vural/status/1390656925336055808) on Twitter. And with the help, I found out that this plugin causes the issue.

Basically when this plugin is enabled,
```php
<?php

use function \count;

$array = [];

count($array);
```

in the above code, PHPStorm thinks `count` function is coming from `squizlabs/php_codesniffer` test file. And when I disable the plugin, it works as expected.

![image](https://user-images.githubusercontent.com/1574232/117467390-ee4b7100-af53-11eb-8c5e-af4d280dffd9.png)
(see the `Source:` part)

I can reproduce this in multiple machines and projects. And consistently, error disappears when the plugin is disabled.

**Comment by adelf** [comment]
It's possible. I'm trying to help PhpStorm to find the correct reference if there is more than 1 candidate. It seems, for some reason I like php_codesniffer implementation more than the standard one :)

Thank you for posting and finding this out. I'll try to fix it.

P.S. As I understand, test sources shouldn't be downloaded for the normal package using. A `--prefer-dist` flag was forgotten? :)

**Comment by canvural** [comment]
Thank you for the response!

> A --prefer-dist flag was forgotten? 

I thought that was the default. If it's a stable tag. (not `dev-..`) I'll check later again :+1:

**Comment by adelf** [comment]
No, I checked. Seems, they include tests in their distribution...

**Comment by adelf** [comment]
Fixed. Thank you again.

**Comment by adelf** [comment]
4.3 is released
