### ISSUE TITLE
Multiple definitions exist for class 'xxxxx' in PhpStorm

### ISSUE THREAD

**Issue by MattDaviesHD** [laravel-idea/plugin#3]
I am getting this in a few places - I have all of the default Laravel stuff turned off (except for the helper and your plugin), yet I still get said error in a bunch of places.

**Comment by adelf** [comment]
Hi, Matt.
Seems, it’s about Laravel Facades, isn’t it? They have duplicates in the _ide_helper.php file. I already fixed this issue for Eloquent models... I’ll try to fix it for facades this week.

**Comment by MattDaviesHD** [comment]
Yup, that's the one!

**Comment by adelf** [comment]
Fixed for Facades in 1.0.6. This version is currently waiting Jetbrains review.
