### ISSUE TITLE
Resolving Scopes

### ISSUE THREAD

**Issue by sykorax** [laravel-idea/plugin#30]
Hey there,

It's a really great and powerful tool. I'm looking forward to see more cool stuff like it ships already.
So i was wondering if the tool could resolve inline scopes somehow.
It would be nice so we could keep chaining queries containing scope(s).

The following image illustrates IDE is not able to resolve the ``scopeShouldBePublished()`` scope

![image](https://user-images.githubusercontent.com/5334912/77846112-eeefd080-71b3-11ea-89f4-bc1432df22ed.png)

Also, it'd be nice if it could work with global scopes as well.
Thank you for the great work!

**Comment by adelf** [comment]
Hi, Forgács.

Yes, I'm working on ide-helper replacement and helper code generated for
models should be much more complicated than current ide-helper generates.
Thanks. I hope v3.0 will contain a new generator with scopes and other
virtual methods.

**Comment by sykorax** [comment]
Hi,

It's really nice. Thank you for your swift answer! :)

**Comment by adelf** [comment]
implemented in 3.0 version. You can try new generator :) please check and comment if there are some issues.

**Comment by sykorax** [comment]
Hey @adelf,

I am not sure, what do you mean when saying new generator? :)
Thank you for the hard work!

**Comment by sykorax** [comment]
You are a Hero!
Thank you for your hard work! :)

**Comment by LFTroya** [comment]
Hi @adelf, I am using the version 0.15.4 but plugin doesn't resolve scopes.

How can I update to that version?
