### ISSUE TITLE
[Feature Request] Autocomplete package translations using the package::file.line syntax

### ISSUE THREAD

**Issue by pavlentij** [laravel-idea/plugin#300]
Would be great to autocomplete package translations using the package::file.line syntax (https://laravel.com/docs/8.x/packages#translations).

![image](https://user-images.githubusercontent.com/971128/117534786-9405eb00-affb-11eb-8c04-248be5dd63af.png)

**Comment by adelf** [comment]
Hi, Pavel. Sorry for the long response.

There is a setting in the plugin already. If you choose the "Package" module system:

![image](https://user-images.githubusercontent.com/2818394/118012971-4d492580-b35a-11eb-9a92-4435834a7c05.png)
