### ISSUE TITLE
Add event listener as listener

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#301]
It could be cool if we from an event and event listener could add them.

E.g. on this screenshot I am on an event listener, and have opened the context menu
![image](https://user-images.githubusercontent.com/5870441/117654741-78831780-b196-11eb-9a80-c877e7f0d6ef.png)

It would be really nice if from the context menu a new menu point was there to link it to an event. 
So basically it will open up a modal where I autocomplete the event class name. When pressing the button in the dialog, a new line will be added into the service provider, making the listener a listener on the event.

**Comment by adelf** [comment]
Implemented by "Create Listener" generation action.
