### ISSUE TITLE
Facade methods missing for PHP/JS Transformer

### ISSUE THREAD

**Issue by plweil** [laravel-idea/plugin#303]
I haven't been able to get PHPStorm/Laravel Idea to recognize methods (that is, `Javascript::put` for the [Laracast PHP/JS Transformer utility](https://github.com/laracasts/PHP-Vars-To-Js-Transformer). The inspector flags with the message

`Method 'put' not found in \JavaScript`

I reference the facade at the top of my classes with `use Javascript`. I've tried generating helper and facade code with Laravel Idea. Still no dice.

This is not the end of the world, but it is a bit annoying. I don't know whether this utility/facade is written in an unusual way, or in a way that prevents this, or whether there is anything that can be done with Laravel Idea to fix this.

PHPStorm 2021.1
Laravel Idea 4.2.2.211

**Comment by adelf** [comment]
Hi, Peter.

Yes, the current implementation of the Facade helper code generator can't understand some facades and JavaScript Facade is one of them. 
You can run an `ide-helper:generate` command from https://github.com/barryvdh/laravel-ide-helper once and it should work much better for now. I'll try to fix this soon.

**Comment by plweil** [comment]
Ok. Thanks for the quick response, Adelf.

**Comment by adelf** [comment]
Fixed in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
