### ISSUE TITLE
add auto set fillable data [suggestion]

### ISSUE THREAD

**Issue by ibrahem-kamal** [laravel-idea/plugin#304]
it will be super useful to add an option to auto add the fillable array from the migration . 

current scenario : u need to autocomplete each fillable property

expected scenario : fillable array is generated with a shortcut and you can edit it

**Comment by adelf** [comment]
Sorry, I forgot to answer. 
I'll try to implement it. Maybe by special action which will put all fields to this array and then some of them can be deleted... or something else.

**Comment by ibrahem-kamal** [comment]
great , looking forward it

**Comment by adelf** [comment]
Implemented in 4.3.3 version: https://twitter.com/laravel_idea/status/1412024579615301635

**Comment by ibrahem-kamal** [comment]
any ETA when 4.3.3 will be released ? xD

**Comment by adelf** [comment]
@ibrahem-kamal it was released, but there is a bug. 4.3.4 will be released today or tomorrow.

**Comment by elbaylot** [comment]
How to use it ?

**Comment by adelf** [comment]
@elbaylot with cursor on the $fillable array. Alt-Insert or ⌘N - Generate menu.

![image](https://user-images.githubusercontent.com/2818394/141284327-58bcf1da-642a-402d-bf72-6294ea908c70.png)
