### ISSUE TITLE
Route name prefix autocomplete not working

### ISSUE THREAD

**Issue by Cbrad24** [laravel-idea/plugin#305]
Love this plugin but just noticing a small issue:
Noticed in issue #115 you mentioned this should be working but doesn't appear to be in my testing.

In my RouteServiceProvider file I am using a name prefix to separate out the API routes so I can use the same names in my web routes.
```php
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->name('api.') // This doesn't appear to be getting picked up by autocomplete, also tried to use the alias ->as()
                ->middleware('api')
                ->namespace($this->namespace)
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
        });
    }
```
My API routes file:
```php
Route::get('/blacklist',  \App\Http\Controllers\API\IPBlacklistController::class)->name('blacklist');
```

My WEB routes file:
```php
Route::get('/blacklist', \App\Http\Controllers\IPBlacklistController::class)->name('blacklist');
```

The result I get:
![image](https://user-images.githubusercontent.com/2669153/118735225-53bc2d80-b883-11eb-9c4e-d657d69cdf4a.png)

Expecting the value `api.blacklist` to show up as well, but alas it does not.
Thanks for your time in advance.

**Comment by adelf** [comment]
Hi.

If you'll change `->name('api.')` to `->as('api.')` it should work... I think)

I'll check if it's an alias I'll add the `name()` method support here.

**Comment by Cbrad24** [comment]
Yeah I found it in the code earlier just before posting this:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/RouteRegistrar.php#L61-L68

They were using ->name in the 8.0 docs:
https://laravel.com/docs/8.x/routing#route-group-name-prefixes

I did try change it to ->as, but had no luck. Do I need to flush the IDE cache first?

**Comment by adelf** [comment]
Yes, please try and write if everything will work. If not I'll try to reproduce this bug tomorrow.

**Comment by Cbrad24** [comment]
Changed to ->as, flushed cache, still no luck.
Running PHPStorm 2020.3.3, with Laravel Idea 4.2.2.203.

**Comment by adelf** [comment]
> ->namespace($this->namespace)

Do you have a `namespace` field in this class? If not, please add it, or remove this call.
