### ISSUE TITLE
[Feature Suggestion] Macro Autocompletion

### ISSUE THREAD

**Issue by RJFares** [laravel-idea/plugin#306]
Macros in Laravel are a great way to implement custom logic embedding it in the framework.

A good example is adding new functions to a collection.
https://laravel.com/docs/8.x/collections#extending-collections

An example library:
https://github.com/spatie/laravel-collection-macros

I have my own private library which hosts a lot of macros for strings, ie:
```
Str::macro('linesCount', app(Macros\Str\LinesCount::class)());
Stringable::macro('linesCount', app(Macros\Stringable\LinesCount::class)());
```

The thing that "sucks" is that autocomplete does not seem to grab them natively. So I was wondering how feasible would it be to have Laravel Idea implement autocomplete for macros on collections or Stringables?

**Comment by adelf** [comment]
I already have a macro helper code generation: Code generations - "Generate Helper Code". But I don't support these constructions. I'll try to add them in the next version.

BTW, supporting this kind of macro registration (https://github.com/spatie/laravel-collection-macros) is much harder, so this won't work for now...

**Comment by adelf** [comment]
Direct calls like this will work in the next version:
```
Str::macro('linesCount', app(Macros\Str\LinesCount::class)());
```

**Comment by adelf** [comment]
4.3 is released.
