### ISSUE TITLE
[Idea/suggestion] Type inference from factory create/make methods

### ISSUE THREAD

**Issue by tanerkay** [laravel-idea/plugin#307]
Currently if we create a model using a factory, we have to type hint the result using phpDoc or similar for the IDE to infer the type.

```php
$shape = Shape::factory()->create();

// Won't autocomplete or will complain about polymorphism as it doesn't know what subtype of Model comes from the factory
$shape->width;
```

So we have to type hint the result using phpDoc or similar for the IDE to infer the type, e.g.

```php
/** @var Shape $shape */
$shape = Shape::factory()->create();
```

Otherwise it gets treated as a model (`\Illuminate\Database\Eloquent\Model`).

It would be awesome if factory methods such as `create()` and `make()` map to the type of the appropriate model.

There might be some complexity in implementing this, as if there is a `count()` on the factory, then the type inferred would be a collection of the appropriate model, e.g. `Shape[]|\Illuminate\Database\Eloquent\Collection`

**Comment by adelf** [comment]
Hi. Have you tried to generate Eloquent helper code: https://laravel-idea.com/docs/eloquent#helper-code-generation ?

**Comment by tanerkay** [comment]
Aha. I already had the mixins and helper code from barryvdh's package, but I've now switched to the Laravel Idea helper code which has indeed resolved this. Thanks and sorry for the non-issue!

**Comment by adelf** [comment]
No problem)
