### ISSUE TITLE
whereHas and whereDoesntHave autocomplete eloquent attributes

### ISSUE THREAD

**Issue by mgralikowski** [laravel-idea/plugin#308]
My suggestion for next releases is handling:

- whereHas
- whereDoesntHave

![image](https://user-images.githubusercontent.com/17027876/119802011-77fcb780-bede-11eb-96b9-ccf86bcda9f9.png)

going deeper (I guess more complicated):

- whereHasMorph
- whereDoesntHaveMorph
- withCount
- loadCount

**Comment by adelf** [comment]
Hi. I've checked. Everything works... 
![image](https://user-images.githubusercontent.com/2818394/125448070-7ad4c107-e823-4be2-94bb-04b4763ac152.png)

Do you still have these completion issues?
