### ISSUE TITLE
Feature Request: Support table prefix for models and migrations

### ISSUE THREAD

**Issue by DarkTke** [laravel-idea/plugin#309]
Is it possible to add support for table prefixes generated on the basis of a variable from a config file?

Example: 
![Снимок экрана от 2021-05-28 11-01-47](https://user-images.githubusercontent.com/19700297/119915176-4c90d000-bfa5-11eb-9e89-c5332786fd2a.png)

**Comment by tmiller** [comment]
So I've just run across this issue. I have a project that uses a prefix configured at the database level. I would love to be able to have a configuration option in the settings to set the prefix for all the tables. I believe right now my only option would be to go explicitly set the table name on each model and I don't really want to have to do that.

**Comment by adelf** [comment]
I've implemented fetching prefixes from config/database.php and if the table is not found for the model Laravel Idea will try to find the table by adding all found prefixes.

Is this logic ok?

**Comment by tmiller** [comment]
Yea I think that works in my particular situation. Thanks!

**Comment by adelf** [comment]
Implemented in Laravel Idea 5.6.
