### ISSUE TITLE
Validation Rules - Loosing track using array_merge()

### ISSUE THREAD

**Issue by sykorax** [laravel-idea/plugin#31]
Hey,

So when we use validations like..

![image](https://user-images.githubusercontent.com/5334912/77846165-6de50900-71b4-11ea-8336-d63aff232769.png)

it is working as expected.
However once you wrap your rules into an array_merge it cannot track the context, like..
![image](https://user-images.githubusercontent.com/5334912/77846192-8a814100-71b4-11ea-8874-793e3b81e81b.png)

Sometimes it's a necessary step we have to do here since we want to validate a bunch of rules at the same time, not separately.

**Comment by adelf** [comment]
Good idea! Seems, this should be implemented for all array completions too.
Thanks!

**Comment by adelf** [comment]
implemented in 2.4 version. please check and comment if there are some issues.
