### ISSUE TITLE
[BUG] Policies generated in the wrong directory

### ISSUE THREAD

**Issue by gander** [laravel-idea/plugin#310]
Laravel version: **6.20**
Plugin version: **4.3.0.211**

#### Docs: [Registering Policies](https://laravel.com/docs/6.x/authorization#registering-policies) > Policy Auto-Discovery
> Specifically, the policies must be in a `Policies` directory below the directory that contains the models. So, for example, the models may be placed in the `app` directory while the policies may be placed in the `app/Policies` directory.

In my project, the plugin correctly generates models in the `app/Models` directory, but also generates policies in `app/Policies`. Thus, Auto Discovery is not working.

PS. I know I can set this directory in plugin settings, but that's not the point.

**Comment by adelf** [comment]
For now, I just made auto switching if there is no 'app/Policies` folder but `app/Models/Policies` exists. It checks this on each startup.

In the future I'll implement an Initial Project Configuration window and ask user about policies auto-discovery "on"/"off". Thanks for posting this issue!
