### ISSUE TITLE
[BUG] "Register in Auth Service Provider" not working without "Under policy class (optional)"

### ISSUE THREAD

**Issue by gander** [laravel-idea/plugin#311]
Laravel version: **6.20**
Plugin version: **4.3.0.211**

Both fields must be filled, otherwise the generator does not add the configuration entry in `AuthServiceProvider.php`. This is independent of the target directory settings.

![image](https://user-images.githubusercontent.com/421597/120028371-e5027100-bff4-11eb-91b2-94697b369e7d.png)

**Comment by gander** [comment]
@adelf I know the problem is related to what I reported earlier, but could you add a tag saying it will be fixed or not?  For my peace of mind.

**Comment by adelf** [comment]
It's just a little UI error. I'll try to fix it, but can't say when. Anyway, thank you for posting!

**Comment by gander** [comment]
@adelf What status?

**Comment by gander** [comment]
Has anything changed since the last comment?

**Comment by abishekrsrikaanth** [comment]
@adelf  is there a fix expected for this soon?

**Comment by adelf** [comment]
What will be the expected behavior here?
