### ISSUE TITLE
[BUG] "Find migration, policy, factory, etc." not working for policy Auto Discovery

### ISSUE THREAD

**Issue by gander** [laravel-idea/plugin#312]
Laravel version: **6.20**
Plugin version: **4.3.0.211**

#### Docs: [Registering Policies](https://laravel.com/docs/6.x/authorization#registering-policies) > Policy Auto-Discovery
> Specifically, the policies must be in a `Policies` directory below the directory that contains the models. So, for example, the models may be placed in the `app` directory while the policies may be placed in the `app/Policies` directory.

Regardless of whether the policy was generated in `app/Policies` or `app/Models/Policies`, if there is no entry in `AuthServiceProvider`, the _"Find migration, policy, factory, etc."_ function will not find a policy for the model.

**Comment by gander** [comment]
@adelf I know the problem is related to what I reported earlier, but could you add a tag saying it will be fixed or not?  For my peace of mind.

**Comment by adelf** [comment]
I was busy with 2021.2 EAP versions. I'll definitely try to fix this. Thank you.

**Comment by adelf** [comment]
Should work in 4.3.1

**Comment by gander** [comment]
I confirm that it is already working.
