### ISSUE TITLE
From Controller function to routes file

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-idea/plugin#313]
Hello,

sometimes I want to got from my Controller action to the lines in the web.php where these functions are defined (i.e. to change the parameters). 
Is it possible to add this functionality?

Thanks!

**Comment by adelf** [comment]
Just try to ctrl-click in the action method name. PhpStorm should try to “Find usages” and find the usage in the route file.

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1399684065100550149 :)

**Comment by SudoGetBeer** [comment]
Oh man sorry. Nice that this is already there
