### ISSUE TITLE
[BUG] Filename template

### ISSUE THREAD

**Issue by trin4ik** [laravel-idea/plugin#317]
first, big thanks 4 this plugin.
no problem with jetbrains file template, when i create "Laravel 2T Controller" and write filename like "Todo", jetbrain create "TodoController.php". but amazing laravel idea create "Todo.php" file ( its makes me cry
![image](https://user-images.githubusercontent.com/839633/120650895-e1546b80-c486-11eb-8d9c-96507c2e6f27.png)

pls fix this

**Comment by adelf** [comment]
Didn't know about this feature. I'll try to fix. Thank you.

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1400799733875187713

what do you think?

**Comment by trin4ik** [comment]
> https://twitter.com/laravel_idea/status/1400799733875187713
> 
> what do you think?

use it everyday, ty
