### ISSUE TITLE
Incompatible new version PhpStorm

### ISSUE THREAD

**Issue by luneapps** [laravel-idea/plugin#318]
Hi,

I upgraded the PHPStorm version and the plugin was incompatible.

My version:

PhpStorm 2021.2 EAP
Build #PS-212.3724.24, built on June 4, 2021
PhpStorm EAP User
Expiration date: July 4, 2021
Runtime version: 11.0.11+9-b1481.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2981M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Non-Bundled Plugins: com.xiaobing1024.laravel (1.1.1), net.seesharpsoft.intellij.plugins.csv (2.16.4), de.espend.idea.laravel (0.15.4)

**Comment by adelf** [comment]
Yes. I'll release a version for 2021.2 soon.

**Comment by adelf** [comment]
Should work now.
