### ISSUE TITLE
Resolving email template in Notifications

### ISSUE THREAD

**Issue by boryn** [laravel-idea/plugin#319]
This (it's a part of `public function toMail($notifiable)` in a `Notification` class) could be "clickable to" `resources/views/vendor/notifications/email.blade.php`

![image](https://user-images.githubusercontent.com/807297/121051534-d3ba2100-c7b9-11eb-8b4c-96b4b93a3517.png)

**Comment by adelf** [comment]
I'll try to add it.

If it's urgent, you can add it yourself by creating an `ide.json` file in the project with this content:

```
{
    "$schema": "http://laravel-ide.com/schema/laravel-ide-v1.json",
    "completion": {
        "view": [
            {
                "methods": ["markdown", "view", "template"],
                "classes": ["MailMessage"]
            }
        ]
    }
}

```

**Comment by boryn** [comment]
Good to know :)

**Comment by adelf** [comment]
4.3.1 is released
