### ISSUE TITLE
X-Component parameter code suggestion not working when component is inline

### ISSUE THREAD

**Issue by sykorax** [laravel-idea/plugin#32]
Hello,

It's cool that the tool suggests component parameters out of the box, like..

![image](https://user-images.githubusercontent.com/5334912/77846286-535f5f80-71b5-11ea-92d6-a8abcdb526cd.png)

However as i noticed it works only when the related component consumes a real blade template.
When it comes to inline components it doesn't work the same way. In fact, there's no completion for inline components.

![image](https://user-images.githubusercontent.com/5334912/77846305-90c3ed00-71b5-11ea-987d-f96213256f51.png)

Also let me mention something else here.
When the tool offers parameters for completion then it's really under the built in blade directives like..

![image](https://user-images.githubusercontent.com/5334912/77846354-d54f8880-71b5-11ea-9c59-ac205461b38f.png)

Is there any chance that we could make the offered attributes to be appeared as the very first elements inside the list illustrated on the image above?

**Comment by adelf** [comment]
Constructor of component class can contain some services so, I decided to
filter all parameters with non-primitive types. But, yes, I'll make
exception for carbon classes.

**Comment by sykorax** [comment]
Thank you,

Actually did not notice that primitives might be resolved already. Sorry!
