### ISSUE TITLE
Class completion for Blade components when doing $attributes->merge()

### ISSUE THREAD

**Issue by smares** [laravel-idea/plugin#320]
Many of my Blade components have something like `<div {{ $attributes->merge(['class' => 'my-blade-component card']) }}>` on their root element and I noticed that IDEA does not auto-complete CSS classes in that scenario because it's not HTML I am writing, but PHP.

Is this something the plugin can improve?

**Comment by adelf** [comment]
I already complete classes here:
![image](https://user-images.githubusercontent.com/2818394/121657177-da41e480-caa8-11eb-85cb-b7293da7a6bd.png)

I'll try to add this completion also. Thanks!

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/121687169-b5f6ff80-caca-11eb-85ad-eb0917e6d71e.png)

:)

**Comment by adelf** [comment]
4.3.2 version is available.
