### ISSUE TITLE
[Feature Request] Anonymous Migrations

### ISSUE THREAD

**Issue by pxlrbt** [laravel-idea/plugin#323]
Would be cool to have a checkbox for the new anonymous migrations feature when creating a migration.

**Comment by fabio-ivona** [comment]
there is a checkbox already:

![image](https://user-images.githubusercontent.com/8792274/122412137-9d349100-cf85-11eb-9a64-cd48fa488109.png)

**Comment by adelf** [comment]
It appears for Laravel projects with version... More than 8.31 I suppose...
When anonymous migrations were implemented.

**Comment by pxlrbt** [comment]
Thanks guys. I guess I had to reopen the project which I just upgraded to L8 before PhpStorm/Laravel Idea noticed it. 
Or I tried before the upgrade 🤷🏼
