### ISSUE TITLE
Missing Livewire autocompletion

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#324]
it seems that livewire's `wire:model.defer` autocompletion is missing:

![image](https://user-images.githubusercontent.com/8792274/122412381-cbb26c00-cf85-11eb-9ca5-2940cffee2f8.png)

**Comment by adelf** [comment]
Fixed. Thanks. Please don't hesitate to add any other missing completions here or in the new issues.

**Comment by fabio-ivona** [comment]
Thanks!! 

will update as soon as I find any missing completion
