### ISSUE TITLE
Not a facade

### ISSUE THREAD

**Issue by lloricode** [laravel-idea/plugin#329]
`Str` and `Arr` is not belong to a facade list, IDE does not give warning while this is an error, 

thank you

**Comment by adelf** [comment]
As far as I know, they were facades before they were excluded from the facades list in one of the Laravel versions. I'll remove them also. Thanks.

**Comment by lloricode** [comment]
> As far as I know, they were facades before they were excluded from the facades list in one of the Laravel versions. I'll remove them also. Thanks.

thank you
