### ISSUE TITLE
Type hint for ResourceRoutes

### ISSUE THREAD

**Issue by christian98** [laravel-idea/plugin#33]
I really like your plugin, but there is one thing missing i would really like to see in this plugin.

when I registered routes like  so:
```php
Route::resources([
    'gallery' => 'GalleryController',
]);
```
the routes are actually registered, but when i try to use this any where in my code, the type-hinting does not recognize these routes:
![grafik](https://user-images.githubusercontent.com/26673604/77855069-6cd0cd80-71ee-11ea-9a03-ad8a7cb86328.png)

It would be nice, if your plugin could recognize these routes too.

**Comment by adelf** [comment]
Seems, this method was forgotten. Thanks for catching! Will be fixed.

**Comment by adelf** [comment]
implemented in 2.4 version. please check and comment if there are some issues.

**Comment by christian98** [comment]
Hey man,
thanks for implementing. It seems to work great for non-nested resources. But now I also have nested resources like:
```php
Route::apiResources([
            'users' => 'Api\UserController',
            'users.libraries' => 'Api\UserLibraryController',
        ]);
```
'users' routes are getting recognized by the auto-completion. But the nested routes like 'users.libraries' are not available.
![grafik](https://user-images.githubusercontent.com/26673604/80304532-f60bfd80-87b6-11ea-9db7-029ccb530ef6.png)

**Comment by adelf** [comment]
I didn't know about this kind of nesting :) It will be added to the next version. Thank you.

**Comment by adelf** [comment]
implemented in 3.0 version. please check and comment if there are some issues.

**Comment by christian98** [comment]
It works great, THANKS!!

**Comment by adelf** [comment]
Thank YOU for reporting this :)
