### ISSUE TITLE
Translation Generator → translation existence check

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#331]
Was just wondering...

if I create a new traslation through the generator:

![image](https://user-images.githubusercontent.com/8792274/124265182-aa30b300-db35-11eb-9a84-9c2f2b6fbc3c.png)

it would be a nice feature to warn me that another translation string exists with the same value.

sometimes it happens to create two translation keys with the same value, maybe because they are created from two different places of my code where the key that comes into mind is different...

**Comment by adelf** [comment]
Good idea. Thanks.

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/129078408-03121097-7275-442f-9a0a-d4516d43fe4f.png)


Almost ready :)

**Comment by fabio-ivona** [comment]
Great!

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
