### ISSUE TITLE
Eloquent Code Generator using Connection

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-idea/plugin#333]
Hey,

thanks for the great plugin.

I noticed a small but annoying bug.
A few models will not be detected by the Eloquent Code Generate.
But if I set the protected $table on the model it works.

I use the Connection to fetch the data (but migrations had problems too).

A few names of the Model and Table. 
Manufacturer => manufacturers
StatusCacheManufacturers => status_cache_manufacturers
LowMarginManufacturer => low_margin_manufacturers

Maybe you use a different way for the slugs? 
Laravel uses this: Str::snake(Str::pluralStudly(class_basename($this)))

Thanks!

**Comment by adelf** [comment]
Fixed. Thank you for posting this bug. I'm going to release a new version next week.

**Comment by SudoGetBeer** [comment]
That was quick!
Thanks a lot.

**Comment by adelf** [comment]
@OliverNybroe a new record!

@SudoGetBeer I'll close it when I release this version :)

**Comment by adelf** [comment]
@SudoGetBeer I had to reproduce the Symfony pluralizer in Kotlin, and there are still some differences, so please report any issue like that. I'll say a big Thank you :)

**Comment by olivernybroe** [comment]
@adelf congrats! 10 minutes 😆 gonna be harder and harder to beat the record 🤣

**Comment by adelf** [comment]
4.3.3 is out!
