### ISSUE TITLE
Autocompletion for permissions

### ISSUE THREAD

**Issue by MohammadAbusaleh** [laravel-idea/plugin#334]
How can we use autocompletion for permissions, for example I'm using laravel-permission by spatie.

https://spatie.be/docs/laravel-permission/v4/introduction

Is there a place to insert my permissions so it can be autocompleted when I type ``` $user->can(''); ```

Thank you very much.

**Comment by adelf** [comment]
Hi. How can you find all these permissions?

**Comment by MohammadAbusaleh** [comment]
@adelf in this package in particular the permissions and roles are saved in Database, but I was wondering if there's a way to add a list of permissions being used agnostic from whatever package is used.

If there's a file where the user can add permissions and roles so they get autocompleted.

**Comment by adelf** [comment]
I was thinking about adding completion for example - all constant values of some class... but if you already have a special class with constants, may be better to use them instead?
```php
$user->can(Permissions::EDIT_POSTS)
```

**Comment by MohammadAbusaleh** [comment]
@adelf I did not think of that, thank you!
