### ISSUE TITLE
Can I choose a factory path to generate helpers ?

### ISSUE THREAD

**Issue by boskiv** [laravel-idea/plugin#335]
When I generate a code helpers I've got a warning
```
5:23 PM	Eloquent Helper Code generated successfully
				Eloquent models found: 11
				Show 3 warnings.
				Don't show this again
5:23 PM	Warnings
				More than one factory classes found for \App\Models\Team. First one chosen.
				More than one factory classes found for \App\Models\User. First one chosen.
				Table not found for \App\Models\Membership
```

Is there a way to define what Factory should be used to generate classes?
Or maybe you can respect project folder first, then vendor folder ?
Any options to control will be usefull.

**Comment by adelf** [comment]
Hi.

> Or maybe you can respect project folder first, then vendor folder ?

I’ll implement this one in the next version. I’ll try to release it in 2-3 days

**Comment by adelf** [comment]
Implemented. I'll close this issue after releasing an update. 

BTW, what with "Table not found for \App\Models\Membership"? Everything is ok?

**Comment by boskiv** [comment]
Yes, @adelf thanks. It's expected. It's just a Model without table. My bad.
