### ISSUE TITLE
Autocompletion when using factory classes without trait

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#336]
So in my workplace we use factory classes directly, so we do the following

![image](https://user-images.githubusercontent.com/5870441/125586917-8ae6a631-4536-4d0c-a9f7-aaf4a413c5b5.png)
However Laravel Idea is not able to determine the type from this. 

It would be awesome if this could be supported 👍

**Comment by adelf** [comment]
I tried to implement this request the best way... and realized that I can remove ALL factories helper code and make this by simple "TypeProvider" :) So, thank you very much. 4.3.4 with this fix is available already.

**Comment by olivernybroe** [comment]
@adelf oh wauw that's amazing! Great job ♥️
