### ISSUE TITLE
Code generation: Factory not generate fields

### ISSUE THREAD

**Issue by beregsys** [laravel-idea/plugin#337]
I tried to generate factory from model and noticed that I have in return of definition method empty array, no fields generated.
In model I have fillable and casts properties, I thought that this solve problem, but no. Then I thought maybe it's because I don't have migration, but when I created migration and made migration and tried to generate factory I have the same issue.

**Comment by adelf** [comment]
Hi. Have you tried to generate Eloquent helper code? https://laravel-idea.com/docs/eloquent or by laravel-ide-helper package?

**Comment by beregsys** [comment]
Hi, tried couple seconds ago and It works, ty, maybe add this info to documentation)

**Comment by adelf** [comment]
I’ve added a task to my Trello. Thanks.
