### ISSUE TITLE
[BUG] Unknown Blade Component

### ISSUE THREAD

**Issue by RJFares** [laravel-idea/plugin#339]
After Laravel Idea had its last update, I'm getting "Unknown Blade Component" **from time to time** on aliased components (< x-txt > gives warning, < x-mc::txt > is ok). Sometimes it gets resolved after a PHPstorm restart.

Here is a snippet from my ide.json

```
"viewPaths": [
                {
                    "path": "packages/.../resources/views/components",
                    "namespace": "",
                    "prefix": "",
                    "viewNamespace": "mc"
                }
            ]
```

When it works, ctrl-clicking on the component works, but when it shows the warning, cannot ctrl+click to go to it.

**Comment by adelf** [comment]
Could you try:

```
"viewPaths": [
                {
                    "path": "packages/.../resources/views/components"
                }
            ]
```

It should work. "viewNamespace" is for rare cases with overriding component views with"resources/views/vendor" folder...

**Comment by adelf** [comment]
However, I've fixed it. There was a little mistake with too optimistic "return" if viewNamespace is not empty in the `getBladeComponentViewByName` method :) Sorry for that.
