### ISSUE TITLE
When using Modules, allow for creating in default namespace.

### ISSUE THREAD

**Issue by jgile** [laravel-idea/plugin#34]
It would be great if we would select to use the regular namespace when generating files in "module mode."

**Comment by adelf** [comment]
Hi, John. It will be added, thanks.
Current implementation of modules is very basic. I didn't know what people really need. Do they need to create the same classes(like controllers) in the modules and in the app in the same time, or not? 
So, if you have any inconveniences - please report them here :)

**Comment by jgile** [comment]
Thanks!  I think people do it two different ways:

1. Some people will create an “App” modules, which will store more general functionality that does not belong to a specific module.  In this case, the current setup would work perfectly.
2. Some people will use the default Laravel setup for general functionality, and put everything else in modules.  In this cause, there is not a way to generate in the ‘default’ namespaces if you are using modules.

Does that make sense?

John Gile

**Comment by adelf** [comment]
I'll just add "<app>" module to the top. And maybe will add an option to turn it off for "only-module" projects.

**Comment by adelf** [comment]
implemented in 2.4 version. please check and comment if there are some issues. 
I just added a new setting to Settings | Languages and Frameworks | PHP | Laravel Idea | Module system. By default it's false.
