### ISSUE TITLE
Eloquent completions only works if _ide_helper* files are placed in project root directory

### ISSUE THREAD

**Issue by iraklisg** [laravel-idea/plugin#340]
Running **Generate Eloquent Helper Code** creates the `_ide_helper_*.php` files in `vendor/_laravel_idea` directory.
However code autocompletion does not work unless I manually move the `_ide_helper_*.php` files in the project root directory.

I am using Laravel Idea plugin v. 4.3.3.211

**Comment by adelf** [comment]
Seems, your vendor folder is marked as Excluded. Better to switch it back.

https://twitter.com/laravel_idea/status/1334539817263247363

However, I'll add the option "where to store the generated files". Thank you.

**Comment by iraklisg** [comment]
Thanks for the tip @adelf, marking `vendor/_laravel_idea` directory as not excluded did the trick. Adding an option to select where to put the generated files would be very helpful as well.

**Comment by adelf** [comment]
I've added an option about placing the helper code. And also auto-marking as "Not Excluded" for the `vendor` folder. Of course, it can be turned off. Thank you for posting this bug.
