### ISSUE TITLE
Open in splitted tab plugin compatibility

### ISSUE THREAD

**Issue by raveren** [laravel-idea/plugin#344]
First of all, thanks for the great work and affordable, must-have plugin!

https://plugins.jetbrains.com/plugin/7407-open-in-splitted-tab

Invoking the aforementioned action (I have it bound to middleclick) just focuses cursor on the next split and does not open - the view template - for example.

**Comment by adelf** [comment]
I've tested it in the PhpStorm 2021.2 EAP - it opens a view template, but in the current tab.
It's fixed and at least in 2021.2 - it works ok. Please, wait for the next update. "4.3.5" I suppose...

**Comment by adelf** [comment]
Fixed in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
