### ISSUE TITLE
Conditional Classes

### ISSUE THREAD

**Issue by riaanlom** [laravel-idea/plugin#347]
Will the new blade conditional classes be supported?
https://laravel.com/docs/8.x/blade#conditional-classes

**Comment by adelf** [comment]
Yes. In the next version.
https://twitter.com/laravel_idea/status/1418559219872186369

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
