### ISSUE TITLE
PhpStrom 2021.2 support

### ISSUE THREAD

**Issue by jameswagoner** [laravel-idea/plugin#348]
There an update soon to support 2021.2?

**Comment by adelf** [comment]
It's ready. PhpStorm should ask about updating.
But as I see, this time for some reason PhpStorm waits for indexing to be finished and only after that suggests updating plugins :(

**Comment by jameswagoner** [comment]
Ohhh looks like Jetbrains' plugin system is the issue. Throwing 503 errors for me.

Thanks for replying!

**Comment by jameswagoner** [comment]
Reopening - JetBrains resolved their server issue it seems but still don't see updates being available. Checked for updates manually but not showing anything.

Is there something to force update?

![image](https://user-images.githubusercontent.com/3052854/127591391-8fb1ff38-a115-4b1e-96df-2af6ca20d22b.png)

**Comment by jameswagoner** [comment]
Okay this was very annoying indeed. Had to hit each plugin homepage and hit install to 2021.2. Finally after a little while PhpStorm brought up the update dialog. 

Another thing is that JetBrains' plugin site thought I didn't have a license so had to choose trial option but then PhpStorm had it right.

**Comment by adelf** [comment]
There are a lot of issues with JetBrains marketplace today... and yesterday...
