### ISSUE TITLE
Create new module

### ISSUE THREAD

**Issue by jgile** [laravel-idea/plugin#35]
It would be helpful if we could create a new module that does not exist, yes, when creating resources.

**Comment by adelf** [comment]
You mean just create a new directory?

**Comment by adelf** [comment]
Ah... no. Create new module during creating something else.... I can easily add new "Create new module" command. But I'll think about this option also.

**Comment by jgile** [comment]
I think “Create new Module” would solve the problem perfectly.   Thank you.

John Gile

**Comment by adelf** [comment]
implemented in 3.0 version. please check and comment if there are some issues.
