### ISSUE TITLE
[Feature request] Array shape of `$request->validate()`

### ISSUE THREAD

**Issue by SjorsO** [laravel-idea/plugin#351]
![image](https://user-images.githubusercontent.com/7202674/127764078-5ce55353-304c-4bfc-beef-4cc66c001d8a.png)

Using `$data = $request->validate()` is a common pattern in Laravel. It would be great if `$data` would auto-complete the array shape defined by the validation rules.

This issue is related to https://github.com/laravel-idea/plugin/issues/174. But that issue seems to focus on `FormRequest` objects.

**Comment by smares** [comment]
While at it, could this be implemented for Livewire as well where you define a `$rules` class property and then simply call `$data = $this->validate()`? 😃

**Comment by adelf** [comment]
WIP
![image](https://user-images.githubusercontent.com/2818394/128233349-9a5114b9-0d2b-47b4-9843-d6608c67a59d.png)

**Comment by SjorsO** [comment]
You're brilliant 😁👍

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
