### ISSUE TITLE
Missing wire:* attributes in HTML

### ISSUE THREAD

**Issue by smares** [laravel-idea/plugin#352]
When it comes to `wire:loading`, only `wire:loading.class.remove` appears to be known, `wire:loading.remove` and `wire:loading.attr.remove` do not appear as suggestions, neither do `wire:loading.delay`, `wire:loading.flex`, etc.

Also, none of the `wire:offline` attributes appear while typing.

**Comment by adelf** [comment]
Hi, Sebastian. I have to hardcode all these attributes, and since I don't use Livewire, I definitely forgot many tags. I'll try to add all you wrote here.
`wire:loading.attr.remove` attr here is every HTML attribute?

**Comment by smares** [comment]
Yes, `attr` and `attr.remove` support every HTML attribute.

The ones I know are:

- `wire:init`
- `wire:target` (component public property to watch)
- `wire:dirty`
- `wire:dirty.class` and `wire:dirty.class.remove` (CSS classes)
- `wire:dirty.attr` and `wire:dirty.attr.remove` (HTML attributes)
- `wire:offline`
- `wire:offline.class` and `wire:offline.class.remove` (CSS classes)
- `wire:offline.attr` and `wire:offline.attr.remove` (HTML attributes)
- `wire:loading` and `wire:loading.remove`
- `wire:loading.delay` (same as `wire:loading`, but only if loading takes more than 200ms)
- `wire:loading.flex`, `wire:loading.grid`, `wire:loading.inline`, `wire:loading.inline-block`, `wire:loading.table` (control which kind of CSS `display` value is set)
- `wire:loading.class` and `wire:loading.class.remove` (CSS classes)
- `wire:loading.attr` and `wire:loading.attr.remove` (HTML attributes)
- `wire:click.prefetch` (component method to execute when the mouse hovers on the element having this)
- `wire:poll`, `wire:poll.750ms` (or any other time in ms), `wire:poll.keep-alive`, `wire:poll.visible` (these can be stand-alone or be followed by a public component method to call, e.g. `wire:poll="doSomething"` or `wire:poll.visible="doSomething"`
- `wire:event` where `event` can be any browser event such as `click`, `submit`, `keydown`, etc. `keydown` and `keyup` also supports adding modifiers like `wire:keyup.enter`, `wire:keyup.page-down`, `wire:keyup.arrow-left`. Eventually, all events support the modifiers `stop`, `prevent`, `self` and `debounce.150ms` (or any other time in ms), so `wire:submit.prevent` or `wire:input.stop.debounce.300ms`.
- `wire:model` with the modifiers `debounce.150ms` (or any other time in ms), `lazy`, `defer` as in `wire:model.defer="foo"` for example
- `wire:ignore` and `wire:ignore.self`

**Comment by adelf** [comment]
> or any other time in ms

I can't add every possible time... I'm going to use some predefined set of possible times(maybe configurable). How do you think, what values should be there? 100ms, 150ms, 200ms... 500ms something else?

> (CSS classes)

It will be hard... I'll try to make something like that: user types `wire:dirty.` and only then PhpStorm will start to complete CSS classes.

BTW, a big thank you for your effort!

**Comment by adelf** [comment]
>You don't have to substitute attr or class with HTML attributes or CSS classes

Thank god :)

**Comment by adelf** [comment]
two questions:

![wire_disabled](https://user-images.githubusercontent.com/2818394/128639694-36984a81-f0b3-412c-8567-bcb8dd6e6990.gif)
Is it ok that I complete "disabled" here? I don't remember why I do it... 
If yes, maybe there are some "90% cases" values for another ".attr" attributes? "wire:offline.attr", "wire:dirty.attr"?

As I see I complete method names of component class for `wire:loading.attr` attribute value and that seems not correct. What should be completed there? Only HTML attributes?

**Comment by smares** [comment]
I think `disabled` is a very sensible choice, it's what people will use most of the time, I guess, beside `readonly` or `hidden` maybe. Other than that, I don't know what other HTML attributes make sense to add or remove based on dirty, loading or offline state.

`wire:loading.attr` should complete HTML attributes only.

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release

I decided to don't complete ".100ms", ".250ms", etc.

**Comment by adelf** [comment]
I forgot to say a big Thank you for this list. It helped a lot.
