### ISSUE TITLE
Route name prefix doesn't get included in auto-complete

### ISSUE THREAD

**Issue by K1ll3rM** [laravel-idea/plugin#357]
If you use a name prefix on a route file doesn't get included in the auto-complete of the route() function

![image](https://user-images.githubusercontent.com/24224847/128692231-543e990f-e4dd-4e94-ad2d-018c2e2260dd.png)
In the route file
![image](https://user-images.githubusercontent.com/24224847/128692261-8dde2ceb-6260-4806-b3e9-2b29ab58a47f.png)
In a view
![image](https://user-images.githubusercontent.com/24224847/128692295-a4bff39b-244a-46b2-881a-0a0448c42d7f.png)

**Comment by adelf** [comment]
Hi, Michel.
Seems, you including admin.php routes in your another route file? Right? Currently I correctly support only route files described in service providers.

**Comment by adelf** [comment]
Another possible reason - $this->namespace. Do you have correct string value for this field?

**Comment by K1ll3rM** [comment]
> Another possible reason - $this->namespace. Do you have correct string value for this field?

I don't use those, removed them and the issue still persists

**Comment by adelf** [comment]
It should be fixed by the 4.4.2 version.
