### ISSUE TITLE
[FeatureRequest] Add model field completion for assertDatabaseHas and assertDatabaseMissing

### ISSUE THREAD

**Issue by bastien-phi** [laravel-idea/plugin#358]
As Laravel now support passing model class in `assertDatabaseHas` and `assertDatabaseMissing` as first parameter, it would be great to have field completion on `$data` parameter : 

![image](https://user-images.githubusercontent.com/10199039/128701240-615236e7-9b18-40f0-a75a-3b773c6a69d9.png)

This should be doable as field completion already exists
![image](https://user-images.githubusercontent.com/10199039/128701151-caeebf9b-dfa9-454f-a2ff-032211ae33c7.png)

**Comment by adelf** [comment]
Done. Thanks.

**Comment by bastien-phi** [comment]
On fire ! :fire: 

Thanks !

**Comment by mertasan** [comment]
Good idea! thank you @bastien-phi

**Comment by adelf** [comment]
Implemented in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
