### ISSUE TITLE
Namespace complete for factory generation

### ISSUE THREAD

**Issue by Davidnadejdin** [laravel-idea/plugin#359]

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/129054563-47eeed8a-5130-461e-8f1c-e6721ab6221b.png)


Works now. Thanks.

**Comment by adelf** [comment]
Fixed in the 4.4 version.
Full list of changes - https://laravel-idea.com/blog/2021/4-4-release
