### ISSUE TITLE
Gate Policy function string not clickable when second argument is array

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#362]
PHPStorm: 2021.2
Plugin: 4.3.4.212

When second argument below is the model class string the first argument can be Command + Click to go to the Policy class method:

```php
Gate::check('viewAny', Member::class))
```

However, if the second argument is an array, which is valid use it is not able to Command + Click.

```php
Gate::check('viewAny', [Member::class]));
Gate::check('viewAny', [Member::class, $someOtherModel]));
```

**Comment by adelf** [comment]
This was fixed in one of the previous releases, but I forgot to close this. Thank you for posing, Daniel.

**Comment by dmason30** [comment]
@adelf 

Neither of the examples above are working for me using 5.0.0.213

**Comment by adelf** [comment]
Sorry. I checked it with old policies, registered in the AuthServiceProvider. But it doesn't work with auto-discovered policies.
![image](https://user-images.githubusercontent.com/2818394/151549877-bd2e8d93-2c22-4037-b414-cb34decacf8f.png)

Returning the issue back.

**Comment by adelf** [comment]
And now it's fixed again. I'll try to release an update next week. Thanks for your patience.

**Comment by dmason30** [comment]
@adelf Great! There is also valid usage where the policy methods are an array in the first argument? Would be nice if they were clickable too:

```php
Gate::check(['view', 'viewAny'], [Member::class]));
```

**Comment by adelf** [comment]
This was fixed also. Thank you again for reporting. Really appreciated.

**Comment by adelf** [comment]
5.1 is released
