### ISSUE TITLE
${FILE_NAME} not functioning 

### ISSUE THREAD

**Issue by ourweb4** [laravel-idea/plugin#365]
I Have double checked spelling and spaces multiple times under different tabs. it doesn't seem to be an error as far as spelling . Am I overlooking or missing a step for this function to work?

**Comment by adelf** [comment]
Laravel Idea has its own templates processing, so there is no `${FILE_NAME}` variable. But I'll try to add all standard IntelliJ template variables in the next version. Thank you.

**Comment by adelf** [comment]
For now: `$CLASS_NAME` variable can be useful for some cases...

**Comment by ourweb4** [comment]
Is there any way I can put in the file name?

**Comment by adelf** [comment]
You can try to use "`${CLASS_NAME}`.php" for class generations... 

You're talking about Laravel Idea code templates, right?

**Comment by adelf** [comment]
It should be fixed by the 4.4.2 version.
