### ISSUE TITLE
[Feature request] autocomplete dispatchable classes

### ISSUE THREAD

**Issue by nuernbergerA** [laravel-idea/plugin#367]
Hey @adelf 

If you have a class that implements `ShouldQueue` and has the trait `\Illuminate\Foundation\Bus\Dispatchable` there are some static methods provided 
- dispatch
- dispatchIf
- dispatchUnless
- dispatchSync
- dispatchNow
- dispatchAfterResponse
if you have a `constructor` with arguments there is no autocomplete for those `dispatch*()` helpers

## Example
```php
class ProcessPodcast implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels, Dispatchable;

    protected $podcast;

    public function __construct(Podcast $podcast)
    {
        $this->podcast = $podcast;
    }
}
```
```php
ProcessPodcast::dispatch($podcast); //currently shows ...$arguments instead of Podcast $podcast
```
**Trait**
```php
public static function dispatch(...$arguments)
{
    return new PendingDispatch(new static(...$arguments));
}
```

**Comment by adelf** [comment]
`use InteractsWithQueue, Queueable, SerializesModels;` - where is Dispatchable here? :)

This can be solved by generating a helper code, but I don't want to ask users to do it. I'll try to implement auto-generation.

**Comment by nuernbergerA** [comment]
> `use InteractsWithQueue, Queueable, SerializesModels;` - where is Dispatchable here? :)
> 
Was lazy and copied from the docs 😜


> This can be solved by generating a helper code, but I don't want to ask users to do it. I'll try to implement auto-generation.

Ah that's why.

Didn't you wanted to implement auto generation if the composer.lock updates?

**Comment by adelf** [comment]
Probably after any Job class change. Also I see events also can be Dispatchable. I’ll add them too.

**Comment by miken32** [comment]
Any update on this one? Would be nice to have autocomplete and hints for `MyJobClass::dispatch()`!

**Comment by adelf** [comment]
@miken32 there are a lot of issues with auto-generation... 

Will it be ok to add a Dispatchable helper code item here(main menu > Laravel > Generate Facades and Macro Helper Code)?

<img width="279" alt="image" src="https://user-images.githubusercontent.com/2818394/166097577-363e40de-5d61-41d4-b025-5ecf70aebf82.png">

**Comment by adelf** [comment]
Should work in Laravel Idea 5.7

**Comment by beeyev** [comment]
Up!
