### ISSUE TITLE
[BUG] The return type is incorrect for some macros.

### ISSUE THREAD

**Issue by mertasan** [laravel-idea/plugin#368]
Return type is not detected when using another macro method within a macro method.

```php
class Mixins
{
    public function foo(): Closure
    {
        return function () {
            PHPUnit::assertTrue(true);

            return $this;
        };
    }

    public function bar(): Closure
    {
        return function (bool $value = true) {
            PHPUnit::assertTrue($value);

            return $this->baz(); // ie return $this;
        };
    }

    public function baz(): Closure
    {
        return function () {
            PHPUnit::assertTrue(true);

            return $this;
        };
    }
}
```

```php
$mixins
    ->foo() // ok
    ->bar(true) // ok
    ->bar(false) // Method 'bar' not found in Closure
    ->baz(); // Method 'baz' not found in Closure

$mixins
    ->foo() // ok
    ->bar() // ok
    ->baz(); // Method 'baz' not found in Closure

$mixins
    ->foo() // ok
    ->baz(); // ok
```

`vendor/_laravel_idea/_ide_helper_macro_static.php`

```php
namespace Foo\Bar {
    /**
     * @method static $this foo()
     * @method static \Closure bar(bool $value = true)
     * @method static $this baz()
     */
    class Mixins {}
}
```

But if I use it this way, it's ok.

```php
public function bar(): Closure
{
    return function (bool $value = true): static {
        PHPUnit::assertTrue($value);

        /** @noinspection PhpIncompatibleReturnTypeInspection */
        return $this->baz(); // ie return $this;
    };
}
```

**Comment by adelf** [comment]
Hi. It's hard to understand the type in that case. I teach PhpStorm to correctly recognize `return $this;` calls. But `$this->baz()` call doesn't make sense here, since for PhpStorm it definitely returns `Closure`... not `$this`.

Is it possible to write like this? Or the `baz` method returns another object?

```
$this->baz();
return $this;
```

**Comment by mertasan** [comment]
If it's not a bug, no problem. Just wanted to let you know in case you haven't noticed. Yes it works as you said. Fortunately, this is not something without a solution.

The reason I reported this was to use the least amount of @noinspection code to suppress ide warnings.

<img width="666" alt="screenshot 126" src="https://user-images.githubusercontent.com/13007665/130156311-862d6be8-70ed-4fff-b5b1-3a03fb4da2ab.png">

<img width="622" alt="screenshot 127" src="https://user-images.githubusercontent.com/13007665/130156314-069096e3-ea7a-43c9-b748-8ce630ce81d7.png">

**Comment by mertasan** [comment]
I guess I should close this issue. Thanks superman!
