### ISSUE TITLE
Generation menu for selected class

### ISSUE THREAD

**Issue by kennyhorna** [laravel-idea/plugin#37]
Hi! I've just installed the plugin, activated and restarted the IDE. Great work by the way!

Now, the docs says that you can generate elements from a class, for example an [Eloquent API Resource](https://laravel-idea.com/docs/2.x/eloquent#json-resource-generation) from a Model. But, in the `Generate.`. menu (<kbd>Alt</kbd>+<kbd>Insert</kbd>) I don't see the generation options. 

![image](https://user-images.githubusercontent.com/16125117/79073941-07c9ad00-7caf-11ea-9469-8edcbc3bc49b.png)

I should see these options instead (screenshot from the docs):

![image](https://user-images.githubusercontent.com/16125117/79073988-5d05be80-7caf-11ea-8e91-96dbe72b4648.png)

I searched in the plugin config but I couldn't find a way to activate them (in case it'd be a requirement). Could you help me with this?

## System info

IDE version: PhpStorm 2019.3.4
Plugin version: 2.3.192
Repo details: A fresh Laravel 7.X installation. I also modified the namespace for models to be inside `/Models` (so the code generation to create a model is working just fine).

----

Thanks in advance.

**Comment by adelf** [comment]
Hi, Kenny.
Thank you, it's already fixed in the new version which hasn't released yet. In current version it needs to have phpDocs generated by `artisan ide-helper:models`. You can use usual code generations(Create Json Resource, etc.) for now(I understand it's not so convenient, sorry).

**Comment by kennyhorna** [comment]
@adelf oh I see. Don't worry, I'll wait the next release then. Do you guys have an ETA for that?

**Comment by adelf** [comment]
I hope to release something in the end of the next week. Version with many minor fixes(2.4) or alpha 
 of new major version(3.0) with ide-helper replacement.

**Comment by adelf** [comment]
implemented in 2.4 version. please check and comment if there are some issues.
