### ISSUE TITLE
Generate Transformers if Fractal is installed

### ISSUE THREAD

**Issue by glorand** [laravel-idea/plugin#375]
Similar like on JsonResoure or ModelResoure, to generate a Transformer for selected Model, if fractal is installed
See more details:
https://fractal.thephpleague.com/
https://github.com/spatie/laravel-fractal

**Comment by adelf** [comment]
I also need a namespace. It can be configured for each project, but I need the default one. `App\Transformers`?

**Comment by glorand** [comment]
> I also need a namespace. It can be configured for each project, but I need the default one. `App\Transformers`?

Yes

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1440242144208297992 )
