### ISSUE TITLE
Remove "Request" on Model Resource generation

### ISSUE THREAD

**Issue by glorand** [laravel-idea/plugin#376]
![Screenshot from 2021-08-27 23-26-37](https://user-images.githubusercontent.com/883989/131184998-4b5fb939-58b7-483d-b33f-31ed62f1042c.png)

Declaration should be compatible with JsonResource->toArray(request: \Illuminate\Http\Request) 
 Inspection info: Reports the overridden methods declarations that are not compatible with the parent class. The inspection is enabled only for the PHP language level lower than 8.0.

**Comment by adelf** [comment]
I'll take a look. Thank you. You can change it to your own project in the Settings > Editor > File and Code templates > Code > Laravel Ideal Json Resource
