### ISSUE TITLE
Adding support of read only property suggestion

### ISSUE THREAD

**Issue by sykorax** [laravel-idea/plugin#38]
Hello,

I'd like to mention this would be really useful. 
Now it supports only the @property syntax, maybe should support the @property-read as well.
For instance i usually mark primary, generated keys with read-only.

What do you think?

**Comment by adelf** [comment]
Yes. You're right. We already talked about it with another plugin user. ide-helper marks with **@property-read** all property accessors, like `getFirstNameAttribute` => `@property-read $first_name`
The only problem that relations are also is marked with **@property-read**. But the types is different: `mixed` and `AnotherModelClass`, so I think I can manage it. Thanks.

**Comment by sykorax** [comment]
Hey, i can see the problem here, you are right.
Maybe primitives and Carbon types should be tracked only when it comes to ```@property-read``` stuff by default.

Thank you!

**Comment by adelf** [comment]
implemented in 2.4 version. please check and comment if there are some issues.
