### ISSUE TITLE
Error. Cannot use 'Arr' because the name is already in use

### ISSUE THREAD

**Issue by ShuaiZhangFmym** [laravel-idea/plugin#380]
![image](https://user-images.githubusercontent.com/68793694/131892969-f49e28ea-ba9d-4626-91ea-7747787d6a8e.png)

**Comment by adelf** [comment]
`_ide_helper.php` file is generated by `laravel-ide-helper` package... so this is that package issue.

BTW, helper code will always have many issues... just don't open it in the PhpStorm...
