### ISSUE TITLE
Cannot Generate Eloquent Helper Code for PostgreSQL with schema (Table not found for xxxx)

### ISSUE THREAD

**Issue by waimichael-hgc** [laravel-idea/plugin#381]
All of my models are extended my own BaseModel which extends Model, each model also states the DB table name of PostgreSQL together with schema in protected $table, eg. protected $table = "public.documents"; protected $table = "sales.orders".

I've found that if I remove the protected $table, all the models with the schema same as default connection have no warning in action "Generate Eloquent Helper Code". If I add the protected $table variable, warnings are shown as "Table not found for XXX".

Could anyone tell me how I can fix this problem? Thanks.

**Comment by pmua** [comment]
does not understand the entry "scheme.table_name" for the table name, apparently substitutes the default schema everywhere (in my case, dbo), and this is incorrect.

**Comment by adelf** [comment]
This is fixed in the 7.4 version.
