### ISSUE TITLE
Generate CarbonImmutable hints

### ISSUE THREAD

**Issue by atymic** [laravel-idea/plugin#384]
### Versions:
- ide-helper Version: 4.4.0.211

### Description:

Currently, a lot of things in the generated blocks indicate that a `Carbon` object is returned for dates.

Would it be possible to detect if `Date::use(CarbonImmutable::class)` is set, and then generate the respective docblocks with `CarbonImmutable` hints?

**Comment by adelf** [comment]
Implemented. Thank you. I'll release an update in 1-2 weeks.

**Comment by atymic** [comment]
Thanks, awesome as usual!

**Comment by adelf** [comment]
It should be fixed by the 4.4.2 version.
