### ISSUE TITLE
Code generation form doesn't show up

### ISSUE THREAD

**Issue by bonk007** [laravel-idea/plugin#386]
I was updating my phpstorm into the latest one and laravel idea updated since then. Code generation dialogue doesn't show up as usually, I was checking on `keymap` (probably the shortcut was modified), but it's not. It's still `ctrl + alt + ,`. But why code generation doesn't show up? Probably it's bug caused by updating.

```
Laravel Idea version: 4.4.0.212
```

```
PhpStorm 2021.2.1
Build #PS-212.5080.71, built on August 26, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-81-generic
GC: G1 Young Generation, G1 Old Generation
Registry: ide.intellij.laf.enable.animation=true, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: Rider UI Theme Pack (0.9.3), com.intellij.kubernetes (212.5080.55), net.seesharpsoft.intellij.plugins.csv (2.17.1), com.intellij.ideolog (203.0.27.0), com.intellij.properties (212.4746.57), com.codestream.jetbrains-codestream (11.0.13+183), mobi.hsz.idea.gitignore (4.2.0), zielu.gittoolbox (212.7.6), String Manipulation (8.15.203.000.3), de.espend.idea.php.annotation (8.0.0), ru.adelf.idea.dotenv (2021.3.0.212), de.espend.idea.laravel (0.15.4), com.intellij.lang.jsgraphql (3.0.0), lermitage.intellij.extra.icons (1.61.0.203), com.laravel_idea.plugin (4.4.0.212), com.jetbrains.space (212.5080.16)
Current Desktop: ubuntu:GNOME
```

**Comment by adelf** [comment]
Some plugins could replace this shortcut with their own. I can't say which of them... 
If you want to find it out you can install the "Presentation Assistant" plugin, turn it on and then try Ctrl-Shift-,

It will look like that:
![image](https://user-images.githubusercontent.com/2818394/132213961-18526924-4993-4603-a19c-d78442da74f9.png)
So you can find the action which really linked to this shortcut.

**Comment by adelf** [comment]
BTW, do you see my Code Generation action in the Code main menu?

**Comment by marclangesauels** [comment]
Have the same issue and the Code Generation action doesn't show up in the Code main menu. phpstorm Version 2021.3.1

**Comment by adelf** [comment]
@marclangesauels what about “Laravel” menu item next to Code?

**Comment by marclangesauels** [comment]
![image](https://user-images.githubusercontent.com/67956769/150083996-433488a8-19de-4c53-818a-4b1df0e4ac5b.png)

That does show up @adelf

**Comment by adelf** [comment]
@marclangesauels its in the main menu. But not in the Code, but in the own Laravel menu item.

**Comment by marclangesauels** [comment]
@adelf thank you i found it... Sorry for bothering
