### ISSUE TITLE
Inspection + quickfix for validation rules split to array

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#387]
Would be really nice with an inspection + quickfix for taking a validation string and split it into a validation array 👍 

E.g. 
```diff
$rules = [
-	'name' => 'required|string',
+	'name' => ['required', 'string'], 
];
```

**Comment by adelf** [comment]
I don't think inspection is good here. But as a context action, it might be good.

**Comment by adelf** [comment]
Forgot to mark this as implemented in the previous release. Thank you as usual for your good suggestions.

**Comment by olivernybroe** [comment]
Thank you for making my day-to-day life easier ❤️
