### ISSUE TITLE
Laravel Mix Issue

### ISSUE THREAD

**Issue by gmartha07** [laravel-idea/plugin#39]
Hello, Excelent plugin and very good the video tutorial you did.
Does your plugin have the option to fix this autocomplete from the webpack.mix.js file?
Mine keeps showing the message (unresolved function or method) in both mix.js and mix.sass.

Issue Screenshot:
[https://intellij-support.jetbrains.com/hc/user_images/hfxGobD_l-9TydnKGRxKjA.jpeg](url)

**Comment by adelf** [comment]
Hi, Gabriel.
I'm not very experienced in Javascript language support, but I'll take a look.

**Comment by gmartha07** [comment]
Thanks for the answer. I look forward to returning if you can identify a solution.

**Comment by madalinignisca** [comment]
@gmartha07 this is not related to Laravel Idea.
First, ensure you did run `npm install`.
Second, check if find the line in your webpack.mix.js is `const mix = require('laravel-mix');`.
Add it if not.

**Comment by adelf** [comment]
Thanks, Madalin.
