### ISSUE TITLE
[Feature Request]: Support inertia macro's

### ISSUE THREAD

**Issue by Lelectrolux** [laravel-idea/plugin#390]
### Feature Description

Inertia adds some macro's to Laravel : [Refs](https://github.com/inertiajs/inertia-laravel/blob/master/src/ServiceProvider.php#L67-L99)

The two main ones are :

    // https://inertiajs.com/routing#route-helpers
    Route::inertia('/about', 'AboutComponent'); // Bypasses the need for a controller
    
    Request::inertia(); // Check if the inertia header is set

It also adds some testing assertions. The docs for these can be found [here](https://github.com/claudiodekker/inertia-laravel-testing/tree/a5ac8d372e456534f5ad2e07a6875e0f27c6a73d)

There is also the `@inertia` blade directive, for completeness.

Builds on #147

**Comment by adelf** [comment]
Hi. Have you tried to generate a helper code? Code > Laravel Idea Code Generation > Generate Helper Code. It should add needed macro-methods. 

> There is also the @inertia blade directive, for completeness.

I'll add. Thanks.

**Comment by Lelectrolux** [comment]
> Hi. Have you tried to generate a helper code? Code > Laravel Idea Code Generation > Generate Helper Code

Just tried it, and it doesn't seem to make a change. Thanks anyway

**Comment by adelf** [comment]
It should be fixed by the 4.4.2 version.

**Comment by maicol07** [comment]
@adelf It doesn't seem to be fixed... It seems that I can get autocompletion via `Inertia::render` but not via `Route::inertia`, although I have generated the helper code...

**Comment by adelf** [comment]
@maicol07 thanks. Fixed also.

**Comment by adelf** [comment]
Oooops... I’m sorry. I’ll fix this soon. And I can also build a special release only with this fix, available only here.

**Comment by maicol07** [comment]
> Oooops... I’m sorry. I’ll fix this soon. And I can also build a special release only with this fix, available only here.

Ok, that will come in any case in the next "official" release, right?

**Comment by adelf** [comment]
Sure)

**Comment by maicol07** [comment]
> Sure)

Great! Waiting for the special release, then! 😁

**Comment by adelf** [comment]
Sorry, I was on vacation and totally forgot about the special release. It should be fixed by 4.4.4.
