### ISSUE TITLE
[Feature Request]: Option to skip generating 'down' method in migrations

### ISSUE THREAD

**Issue by hailwood** [laravel-idea/plugin#394]
### Feature Description

I have a customised stub for generating the migrations via `php artisan make:migration` which removes the down method as we never use it.

It would be pretty sweet if we could have a remembered checkbox to not generate the down method when using laravel-idea :)

**Comment by adelf** [comment]
You can customize Laravel Idea templates also. 


![](https://laravel-idea.com/img/docs/generation/templates.png)
