### ISSUE TITLE
[Feature Request]: Add "anonymous" option in create Model action

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#395]
### Feature Description

Hi @adelf!

It would be nice to have an `Anonymous` option along with the `create migration` section of `Create Model` modal

![image](https://user-images.githubusercontent.com/8792274/133245484-7c4f5720-8618-4ed3-9939-21704633c5bb.png)

After all, that option is already present in `Create Database Migration" modal

![image](https://user-images.githubusercontent.com/8792274/133245285-2347b578-3c8f-4b14-9645-89b440d86371.png)

**Comment by adelf** [comment]
Hi, Fabio.

Usually, developers use one style for all migrations. So, if you will create an anonymous migration once, Laravel Idea will remember it and all migrations will be anonymous.
I'll try to make some kind of Project Setup window and will ask there which kind of migrations is preferable...
I think it's better than to show this checkbox each time :)

**Comment by fabio-ivona** [comment]
Ah! Did not noticed that! Maybe because I used the model dialog to make migrations!

Thanks!
