### ISSUE TITLE
[Bug]: Property accessed via magic method

### ISSUE THREAD

**Issue by hailwood** [laravel-idea/plugin#399]
### Bug description

Properties on models are always marked as 'accessed via magic method' if the property is on the current model.

E.g.

```php
class User extends Model
{

    public function palace(): HasOne
    {
        return $this->hasOne(Palace::class);
    }
    
    public function getSomethingAttribute(): string
    {
        return 'something';
    }

}
```

If we call the following then everything is okay.
```php
$u = new User;
$u->palace->id;
$u->something;
$u->database_column;
```

But if we put a method inside the `User` class
```php
public function test(): void
{
    $this->palace->id; // palace marked as 'accessed via magic method', id is fine.
    $this->something; // marked as 'accessed via magic method
    $this->database_column; // marked as 'accessed via magic method'
}
```

Navigate to declaration etc still works, just the annoying warning.
This was originally brought up in #205 but that appears to be closed as fixed, so maybe this is a regression?

### Plugin version

4.4.0.212

### Operating system

Linux

### Steps to reproduce

Generate eloquent helper code
Access a property/relation/accessor on a model **from within the model class**.

**Comment by adelf** [comment]
Hi, Matthew.

This is an old PhpStorm issue. I posted it on their youtrack... https://youtrack.jetbrains.com/issue/WI-54460
I hope we will find something to fix that.

**Comment by hailwood** [comment]
Cheers, voted for the issue.

**Comment by adelf** [comment]
BTW, it should be fixed by the last update. I've found one hacky way.
