### ISSUE TITLE
Add user model selection to the policy creation window

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#40]
Now the user model is set automatically.

I propose to add the ability to specify different models.

![2020-04-17_01-40-24](https://user-images.githubusercontent.com/10347617/79513450-85454280-804c-11ea-8425-2a6b87d2e96e.jpg)

**Comment by adelf** [comment]
Hi. Andrey. Do you have several User models in your project? Why? :)

**Comment by adelf** [comment]
Ok. Seems I understand why it might be needed. I can suggest this - list all these classes in the settings(separated by comma) and if it more than 1, plugin will ask it in these dialog windows...

**Comment by andrey-helldar** [comment]
> Hi. Andrey. Do you have several User models in your project? Why? :)

I am currently working in a project where there are many user entities: about 50 posts of employees and clients.
So historically, there are two models in the project: employees and users.

**Comment by adelf** [comment]
fixed in 3.0 version. please check and comment if there are some issues.

**Comment by andrey-helldar** [comment]
There is no option to select another user model.

![2020-05-19_17-02-23](https://user-images.githubusercontent.com/10347617/82335897-9938e700-99f2-11ea-881a-076a7556eb29.jpg)
![2020-05-19_17-02-11](https://user-images.githubusercontent.com/10347617/82335901-9a6a1400-99f2-11ea-9242-d8fc6af9e21a.jpg)
![2020-05-19_17-01-47](https://user-images.githubusercontent.com/10347617/82335907-9b02aa80-99f2-11ea-88a5-c1e08f90325e.jpg)

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/82344449-bb376700-99fc-11ea-8774-a6ba29a306e4.png)

:) But I see the bug in this settings window... I have to release a new version now :)

**Comment by andrey-helldar** [comment]
So yes, it works)
Only it is not obvious that you need to specify the model through a semicolon.
In my opinion, it’s better to add a list with a “+” button.

![2020-05-19_18-43-28](https://user-images.githubusercontent.com/10347617/82347753-b2489480-9a00-11ea-8012-354cce9688f8.jpg)
