### ISSUE TITLE
[Feature Request]: Multiple Paths for Controllers & Form Requests

### ISSUE THREAD

**Issue by hailwood** [laravel-idea/plugin#400]
### Feature Description

I have a bit of a strange directory structure as it works for us - 

Your typical laravel setup is
```
/app/Http/Controllers
/app/Http/Requests
```

I have the following setup - 
```
/app/Http/Frontend/Controllers
/app/Http/Frontend/Requests
/app/Http/Frontend/Actions (single action controllers)
/app/Http/Api/Controllers
/app/Http/Api/Requests
```

I'd love to have the option in settings to select "these are the path**s** my controllers/single action controllers/form requests should be in" and if I have multiple then be provided with a dropdown in the create dialog to select the root path for that type.

Note that this also means we have separate base classes - 
```
/app/Http/Frontend/Controllers/Controller.php
/app/Http/Api/Controllers/Controller.php
```

I am aware we can do a single setup - 
![image](https://user-images.githubusercontent.com/709773/133512712-98626f7b-fae8-4af5-ac58-c601e49f3969.png)
But this means I need to create my Api resources manually, and no option to put single action controllers in a different location.

sidenote - sorry for the bombardment of issues 😅

**Comment by adelf** [comment]
This can be solved by Custom generations:

![image](https://user-images.githubusercontent.com/2818394/133587582-5c9028ce-5166-4fe1-9787-5ddcaf88535f.png)

**Comment by hailwood** [comment]
Mate, your plugin as everything.
Definitely a worthwhile investment for any Laravel developer.
