### ISSUE TITLE
[Bug]: Custom User model completion in Create Policy

### ISSUE THREAD

**Issue by MuathIbnHassan** [laravel-idea/plugin#403]
### Bug description

when overriding the default User model with another model in config('auth.providers.users.model')
the custom model should be filled  in polices methods parameters

the user model defined in config:auth :
![the user model defined in config:auth](https://user-images.githubusercontent.com/44880589/134032510-cf65b33a-f30f-40a2-b27b-1657ce35d496.png)

the laravel idea create policy output : 
![the laravel idea create policy output](https://user-images.githubusercontent.com/44880589/134032543-1c5f0d93-a6c2-479c-b9f1-2adae4d723b9.png)

artisan make policy output (the expected one) :
![artisan make policy output (the expected one)](https://user-images.githubusercontent.com/44880589/134032584-c82af385-3001-430d-b786-cf319b2685a9.png)

### Plugin version

4.4.0.212

### Operating system

MacOS

### Steps to reproduce

change the default user model in config/auth.php >  providers > users > model
> 'SHIFT + ⌘ ,' 
> Create Policy
the user model used should be the same as the user model in the config file

**Comment by adelf** [comment]
Hi, Muath. Fetching the user model is hard. Sometimes projects use several user models... so I only have a setting for it.
As you see you can add several user models. Or just one, but different than `App\Models\User`.

![image](https://user-images.githubusercontent.com/2818394/134033875-214fddc1-e455-48b6-a1e9-2074af9388d2.png)

**Comment by theveloperspl** [comment]
> Hi, Muath. Fetching the user model is hard. Sometimes projects use several user models... so I only have a setting for it. As you see you can add several user models. Or just one, but different than `App\Models\User`.
> 
> ![image](https://user-images.githubusercontent.com/2818394/134033875-214fddc1-e455-48b6-a1e9-2074af9388d2.png)

Hello, is similar setting available in current Idea versions?
It has problems with auto filling relations data with auth()->user() and this could help.

**Comment by adelf** [comment]
@theveloperspl Laravel Idea reads your config/auth.php file and fetches all models from there. You have dynamic configuration there?
