### ISSUE TITLE
Plugin "Laravel Idea" is incompatible

### ISSUE THREAD

**Issue by matro-skin** [laravel-idea/plugin#41]
Paid and activated, storm says:
> Plugin Error: Plugin "Laravel Idea" is incompatible (until build 193.SNAPSHOT < PS-201.6668.153).

**Comment by adelf** [comment]
What PhpStorm version you have?

**Comment by matro-skin** [comment]
last one
PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020

**Comment by adelf** [comment]
Laravel Idea has 2 versions: https://plugins.jetbrains.com/plugin/13441-laravel-idea/versions
2.3.192 - for 2019.2-2019.3 IDEs
and 2.3.201 - for 2020.1
Last one should work.

**Comment by matro-skin** [comment]
yep, plugin was outdated, thanks
