### ISSUE TITLE
[Feature Request]: symbols search for route names

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#411]
### Feature Description

Could be cool if searching for a named route via symbols was possible. 

Pressing it would then navigate to the route in the route file 👍 
![image](https://user-images.githubusercontent.com/5870441/135276598-4103c8c8-9274-4a4c-95e6-64782956beb6.png)

If interested in an example, here is the file for how I implemented it for pest tests.
https://github.com/pestphp/pest-intellij/blob/957fc03b0cc8238fe07fc71ce56f95413135c045/src/main/kotlin/com/pestphp/pest/goto/PestTestGoToSymbolContributor.kt
The biggest problem was data presentation change, as many elements in PHP plugin does not have a data presentation.

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1443238888961683458 )

**Comment by adelf** [comment]
@dillingham I was answering you on Twitter... but you deleted it)
My tweet:
"I'll try to implement this for each route name GoTo soon. That's not so easy..."

**Comment by dillingham** [comment]
@adelf didn't want to take away from the accomplishment.. as I assumed it probably was hard to do.

Thats awesome though, thanks
