### ISSUE TITLE
[Bug]: Laravel Folders not identified when developing a Package

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-idea/plugin#416]
### Bug description

When I am developing a Laravel Package, actions to create Model, Command, Middleware don't work and throws an error "Directory Not Found". The Laravel app has a default directory `app` and when developing a package, the default source directory is `src`. It would be great if the plugin to identify the current IDE configuration and identify folders correctly.

### Plugin version

4.4.0.212

### Operating system

MacOS

### Steps to reproduce

I use this repository (https://github.com/spatie/package-skeleton-laravel) as the base for creating laravel packages. So do a lot of other developers.

1. Fork this repo
2. Open the repo in PHP Storm 
3. Try an action "Create Model"

**Comment by adelf** [comment]
You can try to change "Module system" to "Package development": https://laravel-idea.com/docs/modules

**Comment by abishekrsrikaanth** [comment]
Thanks
