### ISSUE TITLE
[Bug]: Renaming Facade doesn't appear to change a lot in PHPStorm due to Laravel Idea hardcoding(?) facades?

### ISSUE THREAD

**Issue by MrWouterNL** [laravel-idea/plugin#418]
### Bug description

I renamed the `Event` Facade alias to `LaravelEvent` because I have a project where I want to use a Model called 'Event'. It looks like in the _facade_aliases.php file:
![image](https://user-images.githubusercontent.com/24954095/135859672-ba343ddb-36d8-42a3-8f60-ada7c4cb0edd.png)

I've changed the alias in my `config/app.php` file in the project to LaravelEvent:
![image](https://user-images.githubusercontent.com/24954095/135859957-2d591e81-17eb-4747-a887-f0c6d306b7f9.png)

What would be the best way to sort this issue out?

### Plugin version

4.4.1.212

### Operating system

Windows

### Steps to reproduce

Renamed the `Event` Facade alias to `LaravelEvent`  in config/app.php, and create a model called 'Event'. Autoimport for Event won't work, because Laravel Idea thinks the Event alias exists.

**Comment by adelf** [comment]
You need to Generate Helper Code again...  In this menu:

![](https://laravel-idea.com/img/docs/generation/menu.png)

choose "Generate Helper Code". It is generated after each project opening... and I'll add its generation after each `config/app.php` file change. Thank you.

**Comment by MrWouterNL** [comment]
Thanks! Really appreciate that :)
