### ISSUE TITLE
[Feature Request]: Generate eloquent model helper codes to separate files

### ISSUE THREAD

**Issue by zhwei** [laravel-idea/plugin#422]
### Feature Description

Overwrite changed model's helper file only when generating which will improve index performance for big project (more than hundreds model)

![image](https://user-images.githubusercontent.com/1446459/136884933-778e30b2-89d8-44cd-b175-29ff3861825f.png)

**Comment by adelf** [comment]
Implemented in 5.4. Thanks.

**Comment by zhwei** [comment]
Thanks
