### ISSUE TITLE
[Bug]: Code Generation Sync

### ISSUE THREAD

**Issue by lioneaglesolutions** [laravel-idea/plugin#428]
### Bug description

When creating a custom generation in a project, it is not available in any other projects. Should they sync across projects?

I have ensure my settings sync is active but can not seem to have the custom generations shared across projects.

Is this possible?

### Plugin version

4.4.2.212

### Operating system

MacOS

**Comment by adelf** [comment]
They are project based for now... so they aren’t shared between projects. But I’ll try to solve this problem somehow.
