### ISSUE TITLE
[Feature Request]: Add the ability to Create Nova Resource when creating a Model

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-idea/plugin#429]
### Feature Description

Not sure if there is a way to detect if Laravel Nova is installed on the project or not, but it would be great if there is a way to show "Create Nova Resource" on the "Create a Model" dialog.

<img width="256" alt="CleanShot 2021-10-20 at 03 29 07@2x" src="https://user-images.githubusercontent.com/1639302/137996889-22aa22f5-051c-4d22-a519-54c610ff560a.png">

Additionally, can you also allow the option to update the path of the resource? I like to group the nova resources and models by the domain they belong to.

**Comment by adelf** [comment]
Implemented in one of previous versions.
