### ISSUE TITLE
Plugin "Laravel Idea" is incompatible

### ISSUE THREAD

**Issue by nyrik8989** [laravel-idea/plugin#43]
PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.intellij.ideolog, mobi.hsz.idea.gitignore, ideanginx9, net.ashald.envfile, com.atlassian.bitbucket.references, ru.adelf.idea.dotenv, com.alicannklc.laravel.snippets, com.aurimasniekis.phppsr4namespacedetector, com.laravel_idea.plugin, org.toml.lang
Current Desktop: ubuntu:GNOME

**Plugin "NPM Script Runner" is incompatible (supported only in IntelliJ IDEA). 
Plugin "Blade" is incompatible (until build 193.SNAPSHOT PS-201.6668.153). 
Plugin "PHP composer.json support" is incompatible (marked as broken).**

**Comment by nyrik8989** [comment]
File directory not showing

**Comment by nyrik8989** [comment]
If you disable the plugin, everything is fine

**Comment by laravel-idea** [comment]
Laravel Idea has version for 2020.1. Please update.

**Comment by nyrik8989** [comment]
PhpStorm 2020.1
Build # PS-201.6668.153, сборка 13 апреля 2020 г.
![image](https://user-images.githubusercontent.com/22983913/79735533-1b08f800-8301-11ea-8b62-70485d7e02e2.png)

**Comment by adelf** [comment]
Some plugins should be updated to 2020.1 versions. Laravel Idea might be marked as incompatible, because Blade plugin is outdated. Try to update all of them.

**Comment by nyrik8989** [comment]
![image](https://user-images.githubusercontent.com/22983913/79735896-aa161000-8301-11ea-8ead-8832ac05f3a3.png)

**Comment by adelf** [comment]
At least Blade plugin has all needed versions: https://plugins.jetbrains.com/plugin/7569-blade/versions You can update it manually.

**Comment by nyrik8989** [comment]
Все хорошо!!!
Спасибо большое
