### ISSUE TITLE
[Feature Request]: Blade file search by dot structure

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#432]
### Feature Description

Often when I have to find a blade file I automatically try to find it the same way I would in Laravel, with a dot syntax. 

E.g. if I have the following structure

* MyFeature/index.blade
* OtherFeature/index.blade

I cannot easily open the index file by searching for `index.blade`, as both will come up.  
Doing a Laravel syntax way, I would normally write `MyFeature.index`, however that does not work, so I will have to do `MyFeature/index` instead, which feels unnatural when dealing with a blade file. 

Two screenshots to show 👍 
![image](https://user-images.githubusercontent.com/5870441/138673653-7685ae22-dbae-452c-b12b-e7b8e3205b58.png)
![image](https://user-images.githubusercontent.com/5870441/138673677-2573b6b7-48de-41dd-aca2-a94e79035336.png)

**Comment by adelf** [comment]
Hi, Oliver. What do you suggest? The same solution as for route names?

**Comment by olivernybroe** [comment]
Basically yes, however if possible I think this should be searchable in files only, not in symbols search 🤔 

As this is something you do when trying to find a file, not finding symbols in a file.

**Comment by ralphjsmit** [comment]
I agree with you Oliver, this is something that I also had a few times 😆

**Comment by adelf** [comment]
Forget to close this :) It's implemented.

**Comment by ralphjsmit** [comment]
Thank you Adel!
