### ISSUE TITLE
[Bug]: Don't use deprecated faker properties

### ISSUE THREAD

**Issue by abenerd** [laravel-idea/plugin#434]
### Bug description

FakerPHP/Faker#164 deprecated the use of property accessors, when creating factories the old syntax is still used for generating values for the models fields.

### Plugin version

4.4.3.212

### Steps to reproduce

Have a model and generate a new factory for it with idea.

**Comment by adelf** [comment]
It will be optional. "methods" will be by default. Thank you.

![image](https://user-images.githubusercontent.com/2818394/142021890-b0e5ddc7-cfbe-4e1e-ba41-102bb288bac0.png)

**Comment by adelf** [comment]
4.4.4 is available.
