### ISSUE TITLE
[Feature Request]: Nova Resource magic method

### ISSUE THREAD

**Issue by Muetze42** [laravel-idea/plugin#436]
### Feature Description

Example from Nova Docs for resource:
https://nova.laravel.com/docs/3.0/resources/fields.html#showing-hiding-fields

```php
Text::make('Name')->showOnIndex(function () {
    return $this->name === 'Taylor Otwell';
}),
```

Php Storm message: `Property accessed via magic method`

![Message](https://user-images.githubusercontent.com/26193232/140571271-c99336fc-2320-46fb-af17-ddde1083d711.PNG)

Will that be possible to add magic methods for Nova resources?

**Comment by adelf** [comment]
Implemented in 5.6.1.
