### ISSUE TITLE
[Bug]: the class attribute don't code-completion into HTML/BLADE files

### ISSUE THREAD

**Issue by DavideNet** [laravel-idea/plugin#437]
### Bug description

While inserting attributes in the various html tags, the class attribute no longer appears! (Deactivating the plugins, it works again)

Example:
![image](https://user-images.githubusercontent.com/12598573/140667204-5121ca69-16aa-4161-b4c2-8f0e9d4f562f.png)

### Operating system

Windows

**Comment by adelf** [comment]
What plugin version are you using? I disabled this in one of the last versions exactly for this reason.

**Comment by DavideNet** [comment]
Now it works correctly, thanks

**Comment by yammycode** [comment]
I have same problem too. Laravel Idea 4.4.6.212
