### ISSUE TITLE
Add HigherOrderCollectionProxy support

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#44]
# Description
So I love to use HigherOrderCollectionProxy, however it bugs me a lot that phpstorm just can't handle that.

It could be awesome if you could do so whatever method or property is ran on a `HigherOrderCollectionProxy`, then afterwards it returns the Collection again. 

# Example
![image](https://user-images.githubusercontent.com/5870441/79747793-9ae88f80-830c-11ea-9b44-954d04fb5a8f.png)
The two statements here are equal. I know that doing so it can understand that the method `shouldRun` is a valid method on my class `Action` is a whole other task.

Hoping it should be possible to say that `shouldRun` returns `Collection` 😄

**Comment by adelf** [comment]
It will be hard to implement it ideally - with full completion. But I'll try to make at least Type provider for it. Thanks.

**Comment by olivernybroe** [comment]
@adelf Yeah, full completion so it understands `shouldRun` seems much harder. 

But if it could understand at least that the `each` method is running on the `Collection` class that would be awesome. It's fine that `shouldRun` is still displayed as a method that doesn't exist, as it can't resolve that yet.

**Comment by adelf** [comment]
Hi, Oliver. I think I found the way to provide **full** completion for these proxies! :) I'll try to include it to the next version.

**Comment by olivernybroe** [comment]
@adelf Oh wauw that sounds amazing! ❤️ 
This is totally game changing!

So just to understand, this means you are actually able to know what type the collection is referring to? Meaning that you also would be able to do the following:

```
collect($actions)->first()->shouldRun();
```

**Comment by adelf** [comment]
Not sure about collect... maybe in the next versions.
But this code will be fully completed:
`Action::whereType('someType')->get()->filter->shouldRun()->each->handle()`

**Comment by olivernybroe** [comment]
@adelf Alright that's pretty awesome! If that part is working then doing it with collect prob. shouldn't be the biggest issue in a future version :) 
Especially because the type to use in the collection can just be taken directly from the array supplied. 

Really looking forward to this. This is really gonna solve the biggest issues with using `HigherOrderCollectionProxy`.

**Comment by adelf** [comment]
New 3.0.4 versions contains Eloquent helper code generation and there is an option about generating proxy classes. 
"Generate Eloquent Helper Code" in Laravel Idea code generations. It analyzes migrations and generates `_ide_helper_models.php` file with the same idea as **laravel-ide-helper** but with additional code for Builder, Collection and now Proxy classes.
Please, check and comment if there are some issues.

**Comment by mityukov** [comment]
So, this is added? Can't make it work, actually:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1751910/156805743-6e464651-1c48-4d83-915d-276361c5ee8f.png">

Note: disregard that `@var` at the top — it doesn't affect anything…
