### ISSUE TITLE
[Bug]: Free licenses for students

### ISSUE THREAD

**Issue by ayoubaitouhmad** [laravel-idea/plugin#441]
### Bug description

i have this issue trying to get my plugin activated. I get this error while trying to activate it but my student license is active
![Capture](https://user-images.githubusercontent.com/70922934/141513579-f2338a9d-3f2e-433e-952a-4e46c1364159.PNG)
.

### Plugin version

4.4.3.212

### Operating system

Windows

**Comment by adelf** [comment]
Hello, Ayoub. Please, try to reactivate the license. Here is the instruction - https://plugins.jetbrains.com/docs/marketplace/community-programs.html

If you haven't discounts select available on this page, please write to sales@jetbrains.com

**Comment by ayoubaitouhmad** [comment]
> Hello, Ayoub. Please, try to reactivate the license. Here is the instruction - https://plugins.jetbrains.com/docs/marketplace/community-programs.html
> 
> If you haven't discounts select available on this page, please write to [sales@jetbrains.com](mailto:sales@jetbrains.com)

I did all that but I stile have the same problem

**Comment by adelf** [comment]
Please ask sales@jetbrains.com to help.
