### ISSUE TITLE
[Feature Request]: Symbol search for Laravel commands

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#443]
### Feature Description

Not sure if you already have indexes for the laravel commands, but if you have it would be awesome to have symbol search for them also 👍 

E.g. being able to search for `backup:clean` and get to the command

**Comment by adelf** [comment]
Oliver "Symbol seeker" Nybroe )

**Comment by olivernybroe** [comment]
Haha 👍  

Gotta be able to search on anything in the world! 🌎 
But actually this was something I discovered would be nice because of a bug that I will create in a moment.

**Comment by olivernybroe** [comment]
I think you can close this one btw 👍

**Comment by adelf** [comment]
Yeah. I forgot. Thanks :)
