### ISSUE TITLE
[Bug]: goto command does not work when parameters in command string

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#444]
### Bug description

![image](https://user-images.githubusercontent.com/5870441/141987867-865f739a-4eee-4976-ae6f-33af3075e77f.png)

When using goto on a laravel command, it does not work if there are parameters in the string.

### Plugin version

4.4.3.213

### Operating system

MacOS

### Steps to reproduce

Create a command string with parameter and press goto on it

```php
$schedule->command('backup:run --db-name=mysql')->daily()->at('02:00');
```

**Comment by adelf** [comment]
Thanks!

**Comment by olivernybroe** [comment]
Hey @adelf, this issue seems to have reappeared 👍

**Comment by adelf** [comment]
Big refactoring for artisan commands... and I don't have a lot of tests for GoTo... Thanks again :)
