### ISSUE TITLE
[Feature Request]: Adding hints when accessing the `each` key

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#446]
### Feature Description

Laravel provides the ability to iterate over each element of a collection, calling the methods built into it.

For example:

```php
$pages = Page::query()->get();

$pages->each(fn (Page $page) => $page->refresh());
```

That being said, Laravel also provides the ability to simplify this code to:

```php
$pages = Page::query()->get();

$pages->each->refresh();
```

I suggest keeping track of such collections and suggesting methods.

![image](https://user-images.githubusercontent.com/10347617/142273480-c22b83c6-f890-4082-a2d4-1fb10b9c3832.png)

![image](https://user-images.githubusercontent.com/10347617/142274089-87fabdc3-4511-4dff-8aaf-53a47bf2e319.png)

**Comment by adelf** [comment]
https://laravel-idea.com/docs/eloquent#helper-code-generation
“Create collection proxy helper code” option?

**Comment by andrey-helldar** [comment]
Hm...

![image](https://user-images.githubusercontent.com/10347617/142276067-32f3b54a-19eb-4062-9a8b-e19322c0f92e.png)

![image](https://user-images.githubusercontent.com/10347617/142276072-29cdf38f-2133-4fd3-96b7-a9373d1b3bb1.png)

**Comment by adelf** [comment]
:(
I’ll check. Thanks.

**Comment by andrey-helldar** [comment]
If it helps, I deleted the folder and generated only these helpers.

![image](https://user-images.githubusercontent.com/10347617/142277072-659ebc17-4642-47e4-9da2-7bd10add5e68.png)

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/142421840-3b2ba9a4-0f57-4b16-a5ff-a41a075d127b.png)


Lets debug? :)

**Comment by andrey-helldar** [comment]
Try entering method names instead of field names. For example `refresh`.

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/142428451-03512017-4eaf-48a8-9869-87cb34902224.png)

![image](https://user-images.githubusercontent.com/10347617/142428501-a2060faa-88ed-43fa-81a7-126a2bc0bac6.png)

![image](https://user-images.githubusercontent.com/10347617/142428536-a96d85f4-1458-4b8e-a143-329a2e530eeb.png)

![image](https://user-images.githubusercontent.com/10347617/142428639-c774e358-c158-450e-aebb-ca191159d9d7.png)

**Comment by adelf** [comment]
I added some Eloquent methods, like `refresh()` to the completion. Thank you.
