### ISSUE TITLE
[Feature Request]: Fetch Table name for Migration from Model class instance via the `getTable` method

### ISSUE THREAD

**Issue by iamriajul** [laravel-idea/plugin#448]
### Feature Description

I think you can add a checkbox when generating a Model called: Get Migration table name from Model Instance.
This way the navigation between Migration to Model would be easier just by clicking the Model class:
The migration file result would be something like this:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\Segment;

class CreateSegmentsTable extends Migration
{
    public function up()
    {
        Schema::create((new Segment)->getTable(), function (Blueprint $table) {
            $table->bigIncrements('id');
            //            
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists((new Segment)->getTable());
    }
}
```

What do you say?

Thanks.

**Comment by adelf** [comment]
It should work and fetch a "segments" table. Do you have special logic in the Segment::getTable() method?

**Comment by iamriajul** [comment]
What I want is the `Single Source of Truth`, because I'm using foreign keys in other tables referencing the `segments` table, when specifying table names using literal string then I've to copy table names accurately, and especially in my project there are a lot of tables and most of their names are long to remember, and easily can be mistaken, but when using Model Instance way for getting table name that way I can have IDE's auto-completion of the class name and also I can change table name at one place (in the Model) that will be reflected everywhere If I need to.

**Comment by adelf** [comment]
@iamriajul I understand this. And Laravel Idea should also understand that `(new Segment)->getTable()` == "segments". It doesn't?

**Comment by iamriajul** [comment]
> And Laravel Idea should also understand that `(new Segment)->getTable()` == "segments". It doesn't?

I don't understand what are you trying to say actually.

By default the expression `(new Segment)->getTable() == "segments"` is **true**
But not when I override the $table property in the Segment model like this (now it's **false**):
```php
class Segment extends Model
{
    protected $table = 'wp_segment';
}
```

**Comment by adelf** [comment]
Laravel Idea meets `(new Segment)->getTable()`. Goes to `Segment` class and tries to fetch it's table. If it sees `protected $table = 'wp_segment';` then the table will be "wp_segment". So, this migration should work. The only problem when `getTable()` method for this model is overrriden and there are something like `return someCalculation();`
So, did you run "Eloquent Helper Code Generation"(https://laravel-idea.com/docs/eloquent) and still have issues?

**Comment by iamriajul** [comment]
Okay, I didn't have issues with auto-completion of fields with a query, as I already manually write PhpDoc every models. Btw thanks for introducing me to the `Eloquent Helper Code Generation` option for Laravel Idea. 
And also I want to give feedback to generated PhpDoc for Models, I write PhpDocs like this with proper nullability and types matching database column type like this:
```php
/**
 * @property-read int $id
 * @property int $pillar_id
 * @property string|null $icon_uri
 * @property string|null $header_image_uri
 * @property int|null $content_id
 */
```
Laravel Idea generate something like this:
```php
/**
 * @property string $id
 * @property string $pillar_id
 * @property string|null $icon_uri
 * @property string|null $header_image_uri
 * @property string|null $content_id
 */
```
You can see the Laravel Idea generated PhpDoc doesn't care about the actual type in the database. it's applying string type to all.

**Comment by iamriajul** [comment]
> What I want is the `Single Source of Truth`, because I'm using foreign keys in other tables referencing the `segments` table, when specifying table names using literal string then I've to copy table names accurately, and especially in my project there are a lot of tables and most of their names are long to remember, and easily can be mistaken, but when using Model Instance way for getting table name that way I can have IDE's auto-completion of the class name and also I can change table name at one place (in the Model) that will be reflected everywhere If I need to.

To understand the context fully I would suggest you look at these migrations for a nested database design with foreign keys: https://gist.github.com/iamriajul/d70619cdda9c23e1fa4f623cd6e737c4

Thanks.

**Comment by adelf** [comment]
I'll check. Thank you.

**Comment by adelf** [comment]
Helper code for `ContentComponent` class. Everything looks ok.

```
    /**
     * @property int $id
     * @property int $content_id
     * @property string $type
     * @property int $order
     * @property Carbon|null $created_at
     * @property Carbon|null $updated_at
     * @method static _IH_ContentComponent_QB onWriteConnection()
     * @method _IH_ContentComponent_QB newQuery()
     * @method static _IH_ContentComponent_QB on()
     * @method static _IH_ContentComponent_QB query()
     * @method static _IH_ContentComponent_QB with()
     * @method _IH_ContentComponent_QB newModelQuery()
     * @method static _IH_ContentComponent_C|ContentComponent[] all()
     * @mixin _IH_ContentComponent_QB
     */
    class ContentComponent extends Model {}
```

**Comment by iamriajul** [comment]
> Helper code for `ContentComponent` class. Everything looks ok.

The [Feature Request] wasn't about Helper code! 
It was about having an option (checkmark whether to use this pattern or not) to generate Migration with `(new Model)->getTable()` instead of `string literal` table name, to have the Single Source of Truth for a table name.

**Comment by adelf** [comment]
Sorry. Didn't get it from the beginning. No, it won't be implemented.

It's hard to find needed model class each time. Also, Single Source of Truth works well when all migrations are ran with `migrate:refresh`. But in the big projects with team the stability of migrations is much more important than SSOT. When you change the table name for the model, better to make a migration with `Schema::rename` than this dangerous automatical change.

**Comment by iamriajul** [comment]
> But in the big projects with team the stability of migrations is much more important than SSOT. When you change the table name for the model, better to make a migration with `Schema::rename` than this dangerous automatical change.

I agree with you, thanks for pointing this out.
