### ISSUE TITLE
Query Scope On Relationship

### ISSUE THREAD

**Issue by gradedcatfood** [laravel-idea/plugin#45]
Hello,

I love this plugin and thank you for all the work on it! Happy paying customer.

I have a question if I needed to add documentation to my Local Query Scope to get my IDE (PHPStorm) to detect it or if the plugin doesn't cover this scenario.

I have a query scope that is on a relationship. This is the best example of what I'm referring to https://stackoverflow.com/a/26178429

Is this issue the same as? https://github.com/laravel-idea/plugin/issues/30

I have tested the code it is valid so I have also attached images of my local code. 

Here is the query scope logic
![query-scope](https://user-images.githubusercontent.com/6394329/79806219-bfe4fe80-831c-11ea-9df5-968f07f748c3.png)

Here is the defined relationship along with the other relationship using this query scope
![relationship-and-consuming-query-scope](https://user-images.githubusercontent.com/6394329/79806224-c2475880-831c-11ea-8a1e-af97c4e40190.png)

**Comment by adelf** [comment]
Hi. No, its not the same issue. But I'll add this to the v3.0. I'll release v2.4 soon. Today or tomorrow. And right after that I'll put the early version of v3.0 to the **alpha** channel. With new generator of `_ide_helper_models.php` file. The completion with it looks fantastic. I'll write here about it.

**Comment by gradedcatfood** [comment]
> Hi. No, its not the same issue. But I'll add this to the v3.0. I'll release v2.4 soon. Today or tomorrow. And right after that I'll put the early version of v3.0 to the **alpha** channel. With new generator of `_ide_helper_models.php` file. The completion with it looks fantastic. I'll write here about it.

Ooo fantastic! Thank you for the speedy reply 👍

**Comment by adelf** [comment]
3.0 version is available. You can try new generator! :) please check and comment if there are some issues.

**Comment by gradedcatfood** [comment]
Hi @adelf , thank you for the update! I got it to work I just had to add this to my docblock defining the relationship to get it to work

`| \App\ReservationContact`

So in result the docblock was:

```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany | \App\ReservationContact
     */
```
