### ISSUE TITLE
[Feature Request]: Add smart suggestion to fast replace {{ $variable }} with {!! $variable !}} and vice versa

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#452]
### Feature Description

Hey there, thanks for creating this absolutely amazing plugin! I haven't even yet discovered every feature, but I really love it. Thanks.

One thing in PhpStorm that I really enjoy is the smart autocompletion or whatever it's called (Alt + Enter) for replacing single quotes with double quotes and vice versa. I really like such simple but helpful commands.

One of the commands I wish I had was the option to replace `{{ $var }}` with `{!! $var !!}` and vice versa. PhpStorm doesn't really handle this well, because when you start changing the first `{{` into `{!!`, it messes everything up by automatically adding a second `!!}` (turning the code into this ugly thing: `{!! !!}$var }}`.

It would be great if you could add support for this small action in Blade files!

**Comment by adelf** [comment]
Nice suggestion. Thanks!

**Comment by ralphjsmit** [comment]
Thank you Adel! Appreciate it that you're so actively listening to feedback and implementing many new things👍

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1463128035792666624 )

**Comment by ralphjsmit** [comment]
Wow that's fast, amazing! You're doing a great job with the fast support👌 Not many companies will do this better👍
