### ISSUE TITLE
[Bug]: Facade 

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#455]
### Bug description

Hi @adelf 

when laravel idea generates _ide_helper_facades.php for a composer package it seems to mark a method that return self/static or the class name as returning `void`

![image](https://user-images.githubusercontent.com/8792274/143461467-35543b49-83d0-4c18-81f6-92fab6caa935.png)

in this case `\DefStudio\Telegraph\Telegraph::html` is returning a ·`Telegraph` instance: 

![image](https://user-images.githubusercontent.com/8792274/143461577-533afbe3-9da9-497e-adf1-3bf1fa262b64.png)

it is well autocompleted and it states the right return type:

![image](https://user-images.githubusercontent.com/8792274/143462812-ff6a7a81-bde2-4df9-8d2f-197e70e9f1a2.png)

but then it is interpreted as returning `void`

![image](https://user-images.githubusercontent.com/8792274/143463013-1d91e01c-2919-407b-bb66-df082a519cfa.png)

![image](https://user-images.githubusercontent.com/8792274/143463081-55d27db3-3165-495c-9f72-12b41ecaf195.png)

The Facade is loaded by Laravel and works as normal, it is jus an issue for autocompletion and inspections

any idea of what could be the cause for this behaviour?

### Plugin version

4.4.0.212

### Operating system

Linux

### Steps to reproduce

Just download this package

[https://github.com/def-studio/telegraph](https://github.com/def-studio/telegraph)

generate helper code:

![image](https://user-images.githubusercontent.com/8792274/143463692-ec5683bd-2afb-470e-912c-b244800be63d.png)

![image](https://user-images.githubusercontent.com/8792274/143463818-e665f8d7-cf9a-4b7b-a6c6-1605dd77edc3.png)

and try to use its facade:

```php
use Telegraph;

Telegraph::html('test')->send();
```

**Comment by adelf** [comment]
Fixed. Thanks.
