### ISSUE TITLE
[Feature Request]: Disable fully qualified namespace inspection on config files

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#458]
### Feature Description

Laravel has the convention of when using classes in config files, they should be FQCN's without imports. 

However PHPStorm by default tries to import the class instead. 
![image](https://user-images.githubusercontent.com/5870441/144236124-a7b780bd-bcb0-41c7-af0d-8a50b955c447.png)

A simple fix for this would be to disable the import class inspection when in config file repositories 👍

**Comment by adelf** [comment]
Nice! Done. Thanks!
