### ISSUE TITLE
Route action name completion

### ISSUE THREAD

**Issue by Insperio** [laravel-idea/plugin#46]
I have a pretty weird error with one of my projects. 
When I add new route and start typing route action (class name), the hints pop-up shows as usual but all my controllers are missing from the list. The search just ignores them somehow.
Everything else works correctly. I tried adjusting project path etc. but it didn't help. Any ideas ? 

I'm running laravel 6 with Twill CMS if that helps. 

Thanks

**Comment by adelf** [comment]
Hi. **Laravel Idea** tries to analyze RouteServiceProvider's and understand about every route file: which is it's root namespace and route names prefix. But if it can't understand it - all completion in this file won't work. If you have complicated routing you can just help **Laravel Idea** with special phpDocs in the beginning of the route file. For example:
```
<?php
/**
 * @routeNamespace("App\Http\Controllers\Api")
 * @routePrefix("api")
 */
```

**Comment by Insperio** [comment]
Thanks for the reply. 

Both RouteServiceProvider and my route files are pretty simple, nothing unusual in there. I tried clearing both files and added some test routes but no success. 
Admin routes (twill related) are added in separate route file. I tried clearing that as well but still the same problem.

Is there anything else I could check ? 
It's not a big problem for me so if it's too "case specific" I don't mind you closing this :)

I tried the phpdocs you provided (adjusted to my needs) but it made no difference. 

Anyway, thanks for the help !

**Comment by adelf** [comment]
Strange. Comments should help. Maybe your route files aren't in the 'routes' directory?

**Comment by Insperio** [comment]
The only routes files I use are: routes/admin.php and routes/web.php. I removed other files. 
It's a pretty standard setup.

Could it be caused by Twill adding new route macro? In admin routes I have:
`Route::module('pages');`

I tried removing this from admin routes file but no success so not sure...

**Comment by adelf** [comment]
The last suggestion: Controller base class setting in Languages & frameworks > PHP > Laravel Idea. It searches controllers only based on this class

**Comment by Insperio** [comment]
That seems to be correct. All of my controllers extend App\Http\Controllers\Controller. 

I'll create new project with same cms and see if the problem exists there as well. Let you know if I figure something out. Thanks for the help !

**Comment by adelf** [comment]
Thank you. I'll check a project with this CMS.

**Comment by adelf** [comment]
Twill CMS has super magical route configuration, so I can't automatically fetch it. Current workaround: make phpDocs, like:

```
<?php
/**
 * @routeNamespace("App\Http\Controllers\Api")
 * @routePrefix("api")
 */
```

and run route methods optimization: main menu > Code > Laravel Idea Code Generation > Optimize Route Completion. This will remove trash completions from route functions.
