### ISSUE TITLE
[Bug]: Code > Laravel Idea Code Generator menu option is not visible

### ISSUE THREAD

**Issue by jannejava** [laravel-idea/plugin#462]
### Bug description

The "Laravel Idea Code Generation" menu option is gone. I have tried reinstalling the plugin, but it's missing in PHPStorm2021.3. The menu short cut does not work either, and I cannot find a conflicting shortcut. 

However, the blade and routing hints works and I can see Laravel Idea in the preferences.

Any ideas?

![CleanShot 2021-12-08 at 08 25 18@2x](https://user-images.githubusercontent.com/543616/145167059-3d2107b6-6831-48de-bfd3-2dc97ec3da15.png)

### Plugin version

4.4.5.213

### Operating system

MacOS

**Comment by adelf** [comment]
Check Laravel menu item right after Code) Sorry, I haven’t updated docs yet.

**Comment by jannejava** [comment]
Doh!! How could I miss the Laravel menu next to it. ;-)

If you also add the shortcut for macOS in the docs - Shift-⌘(=command)-Comma - I would probably found it too. 

Thanks for a great product! 👍
