### ISSUE TITLE
[Feature Request]: Custom methods for inertia components

### ISSUE THREAD

**Issue by stubbo** [laravel-idea/plugin#463]
### Feature Description

I have noticed I can use `ide.json` to add auto-completion for custom view functions - however, I can't find a way to do the same with inertia components.

**Comment by adelf** [comment]
We have this in our roadmap. It probably will be implemented in the 5.0 release which is planned for January 2022.

**Comment by adelf** [comment]
Laravel Idea 5.0 is out. It is available there. Documentation isn't ready yet. But you can try this ide.json:
```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "inertiaPage",
            "condition": [
                {
                    "classFqn": ["Your\\Class\\Name"],
                    "methods": ["page"],
                    "parameters": [1]
                }
            ]
        }
    ]
}
```

And Inertia pages will be completed for the `page` method first parameter for provided classes.

**Comment by stubbo** [comment]
amazing, thank you
