### ISSUE TITLE
[Bug]: Missing query builder completions in large projects using laravel-mysql-spatial

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#465]
### Bug description

After running "Generate Eloquent Helper Code" PhpStorm can autocomplete query builder methods for local scopes defined in the model, but it stops recognizing native query builder methods.
```php
MyModel::customScope()->anotherCustomScope(); // Completion works when chaining custom scopes
MyModel::customScope1()->get(); // But after calling a custom scope, PhpStorm doesn't recognize methods like where() or get()
```
PhpStorm is aware that the scope method returns an `_IH_MyModel_QB` instance, but it doesn't recognize methods from its parent `_BaseBuilder` class.

Workaround:
Uninstall the `grimzy/laravel-mysql-spatial` composer package and run "Generate Eloquent Helper Code" again. Then everything works as expected.

Suspected causes:
The [laravel-mysql-spatial](https://github.com/grimzy/laravel-mysql-spatial) package replaces the default Eloquent query builder with a [custom child class](https://github.com/grimzy/laravel-mysql-spatial/blob/master/src/Eloquent/Builder.php).
I've investigated the differences in `_ide_helper_model_builders.php`, and the main difference is that with the package installed, an extra `namespace LaravelIdea\Helper {...}` block is included, with this content:
<details>
<summary>Click to show</summary>

    namespace LaravelIdea\Helper {
  
      use Grimzy\LaravelMysqlSpatial\Eloquent\Builder;
      
      /**
     * @method \GeometryModel|$this shift(int $count = 1)
     * @method \GeometryModel|null firstOrFail($key = null, $operator = null, $value = null)
     * @method \GeometryModel|$this pop(int $count = 1)
     * @method \GeometryModel|null pull($key, $default = null)
     * @method \GeometryModel|null last(callable $callback = null, $default = null)
     * @method \GeometryModel|null sole($key = null, $operator = null, $value = null)
     * @method \GeometryModel|null get($key, $default = null)
     * @method \GeometryModel|null first(callable $callback = null, $default = null)
     * @method \GeometryModel|null firstWhere(string $key, $operator = null, $value = null)
     * @method \GeometryModel|null find($key, $default = null)
     * @method \GeometryModel[] all()
     * @property-read _IH_GeometryModel_CP $keyBy
     * @property-read _IH_GeometryModel_CP $partition
     * @property-read _IH_GeometryModel_CP $max
     * @property-read _IH_GeometryModel_CP $flatMap
     * @property-read _IH_GeometryModel_CP $each
     * @property-read _IH_GeometryModel_CP $map
     * @property-read _IH_GeometryModel_CP $filter
     * @property-read _IH_GeometryModel_CP $unique
     * @property-read _IH_GeometryModel_CP $groupBy
     * @property-read _IH_GeometryModel_CP $sortBy
     * @property-read _IH_GeometryModel_CP $contains
     * @property-read _IH_GeometryModel_CP $sum
     * @property-read _IH_GeometryModel_CP $until
     * @property-read _IH_GeometryModel_CP $every
     * @property-read _IH_GeometryModel_CP $average
     * @property-read _IH_GeometryModel_CP $some
     * @property-read _IH_GeometryModel_CP $skipWhile
     * @property-read _IH_GeometryModel_CP $sortByDesc
     * @property-read _IH_GeometryModel_CP $takeUntil
     * @property-read _IH_GeometryModel_CP $avg
     * @property-read _IH_GeometryModel_CP $skipUntil
     * @property-read _IH_GeometryModel_CP $first
     * @property-read _IH_GeometryModel_CP $takeWhile
     * @property-read _IH_GeometryModel_CP $min
     * @property-read _IH_GeometryModel_CP $reject
     */
    class _IH_GeometryModel_C extends _BaseCollection {
        /**
         * @param int $size
         * @return \GeometryModel[][]
         */
        public function chunk($size)
        {
            return [];
        }
    }
    
    /**
     * @method _IH_GeometryModel_QB comparison($geometryColumn, $geometry, $relationship)
     * @method _IH_GeometryModel_QB contains($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB crosses($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB disjoint($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB distance($geometryColumn, $geometry, $distance)
     * @method _IH_GeometryModel_QB distanceExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_GeometryModel_QB distanceSphere($geometryColumn, $geometry, $distance)
     * @method _IH_GeometryModel_QB distanceSphereExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_GeometryModel_QB distanceSphereValue($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB distanceValue($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB doesTouch($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB equals($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB intersects($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB orderByDistance($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_GeometryModel_QB orderByDistanceSphere($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_GeometryModel_QB orderBySpatial($geometryColumn, $geometry, $orderFunction, $direction = 'asc')
     * @method _IH_GeometryModel_QB overlaps($geometryColumn, $geometry)
     * @method _IH_GeometryModel_QB within($geometryColumn, $polygon)
     * @mixin Builder
     */
    class _IH_GeometryModel_QB extends _BaseBuilder {}
    
    /**
     * @method \NoSpatialFieldsModel|$this shift(int $count = 1)
     * @method \NoSpatialFieldsModel|null firstOrFail($key = null, $operator = null, $value = null)
     * @method \NoSpatialFieldsModel|$this pop(int $count = 1)
     * @method \NoSpatialFieldsModel|null pull($key, $default = null)
     * @method \NoSpatialFieldsModel|null last(callable $callback = null, $default = null)
     * @method \NoSpatialFieldsModel|null sole($key = null, $operator = null, $value = null)
     * @method \NoSpatialFieldsModel|null get($key, $default = null)
     * @method \NoSpatialFieldsModel|null first(callable $callback = null, $default = null)
     * @method \NoSpatialFieldsModel|null firstWhere(string $key, $operator = null, $value = null)
     * @method \NoSpatialFieldsModel|null find($key, $default = null)
     * @method \NoSpatialFieldsModel[] all()
     * @property-read _IH_NoSpatialFieldsModel_CP $keyBy
     * @property-read _IH_NoSpatialFieldsModel_CP $partition
     * @property-read _IH_NoSpatialFieldsModel_CP $max
     * @property-read _IH_NoSpatialFieldsModel_CP $flatMap
     * @property-read _IH_NoSpatialFieldsModel_CP $each
     * @property-read _IH_NoSpatialFieldsModel_CP $map
     * @property-read _IH_NoSpatialFieldsModel_CP $filter
     * @property-read _IH_NoSpatialFieldsModel_CP $unique
     * @property-read _IH_NoSpatialFieldsModel_CP $groupBy
     * @property-read _IH_NoSpatialFieldsModel_CP $sortBy
     * @property-read _IH_NoSpatialFieldsModel_CP $contains
     * @property-read _IH_NoSpatialFieldsModel_CP $sum
     * @property-read _IH_NoSpatialFieldsModel_CP $until
     * @property-read _IH_NoSpatialFieldsModel_CP $every
     * @property-read _IH_NoSpatialFieldsModel_CP $average
     * @property-read _IH_NoSpatialFieldsModel_CP $some
     * @property-read _IH_NoSpatialFieldsModel_CP $skipWhile
     * @property-read _IH_NoSpatialFieldsModel_CP $sortByDesc
     * @property-read _IH_NoSpatialFieldsModel_CP $takeUntil
     * @property-read _IH_NoSpatialFieldsModel_CP $avg
     * @property-read _IH_NoSpatialFieldsModel_CP $skipUntil
     * @property-read _IH_NoSpatialFieldsModel_CP $first
     * @property-read _IH_NoSpatialFieldsModel_CP $takeWhile
     * @property-read _IH_NoSpatialFieldsModel_CP $min
     * @property-read _IH_NoSpatialFieldsModel_CP $reject
     */
    class _IH_NoSpatialFieldsModel_C extends _BaseCollection {
        /**
         * @param int $size
         * @return \NoSpatialFieldsModel[][]
         */
        public function chunk($size)
        {
            return [];
        }
    }
    
    /**
     * @method _IH_NoSpatialFieldsModel_QB comparison($geometryColumn, $geometry, $relationship)
     * @method _IH_NoSpatialFieldsModel_QB contains($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB crosses($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB disjoint($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB distance($geometryColumn, $geometry, $distance)
     * @method _IH_NoSpatialFieldsModel_QB distanceExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_NoSpatialFieldsModel_QB distanceSphere($geometryColumn, $geometry, $distance)
     * @method _IH_NoSpatialFieldsModel_QB distanceSphereExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_NoSpatialFieldsModel_QB distanceSphereValue($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB distanceValue($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB doesTouch($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB equals($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB intersects($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB orderByDistance($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_NoSpatialFieldsModel_QB orderByDistanceSphere($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_NoSpatialFieldsModel_QB orderBySpatial($geometryColumn, $geometry, $orderFunction, $direction = 'asc')
     * @method _IH_NoSpatialFieldsModel_QB overlaps($geometryColumn, $geometry)
     * @method _IH_NoSpatialFieldsModel_QB within($geometryColumn, $polygon)
     * @mixin Builder
     */
    class _IH_NoSpatialFieldsModel_QB extends _BaseBuilder {}
    
    /**
     * @method \TestModel|$this shift(int $count = 1)
     * @method \TestModel|null firstOrFail($key = null, $operator = null, $value = null)
     * @method \TestModel|$this pop(int $count = 1)
     * @method \TestModel|null pull($key, $default = null)
     * @method \TestModel|null last(callable $callback = null, $default = null)
     * @method \TestModel|null sole($key = null, $operator = null, $value = null)
     * @method \TestModel|null get($key, $default = null)
     * @method \TestModel|null first(callable $callback = null, $default = null)
     * @method \TestModel|null firstWhere(string $key, $operator = null, $value = null)
     * @method \TestModel|null find($key, $default = null)
     * @method \TestModel[] all()
     * @property-read _IH_TestModel_CP $keyBy
     * @property-read _IH_TestModel_CP $partition
     * @property-read _IH_TestModel_CP $max
     * @property-read _IH_TestModel_CP $flatMap
     * @property-read _IH_TestModel_CP $each
     * @property-read _IH_TestModel_CP $map
     * @property-read _IH_TestModel_CP $filter
     * @property-read _IH_TestModel_CP $unique
     * @property-read _IH_TestModel_CP $groupBy
     * @property-read _IH_TestModel_CP $sortBy
     * @property-read _IH_TestModel_CP $contains
     * @property-read _IH_TestModel_CP $sum
     * @property-read _IH_TestModel_CP $until
     * @property-read _IH_TestModel_CP $every
     * @property-read _IH_TestModel_CP $average
     * @property-read _IH_TestModel_CP $some
     * @property-read _IH_TestModel_CP $skipWhile
     * @property-read _IH_TestModel_CP $sortByDesc
     * @property-read _IH_TestModel_CP $takeUntil
     * @property-read _IH_TestModel_CP $avg
     * @property-read _IH_TestModel_CP $skipUntil
     * @property-read _IH_TestModel_CP $first
     * @property-read _IH_TestModel_CP $takeWhile
     * @property-read _IH_TestModel_CP $min
     * @property-read _IH_TestModel_CP $reject
     */
    class _IH_TestModel_C extends _BaseCollection {
        /**
         * @param int $size
         * @return \TestModel[][]
         */
        public function chunk($size)
        {
            return [];
        }
    }
    
    class _IH_TestModel_QB extends _BaseBuilder {}
    
    /**
     * @method \TestNoSpatialModel|$this shift(int $count = 1)
     * @method \TestNoSpatialModel|null firstOrFail($key = null, $operator = null, $value = null)
     * @method \TestNoSpatialModel|$this pop(int $count = 1)
     * @method \TestNoSpatialModel|null pull($key, $default = null)
     * @method \TestNoSpatialModel|null last(callable $callback = null, $default = null)
     * @method \TestNoSpatialModel|null sole($key = null, $operator = null, $value = null)
     * @method \TestNoSpatialModel|null get($key, $default = null)
     * @method \TestNoSpatialModel|null first(callable $callback = null, $default = null)
     * @method \TestNoSpatialModel|null firstWhere(string $key, $operator = null, $value = null)
     * @method \TestNoSpatialModel|null find($key, $default = null)
     * @method \TestNoSpatialModel[] all()
     * @property-read _IH_TestNoSpatialModel_CP $keyBy
     * @property-read _IH_TestNoSpatialModel_CP $partition
     * @property-read _IH_TestNoSpatialModel_CP $max
     * @property-read _IH_TestNoSpatialModel_CP $flatMap
     * @property-read _IH_TestNoSpatialModel_CP $each
     * @property-read _IH_TestNoSpatialModel_CP $map
     * @property-read _IH_TestNoSpatialModel_CP $filter
     * @property-read _IH_TestNoSpatialModel_CP $unique
     * @property-read _IH_TestNoSpatialModel_CP $groupBy
     * @property-read _IH_TestNoSpatialModel_CP $sortBy
     * @property-read _IH_TestNoSpatialModel_CP $contains
     * @property-read _IH_TestNoSpatialModel_CP $sum
     * @property-read _IH_TestNoSpatialModel_CP $until
     * @property-read _IH_TestNoSpatialModel_CP $every
     * @property-read _IH_TestNoSpatialModel_CP $average
     * @property-read _IH_TestNoSpatialModel_CP $some
     * @property-read _IH_TestNoSpatialModel_CP $skipWhile
     * @property-read _IH_TestNoSpatialModel_CP $sortByDesc
     * @property-read _IH_TestNoSpatialModel_CP $takeUntil
     * @property-read _IH_TestNoSpatialModel_CP $avg
     * @property-read _IH_TestNoSpatialModel_CP $skipUntil
     * @property-read _IH_TestNoSpatialModel_CP $first
     * @property-read _IH_TestNoSpatialModel_CP $takeWhile
     * @property-read _IH_TestNoSpatialModel_CP $min
     * @property-read _IH_TestNoSpatialModel_CP $reject
     */
    class _IH_TestNoSpatialModel_C extends _BaseCollection {
        /**
         * @param int $size
         * @return \TestNoSpatialModel[][]
         */
        public function chunk($size)
        {
            return [];
        }
    }
    
    /**
     * @method _IH_TestNoSpatialModel_QB comparison($geometryColumn, $geometry, $relationship)
     * @method _IH_TestNoSpatialModel_QB contains($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB crosses($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB disjoint($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB distance($geometryColumn, $geometry, $distance)
     * @method _IH_TestNoSpatialModel_QB distanceExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_TestNoSpatialModel_QB distanceSphere($geometryColumn, $geometry, $distance)
     * @method _IH_TestNoSpatialModel_QB distanceSphereExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_TestNoSpatialModel_QB distanceSphereValue($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB distanceValue($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB doesTouch($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB equals($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB intersects($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB orderByDistance($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_TestNoSpatialModel_QB orderByDistanceSphere($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_TestNoSpatialModel_QB orderBySpatial($geometryColumn, $geometry, $orderFunction, $direction = 'asc')
     * @method _IH_TestNoSpatialModel_QB overlaps($geometryColumn, $geometry)
     * @method _IH_TestNoSpatialModel_QB within($geometryColumn, $polygon)
     * @mixin Builder
     */
    class _IH_TestNoSpatialModel_QB extends _BaseBuilder {}
    
    /**
     * @method \TestRelatedModel|$this shift(int $count = 1)
     * @method \TestRelatedModel|null firstOrFail($key = null, $operator = null, $value = null)
     * @method \TestRelatedModel|$this pop(int $count = 1)
     * @method \TestRelatedModel|null pull($key, $default = null)
     * @method \TestRelatedModel|null last(callable $callback = null, $default = null)
     * @method \TestRelatedModel|null sole($key = null, $operator = null, $value = null)
     * @method \TestRelatedModel|null get($key, $default = null)
     * @method \TestRelatedModel|null first(callable $callback = null, $default = null)
     * @method \TestRelatedModel|null firstWhere(string $key, $operator = null, $value = null)
     * @method \TestRelatedModel|null find($key, $default = null)
     * @method \TestRelatedModel[] all()
     * @property-read _IH_TestRelatedModel_CP $keyBy
     * @property-read _IH_TestRelatedModel_CP $partition
     * @property-read _IH_TestRelatedModel_CP $max
     * @property-read _IH_TestRelatedModel_CP $flatMap
     * @property-read _IH_TestRelatedModel_CP $each
     * @property-read _IH_TestRelatedModel_CP $map
     * @property-read _IH_TestRelatedModel_CP $filter
     * @property-read _IH_TestRelatedModel_CP $unique
     * @property-read _IH_TestRelatedModel_CP $groupBy
     * @property-read _IH_TestRelatedModel_CP $sortBy
     * @property-read _IH_TestRelatedModel_CP $contains
     * @property-read _IH_TestRelatedModel_CP $sum
     * @property-read _IH_TestRelatedModel_CP $until
     * @property-read _IH_TestRelatedModel_CP $every
     * @property-read _IH_TestRelatedModel_CP $average
     * @property-read _IH_TestRelatedModel_CP $some
     * @property-read _IH_TestRelatedModel_CP $skipWhile
     * @property-read _IH_TestRelatedModel_CP $sortByDesc
     * @property-read _IH_TestRelatedModel_CP $takeUntil
     * @property-read _IH_TestRelatedModel_CP $avg
     * @property-read _IH_TestRelatedModel_CP $skipUntil
     * @property-read _IH_TestRelatedModel_CP $first
     * @property-read _IH_TestRelatedModel_CP $takeWhile
     * @property-read _IH_TestRelatedModel_CP $min
     * @property-read _IH_TestRelatedModel_CP $reject
     */
    class _IH_TestRelatedModel_C extends _BaseCollection {
        /**
         * @param int $size
         * @return \TestRelatedModel[][]
         */
        public function chunk($size)
        {
            return [];
        }
    }
    
    /**
     * @method _IH_TestRelatedModel_QB comparison($geometryColumn, $geometry, $relationship)
     * @method _IH_TestRelatedModel_QB contains($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB crosses($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB disjoint($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB distance($geometryColumn, $geometry, $distance)
     * @method _IH_TestRelatedModel_QB distanceExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_TestRelatedModel_QB distanceSphere($geometryColumn, $geometry, $distance)
     * @method _IH_TestRelatedModel_QB distanceSphereExcludingSelf($geometryColumn, $geometry, $distance)
     * @method _IH_TestRelatedModel_QB distanceSphereValue($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB distanceValue($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB doesTouch($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB equals($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB intersects($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB orderByDistance($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_TestRelatedModel_QB orderByDistanceSphere($geometryColumn, $geometry, $direction = 'asc')
     * @method _IH_TestRelatedModel_QB orderBySpatial($geometryColumn, $geometry, $orderFunction, $direction = 'asc')
     * @method _IH_TestRelatedModel_QB overlaps($geometryColumn, $geometry)
     * @method _IH_TestRelatedModel_QB within($geometryColumn, $polygon)
     * @mixin Builder
     */
    class _IH_TestRelatedModel_QB extends _BaseBuilder {}
    }

</details>

Removing this block fixes the problem. The models in this block are not from the project. They are from the [tests folder](https://github.com/grimzy/laravel-mysql-spatial/tree/master/tests) in laravel-mysql-spatial.

This seems to be a weird edge case that's hard to reproduce. It happens consistently in a huge project (458 models) i work on, but I can't reproduce it in a fresh project. I'll be happy to help investigating the issue further.

### Plugin version

4.4.5.213

### Operating system

Windows

### Steps to reproduce

1. Have a giant Laravel 8 project with 458 models.
2. Install laravel-mysql-spatial: `composer require grimzy/laravel-mysql-spatial`
3. Run `Generate Eloquent Helper Code` (include collection proxies and _count properties)
4. Write a query including a local scope, and see if PhpStorm can complete `->get()` on the query.

See the bug description for further details.

**Comment by adelf** [comment]
Hi, Morten. Thanks for so detailed report! I’ll try to fix that.

**Comment by mortenscheel** [comment]
Cool. Let me know if I can be of assistance. Like I said, it's not easy to reproduce.

I just discovered something interesting. The issue disappears if I disable all inspections.
I don't think it's a memory issue. I've allocated 8GB and according to the memory indicator it never uses more than 1.5 GB.
But the vendor folder contains a whopping 208MB of code (_laravel_idea weighs in at 4.3MB). Maybe PhpStorm just can't handle that amount of code with intellisense?
But that doesn't really explain why uninstalling laravel-mysql-spatial fixes the issue.

**Comment by adelf** [comment]
I was searching a comment and it was yours! https://github.com/laravel-idea/plugin/issues/284#issuecomment-872221711
Could you try this?
I’m working on reducing this file...

**Comment by mortenscheel** [comment]
If you mean `idea.max.intellisense.filesize=10000` then I already have that set.

As a temporary workaround I'll just delete the offending namespace block when necessary:
```bash
FILE='vendor/_laravel_idea/_ide_helper_model_builders.php'; [[ $(grep 'namespace LaravelIdea\\Helper {' "$FILE" | wc -l) == '2' ]] && sed -i "6,480d" "$FILE"
```

**Comment by adelf** [comment]
I separated helper files using namespaces... so if you don't have hundreds models in the same namespace issue should disappear. I think I can close this.
