### ISSUE TITLE
[Feature Request]: Eliminate the need to install laravel-ide-helper

### ISSUE THREAD

**Issue by byGits** [laravel-idea/plugin#466]
### Feature Description

Hello,

Is it possible to do this?

For example most of eloquent Builder and Model methods are not recognized unless we install laravel-ide-helper or use mixin in all models along with some other issues.

Can we expect Laravel Idea to not require laravel-ide-helper and still fix these?

**Comment by adelf** [comment]
Hi. Have you tried to Generate Eloquent Helper code by Laravel Idea?
The latest version(4.4.5): in the main menu - Laravel - Generate Eloquent Helper Code

**Comment by byGits** [comment]
> Hi. Have you tried to Generate Eloquent Helper code by Laravel Idea? The latest version(4.4.5): in the main menu - Laravel - Generate Eloquent Helper Code

Wow thank you and sorry for my ignorance I should've read the docs completely before posting this here.

It worked perfectly but I got some warnings about factory classes:
`Factory class not found for \App\Models\ModelName`

Is it safe to ignore these if we don't have factory classes?

**Comment by adelf** [comment]
It's safe. Probably, this model has the `hasFactory` method, but there is no corresponding Factory class

**Comment by byGits** [comment]
> It's safe. Probably, this model has the `hasFactory` method, but there is no corresponding Factory class

Thank you very much!
