### ISSUE TITLE
Is there a place for the latest compatable version?

### ISSUE THREAD

**Issue by shoemoney** [laravel-idea/plugin#47]
Sorry if this is listed but I just updated my phpstorm and it says that 2.4.1.192 is incompatable with the current version.

I am a paying user and I just want to say thank you !!    Without this plugin not sure I would stick with php storm!!

**Comment by adelf** [comment]
Hi, Jeremy.

There is a 2.4.1.201 version which should be ok.
https://plugins.jetbrains.com/plugin/13441-laravel-idea/versions

**Comment by shoemoney** [comment]
weird 

![Screen Shot 2020-04-25 at 11 42 29 PM](https://user-images.githubusercontent.com/444294/80298126-dc36d000-874e-11ea-900f-26ea9733abec.png)

**Comment by shoemoney** [comment]
Err sorry I see that is a older one.  I will manually install.

**Comment by shoemoney** [comment]
All is well thanks brother!
