### ISSUE TITLE
[Bug]: Route not listed in autocompletion select if declared with the Inertia macro

### ISSUE THREAD

**Issue by maicol07** [laravel-idea/plugin#470]
### Bug description

When I define a route using the Inertia macro, the route isn't listed when autocompleting a route name and I can't click on its name to go to the definition

### Plugin version

4.4.5.213

### Operating system

Windows

### Steps to reproduce

1. Create a named route with inertia macro i.e. `Route::inertia('example', 'ExamplePage')->name('example')`
2. Try to write `route('example')`: there is no autocompletion for the route `example` and I can't click on it to go to the route definition

**Comment by adelf** [comment]
Hi, Maicol. Fixed. Thanks!
