### ISSUE TITLE
[Bug]: Laravel Idea not running

### ISSUE THREAD

**Issue by VadimBesedin** [laravel-idea/plugin#471]
### Bug description

Plugin is purchased and enabled, but missing in Code menu, and not running after pressing CTRL+Shift+,

### Plugin version

4.4.5.213

### Operating system

Windows

### Steps to reproduce

![image](https://user-images.githubusercontent.com/43794421/146337331-3b153560-0837-4be5-8cf7-c58425ab044f.png)
PhpStorm 2021.3, build PS-213.5744.279

**Comment by adelf** [comment]
Hi, Vadim. We moved all Laravel Idea items to own “Laravel” main menu item, but as I see there is no such item also. Did you have issues with plugin incompatibility after updating PhpStorm? Could you share Settings window with Laravel Idea settings?

**Comment by VadimBesedin** [comment]
Hi Adelf, you right it should be in Laravel menu, and it is in one of the open PHP Storm windows. But in second window it's missing. Please see attached screen. Possibly the second Laravel project is corrupt or missing something...
![2021-12-17 - 19-56-34 - phpstorm64](https://user-images.githubusercontent.com/43794421/146587810-b2abcf35-cd15-4d5b-8e9d-2bd4aed9f821.png)
.

**Comment by adelf** [comment]
As you see: “Current state: Disabled”. Laravel Idea couldn’t find any Laravel related packages in composer.json and disabled itself. Do you have laravel installed in this project?
