### ISSUE TITLE
[Bug]: Creating a Resource with a number in the name wont append the "Resource" at the file name.

### ISSUE THREAD

**Issue by K2ouMais** [laravel-idea/plugin#472]
### Bug description

Hello there,

If you want to create a Json Resource and name it "Test", it will save a file named "TestResource.php".

But if you name your Resource "Test1", it will name it "Test1.php", without appending the "Resource" to the name.

Thank you

### Plugin version

4.4.5.213

### Operating system

Windows

### Steps to reproduce

Just try to create a JSON Resource with a number in the name.

**Comment by adelf** [comment]
Fixed. Thanks.
