### ISSUE TITLE
[Bug]: LaravelIdea\Helper\App\Models\_IH_User_QB time two

### ISSUE THREAD

**Issue by yonchando** [laravel-idea/plugin#475]
### Bug description

When use Eloquent Helper code generate, It delcare `use LaravelIdea\Helper\App\Models\_IH_User_QB` two time.

### Plugin version

4.4.5.212

### Operating system

Windows

**Comment by adelf** [comment]
Could you share where it happens?

**Comment by yonchando** [comment]
Anytime I use Eloquent Helper Code Generate from menu Laravel in phpstorm.

[image: image.png]

**Comment by adelf** [comment]
I mean which file? Could you share this file?

**Comment by yonchando** [comment]
It in vendor/_laravel_idea/_idea_helper_models.php.
