### ISSUE TITLE
[Feature Request]: Discover index components in Livewire subfolders / Anonymous Livewire Index Components

### ISSUE THREAD

**Issue by bomshteyn** [laravel-idea/plugin#479]
### Feature Description

The Laravel Idea, correctly discovers [Anonymous Index Components](https://laravel.com/docs/8.x/blade#anonymous-index-components)

But a similarly structured Livewire components are not discovered correctly by the plugin. 

This feature was added to Livewire back in November: [pr](https://github.com/livewire/livewire/pull/4203)

**Comment by adelf** [comment]
Laravel Idea 5.0 with the fix is out. Thank you for posting.
