### ISSUE TITLE
When you enter a validation rule for an array, a colon is inserted

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#48]
Is this the right behavior or not?

There is no colon information in the documentation and code ([this](https://laravel.com/docs/7.x/validation#rule-array) and [this](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L323)).

![2020-04-25_22-58-59](https://user-images.githubusercontent.com/10347617/80289639-7e9f8500-8748-11ea-9c0f-042c3a59d286.jpg)
![2020-04-25_22-59-14](https://user-images.githubusercontent.com/10347617/80289638-7d6e5800-8748-11ea-9eda-471f76be9f0e.jpg)

**Comment by adelf** [comment]
`$parameters` :) But yes, at least I'll remove it for parameters with default values. Thank you.

**Comment by adelf** [comment]
fixed in 3.0 version. please check and comment if there are some issues.

**Comment by andrey-helldar** [comment]
Nice ☺

![2020-05-19_17-04-58](https://user-images.githubusercontent.com/10347617/82336146-e1f0a000-99f2-11ea-9375-f8c18eef8e93.jpg)
