### ISSUE TITLE
[Feature Request]: Full support of Macro Indexing (and Autocompletion)

### ISSUE THREAD

**Issue by handhikadj** [laravel-idea/plugin#480]
### Feature Description

This doesn't work for the moment

AppServiceProvider.php
```php
Builder::macro('someMacro', function ($what) {
   // Some code...
});
```

in Controller or somewhere
```php
User::someMacro('this value')->get();
```

the `someMacro()` doesn't appear on autocomplete suggestions

**Comment by adelf** [comment]
You can generate a helper code to add a completion... main menu - Laravel - Code Generation - Generate Helper Code. 
But there are issues with types.. `User::someMacro()->get()[0]` wont be `User`. I'll try to fix that.

**Comment by handhikadj** [comment]
didn't realize the features exists. thanks.

**Comment by adelf** [comment]
Laravel Idea 5.0 is out.
