### ISSUE TITLE
[Feature Request]: Highlight form request attributes

### ISSUE THREAD

**Issue by leandro-hermes** [laravel-idea/plugin#482]
### Feature Description

Today, the plugin already suggests the attributes and enable navigation for the form request's attributes accessed via magic method. It would be great if they were also highlighted in the editor, so, the developers could easily identify (pre)existing mistakes.

Suggestion:
![image](https://user-images.githubusercontent.com/13833942/147955409-3dc7ef74-292a-4898-ad0e-56d126d04c48.png)

Highlight missing:
![image](https://user-images.githubusercontent.com/13833942/147955440-29326459-b0c3-4fcb-8dbb-04334d791afd.png)

**Comment by adelf** [comment]
Fixed in 8.0.2. Thank you.
