### ISSUE TITLE
[Feature Request]: Mark routes and commands in symbol search as non-project

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#483]
### Feature Description

When searching for horizon all routes and commands related to horizon is shown which is awesome, however they are not shown the same way other non-project results are. 

Could we add the same background color to routes and commands from the vendor folder as files has from the vendor folder?

![image](https://user-images.githubusercontent.com/5870441/148213973-5fad175f-aab7-4be3-ab9a-a63e6a6c03f7.png)

**Comment by adelf** [comment]
Fixed in 8.0.2. Thank you.
