### ISSUE TITLE
[Feature Request]: Good practice for Localization

### ISSUE THREAD

**Issue by freeentr** [laravel-idea/plugin#485]
### Feature Description

Key generation for one language is very handy. But aim of Localization is to have more than one language file. Would be nice to set languages like "en,fr" and create two language files.

And another one.. Why not to allow spaces and other symbols in keys?

Thank you,
JT

**Comment by adelf** [comment]
Hi.

> And another one.. Why not to allow spaces and other symbols in keys?
I added " " and "-" to the allowed symbols.

I'm going to manage the translations other way(this might be released as an independent plugin):
https://twitter.com/laravel_idea/status/1425438027174850561

**Comment by adelf** [comment]
Laravel Idea 5.0 is out. "Why not to allow spaces and other symbols in keys?" is fixed there. Thank you.

**Comment by pkeogan** [comment]
@adelf any update on support for more than one language? My current work around is as follows:

If I need to work on language folder `foo`, 
1) rename `en` to `temp`
2) rename `foo` to `en`
3) make language changes
4)  rename `en` to `foo`
5) rename `temp` to `en`

Is there any we could just get a setting to change the Localization default from `en` to whatever we want? or have the plugin look in `.env` for `LOCALE="foo"` and if not present revert to `en`?
