### ISSUE TITLE
[Bug]: Translation generation doesn't allow `-` in key

### ISSUE THREAD

**Issue by jameslkingsley** [laravel-idea/plugin#488]
### Bug description

When generating a translation for some text, it does not allow you to use a dash (`-`) in the key name.

![CleanShot 2022-01-12 at 12 51 32](https://user-images.githubusercontent.com/11015784/149143784-5369cc2d-7de7-4e1f-a678-876bc9c16ae5.png)

### Plugin version

4.4.6.213

### Operating system

MacOS

### Steps to reproduce

1. Create a language file with a dash in the name, such as `foo-bar`
2. Attempt to generate a translation using that name, such as `foo-bar.baz`

**Comment by adelf** [comment]
Thank you, James. Will be fixed.

**Comment by adelf** [comment]
Laravel Idea 5.0 with the fix is out.
