### ISSUE TITLE
[Bug]: Generated translation key doesn't seem to support recursion

### ISSUE THREAD

**Issue by jameslkingsley** [laravel-idea/plugin#489]
### Bug description

When generating a translation using the key `test.create.schedule.later`:

**Expected:**
```php
return [
  'create' => [
    'schedule' => [
      'later' => 'Later',
    ],
  ],
];
```

**Actual:**
```php
return [
  'schedule' => [
    'later' => 'Later',
  ],
];
```

### Plugin version

4.4.6.213

### Operating system

MacOS

### Steps to reproduce

See description

**Comment by adelf** [comment]
Last time I checked, Laravel wasn’t supported deep key names for translations. Does it?

**Comment by jameslkingsley** [comment]
Yeah it supports it. Not sure if it's documented but it works the same as the config keys

**Comment by adelf** [comment]
Fixed. Thanks. I'm going to release a new version next week.

**Comment by jameslkingsley** [comment]
Awesome thank you!

**Comment by adelf** [comment]
Laravel Idea 5.0 is out.
