### ISSUE TITLE
Use laravel 7 stub

### ISSUE THREAD

**Issue by henryavila** [laravel-idea/plugin#49]
Hi. When crating an Class with Larevel idea, would be great to use Laravel 7 stub.
In my case, the model has some customizations that MUST be present in all new Models. The Laravel Stub solves this problem, but Laravel idea don't use this feature

**Comment by adelf** [comment]
Hi, Henry.

Laravel Idea uses internal PhpStorm's templates. You can configure it easily:
![image](https://user-images.githubusercontent.com/2818394/80476535-30120680-8953-11ea-9cb2-d881b3bbab86.png)

**Comment by henryavila** [comment]
Hi @adelf, thanks for replying. 
Indeed this option exist, but I work in different computer/location for the same projects, So every change in the template, I have to do in all computer, and repeat this for every change. 

The Laravel 7 stub allows me to always keep the templates sync. It's a improvement over the Local phpStorm code template.

**Comment by adelf** [comment]
Got it. PhpStorm templates can be saved to git also:

![image](https://user-images.githubusercontent.com/2818394/80483312-89336780-895e-11ea-91a1-bd43fbc63f2b.png)

this will save all your templates in `.idea/fileTemplates` folder. So, maybe it helps...

**Comment by henryavila** [comment]
Good to know. Thanks @adelf

**Comment by adiletmaks** [comment]
Hi, thank you for code templates, but I bet, it would be cool using stubs, or can you use stub as default template ?

Also, I wanted to ask can I make:model with migration, perfectly I want, ui code generation and make:model command were same.

**Comment by adelf** [comment]
I can't start to use Laravel 7 stubs. I need a more powerful template language. At least for #if operation, like here:

![image](https://user-images.githubusercontent.com/2818394/87317973-5f86e700-c530-11ea-829e-3b7981d61d82.png)

> Also, I wanted to ask can I make:model with migration

Yes. This request is popular. It will be implemented soon.
