### ISSUE TITLE
[Feature Request]: Autocomplete for $router variable in route files

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#492]
### Feature Description

Laravel injects a variable called `$router` into the route files automatically, however the plugin is not able to find this variable and autocomplete for it.

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/RouteFileRegistrar.php#L31-L36

**Comment by olivernybroe** [comment]
Sorry, just read my feature request, so autocompletion for it works
![image](https://user-images.githubusercontent.com/5870441/150112563-73fa132b-3d48-4a80-bb52-778e58936a96.png)
however it is shown as an undefined variable 
![image](https://user-images.githubusercontent.com/5870441/150112613-06b07925-6d3e-43d5-9f69-281486c34741.png)
and autocompletion for it is not possible.

![image](https://user-images.githubusercontent.com/5870441/150112720-45617d43-9384-4f4d-a3e9-580de8f14c98.png)

**Comment by adelf** [comment]
But it does have a type and if you Ctrl(Cmd)-click to it you will see the declaration)

Maybe redirect this to the PhpStorm team... I can also try to suppress this inspection for route files. I'll check. Thanks.

**Comment by olivernybroe** [comment]
@adelf hmm yeah, does seem like it might be a phpstorm issue 🤔
