### ISSUE TITLE
[Bug]: Autocomplete does not work in models and request

### ISSUE THREAD

**Issue by axcherednikov** [laravel-idea/plugin#494]
### Bug description

Hi! Autofill does not work, all actions were performed in accordance with the documentation. Clearing the cache and even deleting a folder .idea didn't help. Tell me what needs to be done to make the plugin work? Phpstorm Version: Build #PS-213.6461.83, built on December 29, 2021

![image](https://user-images.githubusercontent.com/52137648/151173023-90322ee9-f561-4f4e-acfb-9f1bb4ad71cf.png)
![image](https://user-images.githubusercontent.com/52137648/151172903-0eee3eed-a278-4206-b935-caf8faca1ad1.png)

### Plugin version

4.4.6.213

### Operating system

Linux

**Comment by adelf** [comment]
Hi. The plugin only suggests the validation rules for Form requests. But you can add all fields from some model to it: by Alt-Insert or Command-N in the validation array.
`$fillable` values should be completed... Do you have a `create_users` migration? Have you generated an Eloquent helper code(main menu > Laravel > Generate Eloquent Helper code)?

**Comment by axcherednikov** [comment]
Yes, there is migration. The command (Generate Eloquent Helper code) was also executed. Validation rules do not work in Form Request. Can this plugin conflict with some other plugin?

**Comment by adelf** [comment]
do you have `vendor/_laravel_idea`? what files are where?

> Can this plugin conflict with some other plugin?
Very unlikely.

**Comment by axcherednikov** [comment]
Yes, I have. 
![image](https://user-images.githubusercontent.com/52137648/151186135-a0b5a63c-8cf9-41a4-8f86-6782d23e55b4.png)

**Comment by adelf** [comment]
Does the `_ide_helper_models.php` file contain all needed classes with fields? If yes, do you have any exceptions happen in the PhpStorm? They are shown in the right bottom corner of the IDE window. With red marker...

**Comment by axcherednikov** [comment]
Yes, all fields are available. There are no exceptions.

![image](https://user-images.githubusercontent.com/52137648/151200568-ad959c58-a3ac-40d0-9ff8-bc218f11f565.png)

**Comment by adelf** [comment]
That's weird... 
If you have time, could you create a new project(laravel template with ready User model and create_users migration), generate Eloquent helper code, and check?

**Comment by axcherednikov** [comment]
Yes, I will create, check. And how to check the additions to the validation rules?

**Comment by adelf** [comment]
> And how to check the additions to the validation rules?

I search `Validator::extend` calls in all "Provider.php" files.

**Comment by axcherednikov** [comment]
This project in mac os is fine.

![Снимок экрана 2022-01-26 в 20 36 03](https://user-images.githubusercontent.com/52137648/151216887-dbb9bb9d-fab6-426c-9068-f0431e318251.png)

**Comment by axcherednikov** [comment]
The autocomplete in the models started working after deleting the _laravel_idea folder. In the validation rules, the autocomplete still does not work.

**Comment by axcherednikov** [comment]
Thank you for your help! The whole problem was in the file _ide_helper.php generated barryvdh/laravel-ide-helper. Deleted it, everything worked.

**Comment by adelf** [comment]
Thank you. I'll check this. It won't make any problems before.
