### ISSUE TITLE
[Feature Request]: Filament macro autocomplete support

### ISSUE THREAD

**Issue by tanthammar** [laravel-idea/plugin#495]
### Feature Description

I use [Laravel Filament](https://github.com/laravel-filament/filament), which has become very popular in the TALL-stack community.

At the moment I have to install laravel-ide-helper to get Filament macros autocompletion in phpstorm. 

A typical use case, in a package service provider:

```php
<?php

namespace Tanthammar\FilamentExtras;

use Filament\Forms\Components;
use Filament\PluginServiceProvider;

class FilamentExtrasServiceProvider extends PluginServiceProvider
{
    public static string $name = 'filament-extras';

    protected function registerMacros(): void
    {
        Components\Field::macro('ignored', function () {
            $this->dehydrated(false);
        });
    }
}
```

It would be awesome if Laravel idea could support this, so I can avoid installing another package.

**Comment by adelf** [comment]
Hi, Tina.
Could you try this - main menu - Laravel - Code generation - Generate Helper Code. 
It should generate the needed helper code for macro and facades. I know it's a bit annoying, we are working on doing it automatically(but it's not easy :( )

**Comment by tanthammar** [comment]
Hi @adelf I tried, and it didn't work for the macro in my ServiceProvider.
That is when I posted here :)

**Comment by adelf** [comment]
Ok. Seems it's time to try filament and add some support for it :)
