### ISSUE TITLE
[Feature Request]: Exclude 'storage' directory on startup - except logs directory

### ISSUE THREAD

**Issue by SjorsO** [laravel-idea/plugin#496]
### Feature Description

There is a setting that excludes the storage directory on startup. This feature is good, but it has a downside: it also excludes the logs directory. This means you can't the "find file" shortcut to open the laravel.log anymore:

![image](https://user-images.githubusercontent.com/7202674/151358582-cc30e0f3-6fc7-4c48-a3e0-86fd806a8e41.png)

It would be great if it could exclude the storage directory, except the logs directory, like this:

![image](https://user-images.githubusercontent.com/7202674/151358451-fe9fa4b7-64ff-453b-be6c-b83ca86048e8.png)

That way, it is easy to quickly open the laravel.log file:

![image](https://user-images.githubusercontent.com/7202674/151358691-c02ad396-6f92-489e-bb9e-be1bcd1d6ae3.png)

**Comment by adelf** [comment]
Implemented in 5.1.1
