### ISSUE TITLE
[Bug]: Missing support for 2022.1

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#499]
### Feature Description

As 2022.1 is in EAP, it would be nice to be able to run this plugin on it ❤️

**Comment by adelf** [comment]
https://plugins.jetbrains.com/plugin/13441-laravel-idea/versions/stable/155494 :)

**Comment by olivernybroe** [comment]
yay!

**Comment by adelf** [comment]
Let's leave this open for a while.
