### ISSUE TITLE
View autocomplete and link don't work, look like related to not saving config

### ISSUE THREAD

**Issue by xVismutx** [laravel-idea/plugin#5]
Here is screenshot, so you can see project structure
https://i.imgur.com/3er88OM.png

When I set project path, like "reposit", "/reposit/", "reposit/", some of functionality work.
But when project restarted. then it is empty again. So I think view, trans autocomplete don't work because of that setting that reset every time and  right cache can't be build.

**Comment by adelf** [comment]
Sure. I hope new release will be approved tomorrow. Lets check.

**Comment by xVismutx** [comment]
I tried to start PHPStorm as admin user and still the same.

@adelf So, it is known issue?

**Comment by adelf** [comment]
@xVismutx Yes. And it was fixed a week ago, but Jetbrains are in Christmas holidays and they can't check the new version. I hope tomorrow they will check it.

**Comment by xVismutx** [comment]
@adelf May be I can manually change it somewhere in project idea settings?
https://i.imgur.com/t1cTG7z.png

**Comment by adelf** [comment]
No. But I can share the new release with you :) and  you can install it manually.

**Comment by xVismutx** [comment]
> No. But I can share the new release with you :) and you can install it manually.

Lets wait to jetbrains version, I don't know how it will work with subscription if I install it manually.
New year is near, so I will not work a lot this days:)

P.S. Some month ago, when I proved to one more developer, that he should not use repository with eloquent in Laravel, I found your article and gave it to him. And there I found that you have a book...
На русском этой книги нет случайно? :)
https://adelf.tech/2019/architecture-of-complex-web-applications
