### ISSUE TITLE
Blade components of package not found

### ISSUE THREAD

**Issue by tomsix** [laravel-idea/plugin#50]
When I want to use components of a package, they are not automatically completed.
The package I am using registers the component via 'loadViewComponentsAs' with a prefix.

Someone who knows a solution for this?

**Comment by adelf** [comment]
Hi, @tomsix . Plugin has a setting about components path... but it can contain only one directory. I'll add the possibility to setup multiple directories there in the next version.

**Comment by adelf** [comment]
implemented in 3.0 version. It should find your package components without any additional configuration. please check and comment if there are some issues.
