### ISSUE TITLE
[Feature Request]: Option to exclude plugin menu from New File dialog

### ISSUE THREAD

**Issue by mahoho** [laravel-idea/plugin#500]
### Feature Description

Hello, is there any way to remove Laravel menu added by a plugin in New File dialog?
I used to create files quickly via New File hotkey - Enter, very quickly, now I have to press down.
Option appeared after last update.

Thanks!
![image](https://user-images.githubusercontent.com/2101587/151839906-6413697e-850b-47cf-8320-5388d14e42fa.png)

**Comment by adelf** [comment]
Hi. Sorry, not for now. I'll add a "Hide this" sub-menu in the next version. This or next week.

**Comment by adelf** [comment]
You can try to remove an action here:
![image](https://user-images.githubusercontent.com/2818394/151841979-1876104c-ead9-4ca8-8e89-6adbc69ebd95.png)

**Comment by mahoho** [comment]
Thank you for quick reply! 
Unfortunately, removing option you mentioned on screenshot didn't help. 
It removed plugin's row from top menu File - New menu, but dialog I was talking about seems configured in different place, I use cmd+N hotkey to open it.

![image](https://user-images.githubusercontent.com/2101587/151842913-a299059e-5074-47cb-903b-fa062ed48235.png)

**Comment by adelf** [comment]
This is correct:
![image](https://user-images.githubusercontent.com/2818394/151845659-52f1f79a-e812-47f4-812a-2819fab4b482.png)

**Comment by mahoho** [comment]
Thanks, those changes removing plugin's row from right click - File - New menu. But menu opened with cmd+N still remains the same. I have removed all assurances of "Laravel" in * Popup Menus, but it still persists.
It seems that that menu is not easy one for customize from user's side, or I am missing something.

**Comment by adelf** [comment]
> It seems that that menu is not easy one for customize from user's side, or I am missing something.

True. I couldn't find any possibility to find ALL "Laravel" menu items... It's a bit embarrassing. I already implemented the "Hide This Menu" item. I hope to release an update this week.

**Comment by mahoho** [comment]
Thanks!

**Comment by adelf** [comment]
BTW, in this Manus and Toolbars window, you can use "Laravel" search and then arrow down to find the needed action group.

**Comment by mahoho** [comment]
Just got an update, v5.1.0.213. Now this item is gone for me. Thanks a lot!
