### ISSUE TITLE
[Bug]: Config files under directory jump to not working

### ISSUE THREAD

**Issue by moisish** [laravel-idea/plugin#502]
### Bug description

Under the Laravel config folder I have different folders like bellow

```
├── config
|   ├── core
|   |   |   images.php
|   |   |   anotherconfig.php
|   |   |   anotherconfig.php
|   ├── client
|   |   |   anotherconfig.php
```

The content of the images.php file is 
```
return [
    'quality' => [
        'input' => 100,
        'output' => 100,
    ];
];
```

Autocompletion works so I can start typing `config('core.images....` and I get see the options. 
Clicking on it to jump to the relevant place in the config file does not work

### Plugin version

5.0.0.213

### Operating system

Windows

**Comment by adelf** [comment]
Hi, Moisis. Tried to reproduce. It works... Do you have completions for other config keys? 

![image](https://user-images.githubusercontent.com/2818394/152020411-9a982b3d-629f-4569-81ee-c71d95d0b797.png)

**Comment by moisish** [comment]
Hello Adel. The autocompletion works but the jump to the file does not.

**Comment by adelf** [comment]
Fixed. Thanks.

**Comment by moisish** [comment]
Thank you for all the great work

**Comment by adelf** [comment]
The next version will be released this or next week.
