### ISSUE TITLE
[Bug]: Wrong completion for arguments and options in Artisan commands

### ISSUE THREAD

**Issue by silas229** [laravel-idea/plugin#503]
### Bug description

The feature implemented in #116 also completes [option shortcuts](https://laravel.com/docs/8.x/artisan#option-shortcuts) and the asterisk for [input arrays](https://laravel.com/docs/8.x/artisan#input-arrays) which lead to an error

### Plugin version

5.0.0.213

### Operating system

Windows

### Steps to reproduce

`$ php artisan make:command SendEmails`

Code:
```php
<?php

namespace App\Console\Commands;

use App\Models\User;
use App\Support\DripEmailer;
use Illuminate\Console\Command;

class SendEmails extends Command
{
    protected $signature = 'mail:send {--u|users*}';

    protected $description = 'Send a marketing email to a user';

    public function handle(DripEmailer $drip)
    {
        foreach($this->option('u|users*') as $user) { // Completion by Laravel Idea
            $drip->send(User::find($user));
        }
    }
}
```

### Relevant log output

```shell
The "u|users*" option does not exist.
```

**Comment by adelf** [comment]
The right completion should be `users` right?

Fixed.

**Comment by adelf** [comment]
5.1 is released.
