### ISSUE TITLE
[Feature Request]: Change `$table->bigIncrements('id');` to `$table->id()`

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#505]
### Feature Description

I just noticed that a new migration template uses the following way to create an id:

```php
$table->bigIncrements('id');
```

Currently the default way of creating an id is like this:

```php
$table->id();
```

Perhaps an idea to update the Laravel Idea template like this?

**Comment by adelf** [comment]
Good suggestion. Thanks. Do you remember the Laravel version when ->id() was added? :)

**Comment by adelf** [comment]
Never mind. It's Laravel 7.0.

**Comment by adelf** [comment]
Done. Thanks again.

**Comment by adelf** [comment]
7 minutes!

**Comment by ralphjsmit** [comment]
Thank you, that was extremely fast! 🤩💪 Good job.
