### ISSUE TITLE
[Feature Request]: `route()` js is not defined due to `ESLint: 'route' is not defined.(no-undef)` in typescript project

### ISSUE THREAD

**Issue by anburocky3** [laravel-idea/plugin#506]
### Feature Description

A little suggestion:
I'm using Ziggy on my Laravel (inertiajs) project. And generating my Laravel routes with ziggy. I have placed my `@routes` directive on the layout file and it's generating as expected.

Since my IDE doesn't know about this behavior it is yelling at me.
https://user-images.githubusercontent.com/15264938/152645954-8010d2d1-0cf3-4efc-b508-33bc5e2679f1.png
https://user-images.githubusercontent.com/15264938/152610820-ae758f3f-91d1-4ef1-8391-f39ffbd87227.png

On runtime, the `@routes` directive will generate all the routes and inject in the layout file. So my javascript app (Vue) can access it without any additional dependency.

But since my IDE doesn't aware of this, showing error.

**Comment by adelf** [comment]
Laravel Idea focuses on the PHP part. Route completion for JS route() is just an exception. I don't even know how everything works on JS part. 

The workaround is to create somewhere the file, like helpers.js.
```
function route(name){ return name;}
```

Then Go to Settings > Languages and frameworks > Javascript > Libraries. Add. Name "Helpers", Add there this file. And click Ok.

PhpStorm will stop complaining.

**Comment by anburocky3** [comment]
Thanks for your time. I'm closing this issue. (Since this is out of scope of the package.)
