### ISSUE TITLE
label:question Blade completition

### ISSUE THREAD

**Issue by simao-coutinho** [laravel-idea/plugin#51]
Greate tool, i already by the annual licence, it is possible to include blade completition like this plugin does.
It will be one great improvement

https://plugins.jetbrains.com/plugin/10928-laravel-snippets

https://github.com/Alicannklc/phpstorm-laravel-snippets/blob/master/resources/liveTemplates/Laravel-Blade.xml

**Comment by adelf** [comment]
Hi, Simão.
This plugin is available in marketplace, so you can install it, right?

**Comment by BanenoLuso** [comment]
Yes I can install it but your plugin overlaps ther and the completition
appear on the bottom of the results

Adel <notifications@github.com> escreveu em qui, 14/05/2020 às 12:44 :
