### ISSUE TITLE
[Feature Request]: Smart Action to switch between 'regular closures' and Arrow functions

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#510]
### Feature Description

Hey Adel! Thanks for actively listening to feature requests and bugs.

I've got a feature request which would be very nice to have. It is the ability to switch between long-form 'regular' closures and arrow functions.

When developing, I often have the situation where I start with an arrow-function. Later in the process I chain more things to the function, so that it would be better for the readability to switch to a long-form closure. The opposite also of course also happens ;-).

It would be great if PhpStorm supported this with Alt + Enter. I still *love* the `{{ }} -> {!! !!}}` feature, because those Alt + Enter actions are one of the most useful things.

Would be awesome if you could support this! 

In my eyes you shouldn't worry too much about formatting, because PhpStorm can take care of that as well.

**Comment by adelf** [comment]
Hi, Ralph.

What do you mean? This?

<img alt="image" src="https://user-images.githubusercontent.com/2818394/154296775-a6ff6295-45e5-4bb6-bc8f-d229c14c27c1.png">

**Comment by ralphjsmit** [comment]
Hey Adel, yes, that's what I mean! 

Thanks! I never noticed that, but awesome that it's already available in PhpStorm.
