### ISSUE TITLE
[Bug]: No autocomplete on FormRequests that extends a custom BaseFormRequest 

### ISSUE THREAD

**Issue by RoodFruit** [laravel-idea/plugin#513]
### Bug description

All our FormRequests extend a `BaseRequest`, where the `BaseRequest` itself extends the `FormRequest`. This results in not having an autocomplete on rules. Even if I add the `BaseRequest` to the "rules completion base class names" input in the preferences under 'Validation', it does not work.

![1](https://user-images.githubusercontent.com/61903855/154451249-feea91a4-0035-400a-a08a-bb1d83e31d6d.png)

### Plugin version

5.1.1.213

### Operating system

MacOS

### Steps to reproduce

Create a `BaseRequest` class that extends the `FormRequest` class. Now create a new form request called `TestRequest` for example that extends the `BaseRequest` (not the `FormRequest`!).

Now add a rule and try to get autocompletion when typing 'required' for example. Nothing happens.

**Comment by adelf** [comment]
The problem here is not the base class, but array_merge. I'll fix it. Thanks.
