### ISSUE TITLE
[Bug]: LaravelIdea helper Models takes precedence over App\Model

### ISSUE THREAD

**Issue by tanthammar** [laravel-idea/plugin#516]
### Bug description

Phpstorm 2021.2.3

![Skärmavbild 2022-02-21 kl  17 13 32](https://user-images.githubusercontent.com/21239634/154992819-f9c1c2e3-7a82-488b-8b8b-7633e63a2d34.png)

### Plugin version

5.1.1.212

### Operating system

MacOS

### Steps to reproduce

Create App\Models\Event (eloquent model)
Select "Generate Eloquent Helper Code"
LaravelIdea helper Models takes precedence over App\Models\ ...

**Comment by adelf** [comment]
whereId() return a Query builder object. You need call first() or firstOrNull() after it.

**Comment by adelf** [comment]
Or just Event::find($id)

**Comment by tanthammar** [comment]
That is not the issue. The issue is that phpstorm warns me because it doesn't resolve it as an App\Models\Event, it thinks it is a LaravelIdea model.

**Comment by tanthammar** [comment]
Even if I change to `find()` as suggested, the helper shouldn't refer to `_IH_Event_QB::find`

![Skärmavbild 2022-02-21 kl  17 39 30](https://user-images.githubusercontent.com/21239634/154996087-a10eb89f-d19f-4b17-bc45-92d90046b21f.png)

**Comment by adelf** [comment]
I think the warning is correct. `Event::whereId($id)` returns an `Illuminate\Database\Eloquent\Builder` object. Not a `App\Models\Event`. Isn't it?

If you don't like `_Event_QB` class at all, I have to use something like that. Maybe after implementing generic query builders I could use them...

**Comment by tanthammar** [comment]
No the issue I want to report is that:

Event::whereId($id) hints: 
```
Incompatible types: Expected property of type '\App\Models\Event', '\LaravelIdea\Helper\App\Models\_IH_Event_QB' provided.
```
It should hint 
```
Incompatible types: Expected property of type '\App\Models\Event', '\Illuminate\Contracts\Database\Eloquent\Builder' provided.
```
The Laravel Idea plugin should not take precedence over "real" object.


Event::find($id)  hints:
```
_IH_Event_QB::find($id): App\Models\Event
```

whereas it should hint:
```
Event::find($id): App\Models\Event
// or
App\Models\Event::find($id): App\Models\Event
```

**Comment by tanthammar** [comment]
But if this is the way Laravel Idea renames things, I have to learn all the Laravel Idea names.

**Comment by adelf** [comment]
You're right. I use these pseudo-classes to help PhpStorm to understand the types. So, `Event::whereId($id)->get()->filter(...)->first()` will also have a `App\Models\Event` type.
Nuno Maduro implemented a special "generic" `\Illuminate\Contracts\Database\Eloquent\Builder` class for Laravel 9, but for some reason, it was reverted. I hope they will return it and I can use it instead of these pseudo-classes. But for now... it is impossible. Sorry.

**Comment by tanthammar** [comment]
Ok, I don't recognize it from pre Laravel 9 projects. That is why I thought something went wrong with an update or something.
Like it is now it is hard to understand what the helper is trying to tell me, because I have never seen those short names before. 
Fingers crossed this will be resolved :)

**Comment by adelf** [comment]
> But if this is the way Laravel Idea renames things, I have to learn all the Laravel Idea names.

'\LaravelIdea\Helper\App\Models\_IH_Event_QB' means QB for `App\Models\Event`. QB - Query Builder. 

'\LaravelIdea\Helper\App\Models\_IH_Event_C' - Collection of `App\Models\Event` objects.
