### ISSUE TITLE
[Feature Request]: Collapse translate key code into default language

### ISSUE THREAD

**Issue by Chew** [laravel-idea/plugin#519]
### Feature Description

I come from RubyMine/Rails, which has native support for translation keys, and it's able to do this:

Before (this is equivalent to `trans('a.key')`:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/8278263/156701531-e04c3e40-2c6a-470b-aacf-94acba9a3cd5.png">

But if I folding > collapse, it shows the english term:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/8278263/156701576-c9f9a677-2bf4-4d84-b1a8-acfdde10900a.png">

Which of course I can peek at:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/8278263/156701598-1efd95e8-67af-4bd9-bb83-bcce5548d361.png">

Is this something that can be implemented? It would help immensely with translations since it'll let me see it natively without seeing keys everywhere.

**Comment by adelf** [comment]
Hello. Sorry for the long response. It's definitely possible, but I don't know how difficult it will be to implement. Let me check.

**Comment by adelf** [comment]
Implemented.
