### ISSUE TITLE
[Bug]: Cannot find route when registered via `addRoute` method

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#523]
### Bug description

When having a route that looks like the following
```php
\Illuminate\Support\Facades\Route::addRoute(
    ['GET', 'POST'],
    '/web-api/v2/graphql',
    [
        'as' => 'graphql.v2',
        'uses' => \Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController::class,
        'middleware' => [
            'api',
            \Nuwave\Lighthouse\Support\Http\Middleware\AcceptJson::class,

            // Logs in a user if they are authenticated. In contrast to Laravel's 'auth'
            // middleware, this delegates auth and permission checks to the field level.
            \Nuwave\Lighthouse\Support\Http\Middleware\AttemptAuthentication::class,
        ]
    ]
);
```

The plugin is not able to find this route, so autocompletion for it does not exist.

Pretty edgecase, I know 😆 

### Plugin version

5.1.1.221

### Operating system

MacOS

**Comment by adelf** [comment]
> Pretty edgecase, I know

No, it's ok. Thank you for posting.

**Comment by adelf** [comment]
It could be fixed by 1 line change, but I decided to make a refactoring... and it took about 2 hours :)

"12 changed files with 227 additions and 233 deletions."

**Comment by olivernybroe** [comment]
@adelf why simplify when we can make a much cooler solution that is going to take 10x the time to code 😂

**Comment by adelf** [comment]
I hope it works now.
