### ISSUE TITLE
[Feature Request]: Provide translation key autocompletion for packages

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#525]
### Feature Description

Hey! I'm not sure whether this is easy or difficult, but I really love the autocompletion on the keys of translation files and it would be great if that also worked on packages.

In packages, you normally register translations with a prefix, like this:

```blade
{{ __('my-prefix::file.my.key') }}
```

Currently Laravel Idea provides autocompletion for `file.my.key`. Unfortunately that isn't completely correct, because the prefix is missing.

It would already be much better if Laravel Idea would be able to pick up the autocompletion after the two colons `::` in the prefix. For example, when I would type `my-prefix::`, Laravel Idea would provide the completion with `file.my.key`.

Would be great if this is possible to realize. Thanks!

**Comment by adelf** [comment]
Hey, Ralph.

Please check this setting:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/2818394/159027443-4ef4e26d-8b01-4f01-bf19-90090dfc3ddf.png">

a special module system for packages and Translation namespace should help.

**Comment by ralphjsmit** [comment]
Hey Adel, thank you, that's awesome! Sorry for bothering you!

**Comment by adelf** [comment]
> Sorry for bothering you!

Absolutely no problem. Don't hesitate to ask.
