### ISSUE TITLE
[Feature Request]: Auto Complete `route()`

### ISSUE THREAD

**Issue by bogdankharchenko** [laravel-idea/plugin#527]
### Feature Description

Hi,

At some point this plugin allowed me to create a method on a class called "route" which had the same exact signature as the `route()` global method.  It was great as I use this part of a form-builder and need to specify the route the form will hit.

At some point this seems to have stopped working.

It would be cool to being that feature back or allow a mechanism for us to be able to define, if method name is xyz, do autocomplete of routes, or views. etc...

**Comment by adelf** [comment]
Hi.

If you want to complete with route names the first parameters of **any** `route` method, you can add the `ide.json` file with this contents to your project:

```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "routeName",
            "condition": [
                {
                    "methodNames": ["route"],
                    "parameters": [1]
                }
            ]
        }
    ]
}
```

Conditions for classes also can be added. Documentation for it will be added a bit later.

**Comment by bogdankharchenko** [comment]
thank you
