### ISSUE TITLE
[Bug]: Eloquent Completion Not Accurate with Multiple Models/Builders in Chain

### ISSUE THREAD

**Issue by ctalkington-brado** [laravel-idea/plugin#529]
### Bug description

When you have an Eloquent Model with a method that returns an Eloquent Builder of a different Eloquent Model, the auto completion for the method, when chained, refers back to the original Eloquent Model rather than the Eloquent Model related to the Eloquent Builder.

The auto completion works when assigning to variable first or wrapping the method call before chaining as shown in expected examples.

Expected:
![image](https://user-images.githubusercontent.com/65624018/160158560-e707f959-fec1-46f4-a9f5-d3f6af1acbe1.png)
![image](https://user-images.githubusercontent.com/65624018/160159591-1bc78fe5-62ba-4496-b54c-5687c8697d14.png)

Actual:
![image](https://user-images.githubusercontent.com/65624018/160158351-4e7df163-d05a-4171-8563-14958999b80b.png)

### Plugin version

5.1.1.213

### Operating system

Windows

**Comment by adelf** [comment]
It should be fixed by the 5.2.* version. Please post here if something is wrong.
