### ISSUE TITLE
[Bug]: Error writing to non standard path in package.

### ISSUE THREAD

**Issue by sitesurfer** [laravel-idea/plugin#530]
### Bug description

Using the code creation feature, when in a normal package (with src as the root and views in a dir above) the plugin writes the views/blade file part but not the class.

Changing the laravel path to src inside the plugin disables the plugin.

I am certain I have missed something, but cannot see a way to invoke a path different to the standard App/ layout.

### Plugin version

5.11.221

### Operating system

MacOS

### Steps to reproduce

Attempt to create a class using the code creation feature within a package structure.

**Comment by adelf** [comment]
Hi. Please try to change Settings > Languages and frameworks > Laravel Idea > Module System > to Package developement.

**Comment by sitesurfer** [comment]
Amazing, thank you - such a simple solution. I apologise for taking up support time for such an easy one.
Once again many thanks!

**Comment by adelf** [comment]
>> I apologise for taking up support time for such an easy one.

Don't apologize. This issue made me realize that I should fetch the "src" folder and suggest switching to "Package development" automatically. So, don't hesitate to ask!
