### ISSUE TITLE
[Feature Request]: AutoCompletion for `return to_route(/** */)`

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#532]
### Feature Description

Since Laravel 9 we have a `to_route()` helper that can be used to redirect users to another route. I just noticed that this helper doesn't have autocompletion yet, so that's perhaps a nice idea to add.

Thanks!

**Comment by adelf** [comment]
Hi, Ralph.

This completion was added in one of the previous versions. At least Laravel Idea 5.2 completes it.

**Comment by ralphjsmit** [comment]
Hey Adel, thanks! Sorry, I forgot to check for updates, it's a bit too much hidden away.. :(
