### ISSUE TITLE
[Feature Request]: autocomplete for inertia components not in JS dir.

### ISSUE THREAD

**Issue by RomkaLTU** [laravel-idea/plugin#534]
### Feature Description

I have structure like this:
<img width="224" alt="CleanShot 2022-04-07 at 11 04 50@2x" src="https://user-images.githubusercontent.com/10167743/162117987-332dfbf5-d767-496b-a36e-c07714d04472.png">

And autocomplete doesn't work if components aren't in JS dir.

**Comment by adelf** [comment]
You can change the paths here:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/2818394/162126963-3d659d22-eaa2-4b98-814d-30aaf213a5ba.png">
