### ISSUE TITLE
[Feature Request]: Add checkbox "soft delete" in create model

### ISSUE THREAD

**Issue by benounnas** [laravel-idea/plugin#535]
### Feature Description

Since soft deletes are optional in laravel, sometimes we face sensitive models where they are a must, so i was wondering if adding a checkbox of "soft delete" that adds "deleted_at" column that comes with "create migration" is checked and adds automatically the trait underneath it (it's like subcategory), it may opens up a lot of configurations in the model before its creation!.

**Comment by adelf** [comment]
Hello. I'm going to implement a feature of creating a model with fields, migration, model class, controller, and maybe some other things. It will be a good addition there.
