### ISSUE TITLE
[Bug]: Request Facade Macros Not Linked to Illuminate\Http\Request

### ISSUE THREAD

**Issue by ctalkington-brado** [laravel-idea/plugin#538]
### Bug description

If I have something in my AppServiceProvider.php like:

```php
Request::macro('affirmed', function ($key = null) {
    $input = $this->input($key);

    return in_array(strtolower($input), ['y', 'yes'], true);
});
```

and controller code of:

```php
use Illuminate\Http\Request;

public function postRemoveCampaign(Request $request): JsonResponse
{
...
    $action_confirmed = $request->affirmed('action_confirmed');
...
}
```

When trying to access said method in my controller, I'm told the method does not exist but the code actually works fine.

![image](https://user-images.githubusercontent.com/65624018/163872862-ff7efade-983c-4e07-ba00-61871b53ac01.png)

I believe this is because the helper code is generated only for the main Request facade and not also for the Illuminate\Http\Request class.

![image](https://user-images.githubusercontent.com/65624018/163872978-36180db1-0519-44c1-88c5-86d3ab86fca6.png)

### Plugin version

5.3.0.221

### Operating system

Windows

**Comment by adelf** [comment]
Hi, Chris.

There is probably a wrong import in the AppServiceProvider. Something like `use Request;`

With `use Illuminate\Http\Request;` it should work ok.

**Comment by ctalkington-brado** [comment]
@adelf thanks, we were using the `use Request;`, seems ok with direct class instead of Facade.
