### ISSUE TITLE
There are no relay hints when populating the `relationLoaded` method

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#54]
![2020-05-18_00-10-09](https://user-images.githubusercontent.com/10347617/82160166-1b62c780-989c-11ea-85b2-ce9c9649bf59.jpg)

**Comment by adelf** [comment]
Added. Danke )

**Comment by andrey-helldar** [comment]
Bitteshön =)

**Comment by adelf** [comment]
implemented in 3.0 version. please check and comment if there are some issues.

**Comment by andrey-helldar** [comment]
It's works!
![2020-05-19_16-59-19](https://user-images.githubusercontent.com/10347617/82335498-1748be00-99f2-11ea-8e96-8233fe3f8a07.jpg)
