### ISSUE TITLE
[Bug]: Controller in group route doesn't work

### ISSUE THREAD

**Issue by khusan-dev** [laravel-idea/plugin#542]
### Bug description

If I specify a controller in a group, then I can't navigate through the method.

### Plugin version

4.3.4.202

### Operating system

Windows

### Steps to reproduce

`    Route::group(['controller' => AuthController::class], function () {
        Route::post('register', 'register');
        Route::post('send_code', 'sendCode');
        Route::post('check_code', 'checkCode');
        Route::post('login', 'login');
    });`

**Comment by adelf** [comment]
I support only Route::controller() syntax. I'll add support for this syntax in the next version. Thanks!

**Comment by khusan-dev** [comment]
> I support only Route::controller() syntax. I'll add support for this syntax in the next version. Thanks!

Thanks for the answer. But unfortunately the syntax you describe doesn't lead to a method either.

**Comment by adelf** [comment]
Plugin version
4.3.4.202

This is a very old version of the plugin. The current version is 5.3. Please update PhpStorm and plugin.

**Comment by khusan-dev** [comment]
> Plugin version 4.3.4.202
> 
> This is a very old version of the plugin. The current version is 5.3. Please update PhpStorm and plugin.

Thank you. After the update everything worked.
