### ISSUE TITLE
[Bug]: Autocomplete issue for Livewire attributes

### ISSUE THREAD

**Issue by ObaydaAlesawi** [laravel-idea/plugin#543]
### Bug description

the autocompleted attribute should have an underscore separator "_" not just a dash "-"
![image](https://user-images.githubusercontent.com/32073999/165968269-1283c826-7ca2-41d5-842c-90a4e1eb0f33.png)
because livewire can't get the attribute when it's with dash  

### Operating system

Windows

**Comment by adelf** [comment]
Thank you for posting. Will be fixed.

What is the field name?

**Comment by adelf** [comment]
Fixed in 5.4. Thanks!
