### ISSUE TITLE
[Feature Request]: Automatically derive and suggest Blade file for Livewire components without `render()` method

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#546]
### Feature Description

I recently discovered that Livewire components are also allowed to omit the `render()` method, because Livewire will automatically determine the view name based on the convention.

When clicking on a Livewire component in a Blade file, you get an absolutely awesome suggestion, linking to the Component file and the Blade file, so that you can choose which file to go to.

I just noticed that the Blade file is not being determined when you omit the `render()` method in a component. It directly goes to the component file.

It would be great if Laravel Idea could automatically determine this as well! Thanks!

### Example

```php
<?php

namespace App\Http\Livewire\Components\User;

use App\Models\User;
use Illuminate\Contracts\View\View;
use Livewire\Component;

class Edit extends Component
{
    public function mount(): void
    {
        //
    }

       // Blade file: "livewire.components.user.edit"
}
```

Note the namespace of the component.

**Comment by adelf** [comment]
So, the component call will be `<livewire:components.user.edit>` or `@livewire('components.user.edit')` right? If yes, I just implemented it :)

**Comment by ralphjsmit** [comment]
> So, the component call will be `<livewire:components.user.edit>` or `@livewire('components.user.edit')` right? If yes, I just implemented it :)

Yes, correct! Thank you Adel!🙌

**Comment by adelf** [comment]
5.4 is available. thanks!

**Comment by ralphjsmit** [comment]
Great as always, thank!
