### ISSUE TITLE
[Bug]: Blade component escaped attributes still considered as PHP

### ISSUE THREAD

**Issue by aguingand** [laravel-idea/plugin#547]
### Bug description

As stated in the [docs](https://laravel.com/docs/9.x/blade#escaping-attribute-rendering), components attributes can be escaped and rendered "as is" in the view.

However Laravel idea injects php inside of double colon attributes:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/17453506/168564740-735cbc8e-dda8-490b-b208-7c5071916e62.png">

I expect these attributes to not be syntax highlighted nor having PHP autocompletion.

### Plugin version

5.3.1.221

### Operating system

MacOS

### Steps to reproduce

- Create a blade component
- Insert it in another view with `<x-` syntax
- Add an attribute with double colon, e.g `::class="{ 'danger': error }`

**Comment by adelf** [comment]
Thank you for posting this. I'll try to implement this escaping in the next version.

**Comment by adelf** [comment]
Fixed in 5.4. Thanks.
