### ISSUE TITLE
Completions Not Working When Using a Common Library

### ISSUE THREAD

**Issue by s1rc** [laravel-idea/plugin#55]
I'm trying to get the Eloquent completions working as shown in https://laravel-idea.com/docs/2.x/eloquent#completions

ide-helper is generating all the necessary files, however completion and type casting doesn't appear to do anything. This might be a result of how our applications are set up. We have multiple applications that share a common package, which contains our models, migrations, etc.

Since we're not using "modules" I'm not sure how to configure or if this plugin is compatible. I've tried putting a module path of `../app-common` but nothing seems to change.

**Comment by adelf** [comment]
Hi. You said ide-helper generates all necessary files, but is there a phpDocs for these models?
When you make for example 
```
$test = new ModelFromPackage(); 
$test->[do you have completion for fields here?];
```

If not, you can try `--dir` option in ide-helper, or just wait tomorrow. New Laravel Idea release will contain own `_ide_helper_models.php` files generator :)

**Comment by s1rc** [comment]
No completions at all and not generated with the —dir flag. 

I’ll try that but definitely will try new version tomorrow!

**Comment by s1rc** [comment]
I tried `php artisan ide-helper:model --dir --nowrite` and it's giving me errors with packages from my /vendor. i.e.:
```
 Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'League\Container\ServiceProvider\AbstractServiceProvider' not found
``
Thrown from `/vendor/intervention/image/src/Intervention/Image/ImageServiceProviderLeague.php:7`

I'll wait until tomorrow to try the new release. 👍

**Comment by adelf** [comment]
3.0 version is available. please check and comment if there are some issues.

**Comment by s1rc** [comment]
@adelf I updated the plugin this morning, is there anything I need to do to use the built in model generator helper?

I've gotten the ide-helper:models working with:
`php artisan ide-helper:models --nowrite --dir="../app-common/src/Models"` and they are showing up from the IDE now.

**Comment by adelf** [comment]
Today's release has some issues. They will be fixed tomorrow. After that you can try a new generator in the Code menu > Laravel Idea Code Generation > "Generate Eloquent Helper Code"
