### ISSUE TITLE
[Feature Request]: Add folder path to the migrations.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-idea/plugin#552]
### Feature Description

I am currently working with https://tenancyforlaravel.com/ for multi-tenancy apps and this package requires the migrations for the tenants to be in the `migrations/tenants` folder. Whenever I create a migration through this plugin, I have to move them manually to the `tenants` folder. Is there a way to set the folder name on the `Migration class or filename` field like `tenants/add_some_fields_to_the_orders_table`? It would be great if this were possible.

I can still update the Project settings under `Code Generations`, but I don't want to do this because the central app for the multi-tenancy app still has migrations under the default `migrations` folder.

`central_app` -> `migrations`
`tenant_app` -> `migrations/tenants`

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1529382646102601728

**Comment by abishekrsrikaanth** [comment]
@adelf This is awesome...

**Comment by abishekrsrikaanth** [comment]
@adelf, can something similar be done when creating a model? The "Create Model" has the option to create a migration, any way to select if it is a regular migration or a tenant migration?
