### ISSUE TITLE
[Bug]: Local Scopes are always shown as "unused"

### ISSUE THREAD

**Issue by nicolus** [laravel-idea/plugin#554]
### Bug description

Using PhpStorm 2022.1.1, Laravel 9 and Laravel idea 5.4.

When I create a local scope in a model and use it in a controller or anywhere in the code, it is properly recognized by the plugin and I can ctrl+click the usage of the scope to navigate to its definition (this is great !). However, the method itself is always greyed out and recognized as unused by PhpStorm.

I'm not sure if it's a bug or a known limitation, but this is kind of dangerous, because it makes you think that you can safely delete apparently unused scope, and break your code (Yes, that happened to me...)

Thanks for your help !

### Plugin version

5.4.0.221

### Operating system

Windows

### Steps to reproduce

1. Create a scope, for example : 
```php
public function scopeActive(Builder $query): void
{
    $query->where('active', 1);
}
```

2. Use it somewhere : 
```php
public function index()
{
    return User::active()->get();
}
```

3. Generate the Eloquent helper code.

The scope is recognized : 
![image](https://user-images.githubusercontent.com/3315078/170282348-f8534e30-9f90-410f-b869-2c3c43ec0a63.png)

But marked as unused : 
![image](https://user-images.githubusercontent.com/3315078/170282393-73ed5e09-b0e7-445c-a5cf-77d093614c12.png)

**Comment by inovar-tecnologia** [comment]
Important feature for code refactoring and finding method uses

**Comment by nicolus** [comment]
Hi @adelf : Sorry to harass you but it is an important feature for us and it seems like others have a need for this.

Could you let us know if this is a known limitation and if there's a chance you could improve it ?

PS : I just confirmed it still behaves the same with the latest version of the plugin (5.7.3.221) and phpstorm 2022.2

Thanks

**Comment by adelf** [comment]
Let me check.

**Comment by adelf** [comment]
Looks like I managed to make it work as needed.

<img alt="image" src="https://user-images.githubusercontent.com/2818394/182386993-03a04c43-da76-43f9-a9d7-09555ade0a94.png">

**Comment by nicolus** [comment]
Awesome, thanks for taking the time to look into it !

**Comment by adelf** [comment]
I made it configurable and turned it off by default(it might use too much CPU, but I'm not sure 100%).

Preferences | Languages & Frameworks | Laravel Idea | Eloquent
