### ISSUE TITLE
[Bug]: JetbrainsRuntime crashes JITting some of plugin's methods

### ISSUE THREAD

**Issue by VladimirKempik** [laravel-idea/plugin#556]
### Bug description

We ( in jebrains) have discovered an issue for users who use this plugin: 
https://plugins.jetbrains.com/plugin/13441-laravel-idea

Sometimes JetbrainsRuntime crashes doing C2 jit compilation of these methods:
`com.laravel_idea.plugin.eloquent.EloquentInfo::b
com.laravel_idea.plugin.eloquent.EloquentInfo::n
com.laravel_idea.plugin.eloquent.EloquentInfo::h
com.laravel_idea.plugin.eloquent.EloquentInfo::z
com.laravel_idea.plugin.eloquent.EloquentInfo::q
com.laravel_idea.plugin.eloquent.EloquentInfo::v`
We have over few hundred reports.
This affects only JBR11, so far no reports from users with JBR17/222_EAP

It would greately help us if you provide the source code of some of these methods or try to create a reproducert on your side.
This happens during loop optimization in the mentioned methods.

### Plugin version

Latest as of crash time

### Operating system

Linux

### Steps to reproduce

TBD

### Relevant log output

```shell
Example of a crash:

---------------  T H R E A D  ---------------

Current thread (0x00007fcbb017f000):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=15544, stack(0x00007fcb7ccc1000,0x00007fcb7cdc2000)]


Current CompileTask:
C2:10917636 119336 % !   4       com.laravel_idea.plugin.eloquent.EloquentInfo::b @ 744 (986 bytes)

Stack: [0x00007fcb7ccc1000,0x00007fcb7cdc2000],  sp=0x00007fcb7cdbcbb0,  free space=1006k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xa7b109]  PhaseIdealLoop::build_loop_late_post(Node*)+0x109
V  [libjvm.so+0xa7b64b]  PhaseIdealLoop::build_loop_late(VectorSet&, Node_List&, Node_Stack&)+0x14b
V  [libjvm.so+0xa7ed97]  PhaseIdealLoop::build_and_optimize(LoopOptsMode)+0x687
V  [libjvm.so+0x6364df]  Compile::optimize_loops(int&, PhaseIterGVN&, LoopOptsMode) [clone .part.372]+0x22f
V  [libjvm.so+0x639453]  Compile::Optimize()+0x5d3
V  [libjvm.so+0x63aaa1]  Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool, bool, DirectiveSet*)+0xd41
V  [libjvm.so+0x567f14]  C2Compiler::compile_method(ciEnv*, ciMethod*, int, DirectiveSet*)+0xd4
V  [libjvm.so+0x64409d]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0x46d
V  [libjvm.so+0x645328]  CompileBroker::compiler_thread_loop()+0x438
V  [libjvm.so+0xe0a560]  JavaThread::thread_main_inner()+0xd0
V  [libjvm.so+0xe06649]  Thread::call_run()+0x149
V  [libjvm.so+0xbcaace]  thread_native_entry(Thread*)+0xee
```

**Comment by adelf** [comment]
Hi. Your email? or?

**Comment by VladimirKempik** [comment]
More info - https://youtrack.jetbrains.com/issue/JBR-3550
My email is vladimir[censored]com

**Comment by adelf** [comment]
Sent. Hope it helps.

**Comment by adelf** [comment]
I removed the obfuscation of this part, in 5.6.1. Seems, it helped.

**Comment by VladimirKempik** [comment]
Lets see if the amount of reports we get will decrease. When this gonna get released ?

**Comment by adelf** [comment]
already.

**Comment by VladimirKempik** [comment]
so, if I see a similar crash in obfuscated code - it's older version ?

**Comment by adelf** [comment]
yes. I hope so ) I don't understand what is the reason for this crush. One of my users had these crushes regularly and they disappeared with this version(5.6.1)

**Comment by VladimirKempik** [comment]
>I don't understand what is the reason for this crush.

obfuscator made C2 go crazy.
