### ISSUE TITLE
[Feature Request]: Autocomplete Dynamic "trashed" factory state

### ISSUE THREAD

**Issue by inovar-tecnologia** [laravel-idea/plugin#557]
### Feature Description

Laravel 9.14 add a dynamic support of a "trashed" factory state for models using soft delete

![image](https://user-images.githubusercontent.com/62029328/171648943-2662678a-f73f-4836-bd79-9338bba74f79.png)

but, the implementation uses dynamic method "__call", preventing IDE to autoclomplete

![image](https://user-images.githubusercontent.com/62029328/171649311-3bc9b53c-f910-4ff7-9697-ca014029bdf8.png)

![image](https://user-images.githubusercontent.com/62029328/171649397-4e96ef85-83ee-4c5c-a454-4ef530b51aef.png)

**Comment by adelf** [comment]
This is better to fix by PR for Laravel - https://github.com/laravel/framework/pull/42693

**Comment by adelf** [comment]
Merged :)
