### ISSUE TITLE
[Bug]: Looks like the "{{ }} -> {!! !!}" smart action doesn't work anymore

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#558]
### Bug description

Some time ago you implemented two smart actions that allowed to change Blade "{{ }} -> {!! !!}" and vice versa. 

The last weeks it looks like that smart action isn't available anymore. 

I have the idea that it came because of the upgrade to PhpStorm 2022 one or two months ago.

Thanks!

### Plugin version

5.4.0.221

### Operating system

MacOS

### Steps to reproduce

PhpStorm 2022.1.2.

**Comment by adelf** [comment]
Fixed in 5.5. Thanks!
