### ISSUE TITLE
[Bug]: enable default HTML autocompletion for `<x-slot:name>` element

### ISSUE THREAD

**Issue by aguingand** [laravel-idea/plugin#560]
#### Context
- Since Laravel 8.x we can use given slots attributes
- Slots have been renamed to `<x-slot:name>`

#### Bug / Enhancement
With the new `<x-slot:name>` syntax, html attributes are not autocompleted (very useful for classes for example). The autocompletion works with components but my guess is `<x-slot:` is considered as non HTML namespace.

### Plugin version

5.4.0.221

### Operating system

MacOS

### Steps to reproduce

Enter:
```html
<x-slot:name>
</slot:name>
```
add attribute e.g `class=""`, autocompletion does not work

**Comment by adelf** [comment]
How these attributes can be used in the component?

**Comment by aguingand** [comment]
Like this ! https://laravel.com/docs/9.x/blade#slot-attributes

**Comment by adelf** [comment]
Got it. Thx.

**Comment by adelf** [comment]
Laravel Idea 5.6 is out. It should work there. Please check.

**Comment by aguingand** [comment]
Yes thank you !
