### ISSUE TITLE
[Feature Request]: "Generate Laravel Translation" with html in blade should use {!! !!} instead of {{ }}

### ISSUE THREAD

**Issue by imerr** [laravel-idea/plugin#561]
### Feature Description

Sometimes there's just a need to have translations that have some html formatting in them

When writing out the template with normal text in them and then going over it with the generate translation action (which works fantastic btw and is so much easier than copying things around!) it'd be nice if it was smart enough to output them unescaped as well.

Bonus points if arguments that were previously escaped, would be escaped passing them into the translation function.
For example:
 ```html
Welcome back, <b>{{$username}}</b>. {!! $unescapedText !!}
```
Should be turned into:
 ```php
 {!! __("example.key", ["username" => e($username), "unescaped" => $unescapedText]) !!}
 ```

**Comment by adelf** [comment]
Implemented in Laravel Idea 5.5. Thanks!
