### ISSUE TITLE
[Bug]: Livewire not detected (disabled)

### ISSUE THREAD

**Issue by cschilling** [laravel-idea/plugin#562]
### Bug description

I've installed Laravel Jetstream but for some reason, the livewire-functions won't be enabled for me.
Is there anything, that needs to be done in order to enable this part of the plugin?
(Same goes for "blade-ui-kit/blade-icons", which are also not being detected)

As you can see, the ""livewire/livewire""-package is part of my composer.yml and "laravel/jetstream" was found just fine:

![Disabled](https://user-images.githubusercontent.com/343878/173475018-736aac3e-c4eb-461f-a544-22ad6b73a435.png)

### Plugin version

5.4.0.221

### Operating system

Linux

### Steps to reproduce

Install laravel/jetstream and enable livewire-support:

`php artisan jetstream:install livewire

npm install
npm run dev
php artisan migrate

php artisan vendor:publish --tag=jetstream-views`

**Comment by adelf** [comment]
Laravel Idea tries to fetch composer.lock file changes... 
Could you restart PhpStorm or just reopen this project? It should help.

**Comment by cschilling** [comment]
Thanks for the quick response but sadly that doesn't work.

These are the things that I've already tried:
- Restart the IDE
- "composer remove livewire/livewire" and "composer require livewire/livewire"
- deleting the "composer.lock" and doing a "composer install"
- Deleting all Settings in IDEA and only adding the Laravel IDEA-Plugin

All with the same result.
What bothers me is that other packages do get detected just fine (e.g. like Jetstream).

**Comment by adelf** [comment]
Could you send me your composer.json and composer.lock files? I want to reproduce this. Here, or adel@laravel-idea.com

**Comment by cschilling** [comment]
I've found the solution for me:
I didn't have the "blade"-plugin installed in IDEA.
Now everything is working just fine.

![image](https://user-images.githubusercontent.com/343878/173714555-f68d5040-726f-43a4-a675-fd34e7913b9b.png)

**Comment by adelf** [comment]
Thank you. I also should make this more explicit...

**Comment by adelf** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/2818394/173819960-41bc2a8e-76a3-47fe-95a9-34adc3d04681.png">

Thank you again :)
