### ISSUE TITLE
[Bug]: missing laravel idea options in generate menu

### ISSUE THREAD

**Issue by Abdelraman** [laravel-idea/plugin#566]
### Bug description

the generate menu not showing laravel idea options e.g. generate json resource, generate resource controller, etc. 

### Plugin version

5.5.0.213

### Operating system

Windows

### Steps to reproduce

clicking Alt + insert to get the generate menu showing the default IDE generate options without laravel idea at the top
kindly check the attached screenshot
![image](https://user-images.githubusercontent.com/4821833/174072311-884d8219-fd16-45bf-8518-e01d5dc9f1d9.png)

**Comment by adelf** [comment]
Hi. Seems, it's not a model class.
