### ISSUE TITLE
[Typo]: plugin name written as "Laravel Ideal"

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#567]
### Bug description

just a minor typo i found:

![image](https://user-images.githubusercontent.com/8792274/174242433-2b82cfa7-30f4-47a4-bef2-6bc8b98e653e.png)

Ideal → Idea

**Comment by adelf** [comment]
It's not a typo ;-)

**Comment by fabio-ivona** [comment]
Damn, just realized it 😅🤦
