### ISSUE TITLE
[Feature Request]: Support for tpetry/laravel-postgresql-enhanced

### ISSUE THREAD

**Issue by abenerd** [laravel-idea/plugin#568]
### Feature Description

I don't know about libraries for other database drivers, but I use [tpetry/laravel-postgresql-enhanced](https://github.com/tpetry/laravel-postgresql-enhanced) which gives me Postgres specific features and enhancements only some features aren't recognized when generating the eloquent helper code, such as when using `identity` columns instead of `id` in migrations. It would be great if idea could detect the usage of such libraries.

**Comment by adelf** [comment]
Implemented. Laravel Idea 5.6 is out.
