### ISSUE TITLE
[Feature Request]: Add autocomplete for pest's livewire plugin

### ISSUE THREAD

**Issue by MuathIbnHassan** [laravel-idea/plugin#569]
### Feature Description

Adding autocomplete for [pest's livewire plugin](https://pestphp.com/docs/plugins/livewire)

this give autocomplete
```php
Livewire::test(Counter::class)
    ->call('increment')
    ->assertSet('count',1);
```

this is not supported yet 
```php
it('can be incremented')
    ->livewire(Counter::class)
    ->call('increment')
    ->assertSet('count',1);
```

❤️

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1539151144806756353

**Comment by adelf** [comment]
Laravel Idea 5.6 is out.
