### ISSUE TITLE
[Bug] PHPStorms "Add method" doesn't work with existing `_ide_helper_models.php`

### ISSUE THREAD

**Issue by cberane** [laravel-idea/plugin#570]
I checked all existing issues but did not find mine. The closest (partly matching) was: https://github.com/laravel-idea/plugin/issues/235

Let's assume the following situation:
- We have the default `App\User` class:  
  ![image](https://user-images.githubusercontent.com/24572192/175029243-bb6f3664-62e7-4550-8d9d-fe2042f4856b.png)
- In some other class (i.e. a test) I want to define some new method names that do not exist yet. PHPStorm now recommends the creation:  
  ![image](https://user-images.githubusercontent.com/24572192/175029897-b9a1e37b-80d5-4c79-ba7a-ea3e91ba9213.png)
- If I hit the method generation PHPStorm complains about `Class 'App\User' has multiple declarations`  
  ![image](https://user-images.githubusercontent.com/24572192/175030094-c05c57b0-8e73-49f4-8aec-4f08b99999c2.png)
- When I delete the helper file it works as expected

I am not sure if it is a bug of Laravel IDEA but I would like to have some solution for this. 

As a workaround the following works:
- delete the helper file
- trigger method generation for the new methods
- re-generate the eloquent helpers

The workaround feels a little hacky and there should be a better way (folder exclusions? inspection settings? ...)  
Thanks in advance :-)

**Comment by cberane** [comment]
Together with a friend of mine we found a solution for the behaviour. He had running an older version of IDEA and Laravel IDEA. The solution at his place was quite simple: `mark the folder _laravel_idea as 'excluded'` 
After he updated his setup the following tooltip came up (a feature 😉):  
![image](https://user-images.githubusercontent.com/24572192/175053099-27384295-f40c-44bf-9e1b-bd7eb73aeb86.png)  
`This is important for correct Laravel magic completion. Turn off this behaviour.`

The final fix for us was:
- disable the auto-include of the helper folder:  
  ![image](https://user-images.githubusercontent.com/24572192/175053290-fb394147-1875-48f3-ab25-6cf637517ed0.png)
- mark the directory as `excluded`: 
  ![image](https://user-images.githubusercontent.com/24572192/175053403-1c535650-696f-4ad4-981d-738abd45a816.png)
- in `.idea/php.xml` and `.idea/workspace.xml` remove the `<include_path>`  elements pointing to `vendor/_laravel_idea` (if the plugin option was active, they should exist)

After this fix:
- code completion still worked (at least tested in IDEA 2022.1.3)
- the magic method generation with `Add method` works too 🙂

I hope this helps someone else.

**Comment by adelf** [comment]
Hi, Cristoph.

I filled a bug to PhpStorm team some time ago - https://youtrack.jetbrains.com/issue/WI-62677/PhpStorm-Add-method-for-multiple-classes-case-use-referenceResolver2-EP

> code completion still worked (at least tested in IDEA 2022.1.3)

This doesn't work for me. Maybe you have phpDocs generated by the "laravel-ide-helper" package right in the model classes? That works...

**Comment by cberane** [comment]
Hi @adelf,

as you pointed out, the "fix" only did work because when we started the project we used [`barryvdh/laravel-ide-helper`](https://github.com/barryvdh/laravel-ide-helper) to generate PHPdocs directly in the models.  
I tested the behavior in a fresh project with `Laravel 9.17` - it did not work as stated before.

I reopened the issue to have the Laravel IDEA team to have a closer look 🙂

Kind regards, Cris

**Comment by imerr** [comment]
Seems to be fixed now in 2022.3.2 preview
Creating methods works for me now and it didn't in .1

**Comment by adelf** [comment]
Yes. They fixed it. Big thanks to the PhpStorm team.
