### ISSUE TITLE
[Bug]: Intersection types not supported

### ISSUE THREAD

**Issue by ekvedaras** [laravel-idea/plugin#571]
### Bug description

Eloquent helper code is not generated correctly when intersection types are used.

### Plugin version

5.5.0.222

### Operating system

MacOS

### Steps to reproduce

Define a scope on model:

```php
class User extends Model {
    public function scopeUsingIntersection(Builder $query, SomeClass & SomeInterface $object): void
    {
        // ...
    }
}
```

Generated helper code will be `usingIntersection(SomeClass $object)`

**Comment by adelf** [comment]
Hi, Ernestas.

I suddenly realized that PhpStorm doesn't understand this phpDoc:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/2818394/175771885-11b63577-da95-494e-9ca0-2dc862df3c73.png">

So, what I can suggest? "|" instead? Will it be ok?
```php
/**
 * @method void someName(\SomeInterface|\SomeClass $type)
 */
```

**Comment by ekvedaras** [comment]
Interesting 🤔 It does support those types when defined on a method. Maybe only in EAP?

**Comment by ekvedaras** [comment]
But yes, at least pipe would do for now then

**Comment by adelf** [comment]
> Maybe only in EAP?

That screen was from EAP :) For some reason, they forget about phpDoc @method. However, @property works well.
```
/**
* @property \SomeInterface & \SomeClass $some
*/
```

**Comment by ekvedaras** [comment]
Not sure what to do here then 😀 I can make an issue in their tracker if not already there. We could either go with | or wait for the fix. Either is fine for me 🙂

**Comment by adelf** [comment]
https://youtrack.jetbrains.com/issue/WI-62217/Support-intersection-types-for-method

The issue already exists. So, for now, I've implemented "|" for these cases. Will be in the next version. I suppose I can close this when it will be released :)

**Comment by adelf** [comment]
Laravel Idea 5.6 is out.
