### ISSUE TITLE
[Feature Request]: Column completion for factory createQuietly and related methods

### ISSUE THREAD

**Issue by dmason30** [laravel-idea/plugin#572]
### Feature Description

We get column completion for `Model::factory()->create(['my_colum|...' => $model->...])`.

However, in the latest version we do not get column completion for the following methods:

```php
Model::factory()->createQuietly([]);
Model::factory()->createManyQuietly([]);
Model::factory()->createOneQuietly([]);
```

**Comment by adelf** [comment]
Implemented. Laravel Idea 5.6 is out.
