### ISSUE TITLE
[Bug]: HasFactory warning of missing factory incorrectly

### ISSUE THREAD

**Issue by dcaswel** [laravel-idea/plugin#575]
### Bug description

I have started using the request factories package found at https://github.com/worksome/request-factories. This package has an option to use a trait called HasFactory which works very similarly to the same trait in Laravel's models but it is used in a Form Request so you can call something like `EditUserRequest::factory()` in order to create a request factory. When I add that trait to a request, however, I'm getting a message saying that the factory is missing because it is looking for a model factory. I'm wondering if it's possible to make it so that inspection only looks for a corresponding factory if the trait is the Laravel trait found at `\Illuminate\Database\Eloquent\Factories\HasFactory`. What would be even better is if the trait is the Laravel trait, it looks for the model factory and if the trait is `\Worksome\RequestFactories\Concerns\HasFactory` it looks for a request factory.

### Plugin version

5.5.0.221

### Operating system

MacOS

### Steps to reproduce

1. Create a Laravel application and composer require `worksome/request-factories`
2. Create a Form Request and use the `\Worksome\RequestFactories\Concerns\HasFactory` trait on it.
3. At this point, you should see the inspection warning.
4. Ideally, I would like it if you can now create a Request Factory for your Form Request and the warning goes away

**Comment by adelf** [comment]
Thank you. Fixed.

**Comment by dcaswel** [comment]
Wow, that was fast! I will look forward to the next release. Thank you!

**Comment by adelf** [comment]
Laravel Idea 5.6 is out.
