### ISSUE TITLE
[Feature Request]: Add a smart action to convert lines like "UserController@store" to "[UserController::class, 'store']"

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#576]
It would very useful if you could add an action that converts lines like  `UserController@store` to `[UserController::class, 'store']`. 

This would greatly help in modernizing legacy projects that were created several years ago and still use the 'old' syntax. If it were as easy as a smart action, I'd update syntaxes much more often.

Would be very nice if you could consider this. Thanks!

**Comment by adelf** [comment]
I like this idea.
Maybe better will be to convert a whole file?

**Comment by ralphjsmit** [comment]
Converting a whole file is also a great idea!

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1547892296317751305 )

**Comment by ralphjsmit** [comment]
Awesome Adel 🔥

**Comment by adelf** [comment]
Thanks, Ralph. It might help a lot of developers and was pretty easy to implement.

**Comment by adelf** [comment]
5.7 is out!

**Comment by ralphjsmit** [comment]
Thanks!
