### ISSUE TITLE
UI issue on settings

### ISSUE THREAD

**Issue by Naxon** [laravel-idea/plugin#58]
![image](https://user-images.githubusercontent.com/293026/82354875-17ed4e80-9a0a-11ea-9b8a-865a72e7bd1c.png)

As you can see in the screenshot, there an odd overlay hiding code generation fields after the latest update.

PHPStorm 2020.1.1

**Comment by adelf** [comment]
Yes. Thank you. Already fixed it. New version will be released tomorrow.

**Comment by adelf** [comment]
Fixed in 3.0.3 version. Thanks again.
