### ISSUE TITLE
[Bug]: Reformat code in Blade files removes FQDNs and breaks code

### ISSUE THREAD

**Issue by Francismori7** [laravel-idea/plugin#580]
### Bug description

Detailed here: https://youtrack.jetbrains.com/issue/WI-67458/BLADE-FILES-Reformat-code-removes-FQDNs-and-breaks-code

Consider the following blade file:
`index.blade.php`

```php
<x-layout.dashboard title="{{ $title }} - Détail - Rapports">
    <x-report-form :report-name="$title"
                   report-type="retail"
                   :action="[\App\Http\Controllers\Reports\Retail\TireSalesAlignment\TireSalesAlignmentController::class, 'store']"
                   method="POST">
```

Running the REFORMAT CODE action (CTRL+ALT+SHIFT+L) with the following options selected:
![image](https://user-images.githubusercontent.com/520647/178014937-35a1aec9-f029-423e-834f-ba606d09ed18.png)

The file will be reformatted with the following FQDN being removed, and therefore broken:

```php
<x-layout.dashboard title="{{ $title }} - Détail - Rapports">
    <x-report-form :report-name="$title"
                   report-type="retail"
                   :action="[TireSalesAlignmentController::class, 'store']"
                   method="POST">
```

![image](https://user-images.githubusercontent.com/520647/178015009-8a976a7a-f571-4640-9e24-40a2daffa773.png)

I believe the Code cleanup option removes the FQDN thinking it can import it, but it doesn't.

It could import it like so:

```php
@php use \App\Http\Controllers\Reports\Retail\TireSalesAlignment\TireSalesAlignmentController; @endphp
```

At the top of the file.

\---

PS-222.3244.18, JRE 17.0.3+7-b469.16x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 7680.0x4320.0, 6720.0x3780.0, 6720.0x3780.0

### Plugin version

5.6.1.222

### Operating system

Windows

**Comment by adelf** [comment]
Seems, they fixed it. Closing.
