### ISSUE TITLE
[Feature Request]: Support for barryvdh/laravel-dompdf

### ISSUE THREAD

**Issue by abordage** [laravel-idea/plugin#583]
### Feature Description

Package: [barryvdh/laravel-dompdf](https://github.com/barryvdh/laravel-dompdf)

Need support `go to view` on click

![image](https://user-images.githubusercontent.com/28537731/178767273-321ce0ea-c5b0-4792-b062-5a1831ad66c3.png)

**Comment by adelf** [comment]
Should work in 5.7
