### ISSUE TITLE
[Feature Request]: Autocomplete public properties in blade file

### ISSUE THREAD

**Issue by roerlemans** [laravel-idea/plugin#587]
### Feature Description

It would be nice if autocompletion was available in component blade files for public properties. For example:

<img width="508" alt="Schermafbeelding 2022-07-20 om 21 25 29" src="https://user-images.githubusercontent.com/14876955/180065486-e3a8ef59-fb36-4196-9593-f5315ffd5958.png">

Now it only completes: 
<img width="636" alt="Schermafbeelding 2022-07-20 om 21 25 42" src="https://user-images.githubusercontent.com/14876955/180065492-cc6e14ac-8c6e-40fa-a70b-360a72b18109.png">

**Comment by adelf** [comment]
Seems, the `Header` class is not in `App\View\Components\Layout` namespace, right?

**Comment by roerlemans** [comment]
@adelf Oops, you're right. Thank you.

**Comment by adelf** [comment]
Actually, it should also work, so I've fixed it. Thank you.
