### ISSUE TITLE
[Feature Request]: Spatie Data and a way to create simple action class

### ISSUE THREAD

**Issue by dgagn** [laravel-idea/plugin#589]
### Feature Description

First off, I am saving so much time using your plugin. However, I am constantly creating new class with the phpstorm new class option for the data transfer objects with a specified template. Thanks

[laravel-data](https://spatie.be/docs/laravel-data/v2/introduction).

**Comment by adelf** [comment]
Hi. In which namespace should they be created? It seems it's too project-specific...

**Comment by dgagn** [comment]
> Hi. In which namespace should they be created? It seems it's too project-specific...

I was able to create custom templates. Thanks

**Comment by adelf** [comment]
Anyway, I've added some support for this package :)

https://twitter.com/freekmurze/status/1554107941413855235
