### ISSUE TITLE
[Feature Request]: Shortcut for find migration, policy etc

### ISSUE THREAD

**Issue by vaiil** [laravel-idea/plugin#590]
### Feature Description

![image](https://user-images.githubusercontent.com/3755615/180746215-90053c2a-b8c3-4015-bb22-1a122349e20a.png)

Do you have shortcut for it (or can I set it up)? Couldn't find it in the keyboard settings.

**Comment by adelf** [comment]
<img width="122" alt="image" src="https://user-images.githubusercontent.com/2818394/180750213-43b58492-cc8a-43df-babb-0a172b24346b.png">
It's a "Related Symbol" shortcut. Double Shift will help to find.

**Comment by vaiil** [comment]
Thanks!
