### ISSUE TITLE
[Feature Request]: Horizon & Telescope middleware autocomplete

### ISSUE THREAD

**Issue by devmoath** [laravel-idea/plugin#591]
### Feature Description

It will be good addition when we have autocomplete for middleware array in horizon and telescope config file

![CleanShot 2565-07-26 at 13 51 03](https://user-images.githubusercontent.com/28797003/180989387-a909bec4-c134-460d-a4e7-dc1cbd90470f.png)

thanks 💙

**Comment by adelf** [comment]
Should work in the last update.

**Comment by devmoath** [comment]
thanks 💙
