### ISSUE TITLE
[Bug]: Livewire namespace

### ISSUE THREAD

**Issue by hamzaelmaghari** [laravel-idea/plugin#592]
### Bug description

Hi, @adelf
I just faced a problem with Laravel Idea, I don't know if this is a bug or mybe I'm the bug.

When I changed Livewire namespace, the GoTo featured doesn't work anymore.

It would be great to have a feature that enables us customizing the GoTo Livewire namespace.
<img width="418" alt="Screenshot 2022-07-27 at 03 50 47" src="https://user-images.githubusercontent.com/84163115/181151704-1b456b5a-9045-45da-a0ab-429f56180fc8.png">

### Plugin version

5.7.1.221

### Operating system

MacOS

**Comment by adelf** [comment]
Hi, Hamza.

Do you mean you use another tag prefix? Like `<myprefix:component...>`?

**Comment by hamzaelmaghari** [comment]
> Hi, Hamza.
> 
> Do you mean you use another tag prefix? Like `<myprefix:component...>`?

Yes exactly ... I haven't tried blade syntax, I did use @livewire('component') and it couldn't work.
Sorry for the delay

**Comment by adelf** [comment]
Since, 5.7.3 version.

<img alt="image" src="https://user-images.githubusercontent.com/2818394/182406236-65c28ef8-80d9-4d05-960d-3f1a3f7b3263.png">

**Comment by hamzaelmaghari** [comment]
> Since, 5.7.3 version.
> 
> ![image](https://user-images.githubusercontent.com/2818394/182406236-65c28ef8-80d9-4d05-960d-3f1a3f7b3263.png)

Thanks for giving that option ... I'll be always here if there is something needs to be contributed

**Comment by hamzaelmaghari** [comment]
Unfortunately, we got an issue with that.
When generating new livewire component using Laravel Idea ( with: changed namespace to "example" ), it creates component with the prefix of `App\Http\Livewire\ExampleComponent.php` .
