### ISSUE TITLE
[Feature Request]: Allow colon as first separator

### ISSUE THREAD

**Issue by Balsakup** [laravel-idea/plugin#593]
### Feature Description

Allow blade component auto-completion with colon as first separator.  

Taylor added this feature here https://github.com/laravel/framework/commit/dfff0dd133eff56b93dbc27f61f15fb4882fcfbc

**Comment by Okipa** [comment]
+1 for this

**Comment by adelf** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/2818394/206895882-0e2e2f09-833e-42ac-9c52-03bcb679ccac.png">

**Comment by adelf** [comment]
Please try the new version 6.2.3 and this setting.


<img alt="image" src="https://user-images.githubusercontent.com/2818394/212746277-42346411-57f5-435d-8974-e33eae5759df.png">
