### ISSUE TITLE
[Feature Request]: Support wrapper function for `action()`

### ISSUE THREAD

**Issue by skeets23** [laravel-idea/plugin#594]
### Feature Description

Our project has a wrapper function for all `action()` calls. So instead of calling:

`action("controller@method")`

we call this instead:

`Site::action("controller@method");`

Unfortunately, the plugin doesn't auto-complete the route names or allow for navigation with `ctrl+b` or `ctrl+click` when using this wrapper function.

It would be really great if there was an option to tell the plugin to treat `Site::action()` the same as `action()`.

**Comment by adelf** [comment]
You can do it by yourself. Add `ide.json` file to your project. Change YourNamespace to Site class full name.

```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "routeAction",
            "condition": [
                {
                    "methodNames": ["action"],
                    "classFqn": ["\\YourNamespace\\Site"]
                }
            ]
        }
    ]
}
```

**Comment by skeets23** [comment]
Brilliant! Thank you, that's perfect.
