### ISSUE TITLE
[Bug]: whereNotIn has "Unknown Column" inspection on array literal values

### ISSUE THREAD

**Issue by SaintPeter** [laravel-idea/plugin#595]
### Bug description

I am building an Eloquent Query on a model, using the `whereNotIn` with an array literal:

```php
 $query->whereNotIn('status', ['3DMeasureLost', 'InspectionLost', 'LeadLost', 'LeadSpam', 'ShowroomLost']);
```
The first string value in the array shows an 'Unknown Column' inspection, despite the second parameter of the `whereNotIn` being the `values` parameter.
![image](https://user-images.githubusercontent.com/553494/182905423-1caf8e04-45d5-4f2a-8ed7-a2f8ee80c3ed.png)

Note that if I delete the first element ("3DMeasureLost" in this case), the new first element ("LeadLost") gets highlighted for the same error.

### Plugin version

5.7.3.221

### Operating system

Windows

### Steps to reproduce

See above.  I have not spun up a new Laravel app to check this, but my current app is pretty new and not especially complex.

**Comment by adelf** [comment]
It's probably from this plugin - https://plugins.jetbrains.com/plugin/16309-laravel-query

**Comment by SaintPeter** [comment]
You were correct.  Disabling that plugin resolved the issue.  Thanks!
