### ISSUE TITLE
[Feature Request]: Add abilities (gate names) support to ide.json

### ISSUE THREAD

**Issue by filhocodes** [laravel-idea/plugin#597]
### Feature Description

In the same way we can add config or route completions to custom methods, I want to add abilities names (the ones that are suggested for methods like `can()` and `Gate::allows()`)

**Comment by adelf** [comment]
Try this ide.json:
```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "gate",
            "condition": [
                {
                    "methodNames": ["gate"],
                    "classFqn": ["\\YourNamespace\\ClassName"]
                }
            ]
        }
    ]
}
```

It will complete gates for `\YourNamespace\ClassName::gate` calls. Please write if you want another condition. I'll publish full documentation about this ide.json format soon.

**Comment by filhocodes** [comment]
@adelf It worked <3 Thanks!
