### ISSUE TITLE
[Question] Get translation suggestion from a package

### ISSUE THREAD

**Issue by carvemerson** [laravel-idea/plugin#598]
Hello, I started to use this plugin recently, and I'm trying to configure the translation suggestion, but without success. 

I have a project, but all translations are on a package. 
Is it possible to configure this plugin to use the translations from a specific package or folder from vendor directory?

The location of my translation looks like:

project-root\vendor\my-packages\package-translationsl\src\resources\lang

I would like to get the translations from that folder, and, if possible, use that folder as target when generating new translation keys througth the ![image](https://user-images.githubusercontent.com/6718864/183261740-ec2b1bae-fc3b-433f-95f2-c1c3198bac7a.png) feature. 

Thanks in advance

**Comment by adelf** [comment]
Hello.

Could you share how you register this lang folder in the service provider?

**Comment by carvemerson** [comment]
Hi @adelf ,  on the package service provider we do:

![image](https://user-images.githubusercontent.com/6718864/183405325-1af34d2e-6b03-4193-9751-2864ff64c62d.png)

The service provider is located here:

project-root\vendor\my-packages\package-translationsl\src

Then I just use it on the providers of my root project.

**Comment by carvemerson** [comment]
Hi @adelf , is there anything that I can do to make it work properly?

**Comment by adelf** [comment]
Hi. Not in the current version. I'm trying to make it possible now.

**Comment by adelf** [comment]
This new configuration panel has appeared in the new 5.8 version. You can setup your namespace and directory there.

<img alt="image" src="https://user-images.githubusercontent.com/2818394/189540318-7761b6df-210a-406a-9d0a-5e86284a2b07.png">
