### ISSUE TITLE
[Bug]: Builder instance required in `withTrashed` with model relationship

### ISSUE THREAD

**Issue by devmoath** [laravel-idea/plugin#599]
### Bug description

PhpStorm show that builder instance is required when you call `withTrashed` with relationship in a Model (e.g. `hasMany`, `belongsTo` ...).

![CleanShot 2565-08-07 at 07 29 26@2x](https://user-images.githubusercontent.com/28797003/183275471-c6d4089f-cb7f-4efd-969b-b97062fc6ff1.png)

### Plugin version

5.7.3.221

### Operating system

MacOS

### Steps to reproduce

1. Create new project with `laravel new project-name`
2. Create additional model for example `Post`
3. Setup the relationship between `User` and `Post` and chain the relationship function with `withTrashed`
4. PHPStorm will ask you to pass the builder instance to the function

### Relevant log output

```shell
N/A
```

**Comment by devmoath** [comment]
I believe the issue has been fixed. thanks 
![P2yu1F9r](https://user-images.githubusercontent.com/28797003/207444383-7ca6e030-330d-486c-a10e-c0b7cdffd4c8.png)

**Comment by adelf** [comment]
Yes. Sorry, forgot about it.
