### ISSUE TITLE
Feature request: Code generation for move strings to langpack

### ISSUE THREAD

**Issue by KAZAHTIP2007** [laravel-idea/plugin#6]
Code generation for string's in blades/controllers/mailables/etc. With ability to configure style of lang keys/groups/etc. Having such a feature was very good. I'm search this plugin has long been.

## From:
> ![image](https://user-images.githubusercontent.com/59795836/72219689-d4656e00-3559-11ea-8ca4-5e065842eeb3.png)
> ![image](https://user-images.githubusercontent.com/59795836/72219693-ddeed600-3559-11ea-9c03-b43deebed93d.png)
> ![image](https://user-images.githubusercontent.com/59795836/72219699-ea732e80-3559-11ea-9eed-3fdd3924ec39.png)

## To: 
> ![image](https://user-images.githubusercontent.com/59795836/72219756-74bb9280-355a-11ea-997a-775ebebe8265.png)
> ![image](https://user-images.githubusercontent.com/59795836/72219758-7b4a0a00-355a-11ea-9f84-e0d09033a0b1.png)
> ![image](https://user-images.githubusercontent.com/59795836/72219763-8735cc00-355a-11ea-8656-6f5810f778c0.png)

**Comment by laravel-idea** [comment]
Hi. This feature is already in my Trello :) But thanks anyway. I'll move it
upper.

**Comment by KAZAHTIP2007** [comment]
Where i'm can see what in trello?

**Comment by laravel-idea** [comment]
Sorry, it's private. There are about 60 tasks. Maybe it's a good idea to
make some close goals public...

**Comment by adelf** [comment]
Hi again @KAZAHTIP2007 . 
I'm thinking about this feature. Imagine we have 45 languages in the project. Extracting selected string to the English locale is ok, what about other 44? Create empty strings there? What do you think?

**Comment by KAZAHTIP2007** [comment]
Extract to 'fallback locale' by default or user can set a default locale, but can optionally create empty keys in another locales. Make a in-IDE warnings/notices about empty locales. 

But I think that the "fallback locale" plays a role enough, so this should be done optionally

**Comment by adelf** [comment]
Plugin already has "Default language" option('en' by default). It can be used here. Ok., I'll try to implement this feature in the nearest major update.

**Comment by adelf** [comment]
![translation](https://user-images.githubusercontent.com/2818394/72665750-5eab4780-3a1c-11ea-9f24-50ddc0427659.gif)
:)

**Comment by KAZAHTIP2007** [comment]
Cool! Also, it would be a good choice between ```trans()``` and  ```__()```

**Comment by adelf** [comment]
Sure. It will be a setting.

**Comment by andrey-helldar** [comment]
Nice feature!

**Comment by KAZAHTIP2007** [comment]
When can I wait for this update?

**Comment by adelf** [comment]
I hope this week.

**Comment by adelf** [comment]
Implemented in 2.0. Thanks.
