### ISSUE TITLE
[Bug]: Autocompletion not working when using arrow function in model factory

### ISSUE THREAD

**Issue by devmoath** [laravel-idea/plugin#600]
### Bug description

PHPStorm does not give any autocompletion for state attributes in model factory when using arrow function.

https://user-images.githubusercontent.com/28797003/183276056-3612651a-e9d7-4674-af0a-babb652ce524.mp4

### Plugin version

5.7.3.221

### Operating system

MacOS

### Steps to reproduce

1. create new project with `laravel new project-name`
2. go to UserFactory and change the anonymous function under `unverified` to arrow function
3. the autocompletion is gone

### Relevant log output

```shell
N/A
```

**Comment by adelf** [comment]
Fixed. Thanks.
