### ISSUE TITLE
[Bug]: Factory magic relationship methods require `$attributes` while its optional

### ISSUE THREAD

**Issue by devmoath** [laravel-idea/plugin#601]
### Bug description

Based on the docs [here](https://laravel.com/docs/9.x/database-testing#has-many-relationships-using-magic-methods) the `$attributes` of the factory magic relationship methods is optional.

### Plugin version

5.7.3.221

### Operating system

MacOS

### Steps to reproduce

1. create new project with `laravel new projec-name`
2. create additional model e.g. `Post`
3. setup the relationship between `User` and `Post` as `HasMany` relationship
4. generate helper code
5. anywhere in the project write `User::factory()->hasPosts(5)->create();`
6. PHPStorm will ask you to pass `$attributes` to `hasPosts` function 

### Relevant log output

```shell
N/A
```

**Comment by adelf** [comment]
Fixed. Thanks.

**Comment by adelf** [comment]
Fixed in the 6.1 release. Thanks.
