### ISSUE TITLE
[Bug]: incorrect void return type for dispatch method

### ISSUE THREAD

**Issue by stidges** [laravel-idea/plugin#602]
### Bug description

Since recently it has become possible to generate auto-complete helpers for the `dispatch` method for classes using Laravel's `Dispatchable` trait. However, right now the return type for the method is generated as `void`, but it actually returns a `\Illuminate\Foundation\Bus\PendingDispatch` class which allows you to customize the dispatch further. Is it possible to update the return type in the `_ide_helper_dispatches.php` file?

### Plugin version

5.7.3.221

### Operating system

MacOS

### Steps to reproduce

1. Create a Job class which uses the `Dispatchable` trait
2. Generate the helper code
3. Check the `_ide_helper_dispatches.php` file
4. The `dispatch` method is shown having a `void` return type

**Comment by abkrim** [comment]
For me is the same issue.

I use macOS Monterey and the latest plugin version 5.7.3.221

Code work fine (I'm developing with tests) and the test asserts my code sends four jobs dispatched with delay XXXXX.

![castris 2022-08-21 a las 8 59 15](https://user-images.githubusercontent.com/1238625/185779648-13ad5fff-0948-4239-bf15-33ec100cc3aa.jpg)

**Comment by adelf** [comment]
This will be fixed. Thanks.

**Comment by adelf** [comment]
Fixed in the 6.1 release. Thanks.
