### ISSUE TITLE
[Feature Request]: InertiaJs component autocomplete

### ISSUE THREAD

**Issue by hamzaelmaghari** [laravel-idea/plugin#605]
# Hi there,
It could be better if added InertiaJs Vue component autocomplete, I think this feature will boost the plugin.

Thanks,

**Comment by adelf** [comment]
Hi. Where they should be completed?

**Comment by hamzaelmaghari** [comment]
> Hi. Where they should be completed?

I think inside controllers & routes.

**Comment by adelf** [comment]
I complete them for calls like `Inertia::render('<caret>');`
Maybe you have a non-standard configuration. Check it in the Preferences | Languages & Frameworks | Laravel Idea | Laravel Packages

**Comment by hamzaelmaghari** [comment]
> 

Oh, that's right I went to use to helper ````inertia('<caret>')````
Shouldn't this helper have this feature too?

**Comment by adelf** [comment]
It has. Maybe your component's path is a bit non-standard. Check it here: Preferences | Languages & Frameworks | Laravel Idea | Laravel Packages | Inertia

**Comment by hamzaelmaghari** [comment]
### Works
Thanks
