### ISSUE TITLE
[Feature Request]: Navigate to translation from custom method

### ISSUE THREAD

**Issue by zoispag** [laravel-idea/plugin#606]
### Feature Description

Following up on the conversation on Twitter: I have a PHP Attribute that I use in enum cases, that receives a single string argument, that is fed to the `__()` function, to get localized strings. Is it possible to instruct Laravel IDEA to follow translations from custom methods/constructors? 

And how can I share it with my team?

Thanks 🙏🏻

**Comment by adelf** [comment]
Could you try this ide.json?

```json
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "translationKey",
            "condition": [
                {
                    "parameters": [1],
                    "newClassFqn": ["\\Namespace\\YourClassName"]
                }
            ]
        }
    ]
}
```

**Comment by zoispag** [comment]
It works like a charm!

<img src="https://media2.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>
