### ISSUE TITLE
[Feature Request]: Vscode integration

### ISSUE THREAD

**Issue by hamzaelmaghari** [laravel-idea/plugin#607]
### Feature Description

Hi,

These days I become very interested in this plugin ````LARAVEL IDEA```` and I got a question ( why not Vscode? ).

Do you see this idea valuable?

**Comment by adelf** [comment]
Hi. It's hard. 
VS code understanding of PHP is not as good as PhpStorm's. So, I don't know when it could happen.

**Comment by hamzaelmaghari** [comment]
> Hi. It's hard. VS code understanding of PHP is not as good as PhpStorm's. So, I don't know when it could happen.

Yes, that was the reason why I started using Phpstorm <3

**Comment by damms005** [comment]
It's happening. I've been wanting to do this for a while now, but after the progress I made with [DevDb](https://marketplace.visualstudio.com/items?itemName=damms005.devdb) and what I learnt from there, I have now started this.

![image](https://github.com/laravel-idea/plugin/assets/9839355/77e6c812-69bc-4c71-b1a2-572f1d56aa03)

**Comment by adelf** [comment]
@damms005 I'm happy you are working on this extension, but don't call it "Laravel Idea".  Choose you own name.

**Comment by damms005** [comment]
Got it. Many thanks 🙏

**Comment by beshoo** [comment]
Am not fan of vscode , but since cursor Ai , using vscode , then we have a strong reason why to use vscode.

I believe it is time to look into supporting vscode very seriously @adelf
