### ISSUE TITLE
Code completion for getOriginal attributes

### ISSUE THREAD

**Issue by sykorax** [laravel-idea/plugin#61]
Hey there,

Just realized the plugin does not offer code completion for the ```getOriginal($attr)``` method.
Can we have it? :)

- a really satisfied customer here

**Comment by adelf** [comment]
Hi. Thank you. Of course, there are a lot of places where plugin can complete. I can't find them all without plugin users help :) Will be added to the next release.

> a really satisfied customer here

👍 :)

**Comment by adelf** [comment]
Implemented in 3.0.4. Thanks :)
