### ISSUE TITLE
[Bug]: Table not found if add other connection

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel-idea/plugin#610]
### Bug description

Table not found for \App\Models\User 

### Plugin version

5.7.3.221

### Operating system

MacOS

### Steps to reproduce

class User extends Authenticatable
{
     protected $connection = 'other connection';
}

Generate Helper Code

**Comment by adelf** [comment]
Hi. What do you use to fetch tables? Migrations or Connection?

**Comment by CrazyBoy49z** [comment]
Connection

**Comment by adelf** [comment]
You can use multiple databases there. Have you tried it? main menu - Laravel - Helper Code Parameters...

**Comment by CrazyBoy49z** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3448603/185253849-b851f8a7-b4d4-4a6a-954b-2667682e2dff.png">
Maybe the problem is something else

**Comment by CrazyBoy49z** [comment]
> You can use multiple databases there. Have you tried it? main menu - Laravel - Helper Code Parameters...

Thanks this fixed my problem
