### ISSUE TITLE
[Feature Request]: Auto-complete model properties with Eloquent model methods

### ISSUE THREAD

**Issue by hagishi** [laravel-idea/plugin#615]
### Feature Description

Plugin version
5.7.3.221

Operating system
MacOS

PhpStorm Version
2022.2.1

<img width="480" alt="image" src="https://user-images.githubusercontent.com/473379/185724559-66d7ea9c-9e30-485e-86ac-9e7887a920ec.png">

Is it possible to auto-complete model properties with Eloquent model methods?

**Comment by adelf** [comment]
Fixed in the 6.1 release. Thanks.
