### ISSUE TITLE
[Bug]: plugin not working for blade files on phpstorm 2022.2.1 laravel 9.25

### ISSUE THREAD

**Issue by isimmons** [laravel-idea/plugin#618]
### Bug description

I create a new project with `laravel new testproject`
Then I create new project from existing files in phpstorm
Then I generate helper files and run npm install for dependencies.
I create a components directory and a test component 'test.blade.php'
Then in the default 'welcome' view I type `x-test` or `<x-test`

Expected: 
I expect to see laravel idea helper show my test component for selecting.
I also expect phpstorm to recognize `<x-test/>` 
Also if I return a non existent view in my routes file I expect to see a helper option to create the new view

What happens:
I see no sign that the plugin exists at all when inside a blade file
I see no helper menu
I get warnings from PHPStorm 'unknown html tag x-test' and 'empty html tags dont work in some browsers
If I return a non existent view in my routes file I see what I think is just phpstorm option to create a new view but no real sign that the laravel idea plugin is involved here. No laravel icon in other words so I'm not sure if phpstorm does this by default without the plugin.

If there is extra setup in the documentation, it is not clear to me. The version I had several months ago just worked out of the box so I purchased a license. The licensed version continued to work but then I stopped developing for a few months. I just started back and updated everything (PHPStorm, Laravel Idea plugin, and Laravel) to the latest.

### Plugin version

5.7.3.221

### Operating system

Windows

### Steps to reproduce

Open Terminal to code directory.
Create new laravel project with `laravel new testproject`
Open PHPStorm and create new project from existing files.
Choose the new laravel project directory
After project creation run the Laravel Idea plugin option to create helper files
Create a components directory  `resources/views/components`
Create `resources/views/components/test.blade.php`
Go to the default project 'welcom' view and try to add `<x-test/>`

**Comment by adelf** [comment]
Hello, Ian.

Seems, Laravel Idea couldn't find Laravel in this app. Could you try to check Preferences | Languages & Frameworks | Laravel Idea. What's the state of the plugin?  Enabled/Disabled?
This can be fixed just by restarting PhpStorm...

**Comment by isimmons** [comment]
Hi Adelf,

The state of the plugin is "Current state: Enabled. Framework: laravel. Version 9.25"
The plugin is generating helper code in vendor/_laravel_idea and if I return a view from inside my routes file or a controller, the auto complete menu pops up showing me a list of views to choose from so that part is working. 

I can use Laravel>All Code Generations from the top menu to create components and views and it creates them in the correct components and views directories. 

Anything else I should check?

Thanks

**Comment by adelf** [comment]
Looks like the Blade plugin is not enabled. Preferences > Plugins > Blade

**Comment by isimmons** [comment]
I checked that the bundled blade plugin is enabled. I tried disabling and then re-enabling it, closing the project and then restarting each time.

Then I rolled back to an older version of PHPstorm and older compatible version of the Laravel Idea plugin. No change

Then I tried a fresh start.
I completely uninstalled PHPStorm, deleted all saved old versions for rollback, installed the latest version, installed Laravel Idea plugin, confirmed both it and the bundled blade plugin are enabled and the Laravel Idea plugin is the only plugin installed besides the ones that come bundled with PHPStorm. Then I closed out PHPStorm.

I created a new laravel app in terminal, ran npm install, tested artisan serve to confirm it is working, and then opened it with PHPStorm.

I chose to create Laravel Idea helper code when prompted.

Then I create a components directory and test component at resources/views/components/foo.blade.php with nothing but a div and h1 in it. I removed all the Laravel code from welcome.blade.php and then typed  `<x-foo` and I get nothing from Laravel Idea. I still get the warnings from PHPStrom that `<x-foo />` is an unknown tag and an empty tag

**Comment by isimmons** [comment]
I was able to resolve the issue by adding a file pattern in settings>Editor>File Types.

I found the solution [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010677440-Blade-Syntax-Not-Auto-completing-PhpStorm-2021-1-1-)

Fresh install of PHPStorm , by default had, "*.blade.php" assigned to HTML instead of Blade for some reason.

UPDATE: PHPStorm sets this file pattern to Blade file type by default. Apparently changing it to HTML is something I had done at some point in the past for some unknown reason. It was the cause of the issue and the setting carried over to the fresh install because I failed to remove stored IDE settings before reinstalling. [More info here](https://youtrack.jetbrains.com/issue/WI-68484/Need-to-associate-a-file-name-pattern-to-multiple-file-types)

Now everything Laravel Idea works but I lost the html auto complete suggestion dropdown from PHPStorm's bundled Html package. Emmet still works and if I type something like `h1` followed by tab key, it inserts a `<h1></h1>` so it's not a total loss on the Html side. 

I'll close this but please let me know if you have a better solution to keep both the full HTML support and Laravel Idea blade support.

Thanks
