### ISSUE TITLE
[Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version

### ISSUE THREAD

**Issue by jaygoodswp** [laravel-idea/plugin#623]
### Bug description

I have the paid version of Laravel Idea and with the plugin enabled, PhpStorm uses an insane amount of CPU time. My fans were at max speed all day yesterday. This morning, after disabling many plugins, I came across this one and disabled it and that fixed the issue. If it were a free plugin, then I wouldn't complain and would find something else but I've paid for a license. This started after updating PhpStorm to 2022.2.1 and then updating all of my plugins (Update All in Preferences / Plugins).

### Plugin version

5.7.3.221

### Operating system

MacOS

### Steps to reproduce

Enable the plugin and open a Laravel project.

### Relevant log output

```shell
Here is a link to a zip file containing all of the info I could get out of PhpStorm.

https://drive.google.com/file/d/1riT9JdhYPJhPPddbNk-3Owo8Ql4KTDXi/view?usp=sharing
```

**Comment by olivernybroe** [comment]
Do you perhaps have any other laravel plugins installed? They can sometimes collide in weird ways.

**Comment by jaygoodswp** [comment]
I disabled most of the plugins, except for Javascript and PHP. Do the logs that I sent show anything useful?

From: Oliver Nybroe ***@***.***>
Date: Friday, September 2, 2022 at 8:14 AM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, Author ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

Do you perhaps have any other laravel plugins installed? They can sometimes collide in weird ways.

**Comment by jaygoodswp** [comment]
Alright, so I disabled all plugins, except for Laravel Idea, and then re-enabled the ones I needed one at a time. I'm sure I'm missing some functionality but for now, the CPU usage is not spiking. I'll look each time I enable a plugin and try to report back if the symptoms return.
<img width="983" alt="Screen Shot 2022-09-05 at 11 02 40 AM" src="https://user-images.githubusercontent.com/9660340/188486589-3574b5b0-386d-4c67-8e01-d94f7a0feede.png">

**Comment by jaygoodswp** [comment]
I spoke too soon. The problem is back but only when I work on a particular project which has lots of code and lots of blade templates. So, it's like it's spending all of its time indexing. Right now, I have to turn off the plugin when working in this one project.

**Comment by jaygoodswp** [comment]
I updated to the latest version yesterday and this still happens on large projects. Can someone look at the indexing or similar to figure out why so much CPU is used and maybe put in a short delay in each iteration of the loop(s)?

**Comment by adelf** [comment]
hello, @jaygoodswp. I suppose sharing this project for me is not an option, right?

**Comment by jaygoodswp** [comment]
If the source code was mine, I would share it but it’s not ☹ It just has many, many, many blade files. The guy who wrote it, wrote it for re-use. Most templates are used more than once, hence the reason for doing it. I suspect the plugin is scanning these blade files. As for controllers, models, etc., there is an average amount and so  I don’t think it’s that. I have other projects with more controllers and models and the plugin works fine.

From: Adel ***@***.***>
Date: Sunday, September 11, 2022 at 12:09 PM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, Mention ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

hello, @jaygoodswp<https://github.com/jaygoodswp>. I suppose sharing this project for me is not an option, right?

**Comment by adelf** [comment]
You can try to profile indexing by yourself.

<img width="602" alt="Screenshot 2022-09-11 at 22 42 27" src="https://user-images.githubusercontent.com/2818394/189543918-2e75e595-6929-4153-9ef9-8a29a9599a99.png">

**Comment by jaygoodswp** [comment]
I’ve done that. It’s included in the files that I sent to you (same ones I sent to JetBrains).

From: Adel ***@***.***>
Date: Sunday, September 11, 2022 at 1:43 PM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, Mention ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

You can try to profile indexing by yourself.

[Screenshot 2022-09-11 at 22 42 27]<https://user-images.githubusercontent.com/2818394/189543918-2e75e595-6929-4153-9ef9-8a29a9599a99.png>

**Comment by adelf** [comment]
Thanks. I found one issue in these logs and fixed it. The next release will be published next week(13-20 Sep).

**Comment by jaygoodswp** [comment]
Awesome!!! Thank you so much!

From: Adel ***@***.***>
Date: Sunday, September 11, 2022 at 5:51 PM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, Mention ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

Thanks. I found one issue in these logs and fixed it. The next release will be published next week(13-20 Sep).

**Comment by jamiethorpe** [comment]
I'm using the 30 day trial and experiencing the same issue. Looking forward to a fix because so far this plugin is great.

Edit - For some extra context, I'm using Windows and WSL2, so it doesn't seem to be platform specific.

**Comment by jaygoodswp** [comment]
I knew it had to be affecting more than me? Can we get a release sooner since this can be considered critical since the plugin can’t be used in its current state?

From: jamiethorpe ***@***.***>
Date: Tuesday, September 13, 2022 at 12:09 PM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, Mention ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

I'm using the 30 day trial and experiencing the same issue. Looking forward to a fix because so far this plugin is great.

**Comment by adelf** [comment]
Could try the new 5.8.2 release and check?

**Comment by jaygoodswp** [comment]
Yes and it worked beautifully. I've had the large project open for 2 hours now and CPU usage is normal. Thank you so much - I really appreciate!

**Comment by adelf** [comment]
Thank you, @jaygoodswp. Your log files really helped.

**Comment by jamiethorpe** [comment]
@adelf @jaygoodswp 
I had success for about 4 hours and then had it start happening again, but not quite as bad as before. This time it would spike the CPU to 75-80% instead of almost 100%. 

[idea.laravel-idea.log](https://github.com/laravel-idea/plugin/files/9568993/idea.laravel-idea.log)

Edit - CPU started jumping to 100% as well, but it's not happening as much as before.

Adding my system specs in case that's of use

![image](https://user-images.githubusercontent.com/6597612/190237286-f1fcb4c3-a375-42e9-8955-eab29707eb48.png)

**Comment by jaygoodswp** [comment]
And I'm actually having problems with the index not refreshing after the update. This is on the large projects.

**Comment by jaygoodswp** [comment]
Additionally, after noticing that the index was not refreshing, I noticed that the CPU was pegged again, between 200 and 450%.

**Comment by adelf** [comment]
@jamiethorpe I only see a lot of messages from copylot in the log and it took about 11 second to index everything after startup at 9:30 today.

**Comment by jaygoodswp** [comment]
This is a cool plugin and all - I love the features - but if it doesn't work correctly for large projects, it's not useful for me. I'm sure it could be lots of things (we're all developers, right?) but maybe you could just add a few millisecond delay in the loops that refresh the index?

**Comment by adelf** [comment]
It's hard to debug such issues. "Indefinite indexing" still continues?

These can help to get some info: 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/2818394/190374511-a6fbec49-6ac1-4892-84ab-5bfd04667b01.png">

And maybe "Activity monitor..." at the same menu.

**Comment by jamiethorpe** [comment]
@adelf I also didn't see much in the logs that would be helpful. I'll continue working with the plugin and will let you know if I experience the issue again today. I didn't see that it was actually during indexing that the CPU was spiking, but I'll try to keep an eye on that and I'll run the Indexing Diagnostics and Activity Monitor if it occurs. I can definitely say your last update improved things.

**Comment by jaygoodswp** [comment]
I understand that it’s difficult to troubleshoot. I’m just asking that a delay be added to the loops so that when it does get to the bug, it doesn’t completely spike the CPU usage. Just a simple sleep(10); // milliseconds – on each iteration can make all the difference.

From: Adel ***@***.***>
Date: Thursday, September 15, 2022 at 4:55 AM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, State change ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

It's hard to debug such issues. "Indefinite indexing" still continues?

These can help to get some info:
[image]<https://user-images.githubusercontent.com/2818394/190374511-a6fbec49-6ac1-4892-84ab-5bfd04667b01.png>

And maybe "Activity monitor..." at the same menu.

**Comment by jamiethorpe** [comment]
Here's what I received from the Activity Monitor when the CPU started spiking:

812.6  <Process total CPU usage>
127.8  <unidentified: JobScheduler FJ pool>
101.4  lang.impl (in com.intellij)
 53.7  Plugin PHP: php.lang.parser (in com.jetbrains)
 28.1  <JIT compiler>
 25.7  Plugin PHP: php.lang (in com.jetbrains)
 21.9  Plugin PHP: php.lang.lexer (in com.jetbrains)
 18.2  lang (in com.intellij)

I'll try to gather more info throughout the day.

**Comment by jamiethorpe** [comment]
I also took a memory snapshot and profiled the CPU from within PHPStorm. Hopefully these will help.

https://drive.google.com/file/d/1ThohK2palLH2dNidP7wLPyr3WB-Mf-lu/view?usp=sharing
https://drive.google.com/file/d/1nViVlbMLfXUxxEGgy7P4HWfEaPVvdMWu/view?usp=sharing

**Comment by adelf** [comment]
One user provided me with a project where he experience CPU spikes. 
I've found a feature which can be a reason for them. Testing it now.

**Comment by jamiethorpe** [comment]
@adelf Any luck so far? My trial is almost up and I really like the plugin, but it's tough to use when it maxes out the CPU.

**Comment by jaygoodswp** [comment]
Same for me. I paid for a license and it’s unusable at this point (it stays disabled).

From: jamiethorpe ***@***.***>
Date: Wednesday, September 28, 2022 at 2:16 PM
To: laravel-idea/plugin ***@***.***>
Cc: jay goodswp.com ***@***.***>, State change ***@***.***>
Subject: Re: [laravel-idea/plugin] [Bug]: PhpStorm CPU Usage ranges from 100% to 500% with paid version (Issue #623)

@adelf<https://github.com/adelf> Any luck so far? My trial is almost up and I really like the plugin, but it's tough to use when it maxes out the CPU.

**Comment by adelf** [comment]
I'll release a new version tomorrow.
I can't find a reason for this, so I'll just add some options to turn off some of my features. I hope it'll help you right now and maybe give me some helpful info...

**Comment by adelf** [comment]
Please, try the 6.0 version.
I optimized PHP type recognition and turned it off during indexing. I hope it will help. Also, if it won't help, it can be fully turned off here:

<img src="https://user-images.githubusercontent.com/2818394/193255068-a53427c8-98d4-4f6d-ad2a-dd20a986805f.png">

**Comment by jaygoodswp** [comment]
When will the new version be released?

**Comment by adelf** [comment]
It's already released.

**Comment by jaygoodswp** [comment]
Do you have any documentation or reference describing what these options do (just in case I have to disable)?

**Comment by jaygoodswp** [comment]
It's still happening with these options disabled. After bursting to ~300%, it remains constant at around 100% with occasional spikes at ~450%. Please see screen shots.
<img width="982" alt="Screen Shot 2022-09-30 at 8 58 30 AM" src="https://user-images.githubusercontent.com/9660340/193287262-72c23825-b671-4ee9-85ad-f6a8b9aa4ab0.png">
<img width="962" alt="Screen Shot 2022-09-30 at 9 01 14 AM" src="https://user-images.githubusercontent.com/9660340/193287281-dca45208-c6cb-4e5c-9ed3-8a4af8fd2423.png">
<img width="963" alt="Screen Shot 2022-09-30 at 9 02 11 AM" src="https://user-images.githubusercontent.com/9660340/193287293-c6914d41-3f83-4adc-a81a-bccd4cef360c.png">

I'm disabling the plugin AGAIN...

**Comment by jaygoodswp** [comment]
@adelf How do we install an older version of the plugin? Like, if I wanted to go three versions back (two versions before 5.8), in an attempt to get a version that doesn't peg the CPU. Thanks!

**Comment by adelf** [comment]
@jaygoodswp https://plugins.jetbrains.com/plugin/13441-laravel-idea/versions you can find needed versions here. 
"*.222" is for PhpStorm 2022.2, "*.221" is for PhpStorm 2022.1, etc.

I'm really sorry about that. Indexing is fully ruled by PhpStorm. However, it uses some plugin functions, but I don't know which one is the reason for this.

If you find a version without this bug, it might help me to investigate.

**Comment by wblondel** [comment]
Hi,

I also have this problem with very large Blade files (4000+ lines). I disabled inspections on Blade files, it improved the situation a bit BUT I still have massive CPU usage every time I make a change on these files, freezing the whole IDE. 

I am not sure if the problem is Laravel Idea or the bundled Blade plugin.

Any action in the IDE takes forever as long as I have a large Blade file open.

PhpStorm 2022.3.1
Build #PS-223.8214.64, built on December 22, 2022
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Laravel Idea 6.2.2.223

**Comment by jaygoodswp** [comment]
Hey William! I have found that I cannot use the plugin for large projects. It’s great for getting projects started, but for existing projects that have been around for a while and, as a result, have grown significantly, I have to disable the plugin. It seems that it’s difficult to debug, but there’s definitely a conflict happening between PhpStorm and the plugin.

**Comment by adelf** [comment]
You can try to do this to reduce CPU usage by plugin.

Turn off Laravel Idea inspections
<img width="246" alt="image" src="https://user-images.githubusercontent.com/2818394/211117231-ee6dc440-c855-4864-96e9-62b75ceefe95.png">

Turn off type providers:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/2818394/211117492-3104e4ed-3cd1-403f-82c1-0067c2359307.png">

Turn off some Eloquent features:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/2818394/211117546-828dd35c-fd27-45d3-a457-0e6d59c9fb53.png">

**Comment by jaygoodswp** [comment]
I just found this in PhpStorm.

1. Go to Help | Find Action
2. Type in Registry and click to open
3. Change the values below and see if it helps. I'll report back with my findings. I would try this before disabling the plugin features.
<img width="873" alt="Screen Shot 2023-01-07 at 11 14 37 AM" src="https://user-images.githubusercontent.com/9660340/211162648-fa8598ac-8b6c-459b-a68a-d80bc053f05e.png">

**Comment by jaygoodswp** [comment]
Update: That helped with the majority of my projects (together with the @adelf's suggestions). I still have one project that causes PhpStorm to use the max threads (2) all the time UNTIL I shut off the plugin. Once it's turned off, usage goes down to below 20%.

**Comment by ismaail** [comment]
Disabling the option `Blade variables type provider` in `Laravel Idea/Languages/Blade` solves the issue for me.

**Comment by marcusmoore** [comment]
Turning off `Implicit Eloquent method usages searcher (might use a lot of CPU resources)` did it for me.

FWIW, this [eloquent model](https://github.com/snipe/snipe-it/blob/f6a11ac0edba8525e09f1140eaf29f7c8a018769/app/Models/User.php) was the one I noticed the issue on the most.
