### ISSUE TITLE
[Bug]: Generated translation inside @php @endphp uses blade syntax

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#624]
### Bug description

When a translation is generated inside a blade @php/@endphp block

![image](https://user-images.githubusercontent.com/8792274/187869155-c6d5f473-6d67-4527-bae0-a9c32020bcab.png)

the generated code should not use blade curly braces:

![image](https://user-images.githubusercontent.com/8792274/187869236-3130e94b-5a2e-4f83-8b7a-8a7ff50c282c.png)

**Bonus**

the generated translation string contains `'` 

![image](https://user-images.githubusercontent.com/8792274/187869691-897453a4-40c4-428d-b7ec-b8c04e433dd4.png)

### Plugin version

5.7.3.221

### Operating system

Linux

**Comment by adelf** [comment]
Fixed in the 8.0.3 version. Thank you and sorry for long waiting :(
