### ISSUE TITLE
Move _ide_helper_models.php

### ISSUE THREAD

**Issue by OwenMelbz** [laravel-idea/plugin#63]
When generating the helper file, you're able to change the filename/location.

I tried to set this to `./idea/_ide_helper_models.php` to keep it out of GIT and out of search results, jump to, open anything etc, e.g. If you push "Cmd + O" and type "User" it gives you the `idea_helper_models.php` as a result which is fairly annoying.

However it doesn't work when in there - is it possible to make this work so we don't pollute various features with this file?

Thanks

**Comment by adelf** [comment]
Hi, Owen.

Yes, this behaviour is annoying. I'm working with PhpStorm team to remove these pseudo classes from everythere except completion, but it's not easy. The most work should be done from their side. I already removed "duplicate class declaration" warning from everywhere, except class declarations( issue - https://youtrack.jetbrains.com/issue/WI-53186 ).
The _ide* files... yes. Usually people just leave them in the root directory add it to .gitignore file... but when I was writing this answer I realized that there is a good option in PhpStorm to remove this file from project structure but still have completion! Let me check :)

**Comment by adelf** [comment]
I tried to create these files in project "scratch files", special PhpStorm place for project temp files, but it didn't work. So, I have to put these files to the project structure. 
Actually, I just repeated the file name from popular https://github.com/barryvdh/laravel-ide-helper package. Usually these files: `_ide_helper.php`, `_ide_helper_models.php`, etc. are in the .gitignore file... but you can create some directory, like `ignore` and store these files there...

**Comment by adelf** [comment]
By the way... maybe just create `/vendor/laravel_idea` folder and store files there?

**Comment by adelf** [comment]
Moved to `vendor/_ide_helper_models.php` in 3.2 version.
