### ISSUE TITLE
[Feature Request]: Wireui components are not recognized

### ISSUE THREAD

**Issue by haringsrob** [laravel-idea/plugin#630]
### Feature Description

Hi,

When using components from https://livewire-wireui.com they are not recognised/completed. Could these be added?

Cheers,

**Comment by beshoo** [comment]
+1

**Comment by rabol** [comment]
+2

**Comment by adelf** [comment]
<img alt="image" src="https://user-images.githubusercontent.com/2818394/195367160-effc5f8e-bcd0-411b-85f5-580a6e3323ae.png">

**Comment by rabol** [comment]
does not work for me - did you do something extra ?

**Comment by rabol** [comment]
When is next release ?

**Comment by haringsrob** [comment]
Soon https://twitter.com/laravel_idea/status/1592461960419106817

**Comment by adelf** [comment]
Released!

**Comment by rabol** [comment]
yes, but it does not work :(

I have this is my blade:

```
<x-wireui::select
                    label="Search a ingredient"
                    placeholder="Select some ingredient"
                    :async-data="[
                'api'=>route('api.ingredient-search'),
                'credentials' => 'include'
                ]"
                    option-label="name"
                    option-value="id"
                />
```

and then I get this error:

```
Undefined variable $optionDescription
 ```

**Comment by adelf** [comment]
This is a PHP error message? If yes - I only added completion for these components...

**Comment by rabol** [comment]
What kind of setup does one need to do in order for this to work ?

**Comment by ph7jack** [comment]
@rabol You're importing the livewire blade view using it `<x-wireui::select`, the component name is `<x-select`, this component uses a class

**Comment by ph7jack** [comment]
@adelf 
I'm still getting the error highlight for wireui components or any other components from third-party packages
I get the views files auto completions, but not the real component name
![image](https://user-images.githubusercontent.com/38913462/204106159-2ec34196-519b-4827-8253-7a635cfa6ab8.png)

**Comment by rabol** [comment]
> @rabol You're importing the livewire blade view using it `<x-wireui::select`, the component name is `<x-select`, this component uses a class

yes, but i get the auto-complete even if i update the config to have a different alias e.g. i my setup all are named wireui.XXXX

but I still get the autocomplete for wirui::select

**Comment by adelf** [comment]
Let's continue in #682
