### ISSUE TITLE
[Bug]: using route() doesn't show multi level [as=>''] with resource inside it in correct order

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [laravel-idea/plugin#636]
### Bug description

Hello, i have multi level Route group and i use as to define the name
so if i add one more group inside it then use resource and set prefix and write as the route name should be like ```group.name1.name2.index``` but in the route selection it shows ```name1.group.name2.index``` and it doesn't work when i select it i should write it in correct order to work..
i'm gonna show examples
This is the routes, 
![image](https://user-images.githubusercontent.com/30704271/191270632-ef3f23fe-812e-4514-9145-7943ce613023.png)

The expected name
![image](https://user-images.githubusercontent.com/30704271/191271612-2304ee2e-e146-48fa-8b75-12373c3ec9c4.png)

The names i get
![image](https://user-images.githubusercontent.com/30704271/191271696-d114093c-38fb-4c9e-bf0f-fb0fbf6d3b47.png)

i know i should make the name1 as group but it's only 1 Route resource and nothing else inside.

### Plugin version

5.8.2.222

### Operating system

Windows

**Comment by Ahmed-Elrayes** [comment]
Hey, it's me again.
is there any news bout it?

**Comment by adelf** [comment]
Fixed. Thank you for posting.

**Comment by Ahmed-Elrayes** [comment]
thanks a lot for fixing it

**Comment by adelf** [comment]
Fixed in the 6.1 release. Thanks.
