### ISSUE TITLE
[Request] See a list of event listener in events

### ISSUE THREAD

**Issue by olivernybroe** [laravel-idea/plugin#64]
## Problem
So I had a thought which would help our workspace a lot. 

We use events and event listeners often, it it's a pain to go to an event and then find it in `EventServiceProvider` and then see a list of all the listeners. 

This workflow is tedious and makes event usage worse.

## Solution
In IntelliJ, you can add icons in the sidebar for adding extra value to the class. An example of this is the implements icon.
![image](https://user-images.githubusercontent.com/5870441/83644509-a688d080-a5b1-11ea-9f04-7a1f678909f7.png)

I suggest adding a new icon which shows all the listeners for an event, so we can have a dropdown like this
![image](https://user-images.githubusercontent.com/5870441/83644705-dafc8c80-a5b1-11ea-95de-12fdcd9dc9e6.png)
but showing all of the listeners instead.

This would be soo game-changing for us!
Hope you can make it work ❤️

**Comment by djaxho** [comment]
This would be incredible

**Comment by adelf** [comment]
Wow. Great idea! Thanks. Will try to implement.

**Comment by adelf** [comment]
BTW... do you have some base class for events? I'm thinking how to quickly check whether this class an event class...
Some base class or namespace for events...

**Comment by olivernybroe** [comment]
There is not base class unfortunately, which would have helped a lot.

However the base Laravel command for creating events puts it in the namespace `App\Events`. 
All of our events are also located there.

Making the namespace default to that would prob. work great, and if users need to customize it you can always add a setting for it later on. 

But I think you have to check if it's an event by the namespace 😄

**Comment by olivernybroe** [comment]
Another solution instead of scanning for namespace would be to just look at the array in `EventServiceProvider`, if the class is listed in the array, then it is an event.

**Comment by djaxho** [comment]
> Another solution instead of scanning for namespace would be to just look at the array in `EventServiceProvider`, if the class is listed in the array, then it is an event.

I think this makes most sense

**Comment by adelf** [comment]
Ok. Namespace and service provider. Will try both. Thanks :)

**Comment by adelf** [comment]
I really liked this idea and...
![event_listeners2](https://user-images.githubusercontent.com/2818394/83654288-8cf18400-a5c5-11ea-8e89-51111076176e.gif)
Wil be in the next version

**Comment by olivernybroe** [comment]
@adelf OMG that's soo awesome! This is crazy and you made it in under 1 hour. 🤯 

Really love what you are doing, so excited about next version!

Does it also have support for binding a hotkey?

How much work would it be to make it work both ways? So you can go from the listener to all the events also? So you can see all the events the listener is registered to 😄

**Comment by adelf** [comment]
We have some time before release, so let's create a design for this feature :)
I can create an action for this... but don't want to make a default hotkey for it. But you can assign any hotkey you want.

It's also possible for listeners... Maybe use the same action for it...

**Comment by adelf** [comment]
3.1 version is online :)
