### ISSUE TITLE
[Feature Request]: Connection autocomplete on Schema class

### ISSUE THREAD

**Issue by jonatandorozco** [laravel-idea/plugin#642]
### Feature Description

Laravel Idea has connection autocomplete on DB::connection() function but using Schema::connection don't have it. It would be nice to have the same autocomplete.

PhpStorm 2022.2.2
Build #PS-222.4167.33, built on September 15, 2022
laravel_idea 5.8.2.222

**Comment by adelf** [comment]
Fixed in the 6.1 release. Thanks.
