### ISSUE TITLE
[Feature Request]: Support for Vite

### ISSUE THREAD

**Issue by cgreuling** [laravel-idea/plugin#648]
### Feature Description

Is Laravel + Vite support on the roadmap as a replacement for mix?

**Comment by adelf** [comment]
Hi. What kind of support needed?

**Comment by cgreuling** [comment]
Honestly, not sure if it's this plugin or not after thinking about it more. Might be a PHPStorm thing.

The one of the issues with the switch from Mix to Vite (probably minor in the grand scheme) is the autocomplete of imports in a Vue component (i.e. InertiaJS) where it doesn't import the extension.

BTW, this plugin has been incredible since I started using it.

**Comment by SpeakInCode** [comment]
@cgreuling you're correct in assuming that is a PhpStorm thing, and has nothing to do with this plugin.

**Comment by adelf** [comment]
You're right. Currently, this plugin only provides PHP and Blade support.
