### ISSUE TITLE
[Request] Add lang translation string, if it not exists; Support json source

### ISSUE THREAD

**Issue by Insolita** [laravel-idea/plugin#65]
1. I not sure is it possible, but.. when I write translation constant like `__('auth.personaldata_notice')`
the plugin can autocomplete string if it exists, and I can jump to it by ctrl+click or hotkey. But if it not exists - I will be glad to see context action with the ability to add at {$lang}/auth.php stub with 
` 'personaldata_notice'=>'' ` and to open that files (or at least one, predefined, because some projects can have a lot of languages)

2. Strings from json sources haven't autocomplete. (As I think, it can be detected, if translation key have at least one space)

I understand that items above may conflict, but hope that one of them can be realized

**Comment by adelf** [comment]
1. Plugin has ability to add a new translation by Alt-Insert(⌘ N,⌃ N) in strings... I think I can do almost the same for this...
2. I don't remember why I didn't liked the JSON translations... Ah, yes. Typical schema for translations: Project has default language, usually 'en' and some other languages - translations. All translation keys can be found just by analyzing `resources/lang/en` folder. On the other hand `__('Hi!')` means nothing! This string can be in the translation files, or just be a random "translated" string... I gonna create some "Translation manager" to make the translation process as easier as possible in one of the next versions and I hope some solution for JSON translations will appear there.

**Comment by Insolita** [comment]
1. Wow... I somehow missed this opportunity

> I gonna create some "Translation manager" 
It sounds great!  Would it be something separated or inside this plugin?

**Comment by adelf** [comment]
Inside )

**Comment by adelf** [comment]
Insolita died in 22.02.2022 :-( Rest in peace.

1. It is possible by the "Generate" action(Cmd-N) in any string or selected blade file code.
2. JSON translations are supported starting from 8.0.

So, I'm closing this.
