### ISSUE TITLE
[Bug]: Wrong month in file template

### ISSUE THREAD

**Issue by Basti007** [laravel-idea/plugin#651]
### Bug description

If I use the File and Code Template in PHPStorm and want to auto generate code with the Laravel Idea plugin, the month is wrong.
I use the `${MONTH}` variable to display the current month in the comment.

The correct month would be "10" but it displays "9".

### Plugin version

6.0.0.222

### Operating system

Windows

### Steps to reproduce

Edit `PHP File Header` and `PHP Class Doc Comment` (Editor > File and Code Templates > Includes) and add ${MONTH}.
Generate a Model using the Laravel Idea plugin and check the file comment.

**Comment by adelf** [comment]
Fixed in the 6.1 release. Thanks.
