### ISSUE TITLE
[Feature Request]: Custom config path

### ISSUE THREAD

**Issue by lloricode** [laravel-idea/plugin#655]
### Feature Description

Hi, 

I was wondering if possible to add custom config path in ide.json? we have many config in different path and `ide.json` does seems currently not supported

Thank you

**Comment by adelf** [comment]
Hi. Sorry for the late response. Could you share some examples of how you configure your config paths in the code?

**Comment by lloricode** [comment]
Hi @adelf , this is how structured or files

![Screenshot_2022-10-28_10-42-43](https://user-images.githubusercontent.com/8251344/198476427-6e266257-ff92-47a2-9682-d55efa68593a.png)

**Comment by adelf** [comment]
if you're adding it by `mergeConfigFrom` call and parameters aren't super magical, it will work in the next release.

**Comment by adelf** [comment]
Should work in 6.2.2
