### ISSUE TITLE
[Feature Request]: Support for autocompletion in "assertDatabaseHas()" and "assertDatabaseMissing()"

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#656]
### Feature Description

When writing tests (which I do pretty much every day) I often use the `$this->assertDatabaseHas()` and `$this->assertDatabaseMissing()` helpers to check for the existence of a record in the database:

```php
$person = Person::create();

$person->setNameToJohnDoe();

$this->assertDatabaseHas(Person::class, [
    'name' => 'John Doe',
    //
]);
```

It would be very useful if autocompletion could be provided on the database columns for that model. This would work exactly the same as the autocompletion in factories (one of the autocompletions I love most). 

I'm often using Pest, where it works as an imported function like this:

```php
use function Pest\Laravel\assertDatabaseHas;

assertDatabaseHas(Person::class, [
    'name' => 'John Doe',
    //
]);
```

The functions also support directly passing the database table name. So instead of `Person::class` you could also input `'persons'`. For me personally I always use the `Person::class` version, so I'm not sure whether it would be easy or not to support the second syntax as well for the sake of completeness. 

It would be awesome if this could be supported, for both Pest and PHPUnit. Thanks!

**Comment by adelf** [comment]
It also works. Maybe Generate Helper code? 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/2818394/195566627-97ce4b99-682e-478e-bd3b-4c8d59d4d4a4.png">

I'll add "assertDatabaseHas" function support.

**Comment by adelf** [comment]
Let's continue in #657. The reason is the same. And I've added PEST function support.
