### ISSUE TITLE
[Bug]: Incompatible requires IDE 222.*  on PhpStorm 2022.3 EAP

### ISSUE THREAD

**Issue by MarienMupenda** [laravel-idea/plugin#658]
### Bug description

This occurs when you update to the latest [early acccess program](https://blog.jetbrains.com/phpstorm/2022/10/phpstorm-2022-3-early-access-2-code-vision/)

### Plugin version

6.0.0.222

### Operating system

Windows

### Steps to reproduce

1. Install the latest phpstrom (EAP) here [2022.3 EAP](https://www.jetbrains.com/phpstorm/nextversion/)

### Relevant log output

```shell
Incompatible requires IDE 222.*
```

**Comment by adelf** [comment]
Please update the plugin. There is a separate version for each major IDE version.

**Comment by MarienMupenda** [comment]
> Please update the plugin. There is a separate version for each major IDE version.

How can i update it ?

I can't see update notification from the IDE.

Thank you!

**Comment by adelf** [comment]
Settings > Plugins > Laravel Idea

**Comment by MarienMupenda** [comment]
> Settings > Plugins > Laravel Idea

Thank you.
