### ISSUE TITLE
[Bug]: Return type for model-specific Collection

### ISSUE THREAD

**Issue by joke2k** [laravel-idea/plugin#659]
### Bug description

I can't use the [custom Collection](https://laravel.com/docs/8.x/eloquent-collections#custom-collections) as a return type.
That's the warning from PhpStorm:

![image](https://user-images.githubusercontent.com/359076/196550907-90429339-e618-43ad-b64d-a3f9be191337.png)

The same result was for other builder finishers.

I expected to have a `UserCollection` as defined in my `User::newCollection` method.

Thank you

### Plugin version

6.0.0.222 purchased

### Operating system

Linux

### Steps to reproduce

This is how I implemented it in the model class:
```php
class User extends Authenticatable
{
//...
    public function newEloquentBuilder($query): UserQueryBuilder
    {
        return new UserQueryBuilder($query);
    }

    public function newCollection(array $models = []): UserCollection
    {
        return new UserCollection($models);
    }
}
```

**Comment by CastFX** [comment]
I am having the same problem in my project

**Comment by GianlucaApi96** [comment]
I am having the same problem in my project

**Comment by adelf** [comment]
I did some improvements in the helper code and this should be fixed. Please check how these custom collection and builder classes work now. In the new 6.1 release.

**Comment by joke2k** [comment]
@adelf yeah, now it works!

thank you

**Comment by gwillyoo** [comment]
![image](https://github.com/user-attachments/assets/ada63897-67cb-4f84-a395-444c9e1792cd)

Now, It can not recognize the collection. any advice ?

**Comment by adelf** [comment]
You've imported the wrong Collection class. It should be `Illuminate\Support\Collection`.

**Comment by gwillyoo** [comment]
Hi @adelf , thank you for the reply. 

I am using package `lazychaser/laravel-nestedset` and the return of the get method is the `Kalnoy\Nestedset\Collection`.
