### ISSUE TITLE
[Bug]: Generates incorrect model property  

### ISSUE THREAD

**Issue by usersanjib** [laravel-idea/plugin#660]
### Bug description

I have a model Timesheet backed by a table _timesheets_. There is a varchar field called anomaly. 

The helper is generating it as an array called anomalies for some reason. 

Expected behavior is that it should be generated with the same name of the field.

Table Schema
https://pastebin.com/0unmfG0x

Associated Model
https://pastebin.com/cDKbBuw3

Autocomplete suggests anomalies in place of anomaly, and an array
https://i.imgur.com/30NvZH7.png

Generaed Helper code with "anomalies" typehinted in place of a single nullable "anomaly" field.
https://pastebin.com/FqMVHzwk

### Plugin version

6.0.0.222

### Operating system

Linux

**Comment by adelf** [comment]
What source did you use for helper code? Migration or Database? If migration - could you share it too?

**Comment by usersanjib** [comment]
Sorry totally my bad. First time using the plugin and I didn't realize the two sources (db and migrations). Works as expected. Thanks!
