### ISSUE TITLE
[Bug]: When I hold command and click the Model name, there is a pop window.

### ISSUE THREAD

**Issue by YunshuaiPeng** [laravel-idea/plugin#661]
### Bug description

I have to select the correct declaration. In fact I want goto the Model file.

A lot of time was wasted. 😔

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/44765369/198033891-32364dba-2fa9-4607-a1a0-7724ead0edc3.png">

idea version:
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #1U-212.5284.40, built on September 14, 2021

### Plugin version

6.0.0.212

### Operating system

MacOS

### Steps to reproduce

Hold command and click a class name.

**Comment by adelf** [comment]
Hi. It's a PhpStorm bug. I'll fill an issue for them.

For example, if you'll use "::class" syntax - it will work fine: `FullyBomCategory::class`

**Comment by YunshuaiPeng** [comment]
> Hi. It's a PhpStorm bug. I'll fill an issue for them.
> 
> For example, if you'll use "::class" syntax - it will work fine: `FullyBomCategory::class`

Okay, thank you. I will close the issue.

**Comment by adelf** [comment]
Issue in the PhpStorm bug tracker: https://youtrack.jetbrains.com/issue/WI-69399/referenceResolver2-EP-isnt-used-for-class-references-in-strings
