### ISSUE TITLE
[Bug]: Config not detected when not published

### ISSUE THREAD

**Issue by lloricode** [laravel-idea/plugin#663]
### Bug description

Trying to click a config call like `config('activitylog.activity_model')`, but can not find declaration by the plugin, and that config is not already published,  I just want to see the default value in vendor, 

after publishing config, it works fine, but we do not modified it so no reason to published that config, so we have no worries of later version of package config

### Plugin version

6.0.0.222

### Operating system

Linux

### Steps to reproduce

click a call config of not published from the package

**Comment by adelf** [comment]
Should work since 6.2.2
