### ISSUE TITLE
[Feature Request]: Envoy support

### ISSUE THREAD

**Issue by eggnaube** [laravel-idea/plugin#664]
### Feature Description

It would be nice if the plugin supported Laravel Envoy. Helpful would be:

- Syntax highlight
- Code Formatter
- Shell support (Configurable / Third party Plugin?)

Thnaks for the great work!

**Comment by adelf** [comment]
Hi.

I've added some features, like Blade directives and some completions - https://twitter.com/laravel_idea/status/1593581689913090049

Own, separated from Blade plugin, syntax, formatter, and other things - is too hard to implement. Maybe later, much later.
