### ISSUE TITLE
[Feature Request]: Autocomplete for accessors

### ISSUE THREAD

**Issue by justrustyspoons** [laravel-idea/plugin#668]
### Feature Description

With an accessor like ```getNameAttribute()``` or ```name(): Attribute```  it would be cool if when writing ```$user->name``` it would autocomplete and suggest from accessors as well as the migration.

**Comment by adelf** [comment]
Hello.

Have you tried to generate a helper code? main menu - Laravel - Generate Helper Code?

**Comment by mortenscheel** [comment]
@adelf please reopen this. I have the same issue.

I have a model with a `constraints` json column, which is cast to a custom object and `Generate Helper Code` only detects the correct type with 1 out of 3 different cast techniques as listed below. I'd be happy to provide more information if needed.

## Custom cast class
```php
class ConstraintsCast implements CastsAttributes
{
    public function get(Model $model, string $key, mixed $value, array $attributes): Constraints
    {
        // ...
    }
}
```
Detected type: `Constraints`. This is the only way that works. It's not enough to declare the return type in a `@return` phpdoc (in which case type is detected as array)

## Old school accessors
```php
public function getConstraintsAttribute($value, array $attributes): Constraints
{
    // ...
}
```
Detected type: array.

## Modern accessors
```php
public function constraints(): Attribute
{
    return Attribute::make(
        get: function(mixed $value, array $attributes): Constraints {
            // ...
        }
    );
}
```
Detected type: array

**Comment by adelf** [comment]
I did some tests, and everything seems to work ok.

```
        protected function someGetAttribute(): Attribute
        {
            return Attribute::make(
                get: function(mixed $value, array $attributes): ValueObjectClass {
                    return new ValueObjectClass();
                }
            );
        }

        public function getVoAttribute(): ValueObjectClass
        {
            return new ValueObjectClass();
        }
```

**Comment by mortenscheel** [comment]
@adelf thanks for checking up on it. I forgot to mention that I checked the generated helper code with all 3 versions, and wiped the _laravel_idea folder between each. I suspect the issue might be with PhpStorm's caching of the project, which is pretty huge. It seems that every time I invalidate the cache and restart, it fixes some completions, but causes others to stop working. If anyone has a clue about what might be happening, please let me know 😄

**Comment by adelf** [comment]
@mortenscheel, could you tell which Laravel Idea version you use?

**Comment by justrustyspoons** [comment]
<img width="598" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/d09ad55c-4b7e-4cde-b6ad-c647981a339a">
<img width="253" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/4592d51c-e1ba-45c2-9a6a-2d0e09b9f48e">


<img width="574" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/1f743a07-f0bb-4213-a410-3eeff9ae539f">
<img width="487" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/78682a66-42ff-4c32-a4e3-bda0ba2602ed">
<img width="499" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/bd6529f0-65f3-4d10-b6a4-5488a3c152d5">

**Comment by justrustyspoons** [comment]
I have tried generating helper code. Often columns result in "Unknown column" and the getAttribute accessors don't resolve, but returning an Atrribute does seem to resolve

**Comment by mortenscheel** [comment]
@quantumwebco That's because you have to use snake_case when you want to get the value.

**Comment by mortenscheel** [comment]
@adelf I'm always using the latest version. It's been a while since I've checked if it's still an issue. I'll get back to you.

**Comment by justrustyspoons** [comment]
But why the column not found?

**Comment by mortenscheel** [comment]
@quantumwebco try posting on Discord or /r/laravel. It's not related to this issue.

**Comment by justrustyspoons** [comment]
@mortenscheel I literally opened this issue for my issue of not getting autocomplete for accessors, column references and scopes

I still don't get autocomplete for scopes or columns

<img width="657" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/3f03ad55-ba5b-494d-9ed4-6e5e20849583">

<img width="369" alt="image" src="https://github.com/laravel-idea/plugin/assets/12368817/8cb7e808-6564-4505-a785-8e808c86b008">

**Comment by adelf** [comment]
@quantumwebco, why are your scope methods static? I only fetch dynamic methods when generating helper code... Does it work?

**Comment by justrustyspoons** [comment]
Oh yeah that's an error, sometimes PHP storm decides scopes and query builder methods should be static, but I have dynamic methods with the same issue

However, sorry, my bad, I just realized I wasn't passing the ```Builder``` type in the callback, now I've added the type to the argument it resolves fine

Apologies! Thanks for your time

**Comment by justrustyspoons** [comment]
BTW, one thing I just noticed, I have a scope with the same name in another model ```scopeValid```, if I ctrl click it takes me to the other model. I can see how this happens because of the ambiguity, but is there a workaround or some way to make it unambiguous?

**Comment by adelf** [comment]
It shouldn't happen... Only if there are many possible model classes there. Like, you have `Model $model` and `$model->valid();` - and yes, here it can work incorrectly.

**Comment by justrustyspoons** [comment]
It's in a callback ```function (Builder $query) { $query->valid(); }``` which is why I understand it to be ambiguous.

**Comment by adelf** [comment]
In one of the next updates, Laravel Idea will try to guess the correct Builder classes for these lambdas and you will go to the correct method declaration.

**Comment by justrustyspoons** [comment]
Thanks, and thank you for such an awesome plugin!
