### ISSUE TITLE
[Feature Request]: Language suggestion on vue files

### ISSUE THREAD

**Issue by carvemerson** [laravel-idea/plugin#669]
### Feature Description

This plugin give us a very good feature, the intelisense of lang files. 
Does it also work on vue files? It is working fine on php and blade files, but on vue it is not. 

![image](https://user-images.githubusercontent.com/6718864/199975873-20908b66-a3f8-45d6-a1e1-a4e560aec1f9.png)

**Comment by adelf** [comment]
Is this `$t` an official Vue localization function? Or it's just some library?

**Comment by carvemerson** [comment]
Hi @adelf , it is a package: https://kazupon.github.io/vue-i18n

**Comment by adelf** [comment]
Implemented in the 6.1 release.
