### ISSUE TITLE
[Bug]: cannot run laravel idea, nothing menu laravel shown

### ISSUE THREAD

**Issue by AzhariRamadhan** [laravel-idea/plugin#670]
### Bug description

<img width="1204" alt="Jepretan Layar 2022-11-07 pukul 19 11 45" src="https://user-images.githubusercontent.com/32870854/200307533-499f60d7-65cd-41d4-9e27-657ba2c3dea3.png">

### Plugin version

6.0.0.222

### Operating system

MacOS

**Comment by AzhariRamadhan** [comment]
if i go to setting plugin enable, change from auto to manual, its work, but when generate got some errors like directory not found

**Comment by adelf** [comment]
Hello. You should probably put "blog" to the Laravel directory parameter here: 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/2818394/200424138-9e495a95-4ab7-41a9-aff3-405d013b9678.png">
