### ISSUE TITLE
[Bug]: Not working anymore after update to 6.1.0.223

### ISSUE THREAD

**Issue by marcandreappel** [laravel-idea/plugin#673]
### Bug description

All functionalities that makes this plugin worthwhile are not working anymore - **everything**.

### Plugin version

6.1.0.223

### Operating system

Linux

### Steps to reproduce

1. updated the plugin this morning to the latest version - it broke
2. cleared PhpStorm cache to see if it resolves the issue - nothing changed
3. deleted the .idea folder and restartet PhpStorm - noting changed, still not working

**Comment by adelf** [comment]
Could you please check Settings | Languages & Frameworks | Laravel Idea?
Is plugin enabled or not?

**Comment by marcandreappel** [comment]
Seems to be enabled; automatic is active, all options are as usual an all packages are listed under Laravel Packages...

**Comment by adelf** [comment]
Honestly, I don't have any idea why it happened. Do you see the Laravel main menu item?

You can downgrade by removing the plugin and downloading the previous version - https://plugins.jetbrains.com/plugin/13441-laravel-idea/versions/stable/231294

**Comment by marcandreappel** [comment]
I do have the Laravel main menu item, I can even generate helper code, but that's it...

**Comment by marcandreappel** [comment]
Well, it seems the problem ain't your plugin, however sadly only your plugin ain't working anymore.
Even after a complete purge of PhpStorm, and a try-out of the EAP version, still the same strange result.

**Comment by marcandreappel** [comment]
Well, strange thing, I just formatted my PC, new install of Ubuntu 22.04 (instead of my Ubuntu 22.10), new PhpStorm installation, no plugins besides Laravel Idea and a brand new Laravel project - **still not working**!

Older versions of the plugin won't work either... is there somehow a possibility to check what the issue is with my setup ?

**Comment by adelf** [comment]
What exactly doesn't work? You said that the main menu item is there... did you make `composer install`?

**Comment by marcandreappel** [comment]
Yes, composer install did run fine, I installed breeze to generate some views and inside let's say `auth/login.blade.php` I don't have anymore the button next to the line number to go up into the controller, nor can't I `ctrl`-click anymore on the component tag to open the component.

**Comment by adelf** [comment]
Do you have the Blade plugin installed?

**Comment by marcandreappel** [comment]
Hmmm, it was installed but disabled ? And since I enabled it, first your plugin crashed but **now everything works**!
Thanks for the hint!
