### ISSUE TITLE
[Feature Request]: Support for Laravel Modules Livewire

### ISSUE THREAD

**Issue by Basti007** [laravel-idea/plugin#677]
### Feature Description

Hi, there is already a support implemented for the nwidart Modules.
If I want to use Livewire with the modules, I need to use an additional package https://github.com/mhmiton/laravel-modules-livewire.

Using this package, I have no auto completion in my blade files. Example: I write `<livewire:` and it should show `livewire:basic::setup.stepper` but nothing appears in the list.

Best regards

**Comment by adelf** [comment]
It's a duplicate for #666. Let's continue there.
