### ISSUE TITLE
[Bug]: Generated Json column not recognized

### ISSUE THREAD

**Issue by rainbowMeh** [laravel-idea/plugin#678]
### Bug description

The generated models with json column [MySql Database] seems false

![image](https://user-images.githubusercontent.com/46424861/203292201-91d7435a-7963-41d0-95b8-eb4326a0440e.png)

### Plugin version

6.1.1.223

### Operating system

MacOS

**Comment by adelf** [comment]
Yes. I already found and fixed it. Thanks. Will be in the next release.

**Comment by adelf** [comment]
Fixed in 6.2.3.
