### ISSUE TITLE
[Generate Eloquent Helper Code]: Incorrectly handles underscores

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#68]
Model:
![2020-06-05_14-25-36](https://user-images.githubusercontent.com/10347617/83871420-b0890b80-a738-11ea-9d97-8f65a17eaca3.jpg)

Callable:
![2020-06-05_14-25-13](https://user-images.githubusercontent.com/10347617/83871423-b0890b80-a738-11ea-9331-d6195fcf83d7.jpg)

Helper:
![2020-06-05_14-26-23](https://user-images.githubusercontent.com/10347617/83871418-af57de80-a738-11ea-933b-4cc1102aa10f.jpg)

**Comment by adelf** [comment]
Little type in my source code. Sorry. Fixed.
