### ISSUE TITLE
[Bug]: how can I disable wireui::

### ISSUE THREAD

**Issue by rabol** [laravel-idea/plugin#682]
### Bug description

The support for wireui:: is not working or the documentation on how to make it work is missng.
How can the wireui support be disabled ?

### Plugin version

6.1.1.2222

### Operating system

MacOS

**Comment by Blinks44** [comment]
Is it related with new plugin update or we should write to wireui creator?

<x - modal> works fine, but <x-wireui::modal> doesn't

![2022-11-27_15-21-32](https://user-images.githubusercontent.com/8570193/204351399-7f7bd119-1c00-4561-8932-af9a8c91ab56.png)

![2022-11-27_15-21-04](https://user-images.githubusercontent.com/8570193/204351408-eb0774b0-0e88-468d-a1a2-92a15c1336c5.png)

**Comment by adelf** [comment]
Right now Laravel Idea see
```
$this->loadViewsFrom("{$rootDir}/resources/views", 'wireui');
```

And register all components from `resources/views/components` folder, since they are Blade components in Laravel terms. I'll try to fix that by registering the correct components and omitting the "view" ones. Maybe with ide.json...

**Comment by rabol** [comment]
I think the issue is a little more complex :)

the WireUI component is not in the resources/view/components, but in the vendor/... folder, further many of them require a class and to make it even worse, one have to change the alias otherwise one will have issues with 'local' and breeze components.

e.g. I have prefixed all mine with wireui in the /config/wireui.php to avoid conflict with the component that Laravel/breeze installs

so for me I have <x-wireui.button ...> but Laravel Idea, does not pick up on that and say that it's a unknown Blade component.

**Comment by adelf** [comment]
> the WireUI component is not in the resources/view/components, but in the vendor/... folder,

Yes. Laravel Idea analyzes service provider and marks `vendor/.../wire-ui/resources/views/components` with "wireui" namespace as View root folder. and after that find the `components` folder there and fetches Blade components from it.

**Comment by adelf** [comment]
> e.g. I have prefixed all mine with wireui in the /config/wireui.php to avoid conflict with the component that Laravel/breeze installs

@rabol you've changed the `alias` key value for each component, right?

**Comment by rabol** [comment]
yes initial I had changed the alias, but even without changing the key it's not working.

@adelf Any hint on when it will be fixed or is there a workaround as it is it annoying to see the ```<x-wireui::``` as it does not work

**Comment by rabol** [comment]
> > the WireUI component is not in the resources/view/components, but in the vendor/... folder,
> 
> Yes. Laravel Idea analyzes service provider and marks `vendor/.../wire-ui/resources/views/components` with "wireui" namespace as View root folder. and after that find the `components` folder there and fetches Blade components from it.

Somehow it does not find and resolve the WireUI service provider

**Comment by adelf** [comment]
There is a solution for this case by using "ide.json" file. But there is a little bug. It's already fixed, and fixed version will be released next week. After that, I'll write here how to make Laravel Idea to fully understand wireui Blade components.

**Comment by adelf** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2818394/231493653-df0d6344-7007-4fdc-8edc-abe91b730912.png">
;-)

**Comment by rabol** [comment]
now is next week :)

**Comment by adelf** [comment]
I'm sorry. Laravel Idea 7.0.3 was released last Thursday, so it was ready then, but I forgot about this issue.

I already created a PR for wireui library: https://github.com/wireui/wireui/pull/645 and this will turn on the correct completions for all future library versions.

However, you can also do this for your projects if you put `ide.json` file there with this content:
```json
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "blade": {
        "components": {
            "fromConfig": [
                {
                    "configFileName": "wireui",
                    "componentsKey": "components",
                    "classFetch": {
                        "type": "arrayKey",
                        "key": "class"
                    },
                    "aliasKey": "alias"
                }
            ],
            "ignoreViewPaths": [
                "/vendor/wireui/wireui/resources/views"
            ]
        }
    }
}
```
