### ISSUE TITLE
[Bug]: Vue component import autocomplete not working

### ISSUE THREAD

**Issue by avinash403** [laravel-idea/plugin#687]
### Bug description

Plugin doesn't autocomplete the import like below
<img width="536" alt="Screenshot 2022-12-08 at 8 28 22 PM" src="https://user-images.githubusercontent.com/31030044/206479419-d42d3952-8e8b-432b-8fc0-ddb58bb34a76.png">

### Plugin version

6.2.2.212

### Operating system

MacOS

**Comment by adelf** [comment]
Hello, Avinash. This is a Laravel Idea plugin. It doesn't do anything with Vue. 

Please check https://www.jetbrains.com/help/phpstorm/vue-js.html
