### ISSUE TITLE
[Bug]: Nova relations linking to models instead of nova ressource

### ISSUE THREAD

**Issue by saschaende** [laravel-idea/plugin#690]
### Bug description

I installed the plugin yesterday and there is a bug with nova resources.

My suggestion is: Make all the same names. Better than using the model name in the relations.

public static $model = \App\Models\App::class;
HasMany::make('Locations', 'locations', \App\Nova\Location::class),

Actually i have to rewrite every nova resource, because the relation is linked to the model and not to the according nova ressource.

### Plugin version

latest

### Operating system

Windows

**Comment by KevenOuellet** [comment]
I have this problem too.

**Comment by adelf** [comment]
Fixed in 8.0.
