### ISSUE TITLE
[Feature Request]: Support Jetbrains Gateway

### ISSUE THREAD

**Issue by jonatandorozco** [laravel-idea/plugin#691]
### Feature Description

I use a server to store my projects and I use another machine as my dev computer. I cannot use Laravel Idea when I work on projects through ssh (jetbrains gateway).

It doesn't even get listed as a plugin (through ssh)

**Comment by joaopms** [comment]
~This also affects Windows + WSL2 users. I would love to have this implemented!~
**Edit:** Just found out there's a difference between host and client plugins, I just needed to install it as a host plugin :)

**Comment by adelf** [comment]
@joaopms so it works there?

**Comment by joaopms** [comment]
> @joaopms so it works there?

As far as I can tell, yes it does, @adelf! :)
