### ISSUE TITLE
Support autocomplete for $attributes in Blade Component Templates

### ISSUE THREAD

**Issue by saschaende** [laravel-idea/plugin#692]
### Feature Description

Actually i add this to templates:

```
<?php
/**
 * @var \Illuminate\View\ComponentAttributeBag $attributes
 */
?>
```

So, this would be a great feature.

Example in template:

`{{ $attributes->only(['class','id']) }}`

**Comment by adelf** [comment]
<img alt="image" src="https://user-images.githubusercontent.com/2818394/208963274-0fabb97f-7dec-4bed-b702-a323904e54c2.png">

It works with Laravel Idea without any phpDocs.

**Comment by saschaende** [comment]
Not really.

How it is:

![image](https://user-images.githubusercontent.com/17617037/208965896-bfc7c557-329f-4f4d-8f1a-618eb41673b7.png)

How it should be:

![image](https://user-images.githubusercontent.com/17617037/208965811-af83f14d-9dd1-4039-92d7-4ff9d5fdf8fd.png)

**Comment by adelf** [comment]
Where is this iframe.blade.php file located?

**Comment by saschaende** [comment]
Here:

![image](https://user-images.githubusercontent.com/17617037/208970356-07eace25-89d0-48c3-8630-8aa88a86137a.png)

If it helps, code of the component is:

```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Theme extends Component
{
    public $template = 'default';

    public function __construct($template)
    {
        $this->template = $template;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|\Closure|string
     */
    public function render()
    {
        return view('theme.' . $this->template);
    }
}
```

**Comment by saschaende** [comment]
I checked it on another project, it seems to work if it is located in components or a subfolder of components.

Probably this is the issue.

I dont know if it is against standards to put templates of components in other folders? Probably my fault then... will move it to "components/theme" :(

**Comment by saschaende** [comment]
Anyway, best extension for Laravel so long.

**Comment by adelf** [comment]
It works even if the view is not in the 'components' folder. It also works if some component class makes `view('this.view.name')`. But Laravel Idea can't understand your `return view('theme.' . $this->template);`. So, that's why it can't recognize that it is a component view.

I don't want to complete `$attributes` to all blade view files, since not all of them are component views...
