### ISSUE TITLE
[Bug]: ULID columns not recognised

### ISSUE THREAD

**Issue by alexcutts2** [laravel-idea/plugin#694]
### Bug description

I have switched to using `ulid` and `foreignulid` exclusively in my migrations to drop the need for an internal auto incrementing id and an external uuid. This all works fine in Laravel and Laravel Idea generates the relationships correctly but doesn't add any properties for these columns.

For instance, the schema:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/8549772/209796386-d8da1bc4-54c1-4b02-b37a-4f075360e5f9.png">

Generates the following helper code:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/8549772/209796339-e6544481-971a-45a9-ae42-73f46100db20.png">

As you can see, the two ULID columns appear to have been ignored.

### Plugin version

6.2.2.223

### Operating system

MacOS

**Comment by adelf** [comment]
Fixed in the last version. Thank you.
