### ISSUE TITLE
[Feature Request]: Support for permissions created "dynamically"

### ISSUE THREAD

**Issue by MightyPork** [laravel-idea/plugin#696]
### Feature Description

We have a large number of permissions with additional attributes stored in a file. The file is used by a custom authorization  provider and also to set up the permissions in Gate.

```php
class AuthServiceProvider extends ServiceProvider
{
	public function boot()
	{
		// Add all permissions
		$permissionConfig = data('permissions');

		foreach (array_keys($permissionConfig['permissions']) as $permission) {
			// Define an ability for the permission
			// Will be accessible via ->can()
			Gate::define($permission, function(User $user, ...$args) use($permission) {
				$arg = null;
				if (count($args) > 0) $arg = $args[0]; // discard more than one arg
				return \Permission::check($user, $permission, $arg);
			});
		}
	}
//...
}
```

The plugin obviously doesn't understand this and permission auto-completion then doesn't work.

It would be great to have something like an ide-helper file for permissions. The list of permissions we use rarely changes, it's not really dynamic - more like data-driven.

**Comment by adelf** [comment]
Hi. It's possible with the last update.
You can create an 'ide.json' file in your project with this content:
```
{
  "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
  "auth": {
    "additionalGates": [
      "addGate1",
      "addGate2"
    ]
  }
}
```

**Comment by MightyPork** [comment]
I tested it now, works great! Thanks
