### ISSUE TITLE
[Bug]: Please change the Cache typehint of remember and rememberForever to "mixed"

### ISSUE THREAD

**Issue by fbandres** [laravel-idea/plugin#699]
### Bug description

The typehint for "**remember**" and "**rememberForever**" was set to "**void**" and I'm getting squiggly in my PHPStorm. In Laravel, it is set to "**mixed**."

**WORKAROUND:**
- Edit the **_ide_helper_facades.php** file and change the typehint from void to "**mixed**."
     * @method static **mixed** rememberForever(string $key, \Closure $callback)
     * @see \Illuminate\Cache\Repository::remember
     * @method static **mixed** remember(string $key, \Closure|\DateInterval|\DateTimeInterface|int|null $ttl, \Closure $callback)

### Plugin version

6.2.2.223

### Operating system

MacOS

### Steps to reproduce

1. Delete the _ide_helper_facades.php in vendor/_laravel_idea
2. Regenerate the Code helper.

**Comment by adelf** [comment]
Fixed. Thanks. The new release will be available this or next week.

**Comment by adelf** [comment]
Please update and try to generate helper code again.

**Comment by fbandres** [comment]
All good now thanks! :)
