### ISSUE TITLE
Duplicated fields in database factory generation

### ISSUE THREAD

**Issue by Dezeter** [laravel-idea/plugin#7]
Собственно сабж.

**Comment by adelf** [comment]
Hi. Seems, you have phpDocs generated in model files and in the _ide_helper_models.php. Thanks for the bug, I'll fix it, but better for you just choose one way :)

Привет. У тебя phpDoc для моделей сгенерены и в самих моделях и в файле _ide_helper_models.php. За баг спасибо, поправлю. Но ты лучше выбери один путь и иди им :)

**Comment by adelf** [comment]
Fixed in 2.0. Thanks again.
