### ISSUE TITLE
[Bug]: Anonymous component with custom path not found

### ISSUE THREAD

**Issue by slovenianGooner** [laravel-idea/plugin#700]
### Bug description

I am registering a custom path for Blade components in AppServiceProvider with:

`Blade::anonymousComponentPath(resource_path("views/frontend/components"))`.

On Laravel side everything works as expected, but Laravel Idea for some reason does not find the components and gives me an error.

I've updated the path in Laravel Idea settings [Blade -> Blade component views directory] to match what I am registering in the AppServiceProvider. 

<img width="484" alt="Screenshot 2023-01-11 at 14 42 02" src="https://user-images.githubusercontent.com/1257629/211821239-3568a073-16c8-406d-aaab-1878b6ac42bc.png">

If I want to resolve the error it gives me the error that the file already exists.

So, Laravel Idea knows that it cannot create the file, but for some reason still gives me an error that the component cannot be found and also does not offer to autocomplete the component when typing in blade.

### Plugin version

6.2.2.223

### Operating system

MacOS

### Steps to reproduce

1. Register custom path to anonymous components in AppServiceProvider with:
`Blade::anonymousComponentPath(resource_path("views/frontend/components"))`.
2. Update settings in Laravel Idea -> Blade -> Blade component views directory to match the folder.
3. Try to reference an anonymous component in a blade file.

**Comment by adelf** [comment]
Hello.

The `anonymousComponentPath` method was added less than 1 month ago. It will be supported in the next Laravel Idea release.

**Comment by adelf** [comment]
Please update and try. It should work.
