### ISSUE TITLE
[Bug]: laravel-modules translation auto complete and go to translate not work

### ISSUE THREAD

**Issue by SocolaDaiCa** [laravel-idea/plugin#701]
### Bug description

when I create module

- `Modules/admin1` => `__('admin1::ui.dashboard')` can auto complete and goto translation define
- `Modules/admin_1` => `__('admin_1::ui.dashboard')` can auto complete and goto translation define
- `Modules/admin-1` => `__('admin-1::ui.dashboard')` can't auto complete and goto translation define

It not work if folder contains `-` character

### Plugin version

Newest

### Operating system

Windows

**Comment by adelf** [comment]
Should be fixed in the new version released today.
