### ISSUE TITLE
[Bug]: config() autocomplete inserts whole key instead of completing in blade directive

### ISSUE THREAD

**Issue by imerr** [laravel-idea/plugin#702]
### Bug description

Just coming across an autocomplete issue where in some cases instead of completing the typed in selection for example "file.ke" to "file.key.something" it will insert "file.file.key.something"
I can only get this to happen in a blade template in this specific way (so far):
```php
@include("some_view", ["var" => config("file.ke")])
```

Any other way I've tested seems to work fine

Here's a video of the issue as well
https://share.dl.je/2023/01/2023-01-17_11-31-53_KCeRaZeftn.mp4

Let me know if you need any other info or if thats enough to reproduce

### Plugin version

6.2.3.223

### Operating system

Windows

**Comment by adelf** [comment]
Hi. Looks like the Blade plugin bug. Posted it here - https://youtrack.jetbrains.com/issue/WI-70926/Different-completion-behavior-for-Blade-lang-injection-fragments
