### ISSUE TITLE
[Bug]: Macro calls helper code generated invalid signature for Eloquent macros

### ISSUE THREAD

**Issue by miagg** [laravel-idea/plugin#703]
### Bug description

I have register the following macro in my `AppServiceProvider` class

```php
use Illuminate\Database\Eloquent\Builder;

Builder::macro('searchFor', function (string|array $attributes, string $searchTerm) {
            $attributes = \Arr::wrap($attributes);

            foreach ($attributes as $attribute) {
                $this->query->orWhere(function ($query) use ($searchTerm, $attribute) {
                    foreach (explode(' ', $searchTerm) as $term) {
                        $query->whereRaw(
                            "LOWER($attribute COLLATE utf8mb4_unicode_ci) like LOWER(?)",
                            "%$term%"
                        );
                    }
                });
            }

            return $this;
        });
```

However when I generate helper code it seems to skip the first argument (`$attributes`) for some reason.

Here is the generated signature on my `_laravel_idea/_ide_helper_macro.php`

```php
namespace Illuminate\Database\Eloquent {
    
    /**
     ...
     * @method $this searchFor(string $searchTerm)
     ...
     */ 
    class Builder {}
}
```

My macro does work however PHPStorm complains that the signature is wrong.

![screenshot](https://user-images.githubusercontent.com/6439071/213156570-af787381-2a17-44a7-a3bb-571f552a0e6d.png)

Any thoughts?

### Operating system

MacOS

### Steps to reproduce

As described above.

**Comment by adelf** [comment]
Please check the 6.4.3 version released today.

**Comment by miagg** [comment]
> Please check the 6.4.3 version released today.

Yes! It's fixed!
