### ISSUE TITLE
[Bug]: Plugin not working in part

### ISSUE THREAD

**Issue by rootuser** [laravel-idea/plugin#706]
### Bug description

Hello,

this is a strange bug, and alas I can not give you steps to reproduce.
I am using Intellij IDEA on three machines (all Windows), but I have issues with the Laravel plugin on one machine only. On all machines I have the latest IDEA version (2022.3.1) und Plugin-Version (6.2.4.223).

The problem is that blade tag components are neither autocompleted nor recognized as correct code. So Blade tags are shown as errors in view components.

But when I e.g. wish to return a view file in a route, he view autocompletion works fine, so at least this part of the plugin is working.

I have already tried to uninstall/reinstall the plugin, but this did not help.

The 'plugin enabled' option is set to 'automatic' in the settings (and shown as 'enabled'). I also tried to anually activate it, but that does not change anything.

Do you have a hint for me please?

Kind regards,
Tom

### Plugin version

6.2.4.223

### Operating system

Windows

**Comment by adelf** [comment]
Looks like the Blade plugin is not installed in this machine.

**Comment by rootuser** [comment]
Oops, yes, that does indeed solve the problem.

As obvious as the solution seems now: I really thought that the Bade syntax highlightning etc. was part of the Laravel IDEA plugin.

Sorry for bugging you with that!

**Comment by adelf** [comment]
> Sorry for bugging you with that!

No problem. Don't worry.

> Blade syntax highlightning etc. was part of the Laravel IDEA plugin.

I think about it a lot... maybe sometime later... )
