### ISSUE TITLE
[Bug]: "Show module selection" checkbox in code generation can't be unchecked. Reverts to being checked after saving.

### ISSUE THREAD

**Issue by JoshMoreno** [laravel-idea/plugin#707]
### Bug description

![2023-01-25 at 2 22 PM](https://user-images.githubusercontent.com/22627952/214705155-1dbe0df1-86cb-492b-9330-bac9505e766c.png)

After unchecking it, clicking "Apply" or "Ok" closes the preferences window, but the setting doesn't actually get updated. Which means it forces you to always pick a module.

### Plugin version

6.2.4.223

### Operating system

MacOS

### Steps to reproduce

I updated the plugin recently, so I think it's just a bug in the latest version.

**Comment by adelf** [comment]
Fixed. I'll try to release a new version at the beginning of the next week. Thank you.

**Comment by adelf** [comment]
Fixed in the 6.2.5 version. Thank you.
