### ISSUE TITLE
[Feature Request]: Ignore private properties in Blade component attribute completion

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#709]
### Feature Description

I sometimes add private properties to Blade components, and use them to store "computed" values. Here's a very simple example:
```php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class DoubleValue extends Component
{
    private int $double;

    public function __construct(public int $number)
    {
        $this->double = $this->number * 2;
    }

    public function render()
    {
        return view('components.double-value')->with('double', $this->double);
    }
}
```
```blade
<div>
    {{ $number }} * 2 = {{ $double }}
</div>
```
Currently, laravel-idea suggests both `:number` and `:double` when showing completions:
![image](https://user-images.githubusercontent.com/6514342/215450946-0c2d4717-4cb4-4147-889f-fbd6034ef570.png)

An alternative solution could be to compute the value in a public method:
```php
public function double(): int
{
   return $this->number * 2;
}
```
And get the value in the blade file with `{{ $double() }}`. 
But this leads to the same result.

It would be great if laravel-idea could ignore private component properties.

**Comment by adelf** [comment]
Fixed in 7.0
