### ISSUE TITLE
What is the difference between a regular account and an educational account

### ISSUE THREAD

**Issue by mhmd2004** [laravel-idea/plugin#71]
What is the difference between a regular account and an educational account

**Comment by adelf** [comment]
There is no difference.

**Comment by mhmd2004** [comment]
I want you to do the e-mail I sent

**Comment by mhmd2004** [comment]
My friend sent an email about activating the add-on to his educational account, but he has not been answered

**Comment by adelf** [comment]
We are working only on business days. If he has an active JetBrains student account, the license will be added to it on Monday.

**Comment by mhmd2004** [comment]
He has a student account but I have not been contacted yet
What are your official working days?

**Comment by adelf** [comment]
Usually, free license obtaining takes 1-2 business days. Your friend's license should be created already.
