### ISSUE TITLE
[Bug]: Unknown factories inspection not working for subdirectories

### ISSUE THREAD

**Issue by david-fairbanks42** [laravel-idea/plugin#710]
### Bug description

This looks to be a namespace problem not a file location problem.
With a model located at `app/Models/Courses/Asset.php` and its factory at `database/factories/Courses/AssetFactory.php`, the IDE reports that `use HasFactory` in the model can't find the factory class. The artisan command `make:model` correctly creates the factory in matching subdirectories with the correct namespaces.
The model has the namespace `App\Models\Courses` and the factory has the namespace `Database\Factories\Courses`.
Simply changing the namespace of the factory to `Database\Factories` removes the inspection warning.
Moving the factory file up one directly only makes a difference if the namespace is changed.

### Plugin version

6.2.5.223

### Operating system

Linux

### Steps to reproduce

With an existing Laravel project:
Execute the artisan command `php artisan make:model -mf Courses/Asset`
Open the `app/Models/Courses/Asset.php` file in PhpStorm
Place mouse over `use HasFactory;` in model

**Comment by adelf** [comment]
Fixed. Thanks.

**Comment by david-fairbanks42** [comment]
Thank you for the fast response. I can confirm it's working after the update.
