### ISSUE TITLE
[Bug]: Not compatible with PhpStorm 2022.3.2

### ISSUE THREAD

**Issue by mxaadh** [laravel-idea/plugin#712]
### Bug description

Plugin 'Laravel Idea' (version '6.2.5.231') is not compatible with the current version of the IDE, because it requires to build 231 or newer but the current build is PS-223.8617.59

### Plugin version

6.2.5.231

### Operating system

Linux

**Comment by adelf** [comment]
Laravel Idea has versions compatible with all major PhpStorm versions, starting from 2022.1. Please try to update it, or delete and install it again. Seems, you've updated to 2023.1 and then reverted back.
