### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Namvarii** [laravel-idea/plugin#713]
### Bug description

Hello,

Autocompletion and clicking doesn't work on asset() helper after changing public to public_html

When i create again public folder, autocompletion and clicking to target work well.

![image](https://user-images.githubusercontent.com/50305913/216324766-ef22ed19-d38f-4abc-80e5-d3654cef6bd6.png)

### PhpStorm version

2021.3.3

### Plugin version

6.2.2.213

### Operating system

Windows

**Comment by adelf** [comment]
In the 6.3 version, you can open Preferences | Languages & Frameworks | Laravel Idea and set the public path there. Thank you.
