### ISSUE TITLE
[Bug]: Double colon should not be interpreted as PHP

### ISSUE THREAD

**Issue by ya-cha** [laravel-idea/plugin#714]
### Bug description

When using a Blade component, you can use rendered attributes with a colon:
```
<x-mycomponent :attribute="$phpAttribute>"
```

The plugin recognizes that the value ist PHP. 
However, if you use two colons, Laravel leaves it as it is and just removes the colon, because JS frameworks like Alpine need that syntax too:

```
<x-mycomponent ::attribute="jsAttribute>"
```

But the IDE shows an error beacause it tries to interpret `jsAttribute` as PHP.

### Plugin version

6.2.5.223

### Operating system

MacOS

### Steps to reproduce

- Create a blade component
- Call the component with an attribute prefixed with `::`

### Relevant log output

```shell
Undefined constant 'jsAttribute'
```
```

**Comment by adelf** [comment]
Laravel Idea makes processes this correctly. But since 2022.3 version PhpStorm's Blade plugin started to make this PHP language injection byself. So, please create an issue in their youtrack: https://youtrack.jetbrains.com/
