### ISSUE TITLE
[Feature Request]: Generate Eloquent relations functions using camelCase

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#717]
### Feature Description

I just used the function to automatically generate the functions for relations in Eloquent models. However, the generated functions were only suggested as snake case.

For example:

```php
    public function some_booking(): BelongsTo
    {
        return $this->belongsTo(SomeBooking::class);
    }
```

However, how I would like it is using camelCase:

```php
    public function someBooking(): BelongsTo
    {
        return $this->belongsTo(SomeBooking::class);
    }
```

Would be much appreciated if you could add camelCase suggestions as well to the dropdown. 

Thanks!

**Comment by adelf** [comment]
Fixed in the 6.3 version. Thank you.
