### ISSUE TITLE
[Bug]: Create Filament Resource: The Relations Managers view should be scollable

### ISSUE THREAD

**Issue by lalov** [laravel-idea/plugin#719]
### Bug description

I am adding a resource for a table with lots of relations. So many that the screen is full, and I can only select from the top of the list. It is not possible to scroll down. 

### Plugin version

6.2.5.223

### Operating system

Windows

### Steps to reproduce

Make a model with many,many relations. 

Run "Create Filament Resource", and use the model with a lot of relations. 

![bilde](https://user-images.githubusercontent.com/3465648/218769344-5c2e3855-b1f4-4a9e-8204-f9efdc697dac.png)

**Comment by adelf** [comment]
Really sorry about that. Couldn't imagine such a big amount of relations. Will be fixed.

**Comment by adelf** [comment]
Fixed in the 6.3 version. Thank you.
