### ISSUE TITLE
[Feature Request]: Spatie\Permission autocompletes 

### ISSUE THREAD

**Issue by beshoo** [laravel-idea/plugin#720]
### Feature Description

It's wonderful to see how many Laravel programmers are making use of the Spatie\Permission\ library, however, it's currently not supported by PHP Laravel Idea.

We understand how important it is for programmers to have a smooth workflow, and having an autocomplete feature for Role and Permission would go a long way in improving the user experience.

For instance, instead of having to manually type out the code block you provided for defining roles and permissions, having an autocomplete feature would allow programmers to quickly and easily access the necessary code, saving them time and effort.

We empathize with the challenges that programmers face when working with code, and we would love to help make the process as seamless and efficient as possible. Therefore, we strongly recommend the addition of an autocomplete feature for Role and Permission in PHP Laravel Idea.

**Comment by adelf** [comment]
The possibility to add permissions to the completions already exists.

But I'm not sure how to implement it. Console command to fill this file - but where? laravel-permission package might be not a good place for it. I can't go to the database for each completion...

**Comment by beshoo** [comment]
I appreciate your response and your dedication to finding the best way to
implement the feature of adding permissions to completions. It's clear that
you have put a lot of thought into this, and I think your concerns are valid.

Regarding the console command idea, I can see how that might not be the
best approach for this feature. However, I think creating a GUI interface
that allows users to define their own completions, using seeders files as
references, could be a great solution.

By doing this, you would be providing an intuitive and user-friendly way
for users to set up their roles and permissions, and you could use the
seeders files to generate the necessary completions.
Or you may creat your own json database.

This would also avoid the need to go to the database for each completion.

I believe that this solution would provide a good balance of ease of use
and customization, and it would help make the Spatie\Permission\ package
even more valuable to Laravel programmers.

Thank you for your dedication to this project, and I look forward to seeing
the great work you do in the future!

**Comment by beshoo** [comment]
> The possibility to add permissions to the completions already exists.
> 
> But I'm not sure how to implement it. Console command to fill this file - but where? laravel-permission package might be not a good place for it. I can't go to the database for each completion...

Am looking forward to hearing from you about my idea...

Regard

**Comment by adelf** [comment]
Seeders parsing sounds good, but developers prefer different ways to describe permissions there.
I'm busy with releasing a new version now, but I'll try to suggest at least something soon.

**Comment by beshoo** [comment]
@adelf Let me help with this. you do not need to parse any thing.
look at this.
```

{
  "roles": [
    {
      "name": "organization",
      "guard_name": "api"
    },
    {
      "name": "admin",
      "guard_name": "api"
    }
  ],
  "permissions": [
    {
      "name": "add user",
      "guard_name": "api"
    },
    {
      "name": "delete user",
      "guard_name": "api"
    }
  ],
  "role_permissions": [
    {
      "role_name": "organization",
      "permissions": [
        "add user"
      ]
    },
    {
      "role_name": "admin",
      "permissions": [
        "add user",
        "delete user"
      ]
    }
  ]
}
```
This JSON dataset contains three main sections: "roles", "permissions", and "role_permissions". The "roles" section contains an array of objects representing the roles, while the "permissions" section contains an array of objects representing the permissions. The "role_permissions" section contains an array of objects that maps roles to their respective permissions.

Here's an example of how you can use this JSON dataset to create Roles and Permissions in Laravel using a seeder:

```

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolePermissionSeeder extends Seeder
{
    public function run()
    {
        $data = json_decode(file_get_contents(__DIR__.'/data.json'), true);

        foreach ($data['roles'] as $roleData) {
            $role = Role::firstOrCreate($roleData);
        }

        foreach ($data['permissions'] as $permissionData) {
            $permission = Permission::firstOrCreate($permissionData);
        }

        foreach ($data['role_permissions'] as $rolePermissionsData) {
            $role = Role::where('name', $rolePermissionsData['role_name'])->first();

            foreach ($rolePermissionsData['permissions'] as $permissionName) {
                $permission = Permission::where('name', $permissionName)->first();
                $role->givePermissionTo($permission);
            }
        }
    }
}

```
This seeder reads the JSON dataset from a file, creates the roles and permissions, and then maps the roles to their respective permissions using the "role_permissions" section of the JSON dataset.

You can customize this seeder as per your needs, for example, if you want to use a different path for the JSON file, or if you want to add additional fields to the roles and permissions objects in the JSON dataset.
What do you think?

**Comment by adelf** [comment]
Is this file standard? Or only used in your project?

**Comment by beshoo** [comment]
Well, usually I do like this:

```
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Create Roles
        $rootRole = Role::firstOrCreate(['name' => 'root', 'guard_name' => 'api']);
        $adminRole = Role::firstOrCreate(['name' => 'admin', 'guard_name' => 'api']);
        $organizationRole = Role::firstOrCreate(['name' => 'organization', 'guard_name' => 'api']);
        $agentRole = Role::firstOrCreate(['name' => 'agent', 'guard_name' => 'api']);
        $individualRole = Role::firstOrCreate(['name' => 'individual', 'guard_name' => 'api']);

        // Create Permissions
        $addUser = Permission::firstOrCreate(['name' => 'add user', 'guard_name' => 'api']);
        $editUser = Permission::firstOrCreate(['name' => 'edit user', 'guard_name' => 'api']);
        $deleteUser = Permission::firstOrCreate(['name' => 'delete user', 'guard_name' => 'api']);
        $listUsers = Permission::firstOrCreate(['name' => 'list users', 'guard_name' => 'api']);

        // Assign Permissions to Roles
        $rootRole->givePermissionTo([
        
            $editUser,
            $deleteUser,
            $listUsers,

       
        ]);

        $adminRole->givePermissionTo([
            $addRootUser,
        ]);

        $organizationRole->givePermissionTo([
            $listUsers,
            $addReport,
            $editReport,
            $listReports,
            $manageFiles,
            $addUser,
            $editUser,
            $deleteUser,
            $addAgentUser,
            $editAgentUser,
            $deleteAgentUser,
            $addIndividualUser,
            $editIndividualUser,
            $deleteIndividualUser,
            $changeReportStatus,
            $createMoreReports,
            $viewReportsByUserId
        ]);

        $agentRole->givePermissionTo([
            $addReport,
            $listReports,
            $manageFiles,
            $createMoreReports
        ]);

        $individualRole->givePermissionTo([
            $addReport,
            $listReports,
            $manageFiles,
        ]);
    }
}

```

But I came up with this idea for you! The JSON is kind of complicated. i will try to simplify it for you

**Comment by beshoo** [comment]
Check this out:
```

{
    "data": {
        "organization": {
            "guard_name": "api",
            "permissions": [
                "add user"
            ]
        },
        "admin": {
            "guard_name": "api",
            "permissions": [
                "add user",
                "delete user"
            ]
        }
    }
}
```
```

foreach ($data['data'] as $name => $item) {
    $guardName = $item['guard_name'];
    $permissions = $item['permissions'] ?? [];

    $role = Role::firstOrCreate([
        'name' => $name,
        'guard_name' => $guardName
    ]);

    foreach ($permissions as $permissionName) {
        $permission = Permission::firstOrCreate([
            'name' => $permissionName,
            'guard_name' => $guardName
        ]);
        $role->givePermissionTo($permission);
    }
}

```

So the user only needs to create the roles such as "organization" which is the name of the roles
and give it permission, the code will do the rest.

**Comment by beshoo** [comment]
@adelf well, it seems this is the best approach :) have fun and your feed back is welcome

**Comment by beshoo** [comment]
Is there any update on this?

**Comment by beshoo** [comment]
@adelf 
Is there any update on this?

**Comment by adelf** [comment]
You can add this `'ide.json` file to the project:
```
{
  "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
  "auth": {
    "additionalGates": [
      "addGate1",
      "addGate2"
    ]
  }
}
```

And Laravel Idea will complete "addGate1" and "addGate2" authorization gates.

**Comment by adelf** [comment]
It was implemented some time ago, but I forgot about this issue. Sorry.
