### ISSUE TITLE
[Bug]: "Find unused views" ignores @includeWhen()

### ISSUE THREAD

**Issue by mnastalski** [laravel-idea/plugin#721]
### Bug description

"Find unused views" menu option seems to ignore views that are included using `@includeWhen()` in the blade files.

### Plugin version

6.2.5.223

### Operating system

MacOS

### Steps to reproduce

- Create a view `foo.blade.php`
- Include it using `@includeWhen(true, 'foo')`
- Run "Find unused views"

**Comment by adelf** [comment]
Fixed in the 6.3 version. Thank you.
