### ISSUE TITLE
[Feature Request]: Model attributes autocompletion in custom methods

### ISSUE THREAD

**Issue by mathieutu** [laravel-idea/plugin#724]
### Feature Description

Hi, 

Eloquent attributes autocomplete works in some predefined methods. 
It would be great to be able to have them in user defined method.

ex: having autocomplete in a `User::createAdmin([...])` function.

We could leverage a new complete type in `ide.json` file.

Thanks!

Mathieu.

**Comment by mathieutu** [comment]
Actually I managed to do something with the (well hidden 😛) `classFields` type:
```json
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "classFields",
            "options": {
                "fieldsFilter": {
                    "fetch": "own",
                    "modifier": ["public"]
                }
            },
            "condition": [
                {
                    "methodNames": ["myCustomMethod"],
                    "classFqn": ["\\App\\Models\\User"],
                    "place": "arrayKey"
                }
            ]
        }
    ]
}
```

**Comment by adelf** [comment]
It's documented, but very shortly here - https://laravel-idea.com/docs/ide_json/completion#available-completions

Also, this schema helps clever guys to find it out themselves :)

**Comment by adelf** [comment]
I wanted to add a special, clever Eloquent field completion by ide.json, but it isn't implemented yet.

**Comment by mathieutu** [comment]
Yeah, it's how I found it.

However it seems to work only if the type of the instance is defined in the current file, so it's still quite limited 😔:

![2023-02-22 18 55 07](https://user-images.githubusercontent.com/11351322/220714944-f85a4ae4-b32d-40f7-a75a-e6644e0fe5f0.gif)

**Comment by adelf** [comment]
I'll try to fix that.

**Comment by adelf** [comment]
Fixed in 7.0

**Comment by mathieutu** [comment]
Thanks @adelf! Which way did you chose to implement it?
Did you just fix [the bug](https://github.com/laravel-idea/plugin/issues/724#issuecomment-1440515964) or did you implement something else?

**Comment by adelf** [comment]
Fixed the bug :)
