### ISSUE TITLE
[Bug]: long list of migrations not evaluated, no errors 

### ISSUE THREAD

**Issue by ogidimitrov** [laravel-idea/plugin#729]
### Bug description

Long list of 700+ files count of migrations. No errors schema is not latest.

### Plugin version

6.3.0.223

### Operating system

MacOS

### Steps to reproduce

I cannot share the migrations. Its a 5 year long valid migrations list executed on every build.

**Comment by adelf** [comment]
So, some last migrations are ignored?

**Comment by ogidimitrov** [comment]
i don't have time to track specifically. The facts are - i have relation X - not recognized on two different models. Do you have test case for this ? is it even supported. Migration A introduce table X. Migration B changes schema of X , C again, D again..

**Comment by adelf** [comment]
Yes. I have a lot of tests for migrations(adding/removing fields in the tables, renaming tables/fields). In the next version, I implemented the new `renameTo()` method for migrations. What do you mean by "changes schema"?

**Comment by adelf** [comment]
What methods do you use? Maybe I don't support some methods?
