### ISSUE TITLE
It would be nice to suggest guards from the classes

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#73]
![image](https://user-images.githubusercontent.com/10347617/85409744-dc94f100-b56e-11ea-9f72-92d2219dcf3f.png)

![image](https://user-images.githubusercontent.com/10347617/85409816-f3d3de80-b56e-11ea-9200-97579612e026.png)

**Comment by adelf** [comment]
It's possible for 'auth', but hard for 'can'. I'm collecting gates during indexing and it seems not possible to get constants value there... I'll try to find a solution. Thanks.

**Comment by adelf** [comment]
4.0 version is available. It should complete in both cases.
