### ISSUE TITLE
[Bug]: Illuminate\Http\Request::validate return void instead of array

### ISSUE THREAD

**Issue by aldesrahim** [laravel-idea/plugin#731]
### Bug description

Laravel version: 10

After generate idea helper files, `Illuminate\Http\Request::validate` is returned as void. It should return as an array.

![image](https://user-images.githubusercontent.com/37100012/222050494-c323015c-9f2c-4974-aeea-a0e2313be7b1.png)

### Plugin version

6.3.1.231

### Operating system

Linux

### Steps to reproduce

Upgrade from Laravel 9 to Laravel 10 and generate helper files

### PHPStrom Information

PhpStorm 2023.1 EAP
Build #PS-231.7665.36, built on February 28, 2023
Runtime version: 17.0.6+10-b829.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-32-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1962M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    nl.deschepers.laraveltinker (2.5.1)

Current Desktop: ubuntu:GNOME

**Comment by adelf** [comment]
Hi. It's a 2023.1 EAP behavior. I asked PhpStorm devs about it. Waiting for their answer.

**Comment by aldesrahim** [comment]
I see, thanks for info

**Comment by adelf** [comment]
It's fixed in the last PhpStorm 2023.1 beta.

**Comment by aldesrahim** [comment]
Alright, thank you very much
