### ISSUE TITLE
[Bug]: The "missing return type declaration warning" no longer works with Laravel-idea

### ISSUE THREAD

**Issue by nekooee** [laravel-idea/plugin#733]
### Bug description

In the last version, after enabling the "Laravel-idea" plugin in PhpStorm, the "missing return type declaration warning"  in Controllers no longer works.

### Plugin version

6.3.1.223

### Operating system

Windows

**Comment by adelf** [comment]
Hello. It's done on purpose.

Please check Preferences | Languages & Frameworks | Laravel Idea | Suppression. It can be turned off there.
