### ISSUE TITLE
[Bug]: Generate Helper code always fails if Laravel is not installed in the root

### ISSUE THREAD

**Issue by dfumagalli** [laravel-idea/plugin#736]
### Bug description

In our startup we had to put together multiple heterogeneous APIS under the same "<webroot>/v1" folder.

I had to install Laravel 9 under <webroot>/v1/interop/ which is one of these APIs.

I had to adjust the .htaccess file and now Laravel, its tests etc. works perfectly.

However, the Laravel Idea plugin keeps proposing me to "Generate Helper Code" and then it shows a "Helper Code Generation failed" message like in the attached screenshot.

![2023-03-08_001](https://user-images.githubusercontent.com/5745561/223785280-db162895-4e6a-4255-9e19-7097948b10ac.png)

Please allow me to specify the exact directory to the plugin. I already "remapped" some other directories (including the unit tests) by hand to make them work.

### Plugin version

6.3.1.223

### Operating system

Windows

### Steps to reproduce

1. Install Laravel in a sub-folder (in my case, sub-sub-folder)
2. Install plugin
3. It will automatically show a popup asking to generate the helper files.
4. Watch it fail (see screenshot).

**Comment by adelf** [comment]
Hi, Dario.

Try to go Settings | Languages & Frameworks | Laravel Idea and change "Laravel Directory" value to the laravel application root(with "app", "config" and other directories). Also, seems, you haven't done "composer install" yet, right?

**Comment by dfumagalli** [comment]
Hello Adelf,

I had the settings set up already. Otherwise, the plug-in would not work at all. It does some of its jobs as is, but none of what I really want (autocomplete database fields and so on).

![2023-03-12_001](https://user-images.githubusercontent.com/5745561/224536166-9899164a-1ebb-4b57-99bf-ab9ea74c12f8.png)

![2023-03-12_002](https://user-images.githubusercontent.com/5745561/224536175-a267eb7d-a67e-4d4a-91d6-04c985bd98eb.png)

**Comment by adelf** [comment]
I checked - everything works if the Laravel installation is not in the root.

At the beginning of Helper code generation, Laravel Idea asks PhpStorm "give me meta-information about the \Illuminate\Support\Collection class" and. if PhpStorm says - there is no such class - it shows this message. Please check your vendor folder. And try to find this class by the standard PhpStorm "Find class" function - Ctrl+N in Windows default keymap.

**Comment by dfumagalli** [comment]
At first I did not find it, then I read [this forum post](https://laravel.io/forum/illuminatesupportcollection-doesnt-exist) and found it under Illuminate/Collections/Collection.

The "Find class" function cannot find it. However, if I type:

use Illuminate\Support\Collection

then I can use it just fine as a function parameter.

This is weird.

![2023-03-13_001](https://user-images.githubusercontent.com/5745561/224781607-008f20d4-ce76-4cab-b50d-b20a6b4505e6.png)

**Comment by dfumagalli** [comment]
I am attaching the composer.json file. It looks "normal". The only thing I added since I've installed Laravel (only using it as REST backend right now) is the "files" stanza:

 "files": [
            "app/Helpers/GeneralFunctionsHelper.php"
        ]

However, the issue was present before adding it.

composer.json:
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/GeneralFunctionsHelper.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
          "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
          "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
          "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by adelf** [comment]
Do you have other composer.json files in the project? Maybe PhpStorm uses another one and didn't configure vendor libraries correctly?

Please check this setting:

<img alt="image" src="https://user-images.githubusercontent.com/2818394/224784611-0b346c01-57e3-4d4c-82b1-c28794b893a5.png">

**Comment by dfumagalli** [comment]
I didn't touch anything in that preference. Here's how it looks like:
![2023-03-13_002](https://user-images.githubusercontent.com/5745561/224785387-fca24fb6-ab9e-4855-af6a-807bec2a9d1d.png)

**Comment by dfumagalli** [comment]
I found out something. Apparently the autodetection (if PHPStorm even does it!) of the above path failed.

Should have been ".../source/v1/interop/composer.json"

v1 is missing.

Now, I added it and....


WHAZAM! The plugin bombed as per screenshot.
![2023-03-13_003](https://user-images.githubusercontent.com/5745561/224786495-ca1d983f-5fe6-447b-88bd-5a42b677d479.png)

**Comment by adelf** [comment]
It's ok. This exception happens sometimes. Now, if PhpStorm correctly configures the project with the correct composer.json file - it should work.

**Comment by dfumagalli** [comment]
Ok, how do I check that PHPStorm has configured the project? Does it create some file whose presence I can check?

**Comment by adelf** [comment]
try to find this class by the standard PhpStorm "Find class" function - Ctrl+N in Windows default keymap.

**Comment by dfumagalli** [comment]
Now it appears!
I guess this incident is fixed, then 🏆

Thank you very much!
