### ISSUE TITLE
[Feature Request]: Allow specifying fetched class in class fields completion

### ISSUE THREAD

**Issue by BertvanHoekelen** [laravel-idea/plugin#738]
### Feature Description

I'm trying to add auto completion to one of my factory methods that takes the properties of an eloquent model.

```php
User::factory()->withProfile(['first_name' => 'Bert']); // should autocomplete the fields from Profile model.
```

I tried setting fetch to a class implementation but according to the schema this is not possible. I also don't know if this would even work with that public modifier but it gives you an example of what I tried :)
```json
{
  "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
  "completions": [
    {
      "complete": "classFields",
      "options": {
        "fieldsFilter": {
          "fetch": "\\App\\Models\\Profile",
          "modifier": ["public"]
        }
      },
      "condition": [
        {
          "methodNames": ["withProfile"],
          "classFqn": ["\\Database\\Factories\\App\\Models\\UserFactory"],
          "parameters": [1],
          "place": "arrayKey"
        }
      ]
    }
  ]
}

```

**Comment by adelf** [comment]
`withProfile` is a standard Laravel magic method, right? It uses `profile` relation?

**Comment by BertvanHoekelen** [comment]
No, It's a method I added to the UserFactory myself.  I know you can use `for` in those factories, but I have some nested things I want to autocomplete but this is just the simplest example.

```php
public function withProfile(array $profileFields = []): self
{
    return $this->afterCreating(function (User $user) use ($profileFields) {
        Profile::factory()->createOne(array_merge(['user_id' => $user->id], $profileFields));
    });
}
```

**Comment by adelf** [comment]
It will look like this.
```json
{
  "complete": "classFields",
  "options": {
    "fetchClass": "\\App\\Data\\SomeData",
    "fieldsFilter": {
      "fetch": "own",
      "modifier": ["public", "protected"]
    }
  },
  "condition": [
    {
      "functionNames": ["custom_fetch"]
    }
  ]
}
```

**Comment by BertvanHoekelen** [comment]
Amazing! Thank you!

**Comment by adelf** [comment]
Works in 7.0

**Comment by maicol07** [comment]
@adelf this feature is great! However, currently, it can only be used with a single class/model. I would like to use it dynamically.

For example, I'm currently using [Restify](https://restify.binarcode.com/) and I want to achieve full autocompletion on it. The issue is: I want model attributes autocompletion on the field function, referencing the model class in the `$model` static property.

Code example:

```php
<?php

namespace App\Restify;

use App\Models\User;
use Binaryk\LaravelRestify\Http\Requests\RestifyRequest;

class UserRepository extends Repository
{
    public static string $model = User::class;

    public function fields(RestifyRequest $request): array
    {
        return [
            field('name')->rules('required'), // Wanted: Autocompletion of 'name'
            field('email')->storingRules('required', 'unique:users') // Wanted: Autocompletion of 'email'
        ];
    }
}
```

Is it possible to add a way to specify the method?

Thanks
