### ISSUE TITLE
[Feature Request]: lang_path file suggestions

### ISSUE THREAD

**Issue by Muetze42** [laravel-idea/plugin#740]
### Feature Description

Would it be possible to implement file suggestions for the `lang_path` function to the directory `/lang`?

Available in Laravel 9 & 10. Laravel 8 and older, I don't know....
https://laravel.com/docs/9.x/helpers#method-lang-path  
https://laravel.com/docs/10.x/helpers#method-lang-path

| Function          | Target       | File suggestions work | Reference                                                                               |
|-------------------|--------------|-----------------------|-----------------------------------------------------------------------------------------|
| `app_path()`      | `/app`       | :heavy_check_mark:    | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-app-path)                   |
| `base_path()`     | `/`          | :heavy_check_mark:    | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-base-path)                  |
| `database_path()` | `/database`  | :heavy_check_mark:    | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-database-path)              |
| `lang_path()`     | `/lang`      | :x:                   | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-lang-path)                  |
| `mix()`           | `/public`    | :grey_question:       | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-mix)                        |
| `resource_path()` | `/resources` | :heavy_check_mark:    | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-resource-path)              |
| `storage_path()`  | `/storage`   | :heavy_check_mark:    | [Laravel Docs](https://laravel.com/docs/10.x/helpers#method-storage-path)               |
| `@vite()`         | `/`          | :heavy_check_mark:    | [Laravel Docs](https://laravel.com/docs/10.x/10.x/vite#loading-your-scripts-and-styles) |

**Comment by adelf** [comment]
Works in 7.0
