### ISSUE TITLE
[Bug]: Filament Resource with RelationManager doesn't create the Resource class

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-idea/plugin#742]
### Bug description

When creating a new Filament Resource, if I don't opt to create `RelationManager` for the resource, then all the files get created correctly. But if I select a relation for the `RelationManager` then the `Resource.php` file doesn't get created for the Resource.

### Plugin version

6.3.1.223

### Operating system

MacOS

### Steps to reproduce

For the below steps please use a model that has relations
1. Open `Actions` window
2. Select `Create a Filament Resource`
3. Type the name of the Resource and the Eloquent Model
4. Select the relation you want to create a `RelationManager` for.
5. Press OK

**Comment by adelf** [comment]
Hi. I can't reproduce this. It works in both cases. Do you have any warning shown in the right bottom corner?
