### ISSUE TITLE
[Feature Request]: Variable detection in Blade view child

### ISSUE THREAD

**Issue by peterpan666** [laravel-idea/plugin#744]
### Feature Description

Hi !

Say I include a view from another view, it seems that there is no detection of the available variables from the parent view.

Example :

web.php
```php
Route::get('test', function () {
    return view('test', ['user' => \App\Models\User::first()]);
});
```

test.blade.php, in this file the `$user` is recognized and I have autocomplete working
```blade
<h1>{{ $user->name }}</h1>

@include('sub-test')
```

sub-test.blade.php, in this file the `$user` is **not** recognized and autocomplete is **not** working
```blade
<span>{{ $user->email }}</span>
```

Even if I make it clear to the `@include` directive that the user is passed to the sub view, I can't find a way make the sub view aware of the `$user` variable and its type.

Example :

```blade
@include('sub-test', ['user' => $user])
```

Any chance to make something like that work ?

**Comment by adelf** [comment]
Hi. In the last update, I added support for everything except the last one:
```
@include('sub-test', ['someParameter' => $user])
```

I'll try to add support for them in the next versions.

**Comment by peterpan666** [comment]
It seems to be working perfectly well ! Thanks !
