### ISSUE TITLE
[Bug]: Unknown Blade component

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel-idea/plugin#746]
### Bug description

Show "Unknown Blade component" laravel idea 7+

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3448603/228489798-e3ac8434-40b9-4489-b708-929c545bec28.png">

### Plugin version

7.0.1.231

### Operating system

MacOS

### Steps to reproduce

https://laravel.com/docs/10.x/blade#slots

**Comment by adelf** [comment]
Fixed. Thanks.
