### ISSUE TITLE
[Bug]: Helper generator dont scan extended model with $table property

### ISSUE THREAD

**Issue by walterdis** [laravel-idea/plugin#747]
### Bug description

Hi,

I'm using Laravel modules, and in each model, I extend a parent model, for example, the UserRole class extends Shared\Models\UserRole.

The Shared\Models\UserRole class has a $table property with the value "users_has_roles". When I use the help file generator, it throws some warnings, as shown in the image below.

Have I done something wrong?

Thanks

![image](https://user-images.githubusercontent.com/1938830/228524801-d0a31c62-7f79-496e-8ce7-4a003e1bf9b4.png)

### Plugin version

7.0.1.22

### Operating system

Windows

### Steps to reproduce

Create a UserRole class into a Shared folder for exemple.
Add the $table = 'users_has_roles' property

Create a UserRole class into a Module folder and extends Shared\UserRole

**Comment by adelf** [comment]
Right now, Laravel Idea searches $table field only inside the current model class. Fixed. Will be available in the next version. Thanks.

**Comment by walterdis** [comment]
Thank you ;)
