### ISSUE TITLE
Factory state(s) autocompletion

### ISSUE THREAD

**Issue by sykorax** [laravel-idea/plugin#75]
Hey there,

I was wondering if you could make an autocompletion for factory states. During writing tests it'd be really awesome!

**Comment by adelf** [comment]
You mean `account_status` and `address` fields here: https://laravel.com/docs/7.x/database-testing#factory-states ?

**Comment by sykorax** [comment]
Yeah, like:
```php
factory(User::class)->state('*** this to be autocompleted based on the states described by the factory***');
```

**Comment by adelf** [comment]
Is there any standard for factory file names? Are they always like `*Factory.php`?

**Comment by sykorax** [comment]
And there's the other function, called ``states``, which expects a list of state argument.

**Comment by sykorax** [comment]
Yeah, they have that name suffix usually.
I don't know if it'd help but those files do not contain any class definitions at all.

**Comment by adelf** [comment]
I'll try to implement it. Thank you.

**Comment by sykorax** [comment]
Thank you!

**Comment by adelf** [comment]
Added to 3.3 version.
