### ISSUE TITLE
[Feature Request]: Add possibility to control facades aliases generation to _ide_helper_facades.php

### ISSUE THREAD

**Issue by swayok** [laravel-idea/plugin#752]
### Feature Description

Hello.

I have disabled aliases for facades in config/app.php:
```
'aliases' => [],
```

But plugin still generates code assists for aliases in _ide_helper_facades.php:
```
namespace {
    class App extends Illuminate\Support\Facades\App {}
    class Arr extends Illuminate\Support\Arr {}
    ...
}
``` 

I think that some people also disable some or all aliases and then receive errors like "Class \"Str\" not found" when code assist suggests `\Str` instead of `\Illuminate\Support\Str`. 
So the suggestion is either be able to control a list of default Laravel aliases or somehow automatically detect which aliases are actually available. 

Thank you for this great plugin!

**Comment by adelf** [comment]
It should be smarter now. Please check 7.0.3 version

**Comment by swayok** [comment]
Perfect! Thank you!
