### ISSUE TITLE
[Bug]: Jetstream Response macro is not recognised

### ISSUE THREAD

**Issue by riabiy** [laravel-idea/plugin#755]
### Bug description

Something like 
`redirect()->route('project.index')->banner(__('toast.project.deleted'));`
gives an error. 

<img width="1038" alt="Screenshot 2023-04-14 at 14 46 24" src="https://user-images.githubusercontent.com/124934838/232024625-755745a1-345b-4bfe-8eb5-9ba8e1b61b55.png">

### Plugin version

Latest

### Operating system

None

**Comment by riabiy** [comment]
Just FYI, if it's a known issue -> that's it :D

Wanted to report just in case.

**Comment by adelf** [comment]
Hi.

Just tested. 

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2818394/234795474-c8beeebd-202e-4a1b-b2f4-66bf392929de.png">

What Laravel, Laravel Idea and PhpStorm version do you use?

**Comment by riabiy** [comment]
@adelf 

**Versions**

<img width="532" alt="img3" src="https://user-images.githubusercontent.com/124934838/234809056-c502c6be-1008-4f1e-b37a-c37006a3ec25.png">
<img width="563" alt="img copy" src="https://user-images.githubusercontent.com/124934838/234809335-ff2018c7-5fd2-4a8c-84fd-694255ee209f.png">


**FYI**

Did 
- removed vendor and composer install
- cache invalidation
- regenerated helpers

Issue persists on my setup, but it's cool, that I won't have one soon. Though it's quite strange. I've checked how next version of Jetstream does the banner. It's the same macro. And the same `route()` method (https://github.com/laravel/framework/blob/be2ddb5c31b0b9ebc2738d9f37a9d4c960aa3199/src/Illuminate/Routing/Redirector.php#L152).

Weird.

  
<img width="991" alt="adsf" src="https://user-images.githubusercontent.com/124934838/234811613-b13187a2-b08b-433c-bc8d-025d683922b6.png">

**Comment by adelf** [comment]
This issue was happening in one of the previous versions of Laravel Idea. Which version do you have?

**Comment by riabiy** [comment]
@adelf latest. 

I've invalidated caches for that reason. Made sure the plugin is up to date and then busted caches. 

<img width="246" alt="sd" src="https://user-images.githubusercontent.com/124934838/234850245-75c0525a-f056-45f1-8537-9d4121dfd383.png">

**Comment by riabiy** [comment]
@adelf https://github.com/laravel/jetstream/blob/45e3af7e72a1423261b23c81cf883cc7c63b9d4e/src/JetstreamServiceProvider.php#L76

This is the fix. Seems like just to upgrade and should be fine.
