### ISSUE TITLE
"generics" for Laravel collections

### ISSUE THREAD

**Issue by BoyeMagnus** [laravel-idea/plugin#76]
Would it be possible to add support for "generics" for Laravel collections?
Just like with models, where its properties is supporten in groupBy function and higher proxy collections: (Right where the white lines are)
<img width="439" alt="Skærmbillede 2020-07-02 kl  19 09 56" src="https://user-images.githubusercontent.com/24491343/86390113-c76b4100-bc97-11ea-836b-1e8952cb798f.png">

This is the only current support we got with collection by default:
![image](https://user-images.githubusercontent.com/24491343/86389908-604d8c80-bc97-11ea-86a6-05475097582f.png)

**Comment by adelf** [comment]
I can try to implement this for `groupBy` and `pluck` method, but for implementing high order proxy collections I'm creating special helper classes, like `_UserCollectionProxy`, for each Eloquent model...

**Comment by BoyeMagnus** [comment]
Okay. Would it be possible for all of the other collection methods as well? The ones I think should have it is:
keyBy, groupBy, sortBy, median, max, avg, contains (with key), except, firstWhere, get, has

Most needed for me is:
keyBy, groupBy, sortBy and sum :)

Would it be possible to support these as well?
![image](https://user-images.githubusercontent.com/24491343/86393086-cc7ebf00-bc9c-11ea-9a86-99c9838dd75e.png)

![image](https://user-images.githubusercontent.com/24491343/86393121-dd2f3500-bc9c-11ea-9d27-6762baf840bb.png)

**Comment by skeemer** [comment]
Is this fixed by using the now supported generics doc?
`/** @var Collection<SomeClass> $collection */`

**Comment by adelf** [comment]
AFAIK, it will be fixed in Laravel 9.

**Comment by BoyeMagnus** [comment]
Yes agreed!

It is resolved with the new collection template docblocks from Laravel 👍
