### ISSUE TITLE
[Feature Request]: Smart GoTo Job dispatch

### ISSUE THREAD

**Issue by MrAtiebatie** [laravel-idea/plugin#760]
### Feature Description

Just like opening the factory class when going to the definition of `User::factory()`, it would be nice to open the Job when going to the definition of `MyJob::dispatch`. Now it opens up the dispatch method.

Furthermore I love this plugin!

**Comment by adelf** [comment]
Hello. Why don't you click on `MyJob` instead?

**Comment by MrAtiebatie** [comment]
It's possible but it feels inconsistent compared to the User::factory() feature to open the factory class. And I'm not really interested in the declaration of the dispatch method.

**Comment by adelf** [comment]
Another user also asked about it. I'll try to implement.

**Comment by adelf** [comment]
Available in 7.1
