### ISSUE TITLE
[Bug]: Property accessed via magic method

### ISSUE THREAD

**Issue by rforced** [laravel-idea/plugin#761]
~

**Comment by adelf** [comment]
399 issue was about $this->fields. So, it's different. I can't reproduce it. Have you generated a helper code? main menu > Laravel > Generate Helper Code.

**Comment by rforced** [comment]
Yes, I have generated helper code. Everything was working well for me until I updated phpstorm to 2023.1. I'm also using the new UI if that matters.

**Comment by xsjcTony** [comment]
Upvote for this.

I get this error even the property has auto-completion by the plugin:
![image](https://github.com/laravel-idea/plugin/assets/45784210/61c8e0ef-4187-4255-b982-1250abee7331)
![image](https://github.com/laravel-idea/plugin/assets/45784210/dd5d1096-a23a-4b87-8b18-a42349957ebf)

Helper code generated.

PhpStorm and Laravel Idea plugin is all latest
