### ISSUE TITLE
[Bug]: Migration adds $MIGRATION_ID_METHOD with no fields

### ISSUE THREAD

**Issue by turiondolby** [laravel-idea/plugin#765]
### Bug description

When I generate a new migration, after entering the fields I need, I get the following:
```php
Schema::create('test_product', function (Blueprint $table) {
    $MIGRATION_ID_METHOD

    $table->timestamps();
});
```

### Plugin version

7.1.0.231

### Operating system

Windows

### Steps to reproduce

Generate a new model with some fields OR generate a random migration.

**Comment by adelf** [comment]
Hello. Could you please go to the Settings > Editor > File And Code Templates > Code > Laravel Ideal Database Migration and Revert it?

<img alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/7bbb59f2-ece7-4342-916e-9fb4bed354b2">

**Comment by turiondolby** [comment]
This fixed the issue. Thank you 👍
