### ISSUE TITLE
[Feature Request]: Detect and suggest model methods/properties/attributes in `JsonResource` classes

### ISSUE THREAD

**Issue by tadhgboyle** [laravel-idea/plugin#767]
### Feature Description

Thanks so much for the amazing plugin - it makes life so much easier!

I would like to propose the functionality to be able to get autocompletion suggestions when in the context of a `Illuminate\Http\Resources\Json\JsonResource` ([Laravel docs](https://laravel.com/docs/10.x/eloquent-resources#writing-resources)).

Currently when writing resources, we do not have any autocompletion because we have to use `$this` when defining them:
<img width="642" alt="image" src="https://github.com/laravel-idea/plugin/assets/26070412/671d56d4-9e71-4c16-98d9-8abe4d1417d5">

I think this could be solved by the plugin attempting to detect the model name based on the class, so:
`MyModelResource` detects it is for `MyModel`, and is able to give suggestions when within the file to access attributes and methods within `MyModel`.

<img width="535" alt="image" src="https://github.com/laravel-idea/plugin/assets/26070412/51774be0-d6fa-4fa3-aa2d-9de54576d9a1">
<img width="519" alt="image" src="https://github.com/laravel-idea/plugin/assets/26070412/586d8aab-0289-47fe-bfa2-419457f96679">

I hope this makes sense - let me know if I did not explain it nicely!

**Comment by adelf** [comment]
Could you try to generate resource based on this model?

Inside the MyModel class: Generate action(Alt-Ins, Cmd-N) and choose Json Resource.
Everything will be completed after that.

Also, don't forget to generate helper code(Cmd(Ctrl)-Shift-.).

**Comment by tadhgboyle** [comment]
Thanks for the quick reply 🙇🏼‍♂️ 

This did not change anything - all of my resources have been generated this way, and the helper code was re-generated without changes as well

If there is some debug log or anything I can provide please let me know

**Comment by adelf** [comment]
Json resource should be generated with 
```
/** @mixin \App\Models\MyModel */
```
So, it will be completed. However, if you changed the template in the Settings > Editor > File And Code Templates > Code > Laravel Ideal Json Resource - this phpDoc can be omitted...

**Comment by tadhgboyle** [comment]
Ah, thank you very much!
