### ISSUE TITLE
[Bug]: Third Party UI Kit Auto Complete Support

### ISSUE THREAD

**Issue by chriischambers** [laravel-idea/plugin#770]
### Feature Description

Sorry to open this as a bug report.  I know from searching that Laravel Idea does support autocomplete for third party packages but the documentation is missing and I cannot get this to work using laravel-ide-v2.json. I have tried lots of combinations to get this to work but my components do not seem to be recognized. 

Also - this may be a silly question but after I update the json file, do I need to actually do something to register my components?  I was clicking Generate Helper Code but i'm not sure if that is needed or not?

So say for example my vendor config file is in this format - 

```php
return [
    ...
    'components' => [
        'alert' => \Kit\Components\Alerts\Alert::class,
        'button' => \Kit\Components\Buttons\Button::class,
    ],
    'prefix' => '',
    'namespace' => '',
    ...
];
```

These components are registered in my app as `<x-alert>` and `<x-button>` etc.

For the json config I have this - 

```json
{
    "$schema": "http://laravel-ide.com/schema/laravel-ide-v2.json",
    "blade": {
        "components": {
            "fromConfig": [
                {
                    "file": "vendor/my-kit/my-kit/config/my-kit.php",
                    "key": "components"
                }
            ]
        }
    }
}
```

Any advice here would be greatly appreciated.

**Comment by adelf** [comment]
Hi. We are working on docs already. Sorry for that.

It's hard to help without your code... Usually, if it is a package, ide.json file should be there... Try this one.
```
"blade": {
    "components": {
      "fromConfig": [
        {
          "configFileName": "my-kit",
          "componentsKey": "components",
          "prefixKey": "prefix",
          "namespaceKey": "namespace",
        }
      ],
      "ignoreViewPaths": ["path/to/package/resources/views"]
    }
  }
```

**Comment by chriischambers** [comment]
Hi @adelf 

Thank you for this response.  This is really helpful indeed.

Thank you for the great work as usual.

Chris
