### ISSUE TITLE
Plugin not working on 2023.2 EAP

### ISSUE THREAD

**Issue by MarkoKaartinen** [laravel-idea/plugin#772]
Just to let you guys know that this is not working on latest EAP build

<img width="333" alt="image" src="https://github.com/laravel-idea/plugin/assets/431075/43b67d11-228f-46fe-8b88-c87fd485e08a">

**Comment by adelf** [comment]
There are a lot of updates after the 7.0.3 version, including versions for 2023.2.

If you don't get them automatically, try Check for Updates...
![image](https://github.com/laravel-idea/plugin/assets/2818394/1deca278-14d5-4481-a62c-db452bd0c968)

**Comment by MarkoKaartinen** [comment]
@adelf of course after I write this and see this reply I get an update... Thanks, I shall close this.
