### ISSUE TITLE
[Bug]: Attribute methods generation wrong visibility

### ISSUE THREAD

**Issue by emargareten** [laravel-idea/plugin#773]
### Bug description

Model accessor method generation sets the method visibility to `public` but it should be `protected`, otherwise [larastan sees it as an undefined property](https://github.com/nunomaduro/larastan/blob/master/src/Properties/ModelAccessorExtension.php#L33). this is also how it's [documented](https://laravel.com/docs/10.x/eloquent-mutators).

### Plugin version

7.1.4.231

### Operating system

MacOS

**Comment by adelf** [comment]
Fixed in 7.2. Thank you.
