### ISSUE TITLE
[Feature Request]: Re-enable code generation notification

### ISSUE THREAD

**Issue by BlackLight4K** [laravel-idea/plugin#774]
### Feature Description

I accidentally turned off code generation notifications in phpstorm, now i cannot turn it back on

**Comment by adelf** [comment]
Hello. What notifications do you mean?

However, I'll try to make a page in the Settings about all of them anyway. Thank you for posting.

**Comment by BlackLight4K** [comment]
I used to see a balloon notification after i ran Generate Eloquent Helper Code in the bottom right corner (with errors)

**Comment by adelf** [comment]
<img width="723" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/28703646-57f8-441b-8a51-bb3021868ea8">
