### ISSUE TITLE
[Bug]: Invalid method parameter classes shown

### ISSUE THREAD

**Issue by hasnat-we** [laravel-idea/plugin#775]
### Bug description

When I run generate method docs then in my autocomplete I see invalid classes for me '_IH_Thread_QB' are taking place. 
Is this known issue? Thanks

```
    /**
     * @param string|null $threadID
     * @param array $options
     * @return \App\Features\Messenger\Models\Thread|\LaravelIdea\Helper\Cmgmyr\Messenger\Models\_IH_Thread_QB[]|null
     */
    public function findOrFailThreadByID(?string $threadID, array $options = [])
    {
```

### Operating system

Linux

**Comment by adelf** [comment]
I have to generate a lot of dummy classes to make a great completion for the Eloquent magic. So, this happens sometimes.

However, I see weird class names here. 
`\App\Features\Messenger\Models\Thread` and `Cmgmyr\Messenger\Models\Thread`. Do you have both classes?

**Comment by hasnat-we** [comment]
@adelf Hi, thanks for your response. Ideally class `\App\Features\Messenger\Models\Thread` is extended from `Cmgmyr\Messenger\Models\Thread` and I feel these classes has meaningful base names. Yes both class exists.

**Comment by adelf** [comment]
Ok. I'm sorry about this, but I have to make these classes. I hope PhpStorm's API will allow me to make the completions and type hinting without these ugly hacks in the future.
