### ISSUE TITLE
[Bug]: Missing '\' in the FQCN during the event handler creation

### ISSUE THREAD

**Issue by riabiy** [laravel-idea/plugin#776]
### Bug description

Very simple typo. This is how it creates. 
<img width="2022" alt="Screenshot 2023-06-13 at 19 44 57" src="https://github.com/laravel-idea/plugin/assets/124934838/99fc2c52-3ff7-4f5e-8406-d5cf0d8e2591">

This is how it should be. 
<img width="2002" alt="Screenshot 2023-06-13 at 19 45 02" src="https://github.com/laravel-idea/plugin/assets/124934838/c957ce59-a483-4a85-b9c6-af7904b8a9e7">

LMK if you need more info or I'm wrong. Should be a simple fix. Have a nice day :) 

### Operating system

None

**Comment by adelf** [comment]
Fixed. Thanks.
