### ISSUE TITLE
[Feature Request]: Better support for config keys through custom macro's

### ISSUE THREAD

**Issue by henzeb** [laravel-idea/plugin#777]
### Feature Description

Given the following macro:
````php
 Config::macro(
    'prefix',
    function (string $prefix): Repository {
        /**
         * @var $this Repository
         */
        return new Repository(
            $this->get($prefix)
        );
    }
);
````

Given the following config file:
````php
return [
    'queue' => [
        'strategy' => 'default'
    ]
];
````

This macro `Config::prefix('queue')->get('strategy')` returns the same as `Config::get('queue.strategy')` and returns the same as `Config::get($prefix.'.strategy')` (which i do quite often)

Now this might look silly, but sometimes you might use a different configuration set based on user input. 

With this plugin, the typehint on `Config::prefix()->get()` is the same as `Config::get()`.  that is not desirable.

I know the concatenated version would not work always, but it would be helpful that if possible the plugin tries to parse the string passed to the get or set method.

**Comment by adelf** [comment]
Sorry, it is too specific and too hard to implement.
