### ISSUE TITLE
[Bug]: Unknown column with yellow highlight

### ISSUE THREAD

**Issue by ObaydaAlesawi** [laravel-idea/plugin#782]
### Bug description

Unknown column with yellow highlight.
as you see here, it shows that the column is not exists, even thought it is exists even in the property in _idea_helper_models files and it take me there when I click on it. 
![image](https://github.com/laravel-idea/plugin/assets/32073999/68c01f22-9de1-4850-8313-05078f133f18)

### Plugin version

7.1.4.231

### Operating system

Windows

**Comment by adelf** [comment]
Hello. I think it's the Laravel Query plugin.

**Comment by ObaydaAlesawi** [comment]
@adelf  Hi, thank you for your prompt response! This is truly a great plugin.
Yes, you're correct, it originates from the Laravel Query plugin.
Apologies for any inconvenience caused.

**Comment by adelf** [comment]
No problem. Don't hesitate to post any issues here)
