### ISSUE TITLE
[Request] autocomplete for livewire validation rules 

### ISSUE THREAD

**Issue by Algeneralo** [laravel-idea/plugin#79]
Hi, first of all, thanks for this amazing package.
It would be greater if the autocomplete for validation also work with livewire
Genralrly, livewire has 2 validation functions witch is:
```
$this->validate([
            "message" => 'required'
 ]); 
```
and 

```
$this->validateOnly([
            "message" => 'required'
 ]); 
```
Thanks

**Comment by adelf** [comment]
Hi, Obayda.
I’ll add it to the next version, thanks. If I missed some other livewire features, please share) I don’t have any meaningful livewire experience, so I could easily miss a lot of possible improvements.

**Comment by Algeneralo** [comment]
@adelf 
Also regarding to the action when clicking on the livewire path like this one:
`@livewire("admin.exam.index")`.
When I click on the text, it takes me to the Class.
But, sometimes I want to open the view file, not the class one.

What I suggest is, to give the user an option to choose where to go, Like the one that you did for Laravel x-blade tags.
for example this one:
![image](https://user-images.githubusercontent.com/32073999/87147750-db292f80-c2b5-11ea-8767-1ddbd45f25de.png)

**Comment by adelf** [comment]
For blade components, it was logical, because these components can be just blade files, without PHP class. That's not true for Livewire. However, I can try to add a view 'livewire.component-name' to GoTo targets...

**Comment by adelf** [comment]
Implemented in the 3.2 version. Please write here if I missed something.

**Comment by Algeneralo** [comment]
@adelf 
I saw something wrong with the "choose declaration" action.
It's working correctly only if the view exists inside the livewire directory, otherwise, it will open the Livewire component class.
Ex: for Laravel jetstream 
![image](https://user-images.githubusercontent.com/32073999/100062298-6ad41280-2e40-11eb-9439-2dfcdae4abc5.png)

**Comment by adelf** [comment]
@Algeneralo I'll try to analyze Component's code to get a needed view.

**Comment by adelf** [comment]
3.6 version is available. It should work there. Please create a new issue next time. It's a bit more convenient for me.
