### ISSUE TITLE
[Bug]: Not creating generated classes in expected folder/directory

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel-idea/plugin#790]
### Bug description

I'm sure this might just be a config setting that I can't see, because I know for certain that this issue did not used to happen.

When I am coding in a class (eg. `App\Actions\MyAction`) and I need to create another file, (say I want to make a new event) I use the laravel idea menu to create a new event class.

I expect that event class to be generated and created in the `App\Events` directory. However it is currently being created in the same folder as the the class I was working with is in `Apps\Action`.

The same is true for controllers or models or anything, I have to go to the correct folder in the side bar BEFORE i create any file using the Laravel Idea menu otherwise it always ends up in the wrong folder.

What have I done wrong/misconfigured.

Here is an example screen recording of it happening. Watch how I make a new event class but it gets created in the wrong folder and not in `App\Events` as I would expect

https://github.com/laravel-idea/plugin/assets/2513663/b44d66ff-3d37-417b-82f9-07f13ef1dfe3

### Plugin version

7.1.4.231

### Operating system

MacOS

### Steps to reproduce

Open a class in any folder other than Events
Select the laravel idea menu.
Create a new event, give it a name.
The event class created is in the folder of the original class opened and not the default expected folder of App\Event

**Comment by jonnywilliamson** [comment]
I also tried putting Events in for directory in the settings page but that didn't work either.

<img width="1129" alt="CleanShot 2023-07-05 at 23 50 23" src="https://github.com/laravel-idea/plugin/assets/2513663/38fb18e2-0660-496a-aa3e-6708c0f7005b">


I definitely never needed to do anything like this previously, I guess I changed something!

**Comment by jonnywilliamson** [comment]
Just wondering am I the only one this is happening too? If so then I'll know it's my system.

How about everyone else? Thanks

**Comment by adelf** [comment]
Hello, Jonathan. Sorry, I didn't see this issue.

The main way to create Laravel classes: using main menu > Laravel > Code Generation. Or by shortcut: Cmd-Shift-,

This "New File > Laravel" menu is used when users want to create files in a non-standard place.

**Comment by adelf** [comment]
And please, return the settings to Namespace: Events.

**Comment by jonnywilliamson** [comment]
Ahhh, ok I see the difference now. 

Thank you, I thought I was going mad.
