### ISSUE TITLE
[Bug]: goto declaration stop working for config helper

### ISSUE THREAD

**Issue by mtariqsajid** [laravel-idea/plugin#791]
### Bug description

goto declaration stop working for config helper 

```php
config('constants.elastic.elastic_search')
```

but its working for other things and env helper also working
i am confuse why its not working
i try to del vendor dir and run php artisan optimize:clear and then restart computer 
but still no joy
my os is linux mint 21.1

### Plugin version

7.1.4.231

### Operating system

Linux

### Steps to reproduce

just click the option Generate Helper Code
![image](https://github.com/laravel-idea/plugin/assets/68206359/803a4582-39d5-45db-b5ae-5a4f9c41bdec)

**Comment by adelf** [comment]
Could you show the config/constants.php file? Especially, elastic-related parts.

**Comment by mtariqsajid** [comment]
this is the constant file @adelf 

```php
<?php
$adminEmails = array_filter(array_map('trim', explode(',', env('HOURLY_REPORT_ADMIN_EMAILS', ''))), function ($item) {
    return trim($item) !== "";
});

return [
    'app_domain' => env('APP_DOMAIN'),
    'sentiment_url' => env('SENTIMENT_URL'),
    'not_include_document_types' => ['SPEC_1', 'SPEC_2', 'SPEC_3'],
    'data_format' => [
        'MM-DD-YYYY' => [
            "frontend_format" => 'MM-DD-YYYY',
            "backend_format" => 'm-d-Y'
        ],
        'DD-MM-YYYY' => [
            "frontend_format" => 'DD-MM-YYYY',
            "backend_format" => 'd-m-Y'
        ]
    ],
    'hourly_report_send_admins' => $adminEmails,
    'elastic' => [
        'elastic_search' => env('SEARCH_INDEX', ''),
        'host' => env('HOST_SEARCH', '127.0.0.1'),
        'port' => env('HOST_SEARCH', '9202'),
        'user' => env('ELASTIC_SEARCH_USER_NAME', 'elastic'),
        'password' => env('ELASTIC_SEARCH_PASSWORD', '')
    ]
];

```

**Comment by adelf** [comment]
it finds the first "return" and tries to process it. In your case it's `return trim($item) !== "";`. That's why it doesn't work. I'll try to fix it. Thank you.

**Comment by mtariqsajid** [comment]
@adelf the problem was if i want to read admin emails and they can be multiple then i have to explode it first and then check if any of them are not empty string and trim them if emails has space in the start 
so env like this

```
ADMIN_EMAILS = "josh@gmail.com, tariq@gmail.com, aslam@gmail.com"
```


that's why i try to write code in config
and if i run php artisan optimize it compile and cache it so it's not create issue in php artisan optimize 
so my code is totally correct


the funny thing is that on the first try i wrote them inline and plugin was working fine issue arise when move the adminEmails on top of the config. I did that for readability of the code.

**Comment by adelf** [comment]
I know it's correct. I already fixed it. A new version will be available on Monday.
