### ISSUE TITLE
[Bug]: Plugin does not reflect view storage path

### ISSUE THREAD

**Issue by andrewvaca** [laravel-idea/plugin#797]
### Bug description

Plugin does not reflect view storage path defined in `config/view.php`. I have moved the path from default `resource/views/` to cumstom `templates/` using `base_path('templates')` and the plugin does not see any of my templates when using them.

### Plugin version

7.1

### Operating system

MacOS

### Steps to reproduce

1. change the default view storage path in `config/view.php` (key "paths")
2. create 2 new blade files inside path defined in step 1
3. write in one of the two blades `@include('path.to.second.blade.using.dot.notation')`

What should be the result:
 - Plugin should find the path to the second blade an enable user to click-through 

What happens instead:
 - Plugin is searching for the template in default location `resources/views/` instead of the defined one

**Comment by adelf** [comment]
Currently, the plugin doesn't parse the `config/view.php` file.

You can change the path and namespace in Preferences | Languages & Frameworks | Laravel Idea | Views. 
"Default views path", "Default views namespace."

**Comment by andrewvaca** [comment]
hi @adelf, thanks for message, unfortunately it is not working. I've changed the Default views path in settings to `temaplates` (because we moved our views from `/resources/views` to `/templates`). 

I've saved the settings and even restarted PHPStorm and the plugin still can't find the view. When I click the warning and choose "Create view", it creates new view in "/resources/views" path (regardless of the settings).

**Comment by raveren** [comment]
On a semi-related note: 

https://laravel-idea.com/docs/changelog#v7_1
says that `\View::addLocation() support` was added, and I cannot get it to work, nor does the plugin acknowledge `view()->addNamespace` directives:

![image](https://github.com/laravel-idea/plugin/assets/364220/a4de6b33-1a24-4bdc-8fde-069be04d4925)

**Comment by adelf** [comment]
@raveren I've fixed it. But it will only work when `addNamespace()` is called inside ServiceProvider class.

**Comment by raveren** [comment]
oh wow, that's amazing, thanks, @adelf!

I am experimenting with grouping all related code under the app/Http/Controllers/MyController namespace like in the screenshot above. It makes life easier for complex stuff that involves a lot of split, related functionality, I'd love to also store the views alongside, but maybe it's not the greatest idea...
