### ISSUE TITLE
From templates, the ability to specify your base class has disappeared

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#80]
I have a custom base class...

![image](https://user-images.githubusercontent.com/10347617/86923363-9aef7300-c136-11ea-994a-f6b86af4cc99.png)

**Comment by adelf** [comment]
You can customize you base classes in Laravel Idea > Code generations settings. And don’t forget to change it in the main Laravel Idea settings window. It needs it to find your controllers for routing.

**Comment by andrey-helldar** [comment]
Right! I forgot that it’s possible 😁
