### ISSUE TITLE
[Feature Request]: Support Filament 3

### ISSUE THREAD

**Issue by sbc640964** [laravel-idea/plugin#805]
### Feature Description

Filament 3 has been launched but the plugin doesn't support it yet
There are many changes
Changed namespaces, panels, widgets, etc...
It will be very helpful for the thousands of users that you will support all their settings...

By the way, waiting for updates on the creation of the new model...

**Comment by adelf** [comment]
I'm already working on it(namespace, some attributes). However, I can forget some needed features, so if you want to add that specifically should be changed/added I will be very thankful.

**Comment by StringKe** [comment]
click static `$view` can't auto open editor in filament pages

**Comment by abishekrsrikaanth** [comment]
I am assuming the generators will use stubs based on what version of Filament is being used on the project right? because the class reference paths are different in Filament v3

**Comment by EG-Mohamed** [comment]
any update !

**Comment by adelf** [comment]
Plugin generators are updated to respect Filament v3 and <v3 versions (in the Laravel Idea 7.4.2).
If you want to add new Filement-based(or other) code generators - please create a new issue with at least minimal description of what should be there. It will dramatically reduce the time I will spend on implementation and increase the chance of being implemented.
