### ISSUE TITLE
[Bug]: Custom blade directives not recognised if `Blade` facade is aliased in service provider

### ISSUE THREAD

**Issue by bram-pkg** [laravel-idea/plugin#814]
### Bug description

In our codebase, we have a `use Illuminate\Support\Facades\Blade as BladeFacade`, but when you run the "Register Custom Blade Directives" action, these are not picked up by Laravel Idea.

### Plugin version

7.2.0.232

### Operating system

Linux

### Steps to reproduce

Register a custom blade directive in the `AppServiceProvider` using an aliased `Blade` facade.
Then try to autocomplete in a .blade.php file, the custom directive will not autocomplete.

**Comment by adelf** [comment]
Fixed. Thank you.
