### ISSUE TITLE
[Bug]: Phpstorm doesn't detect query scope as having been used

### ISSUE THREAD

**Issue by RyanPaiva56** [laravel-idea/plugin#816]
### Bug description

On my model, I have a scopeSorted() function. It works great and when used the IDE can track it back to the scopeSorted() function. Here's it working great:

![Screenshot from 2023-08-26 21-06-16](https://github.com/laravel-idea/plugin/assets/595049/f6766c45-7da5-4adc-8ad7-a4ed99e67e52)

And if I hit control b, it correctly sends me here but the IDE gives me an unused function warning:

![Screenshot from 2023-08-26 21-03-20](https://github.com/laravel-idea/plugin/assets/595049/9a297367-7cfb-4bf1-8b69-3a999793bc78)

Odd thing is I can hit control b on it and will show me the usages.

![Screenshot from 2023-08-26 21-08-47](https://github.com/laravel-idea/plugin/assets/595049/a2f95c11-1a2f-45e4-ba96-e4bd0340163b)

### Plugin version

7.2.0.232

### Operating system

Linux

**Comment by adelf** [comment]
You can turn this on, but you can see in the label why it's turned off by default.

<img width="808" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/ee2c2774-ede5-433a-aeda-d21b4244ea0b">

**Comment by RyanPaiva56** [comment]
That did it! I'm not seeing larger ambient CPU usage, where/when would I notice this? On build, or like while coding?

**Comment by adelf** [comment]
During scrolling the model class file. Maybe it was fixed somehow from PhpStorm's side...

**Comment by RyanPaiva56** [comment]
Yeah, I think I do see what you're saying. It jumps briefly to 100% on one core, but nothing I would notice if my system monitor weren't up. Thank you for the support!
