### ISSUE TITLE
[Feature Request]:  Support for Livewire forms in V3 

### ISSUE THREAD

**Issue by ahmdsadik** [laravel-idea/plugin#818]
### Feature Description

I just found the livewire component

![image](https://github.com/laravel-idea/plugin/assets/74914469/3de8ccb4-b0cb-4a4a-b9e4-a213a9b6ce9b)

**Plugin version**
7.3.0.232

**Comment by sohailahmad07** [comment]
Hi yes i also upgrade the plugin but i can not create livewire form object or Attribute

**Comment by adelf** [comment]
Implemented in v7.3
