### ISSUE TITLE
Creation of facades

### ISSUE THREAD

**Issue by andrey-helldar** [laravel-idea/plugin#82]
It would be great to be able to quickly create a facade 😊

For example:
![image](https://user-images.githubusercontent.com/10347617/87039769-575d3d80-c1f8-11ea-8f99-b070ee075dd7.png)

**Comment by adelf** [comment]
Facade-lover! However, it’s easy to expect something like that from guy with **App\Deprecated** namespace :)

Do you know from which Laravel version facades can work like that?

**Comment by andrey-helldar** [comment]
Deprecated methods have been moved to a separate folder so that they do not interfere with the main code, but you can’t delete them yet.

Facades in Laravel have been operating since they were added to the framework. It doesn’t matter what folder they are located in.

**Comment by adelf** [comment]
It's definitely a non-standard type of classes, so I suppose you can use Custom generations for that: https://laravel-idea.com/docs/custom_generations

Closing this.
