### ISSUE TITLE
[Feature Request]: there is no @teleport directive for livewire 3

### ISSUE THREAD

**Issue by sohailahmad07** [laravel-idea/plugin#821]
### Feature Description

i have upgraded to Livewire Will although the Livewire 3 support is amazing there is something missing for example 
you can not create livewire FormObject or Attribute there is also no @teleport directive

**Comment by adelf** [comment]
Thanks! I've just added the teleport directive. Laos, I'm going to create Forms, and even fill them by Eloquent model fields.
What about attributes?

**Comment by sohailahmad07** [comment]
cool as far as the attributes go i have not encountered any issue

**Comment by sohailahmad07** [comment]
also, while you are fixing, the rules attribute does not provide autocompletion when using array syntax. autocompletion only works for pipe syntax

**Comment by adelf** [comment]
Added in 7.4 version. Thank you.
