### ISSUE TITLE
[Bug]: Request macro generating as a static method

### ISSUE THREAD

**Issue by alexrififi** [laravel-idea/plugin#823]
### Bug description

Hi.

I'm using the following macro:

```php
// AppServiceProvider.php


class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Request::macro(
            'requiresLocalization',
            fn () => $this->headers->has('Accept-Language')
        );
    }
}
```

But when calling it this way, PhpStorm reports a problem

![изображение](https://github.com/laravel-idea/plugin/assets/21067613/a13c102c-0998-4064-a67d-90e0a43509cf)

This behavior is often annoying. Is this normal or a bug?

### Plugin version

7.3.0.232

### Operating system

Windows

**Comment by adelf** [comment]
It seems you have this inspection turned on. AFAIK, it's turned off by default. 

<img width="1063" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/35c7fb4a-d8e8-4671-a326-c11850163d28">

**Comment by alexrififi** [comment]
That's true. Thank you, darling man!

_We should probably figure out why the methods are static, but maybe later_ 😄

**Comment by adelf** [comment]
They are static and dynamic. __call and __callStatic call them. PhpStorm can't understand this, that's why it's better to disable this inspection.
