### ISSUE TITLE
[Feature Request]: Laravel Nova Fields

### ISSUE THREAD

**Issue by saschaende** [laravel-idea/plugin#830]
### Feature Description

Hi,

actually I get:

            Boolean::make('Internal Only');
            
 Can you please generate all fields like this:
 
             Boolean::make('Internal Only', 'internal_only'),    
             
 This would be a huge timesaver, because actually I always have to add the fields manually. Normally i add another title and not the field name itself.

**Comment by adelf** [comment]
The parameter for generation is added in the last update.
