### ISSUE TITLE
[Bug]: Classname in helper code is wrong

### ISSUE THREAD

**Issue by rabol** [laravel-idea/plugin#832]
### Bug description

The generated helper code have class names like this: _IH_TestUser_C, then in PHPStom one will get _IH_TestUser_C as a return type of a method, which is incorrect

### Plugin version

7.3.0.232

### Operating system

MacOS

### Steps to reproduce

generate helper code

**Comment by adelf** [comment]
Hello. I have to generate these classes to have a good completion and typing. Sadly, I can't change the behavior of return type hinting generation. I hope this will be fixed by using Collection<User> classes soon.
