### ISSUE TITLE
[Bug]: Helper for \Illuminate\View\ComponentAttributeBag constructor now expects 0 arguments

### ISSUE THREAD

**Issue by philtune-primevox** [laravel-idea/plugin#835]
### Bug description

Installed Laravel Idea within the last 4 days.

When instantiating a `new \Illuminate\View\ComponentAttributeBag` with an array, I get a new IDE warning:

 > Method call is provided 1 parameters, but the method signature uses 0 parameters

Of course if I Cmd+click into the `ComponentAttributeBag` class constructor (or just Cmd+hover to see the signature), it shows:

> public function __construct( array $attributes = [] ) : ComponentAttributeBag

I checked my projects for reference to this class, and they all also are now showing this warning. I have not yet found this issue with any other Library classes.

![image](https://github.com/laravel-idea/plugin/assets/130385353/e378b671-f0f3-4a03-89eb-6a57f35de846)
![image](https://github.com/laravel-idea/plugin/assets/130385353/2e7b7d21-6461-4bd9-acb1-101cca56ce3b)

### Plugin version

7.3.0.232

### Operating system

MacOS

### Steps to reproduce

Instantiate a new instance of that class with an array:

> $attributes = new \Illuminate\View\ComponentAttributeBag([...]);

**Comment by philtune-primevox** [comment]
Interestingly, here it is 2 hours later, and PHPStorm just resolved the argument. Just while I was editing the class the gray text with squiggle underline switched to full-color:

![image](https://github.com/laravel-idea/plugin/assets/130385353/d42d94cc-d138-45ae-b365-3344eb53fa09)

I had done a "Generate Helper Code" a few times when I submitted this ticket, and it indicated it was finished indexing, but otherwise didn't fix my warnings. I don't know if anyone has any insight into what happened that would be helpful if I run into it again (or for others Googling this). If not, shrug emoji and I can close this issue.

**Comment by cyppe** [comment]
I have similar issue. bit with Redis facade usage and Redis::pipeline method.  

Anyone know what to do?

<img width="937" alt="image" src="https://github.com/laravel-idea/plugin/assets/591720/eb28736a-84de-4cbb-a12a-bbdc04308012">

**Comment by cyppe** [comment]
In the generated helper files it does not mention the closure, if that's the issue ? Possible to override this in some config? As it's a bit annoying when you think there is something wrong with your code.

     * @see \Redis::pipeline
     * @method static bool|\Redis pipeline()

**Comment by adelf** [comment]
Yes.

There is `pipeline()` method in the `\Redis()` and `pipeline($callback)` method in `RedisManager`. There is a little conflict here.

**Comment by cyppe** [comment]
Allright, I see it now. Is it possible to resolve it?

**Comment by adelf** [comment]
Yes. Working on it.

**Comment by cyppe** [comment]
Wow, awesome!

**Comment by cyppe** [comment]
Impressive. 

Do you have some ETA for next release?

**Comment by adelf** [comment]
It's released. 8.0.4.

**Comment by cyppe** [comment]
Awesome. I can confirm it works.   It sure has benefits to pay for software :-) Happy customer.

<img width="675" alt="image" src="https://github.com/laravel-idea/plugin/assets/591720/aca70806-e0b1-46a6-b8b4-4060dfc179bc">
