### ISSUE TITLE
[Bug]: Generate Completion is missing from the tools tab and search everything (PHPStorm)

### ISSUE THREAD

**Issue by BroNils** [laravel-idea/plugin#836]
### Bug description

<details>
  <summary>Tools Tab</summary>

![image](https://github.com/laravel-idea/plugin/assets/19589820/9b0f91f2-539f-4974-a4be-9172c4249270)
</details>
<details>
  <summary>Search on everything</summary>

![image](https://github.com/laravel-idea/plugin/assets/19589820/d5eabbb9-f1c3-41c8-9da0-87b9eacd88ac)
</details>
<details>
  <summary>I have paid this plugin from long ago</summary>

![image](https://github.com/laravel-idea/plugin/assets/19589820/edf68891-51c0-433b-9d87-fa180c1c5857)
</details>

### Plugin version

7.3.0.232

### Operating system

Windows

### Steps to reproduce

dunno, just an usual daily use. then it is missing when im tryna to re-generate completion

**Comment by BroNils** [comment]
i've done relogin my account in phpstorm, but problem still occur

**Comment by adelf** [comment]
Hello. Code generation moved to the new menu about two years ago.

<img width="563" alt="Screenshot 2023-09-25 at 09 20 37" src="https://github.com/laravel-idea/plugin/assets/2818394/0e2cd750-14d7-4fd8-a352-b32a1f18ad0e">

**Comment by BroNils** [comment]
thanks for your reply. i know about that, and i've used it from new menu but now i dont find it anywhere. or did i messed up thing ? hidden accidentally ?
![image](https://github.com/laravel-idea/plugin/assets/19589820/33a72400-8808-4e65-a00e-8b39d28ab190)

**Comment by BroNils** [comment]
re-switching to new ui, still not find any of laravel tab
![image](https://github.com/laravel-idea/plugin/assets/19589820/87452347-0b8f-475a-a447-e9405dc4ba9d)

**Comment by adelf** [comment]
Could you check your settings? There should be something like that.

<img width="435" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/2edf749f-2acb-4c8f-9a4e-f3f54151e7d0">

If yes, you can restart PhpStorm. If not, you probably opened not a Laravel project.

**Comment by BroNils** [comment]
thanks, i figure it out. my compose have invalid format, lol
![image](https://github.com/laravel-idea/plugin/assets/19589820/c5954bdb-e546-4b46-9076-d21bea1165f0)
