### ISSUE TITLE
[Bug]: Error when generating help code, missing class.

### ISSUE THREAD

**Issue by robs007** [laravel-idea/plugin#837]
### Bug description

I can no longer generate helper code. I get an error stating it can't find "\Illuminate\Support\Collection class not found." This happens in all my Laravel applications. 
PHPstorm version 2023.2.2

### Plugin version

7.3.0.232

### Operating system

Windows

### Steps to reproduce

Run generate helper code from Laravel dropdown.

**Comment by adelf** [comment]
Please try to invalidate caches: main menu > File > Invalidate Caches...

**Comment by robs007** [comment]
Still get the error. Tried twice and restarted.
________________________________

**Comment by adelf** [comment]
Did you run `composer install`?

**Comment by robs007** [comment]
Yeah, multiple times. I mean it's correct, that class does not exist in that location, but it doesn't exist in any of my standard Laravel applications. Looking at the Laravel Illumante repo it's not there either
https://github.com/illuminate/support
[https://opengraph.githubassets.com/d2a8560917bd3d82fdfdd301b5f26d6294c3c3343bc7924b0c74f93c922adf7e/illuminate/support]<https://github.com/illuminate/support>
GitHub - illuminate/support: [READ ONLY] Subtree split of the Illuminate Support component (see laravel/framework)<https://github.com/illuminate/support>
[READ ONLY] Subtree split of the Illuminate Support component (see laravel/framework) - GitHub - illuminate/support: [READ ONLY] Subtree split of the Illuminate Support component (see laravel/frame...
github.com

[cid:f7c573f2-75f9-4e4a-8a4a-e7ab417acb0f]
________________________________

**Comment by adelf** [comment]
It's here - https://github.com/illuminate/collections and included in every Laravel setup. Laravel Idea always searches for some important Laravel classes since they are needed to generate the correct helper code.

Are you're projects - packages which only include illuminate/support?

**Comment by robs007** [comment]
No, they are standard laravel applications. I do have illumante\collections like the error is looking for.

[cid:f5813d1a-1616-490a-afd1-a5ceedd07f84]

But I don't have /support/collections

[cid:b59a5d65-881c-4363-9326-bd5de6ed7a5d]
[cid:941cc903-e25b-47eb-9fb9-8f946dc72ca5]
________________________________

**Comment by adelf** [comment]
Sorry, but I still don't get it. Do you have a "\Illuminate\Support\Collection" class in your projects?

**Comment by robs007** [comment]
Yes

[cid:f77b9905-7351-415c-9d12-734f91bff1a3]
________________________________

**Comment by robs007** [comment]
It must be something with those projects. I tried it on a clean laravel install and it worked fine, and on and older project and it worked fine. The problem projects may have been updated using shift. Maybe that broke something along the way.
________________________________

**Comment by adelf** [comment]
Laravel Idea asks PhpStorm to find this class.

If you click Shift-Shift and then search, do you see this class? Don't forget about "Include non-project items" checkbox.

<img width="791" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/c090342c-e74a-4ff6-a2d0-8caa031a3f58">

**Comment by robs007** [comment]
No, I don't see it. But I also don't see it in the one that it works on. Maybe I should delete the vendor directory and run composer again.
[cid:ec533361-06d0-490a-be26-5a675a810c8e]
________________________________

**Comment by adelf** [comment]
Laravel Idea can't work without these base Laravel classes, so PhpStorm should see them.
