### ISSUE TITLE
[Feature Request]: Volt - Avoid FQDN

### ISSUE THREAD

**Issue by robsontenorio** [laravel-idea/plugin#838]
### Feature Description

@adelf I am using Volt class based API. 

It would possible to **avoid** auto import FQDN classes on `<?php ... ?>` block?

**Auto complete works...**

<img width="632" alt="image" src="https://github.com/laravel-idea/plugin/assets/118955/1e7dbde6-f309-4e67-9491-8af047e79d49">

<hr />

**But, when hit enter it imports FQDN**

<img width="337" alt="image" src="https://github.com/laravel-idea/plugin/assets/118955/4989ba3b-51dd-479d-b3e8-70dab130cf6f">

<hr />

**Same happens on methods** 

<img width="453" alt="image" src="https://github.com/laravel-idea/plugin/assets/118955/ddd05fc2-4082-4d95-9d0a-9ab50020f4d4">

<hr />

**I would like to stand to this**

<img width="359" alt="image" src="https://github.com/laravel-idea/plugin/assets/118955/efd15fbc-b27d-40ae-8644-fa4a48bcf1be">

**Comment by robsontenorio** [comment]
For future reference, this works for me.

![image](https://github.com/laravel-idea/plugin/assets/118955/8028038a-353e-4ac5-aa76-a7f35c221778)

**Comment by adelf** [comment]
Wow. Thank you, Robson! I started to think, what can I do to help here... but PhpStorm already has a solution!

**Comment by adelf** [comment]
BTW, Function is also better to "prefer import".

**Comment by robsontenorio** [comment]
@adelf  ohh yes, for sure. I was focusing on class case.
