### ISSUE TITLE
[Bug]: On the day before renewal it says license expired.

### ISSUE THREAD

**Issue by michaelChicherin** [laravel-idea/plugin#839]
### Bug description

Hello

I've monthly subscription. My renewal date is tomorrow - 2023-09-28, but in settings in the plugin it says expired.
![image](https://github.com/laravel-idea/plugin/assets/56351279/d351de23-61ab-4bb1-b3b0-95fbc0de8263)
![image](https://github.com/laravel-idea/plugin/assets/56351279/55da5e4c-e001-4f3c-a00f-adfd26708278)

### Plugin version

7.3.0.232

### Operating system

Windows

**Comment by adelf** [comment]
Hi, Michael.

Please write to sales@jetbrains.com. They manage all licenses, including plugin ones.
