### ISSUE TITLE
psalm - Magic instance property App\Models\XXX::$id is not defined

### ISSUE THREAD

**Issue by adiletmaks** [laravel-idea/plugin#84]
there is reference to _idea_helper_models.php file, but psalm doesn't understand this

**Comment by laravel-idea** [comment]
Could you provide an example? I haven't use psalm.

**Comment by adiletmaks** [comment]
It is okey if I have doc block ``` * @property int $id``` in Model, but I removed all doc and generate _ide_helper_models file.

psalm references to my main model and searches property, but all properties defined in another class in ide_helper_models file.

https://psalm.dev/docs/running_psalm/issues/UndefinedMagicPropertyFetch/

**Comment by adelf** [comment]
I was thinking about the option to add some fields to the main class phpDocs... Seems it should fix this issue, but what about methods? Is there the same psalm issue for methods?
The main reason why I added everything to separate file is that I use some internal classes which should not appear in real code:
```php
/**
 * @method static _UserQueryBuilder whereId($value)
 */
```

You definitely don't want to have `_UserQueryBuilder` in your real code...

**Comment by adiletmaks** [comment]
I returned doc block for main models with command `php artisan ide-helper:generate` (by the way, can I do this with plugin ?)

**Comment by adelf** [comment]
`ide-helper:generate` just generates helper code for Laravel facades. How you generate phpDocs for models there?
I'm thinking about replacing this command, but it's not easy to guess the real implementations of facades sometimes, so I'm still not sure.

**Comment by adiletmaks** [comment]
sorry, I mean `php artisan ide-helper:models`
