### ISSUE TITLE
[Bug]: Not Compatible With PHPStorm 2023.2.2

### ISSUE THREAD

**Issue by XedinUnknown** [laravel-idea/plugin#842]
### Bug description

When installing as directed, I get the following error message, and no plugin is installed:

> Plugin 'Laravel Idea' (version '7.4.0.233') is not compatible with the current version of the IDE, because it requires build 233 or newer but the current build is PS-232.9921.55

![image](https://github.com/laravel-idea/plugin/assets/1428973/aeb1a663-bd84-4714-9a54-49f7b801da71)

I saw a similar issue #712. I'm sure I have the latest version of PHPStorm.

### Plugin version

7.4.0.233

### Operating system

Windows

### Steps to reproduce

1. Ensure PHPStorm 2023.2.2.
2. Download plugin from [here](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=406468).
3. Install as per instruction manual.
4. Observe symptom

**Comment by adelf** [comment]
Hello. 7.4.0.233 is for new 2023.3 EAP. For 2023.2, please use 7.4.0.232
version.

**Comment by XedinUnknown** [comment]
Not only does it work now, but also didn't have to download: it just installed into the IDE now. Thanks!
