### ISSUE TITLE
[Bug]: Hint and set wrong type

### ISSUE THREAD

**Issue by Taurinz359** [laravel-idea/plugin#843]
### Bug description

Need to return type ```UserFactory```. But, return type hint is ```\m```

Code in the method with wrong hint:
```
public function withRoles(...$roles)
    {
        return $this->afterCreating(fn(User $u) => $u->roles()->attach($roles));
    }
```
![image](https://github.com/laravel-idea/plugin/assets/80029674/3642c9b5-c1c4-4aed-8ea4-fe7444c628d0)

Code after accept hint:
```
   public function withRoles(...$roles): \m
    {
        return $this->afterCreating(fn(User $u) => $u->roles()->attach($roles));
    }
```

![image](https://github.com/laravel-idea/plugin/assets/80029674/6d8abcc9-4f60-4805-b141-cfe5bdb6b353)

### Plugin version

7.4.0.232

### Operating system

Linux

### Steps to reproduce

Accept hint

**Comment by adelf** [comment]
This is fixed by 7.4.1 version. Thank you.
