### ISSUE TITLE
[Bug]: model attributes are incorrectly expanded

### ISSUE THREAD

**Issue by adampatterson** [laravel-idea/plugin#844]
### Bug description

In a Model, typing `attribute` and then hitting tab expands incorrectly the live template.

https://d.pr/v/XsdQrF

### Plugin version

7.3.0.232

### Operating system

MacOS

### Steps to reproduce

In a model type `attribute` and then hit **tab**.

If you click on **attribute** the cursor is correctly positioned.
![image](https://github.com/laravel-idea/plugin/assets/31537/b61d4799-dc62-4efb-aad3-f91b17f990ff)

**Comment by adelf** [comment]
Hello, Adam.

Please update the plugin. This is fixed by the last update.

**Comment by adampatterson** [comment]
@adelf yup, thanks!
