### ISSUE TITLE
[Feature Request]: Make `lazy()` work same as `get()`

### ISSUE THREAD

**Issue by robsontenorio** [laravel-idea/plugin#845]
### Feature Description

I suppose `lazy()` should work as `get()`. So, all collection methods should work correctly.

![image](https://github.com/laravel-idea/plugin/assets/118955/2bfceda9-c9c3-4ebc-a804-5d35b9a91668)

![image](https://github.com/laravel-idea/plugin/assets/118955/d3173dac-ef51-496d-8a9e-1dd73e81ee0e)

**Comment by adelf** [comment]
Fixed in 7.4.2. Thanks.
