### ISSUE TITLE
[Feature Request]: Livewire - Add missing `wire:xxx` directives

### ISSUE THREAD

**Issue by robsontenorio** [laravel-idea/plugin#848]
### Feature Description

Not all `wire:xxxx` can be autocompleted.

- transition
- confirmation
- dirty
- stream

![image](https://github.com/laravel-idea/plugin/assets/118955/97898204-8322-4a6f-a450-1c98c8fec558)

**Comment by sohailahmad07** [comment]
hi sir also add the debounce modifier after live 

mean if i use `wire:modal.live` i don't get the completion fo `debounce` modifer

**Comment by adelf** [comment]
They are added in the 8.0. Thank you.
