### ISSUE TITLE
[Feature Request]: all observer methods

### ISSUE THREAD

**Issue by btortoise** [laravel-idea/plugin#854]
### Feature Description

Hi !

When we generate a new observer, it doesn't generate all available default laravel methods.

only this methods are generated : created, updated, deleting, deleted, restored, forceDeleted

But in laravel 10 the full list is : 
'retrieved', 'creating', 'created', 'updating', 'updated',  'saving', 'saved', 'restoring', 'restored', 'replicating',  'deleting', 'deleted', 'forceDeleting', 'forceDeleted'

It could be helpful if all methods are in the generated observer 
or
 maybe have a way to configure which method we would like in the generated observer.

**Comment by adelf** [comment]
https://twitter.com/laravel_idea/status/1729124719126024525

**Comment by ludwig-schubert-lelp** [comment]
Thanks !
nice work ;)

**Comment by adelf** [comment]
Available from 8.0.
