### ISSUE TITLE
[Feature Request]: Generate fillable fields improvement

### ISSUE THREAD

**Issue by DanielSpravtsev** [laravel-idea/plugin#856]
### Feature Description

Hey! 
Would be awesome to have in Laravel Idea settings the ability to specify an option to `generate fillable fields with new line separator`.

[Example image](https://gcdnb.pbrd.co/images/EsaldyKvf7UN.png?o=1)

**Comment by adelf** [comment]
Hi. I'm working on one feature which will fix this.

**Comment by adelf** [comment]
This new completion should help. https://twitter.com/laravel_idea/status/1719748406376063112 It's implemented in 8.0 version.

**Comment by DanielSpravtsev** [comment]
@adelf Yummy 😋
