### ISSUE TITLE
[Feature Request]: Inertia.js component autocomplete also in `resources/ts` (in addition to `resources/js`)

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-idea/plugin#857]
### Feature Description

I'm working on an app that uses Inertia and Vue. However, we use `resources/ts/Pages` as the folder for the pages (TypeScript vs JS).

Could you add the `resources/ts/Pages` folder to the auto-complete as well, in addition to `resources/js/Pages`?

Thanks!

**Comment by adelf** [comment]
You can setup it here.

<img width="638" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/3e2836d7-366c-4035-9d07-088447c6e256">

**Comment by ralphjsmit** [comment]
Amazing as always Adel, thanks!
