### ISSUE TITLE
[Request] component props autocomplete

### ISSUE THREAD

**Issue by Algeneralo** [laravel-idea/plugin#86]
When using @props with Laravel, it doesn't provide the autocomplete things in the directive.
For example:
in component file:
```
@props([
    "spaces"=>7
])
```
and when using that tag:
`<x-component :spaces="4"></x-component >`
it doesn't give you what props are listed there.
Thanks

**Comment by adelf** [comment]
Thanks for reporting this. I'll try to add it soon.

**Comment by adelf** [comment]
Implemented in 3.4 version.
