### ISSUE TITLE
[Bug]: No autocomplete in modals when using jetbrains gateway

### ISSUE THREAD

**Issue by haringsrob** [laravel-idea/plugin#863]
### Bug description

When using jetbrains gateway code generation etc works fine, however there is no autocomplete for things like model classes in modals:

<img width="372" alt="Screenshot 2023-11-02 at 10 27 57" src="https://github.com/laravel-idea/plugin/assets/866743/c6cf8456-f28d-402f-9116-e6b7ec041d89">

### Plugin version

7.4.3.233

### Operating system

Somewhere else (please specify in the description)

**Comment by komatom** [comment]
probably related #867

**Comment by haringsrob** [comment]
Added an issue in the jetbrains issue queue https://youtrack.jetbrains.com/issue/WI-75332/Laravel-Idea-modal-autocomplete-does-not-work

**Comment by adelf** [comment]
Looks like a Gateway bug. Closing this.
