### ISSUE TITLE
[Bug]: Table not found when $table is used in Model

### ISSUE THREAD

**Issue by mvdgeijn** [laravel-idea/plugin#865]
### Bug description

When generating IDE helper files (ctrl+shift+. in phpStorm Windows), I get 61 warnings of tables where the table is not found. I've searched the open issues, but the only open issue that could be related, states that is should be fixed?

I'm not sure if that's causing the problem, but it seems to be related to the model name or the table name. E.g.:

Model name: UserPost
Code in the Model UserPost class:

```php
class UserPost extends Model
{
    ...
    protected $table = 'user_post';
    ...
}
```

Table name in the database: user_post

Warning:

Table not found for APp\Models\UserPost (user_post)

FYI, total number of tables is 87.

### Plugin version

7.4.3.232

### Operating system

Windows

**Comment by komatom** [comment]
This actually happens for some models that doesn't have the $table inside class, and they are still not recongnized, even though we have the migration for it.

class Meta extends Model {}

migration table name is 'metas'

I have to specify that I am using WSL2 remote feature, Laravel Idea seems to have a lot of issues with that

**Comment by adelf** [comment]
Hi, @mvdgeijn. Are you using migrations or a database to fetch tables? You can check it in the main menu - Laravel - Helper Code Parameters. Please use the correct database if you don't have migrations for this table.

If you have migrations, could you please share the one with `user_post` table?

**Comment by mvdgeijn** [comment]
Thank you both for the support, but the problem is fixed by following adelfs directions. When selecting the right connection (was set to migration) the reported warnings were solved immediately. I wasn't aware of the Helper Code Parameters menu option.
