### ISSUE TITLE
[Bug]: Filament Relation Managers generated with static methods when Filament are not

### ISSUE THREAD

**Issue by albofish** [laravel-idea/plugin#866]
### Bug description

When generating a Filament Resource and selecting Relation Managers the `table` and `form` methods are declared static resulting in the following error;

```Cannot make non static method Filament\Resources\RelationManagers\RelationManager::form() static in class App\Filament\Resources\XXXXResource\RelationManagers\YYYYRelationManager```

### Plugin version

7.4.3.232

### Operating system

MacOS

**Comment by adelf** [comment]
Fixed in 8.0. Thank you.
