### ISSUE TITLE
[Bug]: "Root" module not showing in Code Generation with a Laravel project under a directory

### ISSUE THREAD

**Issue by martylamoureux** [laravel-idea/plugin#868]
### Bug description

A project have his Laravel code in a `src` directory.

When enabling modules with "Simple directory" mode, and "Allow app root module ..." checked, we should expect to have the "Root app module" in the Module selection list when using Code Generation, but we only see the defined modules.

### Plugin version

7.4.3.232

### Operating system

MacOS

### Steps to reproduce

- Create a directory
- Spawn a new Laravel project in the "src" project
- Open the root directory in PhpStorm
- Make sure the plugin "General" settings have `src` for the Laravel directory
- Setup the Module System in the plugin as "Simple directory modules", and leave `app/Domain` for the path, and check "Allow app root module in code generation dialogs"
- Create a module Test
- Create module OtherTest
- You should only have "Test" and "OtherTest" in the module selection, where "Root app module" is missing.

**Comment by jfeid** [comment]
Confirmed this bug, no Root module selection in code generation options even if checked on plugin settings.
plugin version: 8.1.2.233
PhpStorm version: 2023.3.4 #PS-233.14475.35
OS: Linux

**Comment by adelf** [comment]
Fixed. Sorry for the inconvenience. A new update will be released soon. In the next week, probably.

**Comment by adelf** [comment]
Fixed in 8.1.4. Thank you.
