### ISSUE TITLE
[Bug]: Eloquent accessors don't override DB column type

### ISSUE THREAD

**Issue by mortenscheel** [laravel-idea/plugin#870]
### Bug description

I've commented about this in another issue, but it's still a problem, and now I can narrow it down to something that should be simple to reproduce.

The issue: If an Eloquent model defines an accessor method _for an attribute from the database_, the return type of the accessor is ignored when helper code is generated.

Here's a simple example.
The model has 2 accessors (type and other) that both return an enum. The only difference is that `type` overrides a DB column (see the migration). I've added both to highlight the difference in the generated helper code.

### Model
```php
<?php

namespace App\Models;

use App\Type;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

class SampleModel extends Model
{
    public function type(): Attribute
    {
        return Attribute::get(fn() => Type::Default);
    }

    public function other(): Attribute
    {
        return Attribute::get(fn() => Type::Default);
    }
}
```
### Migration
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('sample_models', function (Blueprint $table) {
            $table->id();
            $table->integer('type');
            $table->timestamps();
        });
    }
};
```

### Generated helper code
```php
    /**
     * @property int $id
     * @property int $type
     * @property Carbon|null $created_at
     * @property Carbon|null $updated_at
     * @property-read Type $other attribute
     * @method static _IH_SampleModel_QB onWriteConnection()
     * @method _IH_SampleModel_QB newQuery()
     * @method static _IH_SampleModel_QB on(null|string $connection = null)
     * @method static _IH_SampleModel_QB query()
     * @method static _IH_SampleModel_QB with(array|string $relations)
     * @method _IH_SampleModel_QB newModelQuery()
     * @method false|int increment(string $column, float|int $amount = 1, array $extra = [])
     * @method false|int decrement(string $column, float|int $amount = 1, array $extra = [])
     * @method static _IH_SampleModel_C|SampleModel[] all()
     * @mixin _IH_SampleModel_QB
     */
    class SampleModel extends Model {}
```

### Plugin version

7.4.3.232

### Operating system

Windows

### Steps to reproduce

Define an [accessor method](https://laravel.com/docs/10.x/eloquent-mutators#defining-an-accessor) with the same name as a column from the database. 
The accessor should return a different type than the original attribute.
It doesn't matter if you use the new syntax for accessors, or the old one.
Generate the helper code.

**Comment by adelf** [comment]
Fixed in 8.0. Thank you.
