### ISSUE TITLE
[Feature Request]: Link to package on Github in composer.json

### ISSUE THREAD

**Issue by grafst** [laravel-idea/plugin#875]
### Feature Description

It would be very cool if I could click on the packagename in the composer.json and it opens the package page in the browser.
Very useful for quickly reading documentation, or looking up the most recent version and so on.

**Comment by adelf** [comment]
Hello. It's unrelated to Laravel, so you should ask the PhpStorm team about it. However, I don't see the way how PhpStorm can fetch these URL's. 
They can send you to the package page in the packagist.org only...

**Comment by grafst** [comment]
ah interesting. Well packagist page would also be good, right?
the composer.lock has the homepage urls though...
Ok, so this would be a standalone phpstorm plugin, maybe...
