### ISSUE TITLE
[Bug]: Laravel Idea is not launching?

### ISSUE THREAD

**Issue by grafst** [laravel-idea/plugin#876]
### Bug description

I have a project with the following composer.json.
However Laravel Idea is not starting (No "Laravel" Menu item)
What am I doing wrong?

```
{
  "name": "chriskonnertz/deeply",
  "description": "DeepLy is a PHP client for the DeepL.com translation API",
  "keywords": ["deepl", "deeply", "translation", "translate", "language", "neural", "ai", "api", "client", "library"],
  "license": "MIT",
  "authors": [
    {
      "name": "Chris Konnertz"
    }
  ],
  "require": {
    "php": ">=8.0",
    "ext-curl": "*",
    "": ""
  },
  "require-dev": {
    "phpunit/phpunit": "9.*"
  },
  "autoload": {
    "psr-0": {
      "ChrisKonnertz\\DeepLy": "src/"
    }
  },
  "extra": {
    "laravel": {
      "providers": [
        "ChrisKonnertz\\DeepLy\\Integrations\\Laravel\\DeepLyServiceProvider"
      ],
      "aliases": {
        "DeepLy": "ChrisKonnertz\\DeepLy\\Integrations\\Laravel\\DeepLyFacade"
      }
    }
  },
  "minimum-stability": "dev"
}
```

### Plugin version

7.4.3.232

### Operating system

MacOS

### Steps to reproduce

1. `git clone https://github.com/chriskonnertz/DeepLy.git`
2. cd DeepLy
3. phpstorm .
4. cmd+shift+;

**Comment by adelf** [comment]
Hello. Laravel Idea doesn't see Laravel-specific libraries in the composer.json and doesn't work to save your resources.
You can turn it on in the Preferences | Languages & Frameworks | Laravel Idea | General and opt out of the "Fetch Laravel automatically" checkbox.

**Comment by grafst** [comment]
thank you very much.
What would count as laravel specific?

**Comment by adelf** [comment]
"laravel/framework"
"laravel/lumen-framework"
"illuminate/support"
"laravel-zero/framework"
