### ISSUE TITLE
[Feature Request]: Method for Redis Facade

### ISSUE THREAD

**Issue by khannedy** [laravel-idea/plugin#879]
### Feature Description

Method for Redis Facade

![CleanShot 2023-12-05 at 18 36 42](https://github.com/laravel-idea/plugin/assets/70091/442ee595-397d-401c-ad4b-614b04f2e885)

**Comment by adelf** [comment]
They should work in 8.0 version. Thank you.

**Comment by adelf** [comment]
Oops, sorry. It isn't released yet) I'll release a version with it soon.

**Comment by adelf** [comment]
8.0.2 released. Thank you.
