### ISSUE TITLE
[Bug]: Action id of generate helper code keeps changing

### ISSUE THREAD

**Issue by megawubs** [laravel-idea/plugin#884]
### Bug description

I use ideavim and have remapped the generate helper code command in my ideavimrc. But since the last few updates, I have to change the action after the update because the action id has changed. 

Is it possible to keep the action id the same and not change it on package updates?

See these commits in my dotfiles:
https://github.com/megawubs/dotfiles/commit/fd5e38152d0a4cf35337e30366e1d88344ae247f#diff-20d18c0ef22609f7843f0da3516a4c422278835eea84f5bfeb69f46802d45b1dR243

https://github.com/megawubs/dotfiles/commit/18002f5b567ad95f624ebf8b4fb96d1a9e42b3ff#diff-20d18c0ef22609f7843f0da3516a4c422278835eea84f5bfeb69f46802d45b1dR243

### Plugin version

8.0.1.233

### Operating system

MacOS

### Steps to reproduce

No steps to reproduce, just using the plugin the last few months

**Comment by adelf** [comment]
Hello, Bram. Sorry for this. They will be stable starting from the next update.

**Comment by adelf** [comment]
It should be stable starting from 8.0.2, which was released today. Thank you.
