### ISSUE TITLE
[Feature Request]: Add support for new `@use` Blade directive

### ISSUE THREAD

**Issue by rico-vz** [laravel-idea/plugin#885]
### Feature Description

As of Laravel [v10.35.0](https://github.com/laravel/framework/releases/tag/v10.35.0) there now is a new Blade directive. Laravel Idea support for this directive would be great to see!

You can find more detailed information about this directive in [the pull request](https://github.com/laravel/framework/pull/49179).

Example (from the pull request)
```blade
{{-- Before --}}
@php
use \App\Enums\WidgetStatusEnum as Status;
@endphp

{{-- After --}}
@use('App\Enums\WidgetStatusEnum', 'Status')

@use('App\Models\Bar')

{{ Status::Foo }}

{{ Bar::first() }}
```

**Comment by adelf** [comment]
The current architecture of the Blade plugin won't allow us to implement this flawlessly. I created an issue in the JetBrains tracker. https://youtrack.jetbrains.com/issue/WI-75492/new-Blade-use-directive
