### ISSUE TITLE
[Bug]: Livewire v2 works ,but Idea does not recognize <livewire: > and wire:XXX tags

### ISSUE THREAD

**Issue by SpyridonLaz** [laravel-idea/plugin#886]
### Bug description

phpstorm : 2023.3.1
livewire: v2

(livewire disabled?)
![image](https://github.com/laravel-idea/plugin/assets/17540895/53cd9a6c-1f9e-4831-a3b4-1475f3ba74e5)

the view must be detected by laravel Idea but its not
![image](https://github.com/laravel-idea/plugin/assets/17540895/a82f2236-cedc-498a-99cd-fad56f58a655)

sometimes this shows an error "namespace wire is not bound"
![image](https://github.com/laravel-idea/plugin/assets/17540895/d4a27672-f6c2-4f2b-8d15-4f5cbe44f5e7)

### Plugin version

8.0.1.233

### Operating system

Windows

**Comment by adelf** [comment]
> (livewire disabled?)

Yes. For some reason, the plugin doesn't see Livewire package installed.

However, the 'livewire.***' view should work if there is a `resources/views/livewire/***.blade.php` file exist.

**Comment by lettuceDestroyer** [comment]
Is there any update? Because I seem to be facing the same issue. :/

**Comment by adampatterson** [comment]
Unsure if this is the exact Issue that I'm having but after updating a project to Laravel 11 / Livewire 3 I can no longer click through to the component or view on a Livewire Tag.

```
@livewire('lessons.lesson-modal')
```
or
```
<livewire:swimmer.available-lesson-finder/>
```

The Tag components will highlight as if it would clock through, but the blade directives don't do anything at all.

**Comment by adampatterson** [comment]
This feels like a fairly core and critical issue. I'd love an update on this.

**Comment by adelf** [comment]
This should be fixed in the last update. Could you check?
