### ISSUE TITLE
[Bug]: NameSpace autocompletion (use) is broken

### ISSUE THREAD

**Issue by logic-b-o-m-b** [laravel-idea/plugin#889]
### Bug description

While importing name space (eg: when I want to import  Illuminate\Http\Request), just after typing "use Re" IDE shows popup with suggestions. First one comes from  Laravel Idea and shows correct class name and correct namespace. After selecting it instead of having 

```php
use Illuminate\Http\Request;
```

I'm getting

```php
use Request;
```

This is super annoying. 

### Plugin version

recent, recent IDE and php 8.3

### Operating system

MacOS

**Comment by adelf** [comment]
Thank you for the report. It's not supposed to be completed in the `use` statement. I'll remove this completion.

**Comment by adelf** [comment]
Fixed in 8.0.2. Thank you!

**Comment by logic-b-o-m-b** [comment]
Thank you @adelf!
