### ISSUE TITLE
[Bug]: Duplicated suggestions.

### ISSUE THREAD

**Issue by logic-b-o-m-b** [laravel-idea/plugin#890]
### Bug description

Please have a look at the screenshot:
<img width="610" alt="Screenshot 2023-12-16 at 22 53 01" src="https://github.com/laravel-idea/plugin/assets/55141760/cbd5dad9-9593-4241-8382-3376dda3b327">

Is there any config file I can clear or the way I can fix it myself without waiting for new release?

### Plugin version

8.0.1.233

### Operating system

MacOS

**Comment by adelf** [comment]
It's a result of Laravel Idea's helper code. The `$query` variable here has many classes, each with a `toArray()` method. Sorry for the inconvenience, but we can't fix it for now.
