### ISSUE TITLE
[Bug]: Laravel accessors and mutators no longer working  as expected

### ISSUE THREAD

**Issue by Abdelraman** [laravel-idea/plugin#891]
### Bug description

Laravel accessors and mutators no longer working as previous (no autocomplete feature as the previous versions) 

### Plugin version

8.0.1.233

### Operating system

Windows

### Steps to reproduce

create a normal model

add a mutator or accessor

```
public function getImagePathAttribute() {
    return "....."
}
```

by clicking on ctrl + shift + . for helper code generator 

ide can not detect the accessor/mutator it deals with it as a function

BTW I tried to switch on and off the use new eloquent attributes instead of accessor and mutator but the same result 
happens.

**Comment by Abdelraman** [comment]
@adelf it seems to be working when specifying the return type, and no longer working with the new eloquent way of creating attributes, very annoying specially with older projects that doesn't  have return type for accessors and mutators

**Comment by adelf** [comment]
I'll fix. Thanks.

**Comment by Abdelraman** [comment]
Thanks @adelf for your great plugin, can not imagine developing laravel apps without it.

**Comment by adelf** [comment]
I've checked. Helper code generates correctly. The "image_path" field was added in the model class during it...

**Comment by Abdelraman** [comment]
![image](https://github.com/laravel-idea/plugin/assets/4821833/edb91af3-b975-4f49-8ed5-3cda8a230608)
![image](https://github.com/laravel-idea/plugin/assets/4821833/a9ec6a09-789c-4c03-9ec8-2b24ed91236a)
![image](https://github.com/laravel-idea/plugin/assets/4821833/71ce0df0-9e93-48a2-824e-e70486646a82)

kindly check the attached screen shots
it seems to be working if you return a string e.g.

return $varName . ' ' . $varName . ' ' . $varName;

other than that it deals with it as a normal function

**Comment by adelf** [comment]
Reproduced. Thanks!

**Comment by Abdelraman** [comment]
@adelf how long will it take for the next release ?
 Thanks a lot for your efforts.

**Comment by adelf** [comment]
Next week, probably.

**Comment by Abdelraman** [comment]
@adelf  sorry for interruption, any updates regarding the next release. Thanks

**Comment by adelf** [comment]
It's available already.
