### ISSUE TITLE
[Bug]: translation preview and goto lang not working anymore with laravel modules

### ISSUE THREAD

**Issue by n1crack** [laravel-idea/plugin#894]
### Bug description

after 8.x version, The lang preview and goto lang features not working anymore. 

It stopped working after latest update. 

### Plugin version

8+

### Operating system

MacOS

### Steps to reproduce

using:  nWidart/laravel-modules with latest laravel .

**Comment by adelf** [comment]
Could you share your code from one not working module: Service provider and lang folder?

**Comment by n1crack** [comment]
It is working as expected in the fresh install. I don't know what's changed. I'll try to figure it out. Thanks anyway.

**Comment by n1crack** [comment]
I have custom translation system which is working (and preview was working as well),

When I add this line, there is no problem. It shows the preview as expected.

```php
$this->loadTranslationsFrom(module_path('User', 'lang'), 'user');
```

But I'm looping all modules with: 

```php
  foreach (\Module::allEnabled() as $module) {
      $this->loadTranslationsFrom(module_path($module->getName(), 'lang'), $module->get('alias'));
  }
```

and the code is working but the preview is not anymore.

It will be a quite challenge for me, I have dozens of modules and the php trait classes not working as well. I don't want to add the same code in every module..
