### ISSUE TITLE
[Bug]: Creating Migration: Unable to find resource Laravel Ideal Header

### ISSUE THREAD

**Issue by tanthammar** [laravel-idea/plugin#895]
### Bug description

I got an error when creating a migration file. 
The file was created even though the error was displayed.

### Plugin version

8.0.1.233

### Operating system

MacOS

### Steps to reproduce

- cmd + shift + comma. 
- Selected "Create database Migration"
- name: test_table
- migration type: create_table
- table name: blank
- Anonymous: true
- Omit down: true

### Relevant log output

```shell
Velocity error:
Error parsing file template: Unable to find resource 'Laravel Ideal Header.php'
```

**Comment by adelf** [comment]
Hello. Sometimes, it happens with templates in PhpStorm. Please go to the Settings > Editor > File and Code Templates. Find this template in the "Includes" tab. After that, it should be ok.

**Comment by tanthammar** [comment]
Hi @adelf 
I can see it in the list on the Includes tab.
Should I do something with it?, I mean it is already there, in the list...

**Comment by adelf** [comment]
usually, after that PhpStorm finds it well, migrations creating should work.

**Comment by tanthammar** [comment]
It didn't help. Error is still there :)

**Comment by adelf** [comment]
Hmm. Will PhpStorm restart help?

**Comment by tanthammar** [comment]
Yes it did :) 👍  selecting the file in settings again + another restart did the trick.
