### ISSUE TITLE
[Bug]: Creating a Filament Resource doesn't add row and bulk actions

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-idea/plugin#898]
### Bug description

When creating a filament resource, it doesn't include row actions and bulk actions by default on the `table` method.

Basically the following code for the table defition.

```php
->filters([
            //
        ])->actions([
            Tables\Actions\EditAction::make(),
        ])->bulkActions([
            Tables\Actions\BulkActionGroup::make([
                Tables\Actions\DeleteBulkAction::make(),
            ]),
        ]);
```

### Plugin version

8.0.2.233

### Operating system

MacOS

### Steps to reproduce

Create a Filament Resource using Laravel Idea Plugin on PHP Storm

**Comment by adelf** [comment]
They are added in the 8.0.3 version. Thanks.
