### ISSUE TITLE
[Bug]: Wrong default table name for model 'Lens'

### ISSUE THREAD

**Issue by sdapkus** [laravel-idea/plugin#899]
### Bug description

When I'm creating new model with name 'Lens' plugin suggest that table name should be 'lens'. But 'lens' plural form is 'lenses'

Laravel under the hood uses `Str::snake(Str::pluralStudly(class_basename($this)))` to get table name from model name, in this example it for 'Lens' it returns 'lenses' which is what I expect. 
Problem appears also when I delete `protected $table = 'lenses';` from model, which is not required since Laravel generates good name, Laravel Idea does not understand what table I will be using, and auto suggests does not work.

### Plugin version

8.0.2.233

### Operating system

MacOS

### Steps to reproduce

Open UI for creating new model.
Enter model name 'Lens'
Check suggested table name.

**Comment by MuhammedAlkhudiry** [comment]
@adelf same issue with "food". Laravel Idea will look for "foods" table, however, Laravel when
```
php artisan make:model Food -m
```
will create `food` table

**Comment by adelf** [comment]
Fixed for all words in the last 8.0.3 update. Thank you for reporting.
