### ISSUE TITLE
[Feature Request]: Supporting Repository Pattern

### ISSUE THREAD

**Issue by beshoo** [laravel-idea/plugin#900]
### Feature Description

I hope we can see such support or adaptation for rebo:
https://github.com/mwakalingajohn/laravel-easy-repository

Since PhpStorm does not navigate to the repository file when clicking on controller methods.

**Comment by adelf** [comment]
> Since PhpStorm does not navigate to the repository file when clicking on controller methods.

Hello. What do you mean? How should it navigate?

**Comment by beshoo** [comment]
If I click on the controller method,
**Http/Controllers/CharactourController.php**

It takes me to the RepositoryInterface 
**Repositories/Interfaces/CharactourRepositoryInterface.php**
Not 
**Repositories/Eloquent/CharactourRepository.php**

**Comment by adelf** [comment]
You can click "Go To Implementations"(Cmd-Option-B) in the `CharactourRepositoryInterface` class name and go right to the `CharactourRepository` class. 

If you don't have other implementations of this interface, why don't you use the class instead?

**Comment by beshoo** [comment]
> You can click "Go To Implementations"(Cmd-Option-B) in the `CharactourRepositoryInterface` class name and go right to the `CharactourRepository` class.
> 
> If you don't have other implementations of this interface, why don't you use the class instead?

TRUE!!!!!
Thanks
-------------------
What about supporting the creating of Repository Pattern Files when we create a model?

**Comment by adelf** [comment]
For a 6-star repo that has not been updated for more than two years? Sorry, no.
But I'll add support for it by ide.json files, and this package can add this code generation, using its own stub files.

**Comment by beshoo** [comment]
Can you add support for the Repository Pattern similar to what laravel-easy-repository Rebo does ? So when we create a model, we can check a box to create repository files.

**Comment by adelf** [comment]
It will be possible soon by adding a special ide.json file to the package.

**Comment by beshoo** [comment]
I hope Soon, I can remove https://github.com/mwakalingajohn/laravel-easy-repository since there has been no update for a long time. I will use your plugin to create repository files instead.

**Comment by adelf** [comment]
You can do it.

https://laravel-idea.com/docs/custom_generations

**Comment by beshoo** [comment]
> You can do it.

I have watched the video and found it to be somewhat complicated. 

Can you please provide me with step-by-step instructions on how to create a module with Repository Pattern and its interface since no template is available for it? 

If you add this function to the project as an option, users can create a new model with a new option to create the Rebo and interface. 
You may create 2 folders in the App directory, Repository and Interface
Both can then be linked to the app service provider.
This will be GREAT

**Comment by beshoo** [comment]
@adelf :) any advice please

**Comment by beshoo** [comment]
Th Problem, how can I add this  the generated controller 

**app/Providers/AppServiceProvider.php**
```
    public function register()
    {
        $this->app->bind({modelName}RepositoryInterface::class, {modelName}Repository::class);
    }
```

**app/Http/Controllers/{modelName}Controller.php**
```
use App\Repositories\Interfaces\{repositoryName}Interface;

    public $repository;
    public function __construct({modelName}RepositoryInterface ${modelName}Repository)
    {
        $this->repository = ${modelName}Repository;
    }

```

**app/Repositories/Eloquent/{modelName}Repository.php**
```
<?php

namespace App\Repositories\Eloquent;

use App\Models\{modelName};
use App\Repositories\Interfaces\{modelName}RepositoryInterface;
use Illuminate\Http\Request;

class {modelName}Repository implements {modelName}RepositoryInterface
{
    protected $model = {modelName}::class;

    public function all(Request $request)
    {
    }
    
}
```
**app/Repositories/Interfaces/{modelName}RepositoryInterface.php**

```
<?php

namespace App\Repositories\Interfaces;

use Illuminate\Http\Request;

interface {modelName}RepositoryInterface
{
    public function all(Request $request);
}

```
===========================
This is the structure I would like to have!
```
app/
    Repositories/
        Eloquent/
            UserRepository.php
        Interfaces/
            UserRepositoryInterface.php
```

So when I create a new model, I can make it to generate this scaffold!
@adelf

**Comment by adelf** [comment]
I won't add this to Laravel Idea since it's very opinionated and non-standard. But I'm going to add a possibility to implement this with https://laravel-idea.com/docs/custom_generations and even add it to the Model creation dialog.

I mean by ide.json generations. Not with custom generations.

**Comment by beshoo** [comment]
I’m really grateful for your support towards this method. It means a lot!

I’m a bit puzzled about what you meant by “by ide.json generations. Not with custom generations.”. Could you please clarify? I’m just looking for a simple checkbox in the model dialog that would allow us to generate a Repository scaffold.

Also, I’d love to share some thoughts on the comment about being “very opinionated and non-standard”. I truly value your viewpoint and I’m always eager to explore other beneficial approaches.

From my perspective, keeping a clean Controller is crucial, and the Repository pattern can be a great help in this regard. It seems to me that the Repository pattern has gained wide acceptance as a standard practice in contemporary software development.

This pattern offers an abstraction layer between the data storage layer and the application logic, which can greatly enhance code maintainability, flexibility, and reusability.

What do you think?

**Comment by beshoo** [comment]
@adelf

> I won't add this to Laravel Idea since it's very opinionated and non-standard. But I'm going to add a possibility to implement this with https://laravel-idea.com/docs/custom_generations and even add it to the Model creation dialog.
> 
> I mean by ide.json generations. Not with custom generations.

Thank you for this, but I like to ask if this has been supported in the 8.1.0.233!
Regards

**Comment by beshoo** [comment]
@adelf !

**Comment by adelf** [comment]
[repository.zip](https://github.com/laravel-idea/plugin/files/14329146/repository.zip)

This is an example of something you want. ide.json file with stub files.

**Comment by beshoo** [comment]
> [repository.zip](https://github.com/laravel-idea/plugin/files/14329146/repository.zip)
> 
> This is an example of something you want. ide.json file with stub files.


Wow, I just realized what you meant by ide.json and learned about https://laravel-idea.com/docs/ide_json/completion. 
You take PHPStorm to the next next next level!

Question , how can we make this global on PHPstrom so I don't have to copy ide.json each time!
