### ISSUE TITLE
[Feature Request]: Alpine js support

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-idea/plugin#901]
### Feature Description

Hi Adel! 

as usual, thanks for your awesome work :heart: 

just a feature request that I'm sure a lot of people would love: Alpinejs support

it would be awesome to have javascript highlighting and autocompletion in `x-data` fields:

![image](https://github.com/laravel-idea/plugin/assets/8792274/eb9751f5-0c01-41d0-9c98-16e5e541936d)

**Comment by adelf** [comment]
Hi, Fabio.

What about this plugin? https://plugins.jetbrains.com/plugin/15251-alpine-js-support

**Comment by fabio-ivona** [comment]
Will give it a try, thanks @adelf !
