### ISSUE TITLE
[Feature Request]: Dataset input for staticStrings (ide.json)

### ISSUE THREAD

**Issue by emmadesilva** [laravel-idea/plugin#902]
### Feature Description

The static strings completion is really helpful, but if you have a lot of string options the file can get quite long. I think it'd be really neat if the `staticStrings` option supported loading JSON datasets. 

```json
// ide.json
"complete": "staticStrings",
"options": {
    "dataset": "data/completions.json"
},
```

```json
// data/completions.json
["longitude", "latitude"]
```

This would also be helpful in case the dataset is dynamically generated, for example a list of SVG icons.

**Comment by adelf** [comment]
Implemented in the last 8.0.3 update. Please, use the "dataFile" property. Thanks.
