### ISSUE TITLE
[Bug]: Implicit Validations Not In Completions

### ISSUE THREAD

**Issue by mendelsimon** [laravel-idea/plugin#903]
### Bug description

In the `boot()` method of my `AppServiceProvider.php`, adding a regular validation using `Validator::extend('new_validation', ...` causes the "new_validation" to be suggested in the completions for validations. However, adding an implicit rule such as `Validator::extendImplicit('new_validation', ...` does NOT case the "new_validation" to be suggested. There should not be a difference here, and the new rule should be suggested regardless of whether it is implicit.

### Plugin version

8.0.2.233

### Operating system

Windows

### Steps to reproduce

Add a new implicit validation to the `boot()` method in `AppServiceProvider.php` (e.g. `Validator::extendImplicit('new_validation', ...`), then bring up the validation completions and note the newly defined validation missing.

**Comment by adelf** [comment]
Fixed in the 8.0.3 update. Thank you.
