### ISSUE TITLE
[Feature Request]: Custom Faker providers does not have autocomplete

### ISSUE THREAD

**Issue by amshehzad** [laravel-idea/plugin#904]
### Feature Description

I've registered a faker provider but that does not  provide autocomplete on faker object.

In FakerServiceProvider:
```
class FakerServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(Generator::class, function () {
            $faker = Factory::create();
            $faker->addProvider(new Fakecar($faker));
            $faker->addProvider(new DatetimeFaker($faker));
            return $faker;
        });
    }
}
```
inside factory defination:
![image](https://github.com/laravel-idea/plugin/assets/15146578/174e1d92-4cf5-4822-bad0-c256bb4cd535)

I've tried regenerating the helper code but that didn't worked

**Comment by adelf** [comment]
Laravel Idea doesn't support faker providers. Yet)

**Comment by amshehzad** [comment]
Ah I see, would love to see that in there ...  Is that something planned for the roadmap in the near future?

**Comment by adelf** [comment]
It's implemented. 1 minute ago)

**Comment by amshehzad** [comment]
Awesome! that's super fast! thanks man

**Comment by adelf** [comment]
It hasn't been released yet.

**Comment by adelf** [comment]
Please check the 8.0.3 version. It should work there.

**Comment by amshehzad** [comment]
@adelf I tried but it still doesn't recognize. here is what I did:
- updated the plugin
- restarted ide
- regenrated helper code
but still no luck

**Comment by adelf** [comment]
Could you share which package you use? Or the code of the provider and how you add it. 

Also, please make sure in the main menu > Laravel > Helper Code Parameters... that "Generate Macro calls helper code" is turned on.

**Comment by amshehzad** [comment]
Sure,
in FakerServiceProvider:
```
public function register(): void
    {
        $this->app->singleton(Generator::class, function () {
            $faker = Factory::create();
            $faker->addProvider(new Fakecar($faker));
            $faker->addProvider(new DatetimeFaker($faker));
            return $faker;
        });
    }
```

inside: `class DatetimeFaker extends \Faker\Provider\Base` :

```
    public function dateTimeThisHour(): Carbon
    {
        return now()->startOfHour()->addMinutes($this->generator->numberBetween(0, 59));
    }
```

then in my factory: 
```
'created_at' => $this->faker->dateTimeThisHour(),
```

and my helper code params looks like this:
![image](https://github.com/laravel-idea/plugin/assets/15146578/8ab2e535-13d9-49af-a01b-40728f670c77)

**Comment by adelf** [comment]
Strange. Work for me. What plugin version do you use?

<img width="507" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/48ef7649-6729-423b-b06c-2b4e25693b0f">

**Comment by amshehzad** [comment]
i'm using 8.0.3.233 

![image](https://github.com/laravel-idea/plugin/assets/15146578/f03086c3-c8b4-484c-b0ce-dfac761a13f3)

**Comment by adelf** [comment]
Could you show your `vendor/_laravel_idea/_ide_helper_macro.php` file?

**Comment by amshehzad** [comment]
[_ide_helper_macro.zip](https://github.com/laravel-idea/plugin/files/13960423/_ide_helper_macro.zip)

sure, here it is

**Comment by adelf** [comment]
Weird! The last try: please, main menu > File> Invalidate Caches... and then Generate Helper Code again.

**Comment by amshehzad** [comment]
Gave it a try, but no luck unfortunatley.. I invalided caches without checking any options just to be clear
![image](https://github.com/laravel-idea/plugin/assets/15146578/6bc693ed-b00a-47ed-bb02-986a01a492b8)

**Comment by adelf** [comment]
Honestly, I don't know what to do. Let's try to wait for anyone who has the same issue.

**Comment by amshehzad** [comment]
Hello @adelf I don't know when or how, but I just realized that it's now working! thank you

**Comment by adelf** [comment]
Nice)
