### ISSUE TITLE
[Help]: Completion config in ide.json

### ISSUE THREAD

**Issue by amshehzad** [laravel-idea/plugin#907]
I just get started with the the ide.json and just playing around and have few questions:

1. one I add a new completion config or make change, is there a way to know when the settings have been saved and are now in effect? currently when I save a new setting I don't see a way to know if my setting has been not saved yet or there is some issue in it. I just have to wait for few minutes and then try to trigger auto complete to see if that works or not
2. Is there any condition for a Trait?
3. can we provide multiple method names in "methodNames" just like classFqn, if yes that currently does not work for me, it only work for the first method ... wait I just tried while writing this and it works, again I tried multiple times after saving the config but that didn't worked and I had no idea if that is not supported or the settings have not take effect yet .. I tried regenrating the helper code but that didn't worked
4. Also, I created a completion for a User model method, and it worked well but if I create a User from a factory, the autocomplete does not work for the object, is that intended? if yes, is there a way to add autocomplete for that?

**Comment by adelf** [comment]
1. If your ide.json is located in the vendor folder, the saving file won't help. But you can call Cmd-Shift-, or main menu > Laravel > Code generation, and then choose "Update ide.json files" there.
2. What trait do you mean? Could you share your case?
3. Yes, it works.
4. Could you show the code please?

**Comment by amshehzad** [comment]
1. My ide.json is located in the root folder, once I save changes, It take effects after few minutes and I can't see when the changes have taken effect, e.g if I write some completion, I'll have to check back if the auto-complete work after few minutes.
2. Let say I have a method in a Trait, and I want to provide auto-complete for a parameter, Can I then add a condition for the Trait? write now I'm adding all classes that uses that trait in the condition
4. here is the code:

![image](https://github.com/laravel-idea/plugin/assets/15146578/b7190792-c0eb-49fc-8938-f40215882214)

```
    $user = new User();
    $user->getPreference(''); // auto-complete works here
    
    $user = User::factory()->create();
    $user->getPreference('');  // auto-complete doesn't work here
    
    $role = $user->primaryRole;
    $role->getPreference(''); // auto-complete doesn't work here
    
    $role = new Role();
    $role->getPreference(''); // auto-complete works here
```

If I create the object of User or Role class directly, the auto complete works fine on `getPreference` method but if I create them by factory or get them from relationship, auto-complete doesn't work

**Comment by adelf** [comment]
You can try 

```
"classFqn": [
    "\\YourTraitFqn"
]
```
