### ISSUE TITLE
[Bug]: Autocomplete does not work in Pest for $this

### ISSUE THREAD

**Issue by amshehzad** [laravel-idea/plugin#909]
### Bug description

This is my test and I don't get autocomplete on `$this->user`
describe('get preference', function () {
    beforeEach(function(){
        $this->user = User::factory()->create();
    });

    it('will throw error if the given preference is not defined in constants', function () {
        $this->user->getPreference('some_random_name');
    })->throws(\Exception::class, 'Preference some_random_name not found');

});

### Plugin version

8.0.2.233

### Operating system

Windows

**Comment by amshehzad** [comment]
Just realized that it works if I set it on top level but does not work for describe block

**Comment by adelf** [comment]
It is the Pest plugin issue. JetBrains supports it, so you can try to create an issue here: https://youtrack.jetbrains.com/issues
