### ISSUE TITLE
[Request] Report correct return Model based on Relationship

### ISSUE THREAD

**Issue by claudiodekker** [laravel-idea/plugin#91]
It's a bit difficult to describe, but I think the picture below should say sufficient.

![Screenshot 2020-07-24 at 19 51 02](https://user-images.githubusercontent.com/1752195/88421591-1f095200-cde9-11ea-9ed5-d126834c9b0c.png)

Basically, while `Profile` is valid, due to Laravel's `firstOrFail` stating that it returns a `Model`, it can theoretically also be a `User` and therefore PHPStorm marks it as an error. Of course, this code works fine & reliably during runtime.

I think this might be a great opportunity for this plugin to enrich our experience :)

**Comment by adelf** [comment]
Hi, Claudio. Have you tried "Generate Eloquent Helper Code" generation in "Laravel Idea Code generation" menu(main menu > Code)?

**Comment by claudiodekker** [comment]
@adelf Hi, apologies for the slow reply.

Yes, I have. This was one of the first things that I tried.
In addition, I also did a "Reload from Disk" on the entire project, to ensure PHPStorm was indexing everything correctly.

**Comment by adelf** [comment]
No apologies for slow replies on the weekend! :)

Just checked it. This happens only inside the class. As you see, everything is ok for outside function. 

![image](https://user-images.githubusercontent.com/2818394/88527574-222d5980-d006-11ea-90a2-0ec49f3fa088.png)

It's a little bug of PhpStorm which tries to find only current class methods. Seems, it was made during performance reasons. I can create an issue in JetBrains youtrack.

**Comment by claudiodekker** [comment]
Alright, I'll close this for now then. Thanks!

**Comment by adelf** [comment]
Done. https://youtrack.jetbrains.com/issue/WI-54460
