### ISSUE TITLE
[Bug]: Translations autocomplete/navigation not working for modules

### ISSUE THREAD

**Issue by MirazMac** [laravel-idea/plugin#910]
### Bug description

I changed absolutely nothing and all of a sudden, translations autocomplete stopped working for modules. Both in blade views and controllers.

![image](https://github.com/laravel-idea/plugin/assets/13865787/575c4e7e-4223-4b50-a82b-f2d8cc186dca)

To be specific, I'm **nWidart/laravel-modules** package. Everything was working a day before. Didn't change anything or update anything at all. I tried doing IDE repair as described here: https://www.jetbrains.com/help/phpstorm/repair-ide.html . But no luck.

However, autocomplete and navigation for the default translations i.e without any namespace works perfectly fine.
![image](https://github.com/laravel-idea/plugin/assets/13865787/0f3b6988-f86a-417e-96fe-e4a87c898906)

### Plugin version

8.0.2.233

### Operating system

Windows

### Steps to reproduce

I don't really know. As it started happening out of nowhere.

**Comment by adelf** [comment]
Could you show the ServiceProvider class of the module? Starting from the 8 version, Laravel Idea analyzes them to find folders and namespaces.

**Comment by MirazMac** [comment]
This is the method that loads the translations per module.

```php
    public function registerTranslations(): void
    {
        $langPath = lang_path('modules/' . $this->moduleNameLower);

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
            $this->loadJsonTranslationsFrom($langPath);
        } else {
            $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
            $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));
        }
    }
```

And then it's called within the **boot()** method of the service provider.

I've been using the same service providers since Laravel 8 and now I'm on Laravel 10. Everything worked fine just a day before and now it doesn't, didn't update or change anything.

**Comment by adelf** [comment]
And this `registerTranslations` method is located in the base class? If so, it doesn't work...

**Comment by MirazMac** [comment]
No, it's used via a trait. 

But it used to work, worked just a day before. What changed suddenly?

**Comment by adelf** [comment]
Maybe you've updated the plugin? I'll try to fix it somehow...

**Comment by MirazMac** [comment]
I didn't do anything. Unless it updated automatically, which I don't think it does. Anyway I'll try to see if adding the method directly to the provider fixes it or not.

**Comment by MirazMac** [comment]
Update: Adding the code directly to the service provider solves it. However, using it via a trait doesn't work. Is this intended behavior?

**Comment by adelf** [comment]
I've added a fallback locale for modules. So, it should work now even without registering lang folder in each module.
