### ISSUE TITLE
[Feature Request]: Recognize macros on auth()

### ISSUE THREAD

**Issue by FeBe95** [laravel-idea/plugin#913]
### Feature Description

We've created some macros in the `boot()` method of `AuthServiceProvider` like this:

```PHP
use Illuminate\Auth\SessionGuard;

SessionGuard::macro('prevUser', fn() => session()->get('prev_user', new User()));
```

After generating the helper code, `Auth::prevUser()` is recognized while `auth()->prevUser()` is not:
![grafik](https://github.com/laravel-idea/plugin/assets/7470739/2ba31298-97b6-4b7b-8f9f-2bb7df2b1cca)

The following error is displayed:
```
Method 'prevUser' not found in \Illuminate\Contracts\Auth\Factory|\Illuminate\Contracts\Auth\Guard|\Illuminate\Contracts\Auth\StatefulGuard|\Illuminate\Contracts\Foundation\Application|\Illuminate\Foundation\Application 
```

I've also tried adding the marco like so, but still no luck:
```PHP
use Illuminate\Support\Facades\Auth;

Auth::macro('prevUser', fn() => session()->get('prev_user', new User()));
```

**Comment by adelf** [comment]
The warning is absolutely correct. auth() can return another StatefulGuard object. But I've added a SessionGuard type there. Should work ok in the last 8.0.3 version.

**Comment by FeBe95** [comment]
Works like a charm!
Thank you 🚀
