### ISSUE TITLE
[Bug]: `configKey` completion filter does not work for indexed arrays

### ISSUE THREAD

**Issue by amshehzad** [laravel-idea/plugin#915]
### Bug description

I'm using spatie permissions package and I've defined all my permissions in a config file `permissions` grouped by module like this:
![image](https://github.com/laravel-idea/plugin/assets/15146578/fe7104a0-fdc0-4de7-9270-a50604a71bd5)

I want to autocomplete permissions for `user()->givePermissionTo()`

now if write me rule like this:
```
"complete": "configKey",
"options": {
    "prefix": "permissions"
},
```

the auto complete shows only the module names, attendance, user, etc which is expected but not intended ..
so I changed prefix to "permissions.attendance" to see if that works, but it does not show autocomplete. 

Also, is it possible to also make autoomplelte work on nested arrays ? so e.g in my case I want to auto-complete the permissions which are grouped by modules 

### Plugin version

8.0.3.233

### Operating system

Windows

**Comment by adelf** [comment]
configKey completes only keys. not array values. 

If you want to complete permissions, you can try this.

```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "completions": [
        {
            "complete": "gate",
            "condition": [
                {
                    "methodNames": [
                        "hasPermission"
                    ],
                    "parameters": [
                        1
                    ],
                    "classFqn": [
                        "App\\Models\\ConfigConcern"
                    ]
                }
            ]
        }
    ],
    "auth": {
        "additionalGates": [
            "gate1",
            "gate2"
        ]
    }
}
```

Result:

<img width="452" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/8bc399a7-5c05-4d92-8e40-02633c019ad7">

**Comment by amshehzad** [comment]
Thank you for clarification @adelf, in my case I've hundreds of permissions which I've defined in my permissions.php, in the example you have provided, I'll have to write all those permissions in additionalGates, making the file messy, but that aside, every time I add new permission, I'll have to add it in ide.json too. is there any other way possible to achive this?

Also, do you see a potential in having the option to make something like `configValue` to add auto-complete from config values? that will solve my problem. if you that that it might be a common need

**Comment by adelf** [comment]
> I've defined all my permissions in a config file permissions grouped by module like this:

Why did you do that? Any other reason?

**Comment by amshehzad** [comment]
I use it in Permissions seeder, so I just placed them in permissions.php to be used by seeder and ide ( if I can make it work )

**Comment by adelf** [comment]
Sorry, but Laravel Idea can complete only config keys, not inside array values. I've added a possibility to complete prefixed keys recursively, so if your `config/permissions.php` file will be:
```php
return [
    "attendance" => [
       "foo" => 1,
       "bar" => 1,
    ]
];
```
and `ide.json`:
```
"complete": "configKey",
"options": {
    "prefix": "permissions",
    "recursive": true
},
```

it will complete "attendance.foo" and "attendance.bar".

This will be available in the next release.

**Comment by adelf** [comment]
8.0.4 released.
