### ISSUE TITLE
[Feature Request]: Blade Fragments

### ISSUE THREAD

**Issue by pikseli** [laravel-idea/plugin#916]
### Feature Description

It seems like [Blade Fragments](https://laravel.com/docs/10.x/blade#rendering-blade-fragments) are not supported. 

At least syntax highlighting for `@fragment` and `@endfragment` directives would be nice, but completion for fragment names in `fragments` and `fragmentIf` methods would be great addition.

**Comment by adelf** [comment]
What PhpStorm version do you use?
According this - https://youtrack.jetbrains.com/issue/WI-70445/Blade-Add-support-for-endfragment-fragment-directives - they are supported since 2023.1 version. However, I see that they are completed but not highlighted... looks like a Blade plugin bug.

**Comment by adelf** [comment]
Anyway, I've implemented fragment, fragmentIf and other method parameter completion.

**Comment by pikseli** [comment]
Sorry for the late reply. I'm using PhpStorm 2023.3.2 and Laravel Idea 8.0.3.233. I also have Blade plugin 233.13135.108 enabled, but weirdly fragment directives are shown just as plain text and not completed.

Thank you so much for implementing this so swiftly! 👏

**Comment by adelf** [comment]
As I see in 2024.1 EAP they fixed highlighting

<img width="179" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/976dcc14-30de-470e-8360-c32f0c9b5ea0">

fragment, fragmentIf parameters are completed in Laravel Idea 8.0.4. There is an issue that `fragment`, `fragmentIf` methods aren't completed after the `view()`, we will try to fix it.
