### ISSUE TITLE
[Bug]: Blade find usages not working

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-idea/plugin#917]
### Bug description

Hi,

the Blade find usages isnt working for me anymore:
![image](https://github.com/laravel-idea/plugin/assets/7324694/97f4a547-ac36-49d8-a77a-3348a57b922d)
The green button is missing for me. 

Tired cache invalidate.

### Plugin version

8.03.233

### Operating system

MacOS

### Relevant log output

```shell
PhpStorm 2023.3.2
Build #PS-233.13135.108, built on December 21, 2023
Subscription is active until August 30, 2024.
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 10
Registry:
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.intellij.ideolog (222.2.0.0)
  com.wakatime.intellij.plugin (14.3.8)
  com.intellij.ml.llm (233.13135.116)
  com.github.copilot (1.4.9.4300)
  String Manipulation (9.12.0)
  nl.deschepers.laraveltinker (2.6.1)
  izhangzhihao.rainbow.brackets (2023.3.9-233)
  de.espend.idea.php.annotation (9.4.0)
  ru.adelf.idea.dotenv (2023.3)
  com.laravel_idea.plugin (8.0.3.233)
```

**Comment by adelf** [comment]
We've moved it to the right-click > Go To menu. You can attach a shortcut for it.

**Comment by SudoGetBeer** [comment]
Is it possible to get it back there or a bit less clicks?

**Comment by smarkyun** [comment]
I don't have the find usages option in Go to menu either
![image](https://github.com/laravel-idea/plugin/assets/111564000/33b6bd84-2e41-4b95-ae6e-71c039ce84ab)

**Comment by SudoGetBeer** [comment]
![image](https://github.com/laravel-idea/plugin/assets/7324694/33e77b7c-5199-4160-8c39-a22f03cac168)
I have it but its a bit annoying because before it was just one click.

**Comment by smarkyun** [comment]
![image](https://github.com/laravel-idea/plugin/assets/111564000/3aaead0d-d2a3-4d6a-8c8b-bee5b5bc5ef4)

**Comment by adelf** [comment]
@smarkyun please update the plugin. It should be there starting from 8.0.3 version.

@SudoGetBeer, ok. I'll return it back. With the option turned off by default)

**Comment by BlackLight4K** [comment]
It is 8.0.3

**Comment by SudoGetBeer** [comment]
> @SudoGetBeer, ok. I'll return it back. With the option turned off by default)

Oh Thank you! Great work with the plugin, we buy it for every team member who is coding.

**Comment by smarkyun** [comment]
It is 8.0.3
![image](https://github.com/laravel-idea/plugin/assets/111564000/bb2378b5-5bcd-4084-a1d6-47eecbbb9948)

**Comment by adelf** [comment]
@smarkyun, do you see this action here?

<img width="902" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/f3804b92-1300-4e04-831a-8f1cd9664133">

And here?

<img width="792" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/e89c5216-39d3-42c8-aaf7-40a01608654e">

**Comment by smarkyun** [comment]
> @smarkyun, do you see this action here?
> 
> <img alt="image" width="902" src="https://private-user-images.githubusercontent.com/2818394/297308691-f3804b92-1300-4e04-831a-8f1cd9664133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODA2OTEsIm5iZiI6MTcwNTQ4MDM5MSwicGF0aCI6Ii8yODE4Mzk0LzI5NzMwODY5MS1mMzgwNGI5Mi0xMzAwLTRlMDQtODMxYS04ZjFjZDk2NjQxMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMDgzMzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUxMmE0YWJkOGFlYjdmYzk3YmEwNzZkYjJhMzI5ZDMzMDU4OWQ4NTkzMmFhYWU2OTkyMjY4MDAzNDIwMDFmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ux-fQO2yToaBGzliAZ6YqY16XkVvUTegaCh9f8lYZGA">
> And here?
> 
> <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/2818394/297308835-e89c5216-39d3-42c8-aaf7-40a01608654e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODA2OTEsIm5iZiI6MTcwNTQ4MDM5MSwicGF0aCI6Ii8yODE4Mzk0LzI5NzMwODgzNS1lODljNTIxNi0zOWQzLTQyYzgtYWFmNy00MGEwMTYwODY1NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMDgzMzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTY4MmExYTQ1YmE2OGI1ZWU1YTgyMGMwZjA2YTQxMTdhYWMxMzQ2MjYwZTdmYmQzYzQ3MTRiMDU1YmYzYTFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wm11Ee5gRp_yBQcVVPihsrQ6Zssd0eiflH1PgUoUrcw">

Both settings are missing

**Comment by smarkyun** [comment]
Looks like blade directives are not getting recognized at all
![image](https://github.com/laravel-idea/plugin/assets/111564000/5aa585e6-5f22-47a2-9fc7-1c4e46a7f7e9)

**Comment by smarkyun** [comment]
Okay, so I reinstalled the plugin and now i have the option too.
