### ISSUE TITLE
[Feature Request]: Add autocomplete for Blade if/else blocks

### ISSUE THREAD

**Issue by emmadesilva** [laravel-idea/plugin#919]
### Feature Description

When typing `@if`, we get autocomplete to generate the following:

```blade
@if()

@endif
```

Why not also support the following? 
```blade
@if()

@else

@endif
```

![image](https://github.com/laravel-idea/plugin/assets/95144705/64c83a86-ff69-4745-a188-ed97c1268ccb)

**Comment by adelf** [comment]
Why not?)

![ifElseEnd](https://github.com/laravel-idea/plugin/assets/2818394/09b501c6-5721-4417-a057-86f77797abd3)

**Comment by adelf** [comment]
Implemented in 8.0.4. Thank you.
