### ISSUE TITLE
[Request] Auto complete/jump to policy method based on classname

### ISSUE THREAD

**Issue by atymic** [laravel-idea/plugin#92]
When calling`$this->authorize('view', $model);` and `$model` is a known type, could we allow autocomplete/jump to the policy definition?

I often find myself having to manually find the policy method to check how it works.

Thanks :)

**Comment by adelf** [comment]
Will try to add to the next version. Popular request :)

**Comment by atymic** [comment]
Awesome, thanks for the quick response, love your work!

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/88535911-7d197d80-d013-11ea-8814-519c0433d322.png)

:)

**Comment by adelf** [comment]
Implemented in the 3.2 version. Please write here if I missed something.
