### ISSUE TITLE
[Bug]: Not quite correct php-doc type for the `chunk` collection method for relationships

### ISSUE THREAD

**Issue by Oleksandr-Moik** [laravel-idea/plugin#921]
### Bug description

I called `chunk` method on model relationship, but then PhpStorm prompts stop working correctly and not suggest completions. He thinks that chunk returns array instead of collection.

![image](https://github.com/laravel-idea/plugin/assets/50796878/7be182fa-e36e-49e5-8c63-a982c419e9c1)

![image](https://github.com/laravel-idea/plugin/assets/50796878/ab7c6adb-5f54-4692-9c1c-95659e6f2cba)

![image](https://github.com/laravel-idea/plugin/assets/50796878/aa3a3823-e7b5-45ad-ba35-7d74f016d930)

### Plugin version

8.0.3.233

### Operating system

Linux

### Steps to reproduce

Create two models, link with relationships and call `chunk` method on relationship.

```php
class Department extends Model
{
    public function faculties(): HasMany
    {
        return $this->hasMany(Faculty::class);
    }
}

class Faculty extends Model
{
    protected $fillable = [
        'department_id',
    ];
}
```

**Comment by adelf** [comment]
Fixed in 8.0.4. Thank you.
