### ISSUE TITLE
[Bug]: Navigation to method does not work with Route::controller

### ISSUE THREAD

**Issue by mika-iriarte** [laravel-idea/plugin#923]
### Bug description

In this case
```php
Route::controller(TestController::class)->get('/test', 'index');
```
navigate to controller method via Ctrl-Click on `'index'` does not work - got message: "Cannot find declaration to go to".
In other cases it works.

### Plugin version

8.0.4.232

### Operating system

Windows

### Steps to reproduce

Add to routes/web.php code:
```php
Route::controller(TestController::class)->get('/test', 'index');

Route::get('/test', [TestController::class, 'index']);

Route::group(['controller' => TestController::class], function () {
    Route::get('/test', 'index');
});
```
try to click with Ctrl on `'index'`

**Comment by adelf** [comment]
Fixed on one of the last versions.

**Comment by Spezelechse** [comment]
which version fixed this?
i'm running 12.3.0 and it only works with

```
Route::get('/test', [TestController::class, 'index']);
```

the other two versions still produce the "Cannot find declaration to go to" message

**Comment by adelf** [comment]
Hi, @Spezelechse. I just checked, and it works. Maybe you've forgotten to add a "use" statement? Or maybe your route file is added with 'namespace' attribute? Like 

```php
Route::group(['namespace' => '...'], function () {
    include 'web.php';
});
```

<img width="671" height="255" alt="Image" src="https://github.com/user-attachments/assets/6085a698-7cd0-4133-b1b2-c986b6cd1839" />

**Comment by Spezelechse** [comment]
ah damn. the namespace set in the RouteServiceProvider was the issue, **thanks**.

weird that it only affects the Route:controller and Route::group version of the route.
why does Route:get work with a namespace and the other two not?
atleast with the idea plugin. 
the application routes are running fine (all three versions). only the resolving of the controller method within the idea wasn't working.

**Comment by adelf** [comment]
Yes. I hardcoded removing the default prefix (App\Http\Controllers) if it can't find the correct one in some cases(Route::get, etc.). I'll try to fix that for this case too.
