### ISSUE TITLE
[Bug]: Not compatible with the version of your running IDE (PhpStorm 2024.1 EAP)

### ISSUE THREAD

**Issue by aran112000** [laravel-idea/plugin#925]
### Bug description

Not compatible with the version of your running IDE (PhpStorm 2024.1 EAP)

### Plugin version

8.0.3.233

### Operating system

Windows

**Comment by adelf** [comment]
There are some issues in the EAP. So, it will take some time to release a version for 2024.1.

**Comment by ahoiroman** [comment]
Fair enough, but there are major issues on the latest 2023 releases (crashing macs with silicon chips entirely), so I can't wait to see a release ;-) Fingers crossed.

**Comment by aran112000** [comment]
Solved with yesterday's release:
https://plugins.jetbrains.com/plugin/13441-laravel-idea/versions/stable/490047
