### ISSUE TITLE
[Feature Request]: Single Files per Model or Upper Limit of Models in generated files

### ISSUE THREAD

**Issue by danielrona** [laravel-idea/plugin#926]
### Feature Description

Hello,

I'm currently facing an issue as of recently that the re-indexing takes between 20 and 60 minutes to finish

I'm not sure if it's because of faulty code or a update.

It would help a lot if one could split the generated files into a file per Model or a upper limit of how many Models per file that would make it easier to find the culprit.

Right now the index diagnostics shows that some files take up to 36 minutes, but I can't figure out where the error originates from.

![image](https://github.com/laravel-idea/plugin/assets/1699775/66d8ecc5-2725-4edf-af6f-81eb4abd52ae)

**Comment by adelf** [comment]
Hello. That is definitely something wrong with PhpStorm. How big is this file? How many models do you have?

It's probably corrupted index files. Have you tried File > Invalidate Caches?

**Comment by danielrona** [comment]
Hi @adelf thanks for the quick response, yes I've tried that several times already.

The file is currently 1647 KB (builder) followed by the next 2 files wich are 456 KB (proxies) and 437 KB (models) the other 30 files are combined 415 KB

There 233 Models currently available.

**Comment by danielrona** [comment]
After adjusting the settings to store the files inside vendor/_laravel_idea everything works now.

![image](https://github.com/laravel-idea/plugin/assets/1699775/e6ea15e0-2337-4b7d-9753-b50b9d997b0d)

Not sure why it was an issue because I had the files previously in .helpers/laravel_idea
