### ISSUE TITLE
[Request] Code generation for Dusk

### ISSUE THREAD

**Issue by nessor** [laravel-idea/plugin#93]
Hey guys,

first of all thank you for this incredibly good plugin. I noticed that a code generation for Dusk tests would be really helpful. Many tests look like this:

```php
    /**
     * Test sth.
     * 
     * @group 1
     * @group 2
     * 
     * @return void
     * @throws Throwable
     */
    public function testSomeFunction(): void{
        $this->browse(static function(Browser $browser){
            $browser->visitRoute('route')
                ->assert...
                ->assert...
                ...
        });
    }
```

This code block could easily be generated automatically (maybe without the assert methods?) and save a lot of time when designing test cases.
What do you think about this? :)

**Comment by adelf** [comment]
Hi, Florian.
I'm going to release a new version soon. After that, I want to implement a new feature - custom generations. It will be possible to create own code generation with own template.
Little workaround for now: change template and paths for Create Feature or Create Unit Test generation and use it :)
https://laravel-idea.com/docs/3.x/generation#configuration

**Comment by nessor** [comment]
Hi @adelf 

that's great news! I really looking forward to this feature!
In the meantime, I'm not going to die from the little more typing ;) 

-Florian

**Comment by adelf** [comment]
> In the meantime, I'm not going to die from the little more typing ;)

Shame on you ))
