### ISSUE TITLE
[Bug]: Autocomplete on translation helper not work anymore

### ISSUE THREAD

**Issue by PanjiNamjaElf** [laravel-idea/plugin#930]
### Bug description

Before update the plugin to latest version, the feature for autocomplete on translation helper like `trans`, `__`, `\Lang::get('key')` is work normal, but after update it does not work, i cannot display the available translation key via this helper.

### Plugin version

8.0.4.233

### Operating system

Windows

### Steps to reproduce

![Record_2024_02_06_17_39_31_367-ezgif com-video-to-gif-converter](https://github.com/laravel-idea/plugin/assets/16651293/adf24d3c-b62e-4be5-8105-400ed8e8bb47)

**Comment by adelf** [comment]
Could you tell in which folder the lang files are located? And settings from Settings | Languages & Frameworks | Laravel Idea | Translation?

**Comment by PanjiNamjaElf** [comment]
Ahh i see...
The folder change to `lang` on settings but my laravel translation folder on `resources/lang`
Thank's
