### ISSUE TITLE
[Feature Request]: Refactor column name/property

### ISSUE THREAD

**Issue by MichelJonkman** [laravel-idea/plugin#931]
### Feature Description

It would be very nice if the plugin could refactor all usages of a column/property that it knows of. Anything that the plugin/PhpStorm is unaware of will obviously remain untouched but as more features get added the amount of places it will detect will likely also grow!

If this is already a feature or request please, point towards it as I couldn't find anything!

**Comment by adelf** [comment]
There is a solution.

First, mark vendor/_laravel_idea folder as Not Excluded.
<img width="540" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/176e6813-b14c-4810-aae4-ec7d3b20f60e">

Then you can go to any place with this field and use the Rename command.

**Comment by MichelJonkman** [comment]
Aha thank you!
