### ISSUE TITLE
[Bug/Feature?]: Custom auth driver not recognized

### ISSUE THREAD

**Issue by MichelJonkman** [laravel-idea/plugin#935]
### Bug description

I use a custom auth driver using Auth::extend() but the generated helper code doesn't recognize this. Not sure if this is classified as a bug or a feature request but it would be very nice if this worked. Even if we have to manually register it in the config somewhere!

### Operating system

None

**Comment by adelf** [comment]
Hello. What feature doesn't work? Could you show some examples?

**Comment by MichelJonkman** [comment]
If I create a method on my guard, for example test(), Auth::test() won't be autocompleted or recognized by PhpStorm.

In my case I'm using a guard that extends the session guard to add new functionality to it. If you need more info please tell me!

**Comment by MichelJonkman** [comment]
The code I used (DeviceSessionGuard extends SessionGuard): 
```php
Auth::extend('device_session', function (Application $app, string $name, array $config) {
    $guard = new DeviceSessionGuard(
        $name,
        Auth::createUserProvider($config['provider']),
        $this->app['session.store'],
    );

    if (method_exists($guard, 'setCookieJar')) {
        $guard->setCookieJar($this->app['cookie']);
    }
    if (method_exists($guard, 'setDispatcher')) {
        $guard->setDispatcher($this->app['events']);
    }
    if (method_exists($guard, 'setRequest')) {
        $guard->setRequest($this->app->refresh('request', $guard, 'setRequest'));
    }

    return $guard;
});
```

**Comment by adelf** [comment]
You can try to create this `ide.json` file in your project.
```
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "helperCode": {
        "classMixins": [
            {
                "classFqn": "\\Illuminate\\Auth\\SessionGuard",
                "mixinFqn": "YourNamespace\\ DeviceSessionGuard"
            }
        ]
    }
}
```

And then Generate Helper Code 2 times. It might help.

**Comment by adelf** [comment]
```    
if (method_exists($guard, 'setRequest')) {
        $guard->setRequest($this->app->refresh('request', $guard, 'setRequest'));
    }
```
Why don't you sure about method existing? It looks weird)

**Comment by MichelJonkman** [comment]
> ```
> if (method_exists($guard, 'setRequest')) {
>         $guard->setRequest($this->app->refresh('request', $guard, 'setRequest'));
>     }
> ```
> 
> Why don't you sure about method existing? It looks weird)

It's copied from the official Laravel code I believe, I very much do not agree with how they did that... Imo they should've just used the Service Container for it...

**Comment by MichelJonkman** [comment]
> You can try to create this `ide.json` file in your project.
> 
> ```
> {
>     "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
>     "helperCode": {
>         "classMixins": [
>             {
>                 "classFqn": "\\Illuminate\\Auth\\SessionGuard",
>                 "mixinFqn": "YourNamespace\\ DeviceSessionGuard"
>             }
>         ]
>     }
> }
> ```
> 
> And then Generate Helper Code 2 times. It might help.

This works, thank you very much! Is there any documentation for the ide.json file?
