### ISSUE TITLE
After seeder creation need to maually dump composer autoloads

### ISSUE THREAD

**Issue by dobrik** [laravel-idea/plugin#94]
When create seeder with using plugin code generation, seeder class not visible for framework, so command
`php artisan migrate --seed`
returns error
`Target class [UsersTableSeeder] does not exist.`
Need to add dump-autoload command after seeder creation.

**Comment by adelf** [comment]
Good idea. Thanks. Will try to ask Composer plugin to that.

**Comment by adelf** [comment]
Implemented in the 4.3.2 version
