### ISSUE TITLE
[Feature Request]: Support Laravel Actions

### ISSUE THREAD

**Issue by tjarrett** [laravel-idea/plugin#943]
### Feature Description

I realize this package isn't as popular as Livewire or Filament but it'd be pretty neat if this plugin could detect and support it. Especially mapping the documentation from the `handle()` methods to the static method `run()`.

There is an existing tool that is mostly [wulfheart/laravel-actions-ide-helper](https://github.com/Wulfheart/laravel-actions-ide-helper) that could maybe be leveraged to quickly add the functionality to this tool.

**Comment by adelf** [comment]
Fixed in 8.1.4

**Comment by timmaier** [comment]
Does this also support the return type? Would be nice to get the collection type here.

![Screenshot 2024-08-09 at 11 13 23 AM](https://github.com/user-attachments/assets/a4f7f655-f424-4093-b98e-b47532fa2f23)
![Screenshot 2024-08-09 at 11 13 40 AM](https://github.com/user-attachments/assets/45da35bb-02f4-457f-8090-c5ac4dddd7f6)
![Screenshot 2024-08-09 at 11 15 09 AM](https://github.com/user-attachments/assets/9548a022-5f5c-4e9c-bb2c-493fae49680e)

**Comment by msnegurski** [comment]
yes, getting return type would be awesome
