### ISSUE TITLE
[Bug]: Uknown view error for all views

### ISSUE THREAD

**Issue by smarkyun** [laravel-idea/plugin#945]
### Bug description

The plugin cannot find any views. I tried invalidating the cache and reinstalling the plugin, but nothing changed.

![image](https://github.com/laravel-idea/plugin/assets/111564000/38f4aee8-7202-4bf0-b589-e6da46818f23)
![image](https://github.com/laravel-idea/plugin/assets/111564000/7655fadd-669a-49e7-8d94-b59484e9bde1)

### Plugin version

8.1.2.233

### Operating system

Linux

**Comment by adelf** [comment]
Hello. Could you check the Settings, Default view path and Default namespace parameters.

<img width="550" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/124503bc-e80e-475c-ab68-2ce5c2cbbdae">

**Comment by smarkyun** [comment]
![image](https://github.com/laravel-idea/plugin/assets/111564000/46d2c0d9-aaf4-4eae-8700-2aef42223cce)

**Comment by smarkyun** [comment]
Please, it is very annoying

**Comment by adelf** [comment]
Could you find all `loadViewsFrom` and `addLocation` calls(use Scope > All Places)?


<img width="892" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/becf7ebe-f156-4679-ad3c-6dacdce1093b">


You can disable this inspection for now.

<img width="836" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/f865428f-c61d-499c-83bf-1cff6ed877e5">

**Comment by smarkyun** [comment]
Yes, but the inspection is for all views not just those with custom namespace.
Btw The inspection is not the main problem, I have to search for every view usage by name instead of just clicking the icon or using the hotkey

**Comment by smarkyun** [comment]
Even the main view is unknown

**Comment by adelf** [comment]
> with custom namespace

Your view in the custom namespace? Did you set it in the settings?

![image](https://github.com/laravel-idea/plugin/assets/2818394/444a46a3-a801-431c-9048-34425b0ffcfa)

**Comment by smarkyun** [comment]
I meant the loadViewsFrom() 2. param is a namespace, but as I said, the plugin cannot recognize the simple view either

**Comment by smarkyun** [comment]
If i install the legacy deprecated laravel plugin, it can recognize the views normally

**Comment by adelf** [comment]
That's really weird. So you don't have any `loadViewsFrom` calls in the project? It has a default Laravel structure and the views aren't recognized?

**Comment by smarkyun** [comment]
I do have
![image](https://github.com/laravel-idea/plugin/assets/111564000/c15b80b3-991a-44fc-afa9-ed99cdb30e60)
What I am saying is there are many view (like main.blade.php) calls without any namespace, and those are not working either.

**Comment by smarkyun** [comment]
The views I am referring to are in the basic laravel structure resources/views folder

**Comment by adelf** [comment]
does the plugin complete anything in the `view('here')` call?

**Comment by smarkyun** [comment]
Yes, It seems only the ones from the loadViewsFrom call

**Comment by smarkyun** [comment]
Can I provide you any additional information about the issue?

**Comment by adelf** [comment]
I'm not sure. Could you send all `.idea/laravel_*` files? Here or adel@laravel-idea.com

**Comment by smarkyun** [comment]
I fixed the issue. One of the loadViewsFrom call started with `'../'` instead of `__DIR__ . '/'`. It is still weird that this prevents the IDE from recognizing views.

**Comment by adelf** [comment]
Is it in one of the packages or it was your `loadViewsFrom`?

Yes, my logic is that `loadViewsFrom` calls override the default settings, since there are a lot of package creators, who overrides the resources/views with own namespace views.

**Comment by smarkyun** [comment]
It was mine

**Comment by RicardoAugustoTulio** [comment]
Hello, I saw that you already solved your problem, but the solution you provided didn't work for me.
I started looking in the settings and realized that putting a "/" before the views path also solves the problem.
![image](https://github.com/laravel-idea/plugin/assets/41270886/2df32d8f-69a8-444b-8db6-a4cddffafc04)
![image](https://github.com/laravel-idea/plugin/assets/41270886/de2603b0-8682-45c2-a14d-261ad55cd681)

**Comment by adelf** [comment]
@RicardoAugustoTulio 

Could you check your settings? Is Laravel directory empty?

<img width="633" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/68571457-9b7e-49ac-9ac3-3461d7fd4b76">

**Comment by flavius-constantin** [comment]
> Hello, I saw that you already solved your problem, but the solution you provided didn't work for me. I started looking in the settings and realized that putting a "/" before the views path also solves the problem. ![image](https://private-user-images.githubusercontent.com/41270886/329683224-2df32d8f-69a8-444b-8db6-a4cddffafc04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjI4NzMsIm5iZiI6MTcyMDgyMjU3MywicGF0aCI6Ii80MTI3MDg4Ni8zMjk2ODMyMjQtMmRmMzJkOGYtNjlhOC00NDRiLThkYjYtYTRjZGRmZmFmYzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIyMTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YzI1YWMyYzY1NzFkOGExNzQ0MmRmNDgzOTU5MDJhMTFjMDYzZGYzODA3YzRkMGYzZjAyOWUwYzIxZDJkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0AYu_lD-eDJe4q-6AuEhB_fYw-fLLH56O_PQoYk15JQ) ![image](https://private-user-images.githubusercontent.com/41270886/329683540-de2603b0-8682-45c2-a14d-261ad55cd681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjI4NzMsIm5iZiI6MTcyMDgyMjU3MywicGF0aCI6Ii80MTI3MDg4Ni8zMjk2ODM1NDAtZGUyNjAzYjAtODY4Mi00NWMyLWExNGQtMjYxYWQ1NWNkNjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIyMTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTAyNmJmYWVjODY3NmU3YjM3YWZmYzE4NjE4OGVlOTVmYTg2MGI3MGFiMzAxMmM1Y2RjODJhZjYyNjJiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.llb2uuX8EiWe98fZWBAGuFBJJuifnU9IMHDm0-To19Y)

What the heck? This `/` just fixed my problem thought.
But why do I have projects without the `/` prefix and it works?

**Comment by ilkermutlu** [comment]
Can confirm putting a leading slash in default views path resolved it for me too.

**Comment by timotee** [comment]
My suggestions were suddenly appended with other libraries, eg. `<x-livewire-data-tables::select/>` instead of `<x-utils.select/>`. Adding the / fixed this. This also happened about a month ago. Then I decided to reset PHPStorm. Glad to see there is a fix.

After this fix it still suggests the livewire paths after the correct paths btw. If I use the livewire paths I can click on them and they take me to the correct blade file.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/2a1610e5-08f4-4c9b-8bc0-ca0d3720de36">

**Comment by adelf** [comment]
@timotee could you send your composer.lock(and .json if possible) to support@laravel-idea.com?

And maybe some additional parts of the project(service providers, views, etc.). If it doesn't violate NDA.

**Comment by adelf** [comment]
It's fixed. Thank you all for posting about the issue and sorry that it took so long to fix.
