### ISSUE TITLE
[Feature Request]: New Artisan Command for Laravel 11

### ISSUE THREAD

**Issue by khannedy** [laravel-idea/plugin#949]
### Feature Description

```
php artisan make:class
php artisan make:enum
php artisan make:interface
php artisan make:trait
```

![CleanShot 2024-03-14 at 12 47 20](https://github.com/laravel-idea/plugin/assets/70091/b70648a4-8ef3-4283-854b-c4a196846df3)

**Comment by adelf** [comment]
I've implemented a class creation for the next version. Other cases are rare, so they can be created in the PhpStorm standard way.

<img width="275" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/7e34aa35-7bf3-4e99-aa74-9f8c8276226a">
