### ISSUE TITLE
[Enhancement] Use id column type instead of bigIncrements in migration 

### ISSUE THREAD

**Issue by Algeneralo** [laravel-idea/plugin#95]
Laravel now is using `id `column type in migration, but the plugin still using `bigIncrements ` type, is there a specific reason for that?

**Comment by adelf** [comment]
This method is available starting from Laravel 7, so I can't propose it for all projects.
For your project you could just change the template in Settings > Editor > File and Code templates > Code > Laravel Ideal Database Migration.

**Comment by adelf** [comment]
However, I can change the template and use some parameter there, like `$ID_METHOD$`... I'll think about it. Thanks.

**Comment by Algeneralo** [comment]
Great!, I just noticed that I can edit the templates.
Thanks for your help.
