### ISSUE TITLE
[Bug]:  Validation rules shown twice

### ISSUE THREAD

**Issue by henzeb** [laravel-idea/plugin#951]
### Bug description

When I use CTRL+SPACE to show the rules or just start typing, it shows every rule twice. This is since laravel 11, as I could not reproduce it in a Laravel 10 project.

This also is an issue for custom validations using ide.json.

### Plugin version

8.1.2.233

### Operating system

Linux

### Steps to reproduce

1. ./artisan make:request MyRequest
2. go to the rules in that request and add a parameter and then try to show the list of rules using CTRL+SPACE or just start typing.

![issue_with_validation_hints](https://github.com/laravel-idea/plugin/assets/15928532/70e083f5-5dcc-444c-9959-0eda792ffbdb)

**Comment by adelf** [comment]
I tried to fix it, so let's check it after the release.

**Comment by adelf** [comment]
I hope it's fixed...
