### ISSUE TITLE
[Bug]:  Performance - blade

### ISSUE THREAD

**Issue by gulios** [laravel-idea/plugin#956]
### Bug description

PLugin version: 8.1.3.233
PHPStorm version: 2023.3.5

is there any special settings to optimize editing Laravel blades templates ?
When you edit templates files CPU takes all cores and PHPStorm slowing down.
It's hard to work(almost impossible) with blades with plugin turned on.

How can i debug it?

### Plugin version

8.1.3.233

### Operating system

MacOS

### Steps to reproduce

Turn on plugin, go to some Laravel blade file with 50, 100 or more lines with variables, trans etc
After couple of minutes CPU is burning and PHPStorm slowing down.

**Comment by Francismori7** [comment]
Just wanted to drop in saying I do not have this issue, however at times, PhpStorm by itself can feel slow, especially when indexing files inside WSL2.
I run Windows 10 with an i9-12900H with 64GB of RAM

**Comment by gulios** [comment]
i've turned on Activity Monitor and saw that there is some info about Java (infrastructure java2d queue flusher) so i've checked macOs settings and Java "update" tab didn't work for me so i have some old version.
Downloaded and installed latest java  from website and so far PHPStorm works fine.
