### ISSUE TITLE
[Bug]: Only one ide.json file is loaded, second one is ignored

### ISSUE THREAD

**Issue by MichelJonkman** [laravel-idea/plugin#963]
### Bug description

I have 2 ide.json files in the project, 1 by Hybridly and 1 made by me. Only the Hybridly one is loaded, probably because the folder it is in is sorted before mine.

### Plugin version

8.1.3.233

### Operating system

Windows 10 with WSL2 Ubuntu

### Steps to reproduce

Make 2 folders with both and ide.json file in them with differing content. 
1 works, the other one is ignored.

**Comment by adelf** [comment]
They both should work. Are there any syntax errors?

**Comment by MichelJonkman** [comment]
After trying again it now does work, I may have updated my PhpStorm in between then and now but I have no clue what has changed now. Oh well, thanks for the response!
