### ISSUE TITLE
[Feature Request]: Support type annotations in Blade `@props`

### ISSUE THREAD

**Issue by emmadesilva** [laravel-idea/plugin#966]
### Feature Description

Would it be possible to support type annotations within Blade `@props` directives? 

So for a component like this:

```blade
<x-hyde::navigation.navigation-link :item="$item" :active="$item->isActive()" />
```

Using the following:
```blade
@props([
    'active' => false,
    /** @var \Hyde\Framework\Features\Navigation\NavigationItem */ $item
])
```

Would equal this:
```blade
@props([
    'active' => false,
    $item
])
@php /** @var \Hyde\Framework\Features\Navigation\NavigationItem $item */ @endphp
```

**Comment by adelf** [comment]
Hello. It should work like this.

```
@props([
    'active' => false,
    /** @var \Hyde\Framework\Features\Navigation\NavigationItem */ 'item'
])
```

**Comment by emmadesilva** [comment]
> Hello. It should work like this.
> 
> ```
> @props([
>     'active' => false,
>     /** @var \Hyde\Framework\Features\Navigation\NavigationItem */ 'item'
> ])
> ```

Okay that actually works, but feels kinda unintuitive to be honest. I have never seen this syntax before, and it looks like it semantically tries to annotate the type of a literal string instead of a variable.

**Comment by adelf** [comment]
Is this syntax allowed in Blade components?

```php
@props([
    'active' => false,
    $item
])
```

**Comment by emmadesilva** [comment]
> Is this syntax allowed in Blade components?
> 
> ```
> @props([
>     'active' => false,
>     $item
> ])
> ```

Ah, not it does not. You're right. PhpStorm doesn't mark it as an error, but it does throw an exception when trying to render. It makes sense that we annotate a string enclosed thing, because `'active'` is "converted" into `$active`, so same should go for annotating the `$item/'item'` type even though it's weird. An implementation like I was thinking would require a patch to Laravel.

**Comment by adelf** [comment]
So, I suppose we can close this?

**Comment by emmadesilva** [comment]
> So, I suppose we can close this?

Indeed. Thanks for taking the time to help! Maybe it can be documented somewhere so it's easier for people to find?

**Comment by adelf** [comment]
Documentation is the weakest point of Laravel idea... :(
