### ISSUE TITLE
[Bug]: New eloquent model with ulid not create a primary() index for ulid

### ISSUE THREAD

**Issue by abkrim** [laravel-idea/plugin#969]
### Bug description

Hello.

I think that when we are building a model and the configurations for this are to use ulid as primary key, this must be confirmed in the migration because otherwise, if for example we mark a relationship with another table (constrained for example) the migration will fail, since that the table will not have the required index.

### No ok
```php
Schema::create('core_process_issues', function (Blueprint $table) {
            $table->ulid('id')
 ```
 
 ### Ok
 ```php
 Schema::create('core_process_issues', function (Blueprint $table) {
            $table->ulid('id')->primary()
  ```
  
 If master table has not `ulid('id')->primary()` a ` $table->foreignUlid('core_process_id')->constrained('core_processes');`should fails 
 
 ```
 SQLSTATE[HY000]: General error: 1822 Failed to add the foreign key constraint. Missing index for constraint 'core_process_issues_core_process_id_foreign' in the referenced table 'core_processes' (Connection: mysql, SQL: alter table `core_process_issues` add constraint `core_process_issues_core_process_id_foreign` foreign key (`core_process_id`) references `core_processes` (`id`))

```

                     

### Plugin version

8.1.3.233

### Operating system

MacOS

### Steps to reproduce

- Create a master new model with `ulid` in Laravel Idea Preferences 
- Create a relation table in relation with the master table. 
- Generate migration and model.
- Run migrations and get a fail

I need the correct issue in the model son.

### Relevant log output

```shell
INFO  Running migrations.  

  2024_03_28_075352_create_core_processes_table .......................................................................................... 19ms DONE
  2024_03_28_075616_create_core_process_issues_table ..................................................................................... 10ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1822 Failed to add the foreign key constraint. Missing index for constraint 'core_process_issues_core_process_id_foreign' in the referenced table 'core_processes' (Connection: mysql, SQL: alter table `core_process_issues` add constraint `core_process_issues_core_process_id_foreign` foreign key (`core_process_id`) references `core_processes` (`id`))

```
```

**Comment by adelf** [comment]
Fixed in 8.1.4
