### ISSUE TITLE
[Feature Request]: Change visibility for relationships when creating Models

### ISSUE THREAD

**Issue by el-klo** [laravel-idea/plugin#971]
### Feature Description

Whenever i create a model and implent a new relationship, all methods get set to 'protected'. Like this:

`protected function teacher(): BelongsTo {
		return $this->belongsTo( Teacher::class );
	}`

I cannot find where to change this so it will always be set to public. Can someone point me in the right direction or implement this in a feature update?

**Comment by jwktje** [comment]
I just started using the plugin too. And this was my first massive issue with it too. Filament kept throwing errors and it took me a good hour to figure out that the code generation was causing my relations to be `protected`. I don't know why this is the default. But I for sure would like to be able to set it to public by default.

**Comment by adelf** [comment]
Fixed. Sorry for this stupid mistake. The new release will be available this week.

**Comment by adelf** [comment]
Fixed in 8.1.4
