### ISSUE TITLE
[Bug]: inertia-link tags

### ISSUE THREAD

**Issue by DiyarDigiplace** [laravel-idea/plugin#973]
### Bug description

Hello,

I believe the <inertia-link> tags shouldn't be underlined like this :
![CleanShot 2024-03-29 at 18 01 06@2x](https://github.com/laravel-idea/plugin/assets/160529800/43d6f74d-4ee0-4a7f-a350-c56c0a00db04)

I hope it'll be fixed in the future, since the plugin is supposed to provide support for inertiajs.

### Operating system

None

**Comment by adelf** [comment]
Hello. I can't find any documentation about this tag. Could you help me?
