### ISSUE TITLE
[Bug]: "Generate Laravel Translation" does not pop up when cursor is on {

### ISSUE THREAD

**Issue by imerr** [laravel-idea/plugin#974]
### Bug description

The alt+insert "Generate Laravel Translation" helper does not seem to show up when the cursor is on a curly bracket

I noticed this when wanting to translate a line that started with a print statement.

Video:
https://github.com/laravel-idea/plugin/assets/1426904/0e3a1a84-320a-4501-929c-627c51e83ac4

### Plugin version

8.1.3.233

### Operating system

Windows

### Steps to reproduce

1. Open a blade template
2. Add the following line:
```php
{{"Test"}} translation helper test line
```
3. Select the line from the right, so the cursor ends up on the { at the start (via keyboard this would be: End, Shift+Home)
4. Alt+Insert to generate a translation, which will not show up
5. If you select the same line, but from the left so the cursor ends up at the end (via keyboard this would be: Home, Shift+End) the translation works

**Comment by adelf** [comment]
Fixed in 8.1.4.
