### ISSUE TITLE
[Feature Request]: ide.json autocomplete for blade directives

### ISSUE THREAD

**Issue by shadoWalker89** [laravel-idea/plugin#976]
### Feature Description

Hi when using @vite() i would like to autocomplete the file names

i used these and it didn't work.
Could you please add a new condition maybe like "bladeDirective" that will allow the user to add completions for any of the blade directives, even the ones created by the user

```
{
            "complete": "directoryFiles",
            "options": {
                "directory": "/"
            },
            "condition": [
                {
                    "functionNames": ["@vite"],
                    "parameters": [1]
                }
            ]
        }
```

and

```
{
            "complete": "directoryFiles",
            "options": {
                "directory": "/"
            },
            "condition": [
                {
                    "functionNames": ["vite"],
                    "parameters": [1]
                }
            ]
        }
```

**Comment by adelf** [comment]
Starting from 8.1.4 you can use: `"functionNames" : ["vite_func"]`

**Comment by shadoWalker89** [comment]
Thank you so much for adding this, it's working perfectly fine.

But if it is possible, could you please allow defining autocomplete for custom blade directives.

For example i have created a @viteCoreApp() blade directive that allows me to do some logic and i would like to have autocomplete on that too
In fact i have 4 functions

@viteCoreApp
@viteCoreSite
@viteProjectApp
@viteProjectSite

Having this will also allow for example to have autocomplete on any blade directive maybe a custom blade directive that deals with gate permissions or configKey ...

**Comment by adelf** [comment]
You can setup directives in ide.json:
```json
{
  "blade": {
    "directives": [
      {
        "name": "simpleDirective"
      },
      {
        "name": "parametrizedDirective",
        "prefix": "<?php echo yourFunctionName(",
        "suffix": "); ?>"
      }
    ]
  }
}
```

and then use `yourFunctionName` to make completions.
