### ISSUE TITLE
[Bug]: config should hint both in config/* and Modules/<package>/config/*

### ISSUE THREAD

**Issue by sepoa-tiennt** [laravel-idea/plugin#978]
### Bug description

I create a package name admin and config key1
Modules/socoladaica/admin/config/admin.php
```php
<?php

return [
    'key1' => 'key1',
    'name' => 'Admin',

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => [
    ],
    'dashboard_plugins' => [],
];

```

![image](https://github.com/laravel-idea/plugin/assets/126145663/f1d3b19e-aee8-4325-8d2a-abce28f6a815)
It can hint config `admin.key1`, but when I public config to config/admin.php
after that I define `key2` inside Modules/socoladaica/admin/config/admin.php, It not hint `key2`,
![image](https://github.com/laravel-idea/plugin/assets/126145663/22311327-ee4f-41e9-816e-0150b6c9bb2b)
I thing It hint key inside config/admin if both Modules/socoladaica/admin/config/admin.php and config/admin.php exists,

May be hint both Modules/socoladaica/admin/config/admin.php and config/admin.php?

### Operating system

Windows

**Comment by adelf** [comment]
If I understood correctly, this is fixed already. The new release will be available this week.
