### ISSUE TITLE
[Bug]: Escaped attributes on Blade components still injects PHP

### ISSUE THREAD

**Issue by oli-laban** [laravel-idea/plugin#979]
### Bug description

This was already fixed in #547 but I am still experiencing this issue while trying to use the Alpine.js class shorthand:

![Screenshot 2024-04-12 at 13 02 25](https://github.com/laravel-idea/plugin/assets/16418002/c6a250be-ae35-4aed-a13c-ca5e214d03a8)

### Plugin version

8.1.3.241

### Operating system

MacOS

### Steps to reproduce

1. Create a Blade component and display using the `<x-component-name />` syntax.
2. Add any attribute prefixed with `::`
3. Confirm PHP is injected by typing for example a PHP function or in-scope variable.

**Comment by adelf** [comment]
It's because of the PhpStorm Blade plugin. It started to inject PHP language into :attributes.
