### ISSUE TITLE
Completion for custom config files (new feature? not working?)

### ISSUE THREAD

**Issue by squatto** [laravel-idea/plugin#98]
I have a config file `/config/quadra.php` with this (and more) in it:

```php
return [
    'queues' => [
        'fulfillment' => env('FULFILLMENT_QUEUE', 'fulfillment'),
    ],
];
```

Should custom config files autocomplete? If so, they don't appear to be working:

![no-config-autocomplete](https://user-images.githubusercontent.com/748444/90433467-1a068e00-e089-11ea-95f6-720bce936de7.gif)

Thanks!

**Comment by adelf** [comment]
Hi, Scott.
Just checked. Everything works.

![image](https://user-images.githubusercontent.com/2818394/90449536-4f929200-e0f0-11ea-90f4-5cdbc001310b.png)

Do you have anything else in the file? Or...

**Comment by squatto** [comment]
Interesting, I wonder what's wrong with mine? I'll remove everything else from the file and add it in piece by piece until I figure out what's breaking it. I'll let you know, in case it needs to be accounted for.

Thanks for checking!

**Comment by squatto** [comment]
I'm not sure what is going on, but it wasn't working in `app/Jobs/ScheduleCreateWebhooksJobs.php`, so I tried it in `config/quadra.php` and it worked...and now it works in the job file. Maybe it cleared a cache or something? It seems to be working everywhere now. I'm not sure why, but I'll take it 😃

**Comment by adelf** [comment]
Time by time users report about issues with config files, so if you find any reproducible cause of this issue, please tell me :)

**Comment by squatto** [comment]
@adelf Will do! Thank you again!
