### ISSUE TITLE
[Bug]: Files not being populated

### ISSUE THREAD

**Issue by BrickZ28** [laravel-idea/plugin#980]
### Bug description

When I try to make a model or migration (only ones iver tried so far) the file is being created but there is no code being place, it just creates an empty file. 

### Plugin version

8.1.4.241

### Operating system

Windows

**Comment by adelf** [comment]
Sorry for the long response. That's strange. Does it still work like that? Could you check Settings > Editor > File and Code Templates > Code and check Laravel Idea templates?

**Comment by BrickZ28** [comment]
My apologies, i meant to close this out.  It ended up being a PHPStorm issue.  It was doing it even when manually creating a file with a template.  I had to uninstall and reinstall PHPStorm.  So not your software at all, which doesnt surprise me due to the quality of what you have made!!!

________________________________
