### ISSUE TITLE
[Feature Request]: Add possibility to add declare(strict_types=1) to generated files

### ISSUE THREAD

**Issue by swayok** [laravel-idea/plugin#985]
### Feature Description

Using `declare(strict_types=1);` in modern projects is a common use case.

Suggestion is to add to "Code Generation" settings an option "Add declare(strict_types=1) to generated code".

It should generate code like:
```
<?php

declare(strict_types=1);

namespace ...
```

Note: new line between `<?php` and `declare(strict_types=1);` is required to pass CodeSniffer inspections.

**Comment by adelf** [comment]
You can add anything here and it will work.

<img width="972" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/480a7837-49e6-424c-b57c-fc620a7c7e68">

**Comment by swayok** [comment]
My bad. Forgot about this possibility.
