### ISSUE TITLE
Completion is not working after creating _ide_helper_models.php

### ISSUE THREAD

**Issue by decadence** [laravel-idea/plugin#99]
Hi.
When I create _ide_helper_models.php (via plugin or IDE Helper) columns autocompletion begins to fail (in fillable, casts, where, etc). It only works if I delete this file and write phpDoc in actual Model class. What am I doing wrong?

PhpStorm 2019.3.4
Laravel Idea 3.1.2.192

P.S. casts doesn't know about `json` casts.

**Comment by adelf** [comment]
Hi, Victor. Could you check the 3.2 version, please? There are some fixes in the helper code generation, including casts support.

**Comment by decadence** [comment]
Yeah, seems like this is fixed. Thanks.

But `json` casts is not in casts list still.

![2020-08-20_11-41-41](https://user-images.githubusercontent.com/1434668/90747928-33524900-e2da-11ea-858d-b4064f9892eb.png)
