### ISSUE TITLE
[Bug]: Cannot Ctrl + Click on livewire component

### ISSUE THREAD

**Issue by harry-fakir** [laravel-idea/plugin#990]
### Bug description

hi there,

I have laravel idea plugin installed with the latest version 

however I am unable to click through to the livewire declaration using  Ctrl + Click on livewire component OR  Shift + Ctrl + Click on livewire component

<livewire:fund-fees-wizard-preview :Fund="$Fund"/>

### Plugin version

8.1.4.241

### Operating system

MacOS

**Comment by adelf** [comment]
Could you please show the full name of this LiveWire component?

**Comment by harry-fakir** [comment]
hello,

its "FundFeesWizardPreview"

Its also worth noting I cant seem to ctrl + click on other livewire components such as:
          <livewire:search-user /> (Full name of livewire component: SearchUser)
          <livewire:shallow-aml> (Full name of livewire component: ShallowAml)

**Comment by adelf** [comment]
The full class name includes the namespace.

Please check the settings. Sometimes there is a mess between App\Http\LiveWire and App\LiveWire. If your components are located in a different namespace - set it here.

<img width="880" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/788f4e10-4a61-4d70-88d8-025315134ab2">

**Comment by harry-fakir** [comment]
Thank you so much! the correct namespace for was App\Http\LiveWire and i updated the settings per your suggestion and it worked!
![Screenshot 2024-05-16 at 9 10 05 AM](https://github.com/laravel-idea/plugin/assets/91042668/0225e5c1-b0d2-458c-93dd-363305c87977)
