### ISSUE TITLE
[Feature Request]: Monorepo support for helper code generation

### ISSUE THREAD

**Issue by therecluse26** [laravel-idea/plugin#991]
### Feature Description

This package needs the ability to generate helper code for multiple Laravel projects within a monorepo. Monorepos are extremely common for microservice-based platforms, and often it's not a valid solution to say "if they have overlapping functionality, maybe they should be a monolith." 

There are many valid cases in which it makes sense to use a monorepo, and I'd imagine that you'd open up a wider customer base by supporting helper code generation for these kinds of environments (I'm a paying customer, and I personally would stop paying and look for another solution if the answer to this is "no"). I'm assuming that the lift in getting this particular task over the finish line likely would just amount to converting the directory string to an array and iterating over that array and running helper code gen for each, no?

This is necessary enough that PHPStorm added monorepo support by allowing multiple composer.json files in subdirectories after many years of devs asking for it. https://youtrack.jetbrains.com/issue/WI-39151

I'd be happy to assist in any way you might need me, it's a really big deal to me and my organization.

**Comment by adelf** [comment]
The main concept of IntelliJ IDEs is a project. So, even if you have a monorepo, you can open projects separately. 

Generating helper code is a small piece of functionality. I can't even imagine how many changes need to be made to make Laravel ldea work in several Laravel installations in one project. So, I'm sure this won't be implemented soon. Sorry.
