### ISSUE TITLE
[Bug]: New Eloquent Model Dialog prefers vendor models

### ISSUE THREAD

**Issue by dev-idkwhoami** [laravel-idea/plugin#993]
### Bug description

The autocomplete for relations seems to prefer the Order model from the Filament tests over my actual Order model.

![image](https://github.com/laravel-idea/plugin/assets/26493113/91908a38-d12f-4fe5-bec2-e7a8d35c3b5c)

### Plugin version

8.1.4.241

### Operating system

Windows

### Steps to reproduce

Inside a Filament App:

1. Create Order Model
2. Open "New Eloquent Model" dialog
3. Click "Add New Relation"
4. Try to autocomplete the name to `order_id`

**Comment by adelf** [comment]
Hello. I made some improvements in ordering model classes for this window. I hope it will help.
