### ISSUE TITLE
[Bug]:  the batch update method of the model returns an int, but the intelligent prompt displays it as a bool, leading to IDE prompt exceptions.

### ISSUE THREAD

**Issue by season886** [laravel-idea/plugin#994]
### Bug description

Steps to Reproduce

```
    public function claim(array $ids, ?int $uid = null): int
    {
        if (is_null($uid)) {
            $uid = Auth::id();
        }
        return PlmProductPlanList::whereIn('id', $ids)->whereNull('designer')->update(['designer' => $uid]);
    }
```

Expected Result

In strict mode the IDE should not display red wavy lines indicating an exception, as the update method in Laravel actually returns an int rather than a bool as indicated by the intelligent prompt.

### Plugin version

8.1.4.241

### Operating system

windows11+wsl2

**Comment by adelf** [comment]
Hello.

Sometimes, it's hard for IDE to understand if it is a model or query builder. But you can help.
```php
return PlmProductPlanList::query()->whereIn('id', $ids)->whereNull('designer')->update(['designer' => $uid]);
```

**Comment by season886** [comment]
thank you!
