### ISSUE TITLE
[Bug]: Excessive CPU usage

### ISSUE THREAD

**Issue by innocente205** [laravel-idea/plugin#996]
### Bug description

CPU usage increases when editing blade files, load average spikes at around 15. CPU usage decreases from 1700% to less than 300% on the phpstorm activity monitor when the plugin is disabled.

![Screenshot from 2024-05-20 18-26-22](https://github.com/laravel-idea/plugin/assets/57386850/f1c3f172-6e7e-4c12-a3d2-27adc91584c4)

![Screenshot from 2024-05-20 18-24-43](https://github.com/laravel-idea/plugin/assets/57386850/14ef4478-d95e-49f4-8851-377b04a1c09a)

### Plugin version

8.1.4.241

### Operating system

Linux

### Steps to reproduce

Enable the plugin and edit blade files.

### Relevant log output

```shell
I have collected log files if you let me know where to upload them.
$ uname -a
Linux 6.8.4-zabbly+ #ubuntu22.04 SMP PREEMPT_DYNAMIC Fri Apr  5 19:25:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ free -h
               total        used        free      shared  buff/cache   available
Mem:            31Gi       5.6Gi        14Gi       2.5Gi        10Gi        22Gi
```

**Comment by adelf** [comment]
I analyzed it a bit and probably found a reason. I'll try to make an option to turn one feature off. And you could check if it was a reason. Thank you for posting.

**Comment by innocente205** [comment]
Will do. Thanks for the quick response.

**Comment by adelf** [comment]
If you still have this issue, could you please update to Laravel Idea 8.2, turn off this option and check again?

<img width="881" alt="image" src="https://github.com/user-attachments/assets/110a6e7b-affa-43ce-8b26-1effbc19c566">

**Comment by innocente205** [comment]
Thanks. I've actually had the plugin deactivated since having that problem, and have only reactivated it in the past 2-3 days. Not seen the cpu usage spiking. Updated now and will keep you informed.
