### ISSUE TITLE
[Bug]: LaravelIdea Helper Model incorrect property-read

### ISSUE THREAD

**Issue by dustingraham** [laravel-idea/plugin#997]
### Bug description

I have a model that has a getTitleAttribute and setTitleAttribute. The helper generates `@property-read $title attribute` which then causes error highlighting when I try to $model->title = 'x'; because it thinks it is read-only.

### Plugin version

8.1.4.241

### Operating system

Windows

**Comment by dustingraham** [comment]
Example.

```
<?php namespace App\Models;

class ExampleGetSet extends \Eloquent
{
    protected $guarded = ['id'];

    protected function getExampleAttribute() {
        return 'example'.$this->id;
    }

    protected function setExampleAttribute($value) {
        // Handle saving $value
        $this->attributes['example'] = $value;
    }
}
```

```
    public function test(): void
    {
        $x = new ExampleGetSet();
        $a = $x->example;
        $x->example = 'bcd';
    }
```

![image](https://github.com/laravel-idea/plugin/assets/18470466/936b9897-3e7c-4e34-8231-5d647bc7331a)

**Comment by adelf** [comment]
It's fixed. Thank you. A little mistake. If you want to fix it in the current version, you can make the set* method public and regenerate the helper code. Sorry for the inconvenience.

**Comment by dustingraham** [comment]
Great, thank you!
